### ISSUE TITLE
iquest not handling directory names like %select% 

### ISSUE THREAD

**Issue by othmar-weber** [irods/irods#3613] opened 2017-07-24 13:22 UTC
iquest seems to have an issue if a directory which contains the literal ```select``` is referenced in the WHERE clause.
Example:

```
[myriw@icat ~]$ ipwd
/testZone/home/rods
[myriw@icat ~]$ imkdir aa_selected
[myriw@icat ~]$ iquest "SELECT COLL_NAME where COLL_NAME like '/testZone/home/rods/aa%'"
COLL_NAME = /testZone/home/rods/aa_selected
------------------------------------------------------------
[myriw@icat ~]$ iquest "SELECT COLL_NAME where COLL_NAME like '/testZone/home/rods/aa_select%'"
ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND
```

This behavior has been observed with iRODS 4.1.9.

**Comment by trel** [comment] 2017-07-24 13:25
And confirmed in 4.2.1 as well.

Two separate behaviors should be addressed, the `NO_COLUMN_NAME_FOUND` as well as `CAT_NO_ROWS_FOUND`.

```
$ ienv | grep version
irods_version - 4.2.1

$ truncate -s2k foo

$ imkdir -p testing/the_selected_collection

$ iput foo testing/the_selected_collection/

$ ils -Lr
/tempZone/home/rods:
  C- /tempZone/home/rods/testing
/tempZone/home/rods/testing:
  C- /tempZone/home/rods/testing/the_selected_collection
/tempZone/home/rods/testing/the_selected_collection:
  rods              0 demoResc         2048 2017-07-24.08:53 & foo
        generic    /var/lib/irods/Vault/home/rods/testing/the_selected_collection/foo

$ iquest "SELECT COLL_NAME where COLL_NAME like 'th%'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query

$ iquest "SELECT COLL_NAME where COLL_NAME like 't%'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query

$ iquest "SELECT COLL_NAME where COLL_NAME like '%n'"
COLL_NAME = /tempZone/home/rods/testing/the_selected_collection
------------------------------------------------------------

$ iquest "SELECT COLL_NAME where COLL_NAME like '%on'"
COLL_NAME = /tempZone/home/rods/testing/the_selected_collection
------------------------------------------------------------

$ iquest "SELECT COLL_NAME where COLL_NAME like '%collection'"
COLL_NAME = /tempZone/home/rods/testing/the_selected_collection
------------------------------------------------------------

$ iquest "SELECT COLL_NAME where COLL_NAME like '%ed_collection'"
COLL_NAME = /tempZone/home/rods/testing/the_selected_collection
------------------------------------------------------------

$ iquest "SELECT COLL_NAME where COLL_NAME like '%selected_collection'"
 ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND

ERROR(4) $ iquest "SELECT COLL_NAME where COLL_NAME like '%elected_collection'"
COLL_NAME = /tempZone/home/rods/testing/the_selected_collection
------------------------------------------------------------

$ iquest "SELECT COLL_NAME where COLL_NAME like 'the_selected_collection'"
 ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND
ERROR(4) $ 
```

**Comment by kellerb** [comment] 2017-07-24 15:06
I believe this is a duplicate of https://github.com/irods/irods_client_icommands/issues/4. The workaround is to use the lowercase `select` keyword.

<pre>
iquest "<b>select</b> COLL_NAME where COLL_NAME like '/testZone/home/rods/aa_select%'"
</pre>

**Closed** 2017-07-31 19:56 UTC
Labels: bug, consortium-member, duplicate
