### ISSUE TITLE
Delay rule execution fails with mysql in 4.2.11

### ISSUE THREAD

**Issue by peterverraedt** [irods/irods#6738] opened 2022-11-24 18:40 UTC
### iRODS Version, OS and Version

* IRODS 4.2.11 on Centos 7 containers
* Mysql 8 database, SSL required, with transaction isolation level set to "READ COMMITTED";

### What did you try to do?

Executing a delayed irule, e.g.

```bash
cat > myRule.r <<'EOF'

helloWorldRule{
    delay("<PLUSET>10s</PLUSET><EF>1m</EF><INST_NAME>irods_rule_engine_plugin-irods_rule_language-instance</INST_NAME>"){
      writeLine('stdout', 'Hello World!');
    }
}
 
output ruleExecOut
EOF
 
irule -F myRule.r -r irods_rule_engine_plugin-irods_rule_language-instance
```

### Expected behavior

Rule gets executed every minute.

### Observed behavior (including steps to reproduce, if applicable)

Rule engine starts to execute rule but execution fails or storing the result fails.
The delay server dies, no other scheduled delay rules are executed.

Logs show only:

```
[2022-11-24T18:36:55.286Z][icts-p-cloud-rdm-leu-2] rsyslogd stdout | 2022-11-24T19:36:55.286235+01:00 gbiomed-fbi rodsServer[62485]: gbiomed_fbi - remote addresses: 172.17.0.3, 2a02:2c40:0:21::3306:28 ERROR: [-]#011/work/server/core/src/rodsAgent.cpp:556:int runIrodsAgentFactory(sockaddr_un) :  status [SSL_HANDSHAKE_ERROR]  errno [] -- message [failed to call 'agent start']#012#011[-]#011/work/lib/core/src/sockComm.cpp:129:irods::error sockAgentStart(irods::network_object_ptr) :  status [SSL_HANDSHAKE_ERROR]  errno [] -- message [failed to call 'agent start']#012#011#011[-]#011/work/plugins/network/ssl/libssl.cpp:848:irods::error ssl_agent_start(irods::plugin_context &) :  status [SSL_HANDSHAKE_ERROR]  errno [] -- message [error calling SSL_accept]#012
[2022-11-24T18:36:55.316Z][icts-p-cloud-rdm-leu-2] rsyslogd stdout | 2022-11-24T19:36:55.315814+01:00 gbiomed-fbi rodsServer[62465]: (null) -  ERROR: Agent process [62485] exited with status [40]
```

Restarting the irods server process restores the delay server, which immediately tries to execute the irule again, and fails again.

Rebuilding 4.2.11 with b0b252fbba40c6744f64e488cae123408cf1382d reverted fixes the issue.

**Comment by peterverraedt** [comment] 2022-11-25 10:31
The relevant part of our environment can be reproduced on a host running docker using <https://github.com/kuleuven/irods-docker>

1. Run `make` (or `make with-postgres`)
2. Enter the container and execute irule

     ```
     docker exec -ti irods bash
     su - irods
     ils -L
     cat > myRule.r <<'EOF'
     helloWorldRule{
         delay("<PLUSET>10s</PLUSET><EF>1m</EF>"){
           writeLine('stdout', 'Hello World!');
         }
     }
      
     output ruleExecOut
     EOF
      
     irule -F myRule.r
     ```
3. Check `iqstat -l` and `ps aux` output

**Comment by peterverraedt** [comment] 2022-11-25 11:12
The  bug is also present in irods 4.3.0 (change version in the Makefile). It works nice with postgres on 4.3.0.

In 4.3.0 the irods logs are accessible by running `docker logs -f irods`.

```
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/core/src/rodsAgent.cpp:578:int runIrodsAgentFactory(sockaddr_un) :  status [SSL_HANDSHAKE_ERROR]  errno [] -- mes
sage [failed to call 'agent start']\n\t[-]\t/irods_source/lib/core/src/sockComm.cpp:129:irods::error sockAgentStart(irods::network_object_ptr) :  status [SSL_HANDSHAKE_ERROR]  errno [] -- message [failed to call 'agent start']\n\t\t[-]\t/irods_source/plugins/network/src/ssl.cpp:764:irods::error ssl_agent_start(irods::plugin_context &) :  status [SSL_HANDSHAKE_ERROR]  errno [] -- message [error calling SSL_accept]\n\n","server_host":"irods.local","server_pid":169,"server_timestamp":"2022-11-25T11:00:35.023Z","server_type":"agent"}
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/core/src/rsApiHandler.cpp:560:int readAndProcClientMsg(rsComm_t *, int) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']\n\t[-]\t/irods_source/lib/core/src/sockComm.cpp:198:irods::error readMsgHeader(irods::network_object_ptr, msgHeader_t *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']\n\t\t[-]\t/irods_source/plugins/network/src/ssl.cpp:528:irods::error ssl_read_msg_header(irods::plugin_context &, void *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]\n\n","request_api_name":"","request_api_number":110000,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"irods.local","server_pid":168,"server_timestamp":"2022-11-25T11:00:35.023Z","server_type":"agent"}
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/core/src/rodsAgent.cpp:588:int runIrodsAgentFactory(sockaddr_un) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']\n\t[-]\t/irods_source/lib/core/src/sockComm.cpp:160:irods::error sockAgentStop(irods::network_object_ptr) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']\n\t\t[-]\t/irods_source/plugins/network/src/ssl.cpp:850:irods::error ssl_agent_stop(irods::plugin_context &) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error completing shutdown of SSL connection]\n\n","request_api_name":"","request_api_number":110000,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"irods.local","server_pid":168,"server_timestamp":"2022-11-25T11:00:35.023Z","server_type":"agent"}
```

**Comment by peterverraedt** [comment] 2022-11-28 10:14
Mysql with global logging enabled shows that the query is executed:

```
2022-11-28T10:10:37.058773Z       531 Connect   irods@10.0.2.100 on irods using SSL/TLS
2022-11-28T10:10:37.059190Z       531 Query     SET NAMES utf8
2022-11-28T10:10:37.059434Z       531 Query     SET character_set_results = NULL
2022-11-28T10:10:37.059598Z       531 Query     SET SQL_AUTO_IS_NULL = 0
2022-11-28T10:10:37.059887Z       531 Query     set @@max_execution_time=DEFAULT
2022-11-28T10:10:37.060163Z       531 Query     set @@sql_select_limit=DEFAULT
2022-11-28T10:10:37.060338Z       531 Query     set SESSION sql_mode = 'ANSI,STRICT_TRANS_TABLES'
2022-11-28T10:10:37.060603Z       531 Query     set @@max_execution_time=DEFAULT
2022-11-28T10:10:37.060827Z       531 Query     set character_set_client = utf8
2022-11-28T10:10:37.061039Z       531 Query     set @@max_execution_time=DEFAULT
2022-11-28T10:10:37.061209Z       531 Query     set character_set_results = utf8
2022-11-28T10:10:37.061385Z       531 Query     set @@max_execution_time=DEFAULT
2022-11-28T10:10:37.061536Z       531 Query     set character_set_connection = utf8
2022-11-28T10:10:37.061883Z       531 Prepare   select rule_name, rei_file_path, user_name, exe_address, exe_time, exe_frequency, priority, last_exe_time, exe_status, estimated_exe_time, notification_addr, exe_context from R_RULE_EXEC where rule_exec_id = ?
2022-11-28T10:10:37.062054Z       531 Query     set @@max_execution_time=DEFAULT
2022-11-28T10:10:37.062251Z       531 Close stmt
2022-11-28T10:10:37.062302Z       531 Query     select rule_name, rei_file_path, user_name, exe_address, exe_time, exe_frequency, priority, last_exe_time, exe_status, estimated_exe_time, notification_addr, exe_context from R_RULE_EXEC where rule_exec_id = '10014'
2022-11-28T10:10:37.062860Z       531 Quit
2022-11-28T10:10:37.141584Z       532 Connect   irods@10.0.2.100 on irods using SSL/TLS
```

**Comment by peterverraedt** [comment] 2022-11-28 13:27
The issue is that the R_RULE_EXEC is stored as "longtext" in mysql, not as varchar, and the rule `exec_info.push_back(row.get<std::string>(i, ""));` fails on this. The following minimal patch is proven to work on 4.2.11.
This should probably be replaced by the right equivalent in C for the `push_back` call.

```
diff --git a/server/core/src/irodsReServer.cpp b/server/core/src/irodsReServer.cpp
index 01dd121db..0a2dcf3ce 100644
--- a/server/core/src/irodsReServer.cpp
+++ b/server/core/src/irodsReServer.cpp
@@ -119,7 +119,7 @@ namespace {
             nanodbc::statement stmt{db_conn};
             nanodbc::prepare(stmt, "select rule_name, rei_file_path, user_name, exe_address, exe_time,"
                                    " exe_frequency, priority, last_exe_time, exe_status, estimated_exe_time,"
-                                   " notification_addr, exe_context "
+                                   " notification_addr, CAST(exe_context as char(8172)) "
                                    "from R_RULE_EXEC where rule_exec_id = ?");
 
             stmt.bind(0, rule_id.data());
```

**Comment by trel** [comment] 2022-11-28 13:41
oh, very good.   we'll get a test included to box this in as well.

**Comment by korydraughn** [comment] 2022-11-28 13:41
Q. Why is longtext an issue for MySQL?
Q. Does this fail for all delay rules or just some of them?

**Comment by peterverraedt** [comment] 2022-11-28 14:01
A. Longtext is no issue in mysql, but retrieval using nanodbc is. Rules are stored fine.
A. All delay rules fail.

**Comment by peterverraedt** [comment] 2022-11-29 11:20
The following fix is working as well and probably the way to go forward. I see however that the delay rule executor still crashes at a later stage, I need further tests to see why that is happening.

```patch
diff --git a/server/core/src/irodsReServer.cpp b/server/core/src/irodsReServer.cpp
index 01dd121db..e5bffb494 100644
--- a/server/core/src/irodsReServer.cpp
+++ b/server/core/src/irodsReServer.cpp
@@ -134,7 +134,7 @@ namespace {
             exec_info.reserve(number_of_columns); 
 
             for (int i = 0; i < number_of_columns; ++i) {
-                exec_info.push_back(row.get<std::string>(i, ""));
+                exec_info.push_back(row.get<nanodbc::string>(i, ""));
             }
         }
         catch (const std::exception& e) {
```

**Comment by peterverraedt** [comment] 2022-11-30 10:42
This gets weird: the above patch works with `"irods_client_server_policy": "CS_NEG_REFUSE"` but not with `irods_client_server_policy": "CS_NEG_REQUIRE"`.

**Comment by trel** [comment] 2022-11-30 12:50
Make sure to restart the main server after changing that setting -- the `irods_client_server_policy` might be getting 'remembered' by the long-running delay server.

**Comment by korydraughn** [comment] 2022-12-27 16:13
@peterverraedt I tried to stand up the docker container to see what you're experiencing, but it failed with the following message:
```bash
GEM_HOME= GEM_PATH= docker rm -f mysql || echo Container was already removed                   
Error: No such container: mysql                                                  
GEM_HOME= GEM_PATH= docker run -d --rm -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=rootpassword \
  --health-cmd "mysqladmin ping -h localhost" --health-interval 0 --health-retries 12 --health-start-period 10s \                                                                             
  mysql:8 \                                                                                                                                                                                   
  --server-id=1 --gtid-mode=ON --enforce-gtid-consistency=ON               
40b4b09eb8e295e33f6d03662d499f341640ba4b629270be6530208670e8448b                     
Waiting for mysql to start ... (max 180s)                                                                                                                                                     
.docker: 'healthcheck' is not a docker command.                                                                                                                                               
See 'docker --help'                                                                                                                                                                                                                                                                                                                                                                          
..docker: 'healthcheck' is not a docker command.                              
See 'docker --help'                                                         
                                                                                               
Mysql is up and running.                                                                                                                                                                      
GEM_HOME= GEM_PATH= docker exec -i mysql mysql -uroot -prootpassword < initdb.mysql.sql                                                                                                       
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
make: *** [Makefile:78: mysql] Error 1
```

Modifying the Makefile to connect via an IP address produced the following:
```bash
GEM_HOME= GEM_PATH= docker rm -f mysql || echo Container was already removed
mysql
GEM_HOME= GEM_PATH= docker run -d --rm -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=rootpassword \
  --health-cmd "mysqladmin ping -h localhost" --health-interval 0 --health-retries 12 --health-start-period 10s \
  mysql:8 \
  --server-id=1 --gtid-mode=ON --enforce-gtid-consistency=ON
1e411f190447cf6e80e63d98f43d4e83719ab228254fed80c57f7c738bc4a583
Waiting for mysql to start ... (max 180s)
.docker: 'healthcheck' is not a docker command.
See 'docker --help'
..docker: 'healthcheck' is not a docker command.
See 'docker --help'

Mysql is up and running.
GEM_HOME= GEM_PATH= docker exec -i mysql mysql -h 127.0.0.1 -uroot -prootpassword < initdb.mysql.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3306' (111)
make: *** [Makefile:78: mysql] Error 1
```

Any idea why the the MySQL client can't connect to the database?

I tried to reproduce the issue using the iRODS testing environment (Ubuntu 20 / MySQL 8), but it handled the delay rules just fine. Could the patches you've applied be part of the issue?

**Comment by peterverraedt** [comment] 2022-12-27 17:33
If your version of docker doesn't support healthchecks, just add some sleeps in between. 20 seconds should be enough. It seems that the mysql container restarts its daemon from safe mode to unsafe mode and connections get a few seconds refused.

Does the testing environment include `irods_client_server_policy": "CS_NEG_REQUIRE"`?

**Comment by korydraughn** [comment] 2022-12-28 05:35
I did not have SSL enabled. Will give that a try.

**Comment by korydraughn** [comment] 2023-01-03 22:05
I couldn't stand up a CentOS 7 / MySQL 8 environment using the testing environment due to #5715 being a 4.3 only change.

I tried reproducing using Ubuntu 20 / MySQL 8 with SSL enabled instead. Everything worked.

The only path to reproducing what you're seeing seems to be via your docker project.

I'm running **Docker version 20.10.7, build f0df350** on Ubuntu 20.04. What version are you running?

Is `docker healthcheck run` a valid command? See the following:
- https://github.com/kuleuven/irods-docker/blob/cbd6a8d41024e9afc4616dc71e01adb0a7d091bc/healthcheck.sh#L2

Also, what patches have you applied to the iRODS server?

**Comment by alanking** [comment] 2023-01-04 16:45
Just noting here that iRODS 4.3.0 is available on Centos 7: https://packages.irods.org/yum/pool/centos7/x86_64/

If you couldn't stand up Centos 7 in the testing environment, then that's maybe an unrelated issue to look into. Probably for me. :)

**Comment by korydraughn** [comment] 2023-01-04 16:50
No, CentOS 7 is fine in the testing environment.

The problem had to do with 4.2.11, MySQL 8, and the database schema needing changes which aren't available in the 4.2 series.

**Comment by peterverraedt** [comment] 2023-01-05 09:23
I was apparantly running the podman (RedHat) implementation of docker that adds the healthcheck subcommand. I've adapted my scripts to avoid the use of that subcommand.

The patches I apply are minimal for 4.3.0 - see https://github.com/kuleuven/irods-docker/blob/main/bin/apply-patches
The most involved changes are in the setup scripts to set up an ssl-enabled connection to the mysql database, I doubt that can influence anything.

For 4.2.11 the changes are more involved and basically include #5715.

**Comment by peterverraedt** [comment] 2023-01-05 10:26
Removed the mysql ssl-changes in the git repo - problem remains. Now almost no patches are involved for 4.3.0.

**Comment by peterverraedt** [comment] 2023-01-05 15:02
I did test a lot of configuation changes to get more close to https://github.com/irods/irods_testing_environment/tree/main/projects/almalinux-8/almalinux-8-mysql-8 (with ssl enabled) - but the irule problem remained, unless ssl was turned off.

Then I changed my baseimage from centos 7 to almalinux 8 and it started to work correctly. See <https://github.com/kuleuven/irods-docker/commit/38ccf06295b1b2bad9d848bf3e96895eee6c8f0a> for the exact changes. I suspect something related to the openssl version or other libraries. I guess the odbc connector is identical.

It would be useful if you could add a centos 7/irods 4.3.0/mysql 8 combo to verify.

**Comment by korydraughn** [comment] 2023-01-05 15:08
> I did test a lot of configuation changes to get more close to https://github.com/irods/irods_testing_environment/tree/main/projects/almalinux-8/almalinux-8-mysql-8 (with ssl enabled) - but the irule problem remained, unless ssl was turned off.

So SSL appears to be an issue here. During this test, was the base image centos 7?

> Then I changed my baseimage from centos 7 to almalinux 8 and it started to work correctly. See kuleuven/irods-docker@38ccf06 for the exact changes. I suspect something related to the openssl version or other libraries. I guess the odbc connector is identical.

Interesting. This worked even with SSL?

> It would be useful if you could add a centos 7/irods 4.3.0/mysql 8 combo to verify.

Very good. Adding that should be simple enough.

**Comment by peterverraedt** [comment] 2023-01-05 15:15
The base image was centos 7 for all my tests until my final upgrade to almalinux 8.

The almalinux 8 version works with SSL enabled.

**Comment by korydraughn** [comment] 2023-01-05 15:19
Okay. So centos is the main OS we need to investigate.

I'll give your docker project another try and report back when I have more information.

**Comment by korydraughn** [comment] 2023-01-24 17:54
I had to apply the following changes to the docker project so that it stands up.
```diff
 Makefile | 4 +++-                 
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/Makefile b/Makefile
index 4f6acb6..0747561 100644
--- a/Makefile
+++ b/Makefile
@@ -2,6 +2,8 @@

 DOCKER=GEM_HOME= GEM_PATH= docker

+SHELL=bash
+
 # TAG can either be mysql or postgres
 TAG?=mysql

@@ -88,7 +90,7 @@ wait-for-mysql:                                                                              
                sleep 1; \
                done; \
         sleep 1; \
-        for i in $$(seq $$i 60); \
+        for i in {1..60}; \
                do \
                echo -n "."; \
                docker exec -i $(MYSQL_NAME) mysql -uroot -prootpassword -e 'use mysql' &>/dev/null && break; \
```

I have confirmed what you're seeing.

To verify if nanodbc was truly the issue, I wrote an app that contains only the nanodbc logic (from the delay server) and tried fetching a delay rule from the database. It worked. So it may not be an issue with nanodbc. It may be something else happening around the nanodbc calls.

I'll continue to investigate.

**Comment by korydraughn** [comment] 2023-01-25 16:56
I have the testing environment running CentOS 7 with 4.3.0 and SSL enabled between the icommands and iRODS server. The only thing I'm missing is SSL between iRODS and the database.

Delay rules are working in this setup. I'm going to see if enabling SSL between the iRODS server and the database cause any issues.

**Comment by korydraughn** [comment] 2023-01-25 17:15
@peterverraedt Can you share steps for how you enabled SSL between the iRODS server and the database?

**Comment by korydraughn** [comment] 2023-01-25 20:56
Using the following steps, I believe I've confirmed that 4.3.0 works with SSL enabled between the server and the MySQL database just fine.

I did the following (in order):
- In the MySQL 8 container:
  - Ran `mysql_ssl_rsa_setup` to generate self-signed certs.
  - Updated /etc/mysql/my.cnf to point to the certs (see https://dev.mysql.com/doc/refman/8.0/en/using-encrypted-connections.html#using-encrypted-connections-server-side-startup-configuration).
- Outside of the containers:
  - Copied the client-cert.pem and client-key.pem from the MySQL 8 container to the iRODS container.
- In the iRODS container:
  - Updated /var/lib/irods/scripts/database_connect.py to define the following in the .odbc.ini file.
    - `ssl-key: '/path/to/client-key.pem'`
    - `ssl-cert: '/peth/to/client-cert.pem'`
    - `ssl-mode: 'REQUIRED'`
  - Connected to the MySQL 8 container using `mysql -h <mysql_8_container_name> -u irods -p --ssl-cert=/path/to/client-cert.pem --ssl-key=/path/to/client-key.pem`
    - Verified the connection was encrypted by running `\s`
    - Everything looked good

I then removed the `ssl-key` and `ssl-cert` options from database_connect.py and restarted the iRODS server. The iRODS server failed to start indicating the .odbc.ini file was not correct.

@peterverraedt For the 4.3.0 case, please compare what I've done here to what you have. If there are differences or I've done something wrong, please let me know so I can tweak things. Also, are you planning on moving to Almalinux permanently?

**Comment by peterverraedt** [comment] 2023-01-26 15:04
I think that's about it. I use the mysql 8 connector installed as rpm in centos 7.

Anyways, we plan to move to Almalinux 8 when we upgrade to 4.3.0 and this is scheduled for the next month, so this issue will be solved for us.

**Comment by korydraughn** [comment] 2023-01-26 15:26
What version of the MySQL 8 driver were you using for CentOS 7?

I have a PR open, for the testing environment, to add MySQL 8 as a database for CentOS 7. That's what I used to verify this. You can find it at irods/irods_testing_environment#148.

The driver I used was https://downloads.mysql.com/archives/get/p/10/file/mysql-connector-odbc-8.0.29-linux-glibc2.12-x86-64bit.tar.gz. The testing environment PR uses that driver.

> Anyways, we plan to move to Almalinux 8 when we upgrade to 4.3.0 and this is scheduled for the next month, so this issue will be solved for us.

Probably not a bad idea :-)

Does that also mean you no longer need to apply patches to the server?

**Comment by peterverraedt** [comment] 2023-01-26 15:35
I used https://repo.mysql.com/yum/mysql-connectors-community/el/7/x86_64/mysql-connector-odbc-8.0.25-1.el7.x86_64.rpm so apart from the minor version difference, it is the same driver.

In irods 4.3.0 on almalinux 8, patches are very minimal, indeed. We only need some tweaks for have the setup script connect to mysql with ssl enforced, I believe.

**Comment by korydraughn** [comment] 2023-01-26 16:08
The fact that you're having to modify the setup script hints that the setup script probably needs to be more flexible.

What would we need to do to make it so that you don't have to modify the scripts?

**Comment by peterverraedt** [comment] 2023-01-26 16:33
I think a test scenario with mysql running with `require_secure_transport=ON` that functions properly, is enough.

**Comment by korydraughn** [comment] 2023-01-26 17:11
Ok. I think what you're asking is related to the conversation in #6387.

As for the issue regarding delay rule execution failing, we're going to consider this resolved due to the following reasons.
- 4.2.11 does not support the necessary database schema changes found in 4.3.0
- We've verified that SSL between the iRODS server and the database works for 4.3.0 just fine
- You're moving to Almalinux 8 which does not have the problems seen in CentOS 7

**Closed** 2023-01-26 17:13 UTC
Labels: resolved/invalid, bug, consortium-member

**Comment by peterverraedt** [comment] 2023-01-26 18:46
I think a test scenario with mysql running with `require_secure_transport=ON` and with irods set to CS_NEG_REQUIRE should be enough to detect the parts in the setup script that needed adjustion. The commented parts in https://github.com/kuleuven/irods-docker/blob/main/bin/apply-patches#L28-L40 give some indications, although they need review. I remember in any case problems with the initial iput tests when irods requires ssl.
