### ISSUE TITLE
imeta misinterpreting AVU as command line flag

### ISSUE THREAD

**Issue by marchoeppner** [irods/irods#3435] opened 2017-01-05 11:49 UTC
I noticed that certain types of meta data values cause problems with the imeta command - if they start with a hypen:
```
imeta add -d some_file Temperature -80°C temperature
```
The `-80°C` gets interpreted as a command line option and thus produces a failure. Encapsulating the value in `""` or trying to escape it with `\` doesn't fix the problem either. 

Is this behavior intended?

**Comment by kellerb** [comment] 2017-02-07 19:32
This is not intended, this is a bug in the parsing of command line arguments.

**Comment by rskarbez** [comment] 2017-04-21 21:59
Duplicate of #2770.

**Closed by rskarbez** 2017-04-21 21:59 UTC
Labels: bug
