### ISSUE TITLE
iRODS 4.1.x unusable from RTLD_LOCAL plugins

### ISSUE THREAD

**Issue by jmarshall** [irods/irods#3205] opened 2016-06-27 10:35 UTC
[HTSlib](https://github.com/samtools/htslib) uses a plugin mechanism for accessing data via exotic transports such as iRODS, in part so that application code can be unconcerned with such transports' APIs' exotic compilation and linking needs.  Indeed transport libraries like those of iRODS are not linked into either applications or htslib itself, but only into the individual plugins.

The plugin mechanism we have designed loads plugins with `dlopen(…, RTLD_NOW | RTLD_LOCAL)`, in part so that different plugins using similar function names and other symbols will not interfere with each other.  In particular, we designed it this way so that during a transition from iRODS 3.3.x to 4.x, our software can load both _hfile_irods3.so_ and _hfile_irods4.so_ plugins and conveniently access data simultaneously in both old and new systems.

Unfortunately trying to access data via a plugin linked against the 4.1.8 API does not work:

```sh
$ gcc -shared -Wl,-E -pthread -L/usr/lib/irods/externals -o hfile_irods.so hfile_irods.o -lRodsAPIs -lirods_client_api /usr/lib/irods/externals/libjansson.a -lboost_program_options -lboost_filesystem -lboost_chrono -lboost_regex -lboost_thread -lboost_system -lssl -lcrypto -lrt -lstdc++
# …
$ htsfile irods:example.bam
ERROR: [-]	iRODS/lib/core/src/sockComm.cpp:1300:sendStartupPack :  status [PLUGIN_ERROR]  errno [] -- message []
	[-]	iRODS/lib/core/src/sockComm.cpp:1376:sendRodsMsg :  status [PLUGIN_ERROR]  errno [] -- message [failed to resolve network interface]
		[-]	iRODS/lib/core/src/irods_tcp_object.cpp:95:resolve :  status [PLUGIN_ERROR]  errno [] -- message []
			[-]	iRODS/lib/core/src/irods_network_manager.cpp:93:init_from_type :  status [PLUGIN_ERROR]  errno [] -- message [Failed to load network plugin]
				[-]	iRODS/lib/core/src/irods_network_manager.cpp:74:load_network_plugin :  status [PLUGIN_ERROR]  errno [] -- message []
					[-]	iRODS/lib/core/include/irods_load_plugin.hpp:194:load_plugin :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/opt/renci/icommands/plugins/network/libtcp.so] :: dlerror: is [/opt/renci/icommands/plugins/network/libtcp.so: undefined symbol: _ZTIN5irods10tcp_objectE]]
```

If we change [HTSlib to use RTLD_GLOBAL instead](https://github.com/samtools/htslib/blob/develop/plugin.c#L132), this error disappears (thus confirming that the cause is lack of symbol availability from the RTLD_LOCAL _hfile_irods.so_), but as noted redesigning the plugin mechanism in this way is undesirable.

Alternatively, if iRODS plugins like _libtcp.so_ were themselves linked against the iRODS shared libraries they need, this problem would disappear, and _libtcp.so_ and its ilk would be usable from main code and from RTLD_LOCAL and RTLD_GLOBAL plugins alike.

**Comment by jmarshall** [comment] 2016-06-29 13:49
See also irods/irods_auth_plugin_kerberos#13, which is also about iRODS plugins needing to be themselves linked against the libraries they need.

**Comment by jasoncoposky** [comment] 2016-06-29 13:59
The move to shared objects is handled in the 4.2 release with #2308

Also, i noted that you are linking against libRodsAPIs.  We have broken the libraries out into smaller components for 4.x as demonstrated by the netcdf repository which may solve your runtime linking issue:

https://github.com/irods/irods_netcdf/blob/master/icommands/Makefile#L39

**Comment by kript** [comment] 2016-06-29 15:09
@jasoncoposky so as you know @jmarshall is one of our users and HTSlib is used by a lot of the tools our compute farm users use. The kerberos issue is effectively stopping them scripting against our iRODS setup now we're on 4.1.-stable and some teams can't move away from Kerberos due to security restrictions.

@jmarshall : does jason's component suggestion move things along, or would getting on a conf call to talk through it if everyones available be helpful?

**Comment by jmarshall** [comment] 2016-06-29 15:14
Same result when linking against `-lirods_client -lirods_client_api_table -lirods_client_plugins -lirods_client_api -lirods_client_core`.  I had reverted to _libRodsAPIs_ as various permutations of not quite all of the _irods_client*_ libraries were leaving various symbols unresolved.

@jasoncoposky appears to be saying 4.1.x is unsupported for this use case…?

**Comment by jrandall** [comment] 2016-06-29 15:18
I have been assuming that 4.2.x clients will be able to talk to the 4.1.9 server..?

**Comment by kript** [comment] 2016-06-29 16:00
Might be a separate issue, but can we confirm there is test coverage from 4.2 client to talk to 4.1.9 server with all authentication plugins?

**Comment by jasoncoposky** [comment] 2016-06-29 17:28
First, neither we nor the DICE group have ever made a guarantee that older clients will work perfectly with newer servers.  We also do not test across versions of iRODS other than for federation.  If that is a desirable feature we can open a new issue and continue the discussion there, but we will also need to bring it up at the Technology Working Group as it has long term technical ramifications for the project.

Picking up on the existing issue, when i run:
```
echo _ZTIN5irods10tcp_objectE | c++filt 
typeinfo for irods::tcp_object
```

I see that we need the typeinfo for the tcp_object.  These symbols are provided by the libirods_client_plugins library but the issue is that your plugin does not reference those symbols and so they are not linked.  A quick work around for 4.1.x would be to add the necessary references in your irods plugin for HTSlib which will cause the linking and satisfy the tcp plugin's requirements.  And as i said this should not be an issue for 4.2 where we dynamically link everything.

**Comment by jmarshall** [comment] 2016-06-29 17:35
Like I said: when I changed the loading to use `RTLD_GLOBAL`, the same _hfile_irods.so_ plugin object worked fine — thus confirming that the `tcp_object` typeinfo and other symbols have indeed been pulled in during the link.

**Comment by kellerb** [comment] 2016-07-01 19:51
For 4.1, the iRODS plugins (e.g. libtcp.so) are not directly linked (i.e. do not have `DT_NEEDED` entries) to the runtime libraries (e.g. libirods_client_core.so.1), because the server and icommands binaries do not themselves use the runtime libraries (i.e. the server and icommands binaries have their own copies of all the symbols found in the runtime libraries), and there was concern about symbol conflicts if the server/icommands loaded the runtime libraries.

However, I notice that iRODS does [load the plugins](https://github.com/irods/irods/blob/4.1.8/iRODS/lib/core/include/irods_load_plugin.hpp#L189) with `RTLD_LOCAL` (implicitly in 4.1, made explicit in 4.2). I do not currently know how `RTLD_LOCAL` interacts with `DT_NEEDED` entries and library/symbol scopes. It may be possible to add `DT_NEEDED` entries to all the plugins for all the DSOs they need without having the server violate the One Definition Rule and/or explode on process termination when it tries to cleanup all the global variables twice, etc. **If anyone has insight into this, please let us know.**

One possible solution: we could create new instances of all the plugins you need for HTSlib, with the only change being adding the necessary `DT_NEEDED` entries. Of course, these new plugins would need to be stored in addition to and separately from the plugins used by the server and icommands. Towards this, I have begun experimenting with [patchelf](https://github.com/NixOS/patchelf).

For some uplifting future news, this has all been fixed in 4.2, as the server and icommands now link against the runtime libraries. We also now build the plugins with `-Wl,-z,defs`, which makes sure that the plugins don't have any of these undefined symbols or missing libraries.

**Comment by trel** [comment] 2016-08-15 19:39
@jmarshall It looks like you've wrapped this issue in your code?  May we close this issue?

**Comment by jmarshall** [comment] 2016-08-18 13:18
@kellerb's reply makes it clear that as 4.1.x has plugins but no pervasively-used shared libraries, it is impractical to support this use case.

As you've noticed, horrific hack job workarounds are possible for HTSlib past and present.  So WONTFIX for 4.1 / supported in 4.2 seems like a realistic resolution of this issue.

**Closed** 2016-10-28 18:20 UTC
Labels: consortium-member, packaging
