### ISSUE TITLE
irm is slow when removing replicated dataobject

### ISSUE THREAD

**Issue by trel** [irods/irods#3046] opened 2016-02-12 18:27 UTC
Per https://groups.google.com/forum/#!topic/iROD-Chat/WphV4PlqCzs:

> I have install irods 4.1.7 on a debian system.
> I set up a 'resource composition' with two resources on a tree:
>                  #ilsresc 
>                  replResc:replication
>                 ├── inragrid-mtpResource
>                 └── inragrid-tlsResource
> So i set up automatic replication between the two resources.
> This work correctly :
> ```
>                # ils -l
>                /INRAgrid/home/rods:
>                rods              0 replResc;inragrid-mtpResource    258998272 2016-02-09.10:03 & debian-8.2.0-amd64-netinst.iso
>                rods              1 replResc;inragrid-tlsResource    258998272 2016-02-10.16:24 & debian-8.2.0-amd64-netinst.iso
>                rods              0 replResc;inragrid-tlsResource   1073741824 2016-02-11.15:55 & test_data_1G
>                rods              1 replResc;inragrid-mtpResource   1073741824 2016-02-11.15:56 & test_data_1G
> ```
>                
> Transferring a file to the resource 'replResc' is well with correct replication and delay: ~95Mo/sec
> ```
>                # time iput -R replResc /home/pmoreau/test_data_10G
> 
>                 real    1m53.701s
>                 user    0m0.044s
>                 sys    0m8.368s
>                # ils -l
>                /INRAgrid/home/rods:
>                rods              0 replResc;inragrid-mtpResource    258998272 2016-02-09.10:03 & debian-8.2.0-amd64-netinst.iso
>                rods              1 replResc;inragrid-tlsResource    258998272 2016-02-10.16:24 & debian-8.2.0-amd64-netinst.iso
>                rods              0 replResc;inragrid-tlsResource  10737418240 2016-02-12.10:25 & test_data_10G
>                rods              1 replResc;inragrid-mtpResource  10737418240 2016-02-12.10:27 & test_data_10G
>                rods              0 replResc;inragrid-tlsResource   1073741824 2016-02-11.15:55 & test_data_1G
>                rods              1 replResc;inragrid-mtpResource   1073741824 2016-02-11.15:56 & test_data_1G
>                #
> ```
> The strangeness is when i try to delete a file.
> Il i delete a file at once with irm like this, it takes  long time
> ```
>               # time irm test_data_10G
> 
>               real    3m33.210s
>               user    0m0.012s
>               sys    0m0.000s
>               #
> ```
> If I delete the file replicate by replicate it's instant.
> ```
>               # time irm -n 1 test_data_10G
> 
>               real    0m1.612s
>               user    0m0.008s
>               sys    0m0.004s
>               # time irm test_data_10G 
> 
>               real    0m0.468s
>               user    0m0.012s
>               sys    0m0.000s
>               #
> ```
> I see nothing wrong with the log file.

**Comment by jasoncoposky** [comment] 2016-03-18 13:58
The issue is that an OPEN operation is used for hierarchy resolution which leads to additional replications.  This will be resolved by the use of an explicit UNLINK operation for voting.

**Comment by jasoncoposky** [comment] 2016-08-19 21:06
This issue was resolved by #3057

**Closed by jasoncoposky** 2016-08-19 21:06 UTC
Labels: bug, resolved/invalid
