### ISSUE TITLE
GenQuery: % not working as expected (only with DATA_RESC_HIER?)

### ISSUE THREAD

**Issue by kuntzagk** [irods/irods#3714] opened 2017-11-01 16:44 UTC
In 4.2 GenQuery the % does not work as expected when using against DATA_RESC_HIER 

```
$ iquest "select DATA_RESC_HIER where DATA_RESC_HIER like 'cacheHCP'"
DATA_RESC_HIER = defaultResc;compHCP;cacheHCP
------------------------------------------------------------

$ iquest "select DATA_RESC_HIER where DATA_RESC_HIER like '%cacheHCP'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query

$ ilsresc
defaultResc:passthru
└── compHCP:compound
    ├── archiveHCP:s3
    └── cacheHCP:unixfilesystem
demoResc:unixfilesystem
```

Expected result: second query should also return
`DATA_RESC_HIER = defaultResc;compHCP;cacheHCP`

In 4.1.8 this is working as expected

**Comment by jaking92** [comment] 2017-11-27 22:09
Looks like 4.2 is missing some handling. After some discussion, we may have found a path forward.

Queries using % in combination with a "=" condition will return a "not found" error because no entries should contain %. Queries using "like" must use %, or else have an exact match (e.g. 'defaultResc;compHCP;cacheHCP' or '%cacheHCP', but not 'cacheHCP'). Otherwise, this should result in an error.

Since resource hierarchies are no longer stored in SQL as of #3039 (in favor of resource IDs), here is a proposed "like" implementation for resource hiers: GenQuery should generate a list of every resource hierarchy, filter the list using a regex adapted from the GenQuery condition, and get all the leaf resource IDs from the filtered list. Then the 'like' condition will be substituted by a string of ||'d together resource IDs from the result. Some optimizations can and will be made here, but this should handle the general case.

**Comment by trel** [comment] 2017-11-28 16:55
So, to be consistent with 4.1 behavior...

- `= without %`: direct match
- `= with %`: error
- `like without %`: direct match (same as `= without %`)
- `like with %`: generate full hierarchy list, filter via `boost::regex`, populate genquery, execute

**Comment by kuntzagk** [comment] 2017-12-07 15:46
@trel In 4.1 I see following behaviour: 
```
$ iquest "select DATA_RESC_HIER where DATA_RESC_HIER like 'cacheHCP'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```
In the 4.2.3 preview  provided to Bayer (don't know which commit this is based on) I see this:
```
$ iquest "select DATA_RESC_HIER where DATA_RESC_HIER like 'cacheHCP'"
DATA_RESC_HIER = defaultResc;compHCP;cacheHCP
```

**Comment by trel** [comment] 2017-12-07 16:53
The preview is built on bd0725a.

Yes, this was the intended behavior [defined in the 'third bullet' above](https://github.com/irods/irods/issues/3714#issuecomment-347588929)...
 - `like without %`: direct match with leaf (same as `= without %`)

Similarly, I believe that style of  'wildcard-less like' will match in 4.1 when used against `DATA_NAME`...  Can you confirm?

```
$ iquest "select DATA_NAME where DATA_NAME like 'foo'"
DATA_NAME = foo
```

Would you rather the intended behavior for DATA_RESC_HIER be the following?  

```
$ iquest "select DATA_RESC_HIER where DATA_RESC_HIER like 'cacheHCP'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
------------------------------------------------------------
$ iquest "select DATA_RESC_HIER where DATA_RESC_HIER like '%cacheHCP'"
DATA_RESC_HIER = defaultResc;compHCP;cacheHCP
```
This would have been my first choice as well, but we saw 4.1 make a match without the wildcard, so we implemented what you are currently seeing with the preview packages.

**Comment by kuntzagk** [comment] 2017-12-08 08:06
I don't really care for this, just wanted to notify you that this is a change from 4.1.9 behavior.

I would think that the consistend behavior would be to make the 'wildcard-less like' only match the full rescource hierarchy. This is what I see in 4.1.9:

```
$ iquest "select DATA_RESC_HIER where DATA_RESC_HIER like 'cacheHCP'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
------------------------------------------------------------
$ iquest "select DATA_RESC_HIER where DATA_RESC_HIER like '%cacheHCP'"
DATA_RESC_HIER = defaultResc;compHCP;cacheHCP
------------------------------------------------------------
$ iquest "select DATA_RESC_HIER where DATA_RESC_HIER like 'defaultResc;compHCP;cacheHCP'"
DATA_RESC_HIER = defaultResc;compHCP;cacheHCP
```

**Comment by trel** [comment] 2017-12-08 13:35
Got it - that makes sense to me too.

**Comment by trel** [comment] 2017-12-19 11:13
Desired behavior confirmed working by Bayer - closing.

**Closed by trel** 2017-12-19 11:13 UTC
Labels: bug, consortium-member
