### ISSUE TITLE
How should irods_default_resource be handled in federation?

### ISSUE THREAD

**Issue by kript** [irods/irods#3220] opened 2016-07-12 15:02 UTC
When a user connects to a sub zone via Federation, what is the expected behavior when irods_default_resource is set in the users ienv?

```
ilsresc
data:unix file system
demoResc:unix file system
wtsiuser
```

client, talking to the seq-dev Federated zone (which does not contain a resource called 'wtsiuser';
```
time iput -K vmstat.gluplot /seq-dev/jc18_testcol/vmstat.gluplot.1
ERROR: putUtil: put error for /seq-dev/jc18_testcol/vmstat.gluplot.1, status = -78000 status = -78000 SYS_RESC_DOES_NOT_EXIST

real	0m1.056s
user	0m0.028s
sys	0m0.012s
```

and as the user, I have a default resource set;
```
ienv | grep resource
NOTICE: irods_default_resource - wtsiuser
```

Bonus points for an answer that also covers an irods V3 client having a default resource set in their .irodsEnv! :-) 

I suspect the answer is to not have a default resource set at all...

**Comment by trel** [comment] 2016-07-13 15:24
Similar to #3224, if the "forced" flag is used on the server in the logic, then the client environment value should be overruled and will not have an effect.

Also, like you said, you could not have a default resource defined on the client side.

**Comment by andyjp94** [comment] 2016-07-18 13:06
So on 4-1-stable the "forced" flag seems to be half working. It stops the user from writing to the default resource as specified in their irods_environment.json but it fails to store the file in the appropriate resource instead.

```
$ ienv | grep resource
NOTICE: irods_default_resource - demoResc
$ touch blah.txt
$ iput blah.txt
ERROR: putUtil: put error for /seq-dev/home/ap21_testing/blah.txt, status = -1 status = -1 Unknown iRODS error, Operation not permitted
```
In the log file it shows:
```
Jul 18 13:52:17 pid:32259 NOTICE: Agent process 16004 started for puser=ap21_testing and cuser=ap21_testing from 172.17.139.64
Jul 18 13:52:17 pid:16004 NOTICE: writeLine: inString = writing to root
Jul 18 13:52:17 pid:16004 ERROR: [-]    iRODS/server/api/src/rsFilePut.cpp:40:rsFilePut :  status [INVALID_LOCATION]  errno [] -- message [failed in call to irods::get_host_for_hier_string]
        [-]     iRODS/server/core/src/irods_resource_backport.cpp:650:get_host_for_hier_string :  status [INVALID_LOCATION]  errno [] -- message [get_host_for_hier_string - Host from hierarchy string: "root" is NULL]

Jul 18 13:52:17 pid:16004 ERROR: [-]    iRODS/server/api/src/rsFileStat.cpp:28:rsFileStat :  status [INVALID_LOCATION]  errno [] -- message [rsFileStat - failed in call to irods::get_host_for_hier_string]
        [-]     iRODS/server/core/src/irods_resource_backport.cpp:650:get_host_for_hier_string :  status [INVALID_LOCATION]  errno [] -- message [get_host_for_hier_string - Host from hierarchy string: "root" is NULL]

Jul 18 13:52:17 pid:16004 ERROR: _rsDataObjClose - getSizeInVault failed [-1807000]
Jul 18 13:52:17 pid:16004 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jul 18 13:52:17 pid:16004 NOTICE: Agent exiting with status = 0
Jul 18 13:52:18 pid:32259 NOTICE: Agent process 16004 exited with status 0
```
and the governing rule file is:
```
acSetRescSchemeForCreate {
        if ($objPath like regex '/seq-dev/illumina/library_merge/.*\.(bam|cram)$') {
                msiSetDefaultResc("noReplRoot","forced");
                writeLine("serverLog", "writing to noReplRoot");
        }
        else {
                msiSetDefaultResc("root","forced");
                writeLine("serverLog", "writing to root");
        }
}
acPreprocForDataObjOpen{ msiSetDataObjPreferredResc("root"); }
  
#do we need the more involved one here
acPostProcForPut {msiSysChksumDataObj; }
```
which you can see is working due to the writeLine statement in the log file. This also happens if the file matches the criteria to be stored in "noReplRoot" as described in the rule file. In this case the corresponding log output is shown here:
```
Jul 18 14:03:33 pid:32259 NOTICE: Agent process 17124 started for puser=ap21_testing and cuser=ap21_testing from 172.17.139.64
Jul 18 14:03:34 pid:17124 NOTICE: writeLine: inString = writing to noReplRoot
Jul 18 14:03:34 pid:17124 ERROR: [-]    iRODS/server/api/src/rsFilePut.cpp:40:rsFilePut :  status [INVALID_LOCATION]  errno [] -- message [failed in call to irods::get_host_for_hier_string]
        [-]     iRODS/server/core/src/irods_resource_backport.cpp:650:get_host_for_hier_string :  status [INVALID_LOCATION]  errno [] -- message [get_host_for_hier_string - Host from hierarchy string: "noReplRoot" is NULL]

Jul 18 14:03:34 pid:17124 ERROR: [-]    iRODS/server/api/src/rsFileStat.cpp:28:rsFileStat :  status [INVALID_LOCATION]  errno [] -- message [rsFileStat - failed in call to irods::get_host_for_hier_string]
        [-]     iRODS/server/core/src/irods_resource_backport.cpp:650:get_host_for_hier_string :  status [INVALID_LOCATION]  errno [] -- message [get_host_for_hier_string - Host from hierarchy string: "noReplRoot" is NULL]

Jul 18 14:03:34 pid:17124 ERROR: _rsDataObjClose - getSizeInVault failed [-1807000]
Jul 18 14:03:34 pid:17124 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jul 18 14:03:34 pid:17124 NOTICE: Agent exiting with status = 0
Jul 18 14:03:34 pid:32259 NOTICE: Agent process 17124 exited with status 0
```
If the irods_default_resource variable is not set in the client's irods_environment.json file everything works splendidly

**Comment by trel** [comment] 2016-07-18 14:27
Interesting.  That sounds like a bug.

Can you please send an `ilsresc` for both of the Zones in question?
Versions of clients?
Is this from 3.3.1 to 4-1-stable?

We have not been able to replicate this behavior yet.

**Comment by andyjp94** [comment] 2016-07-18 14:39
Both the clients and the servers have been built from commit b71f1503 on 4-1-stable.  
The output of ```ilsresc``` on the head zone is:
```
data:unix file system
demoResc:unix file system
wtsiuser
```
The output of ilsresc on the seq-dev zone (which is where we are trying to write to) is:
```
demoResc:unix file system
demoResc2:unix file system
demoResc3:unix file system
irods-g2-devResource
irods-r2-devResource
irods_r2_dev_sdb:unix file system
noReplRoot:passthru
└── redNoRepl:random
    ├── irods-seq-i21-bc
    ├── irods-seq-i21-de
    ├── irods-seq-i21-fg
    ├── irods-seq-i22-bc
    ├── irods-seq-i22-de
    ├── irods-seq-i22-fg
    ├── irods-seq-i23-bc
    ├── irods-seq-i23-de
    ├── irods-seq-i23-fg
    ├── irods-seq-i24-bc
    ├── irods-seq-i24-de
    └── irods-seq-i24-fg
root:passthru
└── replicate:replication
    ├── green:random
    │   ├── green1:random
    │   │   ├── irods-seq-sr01-ddn-ra08-15-16-17
    │   │   ├── irods-seq-sr01-ddn-ra08-18-19-20
    │   │   ├── irods-seq-sr01-ddn-ra08-21-22-23
    │   │   ├── irods-seq-sr01-ddn-ra08-24-25-26
    │   │   ├── irods-seq-sr01-ddn-ra08-27-28-29
    │   │   ├── irods-seq-sr01-ddn-ra08-30-31-32
    │   │   ├── irods-seq-sr01-ddn-ra08-33-34-35
    │   │   ├── irods-seq-sr01-ddn-ra08-36-37-38
    │   │   └── irods-seq-sr01-ddn-ra08-39-40-41
    │   ├── green2:random
    │   │   ├── irods-seq-sr02-ddn-ra08-0-1-2
    │   │   ├── irods-seq-sr02-ddn-ra08-12-13-14
    │   │   ├── irods-seq-sr02-ddn-ra08-3-4-5
    │   │   ├── irods-seq-sr02-ddn-ra08-6-7-8
    │   │   ├── irods-seq-sr02-ddn-ra08-9-10-11
    │   │   ├── irods-seq-sr02-ddn-rd10-0-1-2
    │   │   ├── irods-seq-sr02-ddn-rd10-12-13-14
    │   │   ├── irods-seq-sr02-ddn-rd10-14-15-16
    │   │   └── irods-seq-sr02-ddn-rd10-3-4-5
    │   ├── green3:random
    │   │   ├── irods-seq-sr03-ddn-gg07-0-1-2
    │   │   ├── irods-seq-sr03-ddn-gg07-12-13-14
    │   │   ├── irods-seq-sr03-ddn-gg07-15-16-17
    │   │   ├── irods-seq-sr03-ddn-gg07-18-19-20
    │   │   ├── irods-seq-sr03-ddn-gg07-21-22-23
    │   │   ├── irods-seq-sr03-ddn-gg07-24-25-26
    │   │   ├── irods-seq-sr03-ddn-gg07-27-28-29
    │   │   ├── irods-seq-sr03-ddn-gg07-3-4-5
    │   │   └── irods-seq-sr03-ddn-gg07-30-31-32
    │   ├── green4:random
    │   │   ├── irods-seq-sr04-ddn-gc10-0-1-2
    │   │   ├── irods-seq-sr04-ddn-gc10-12-13-14
    │   │   ├── irods-seq-sr04-ddn-gc10-15-16-17
    │   │   ├── irods-seq-sr04-ddn-gc10-18-19-20
    │   │   ├── irods-seq-sr04-ddn-gc10-21-22-23
    │   │   ├── irods-seq-sr04-ddn-gc10-24-25-26
    │   │   ├── irods-seq-sr04-ddn-gc10-27-28-29
    │   │   ├── irods-seq-sr04-ddn-gc10-3-4-5
    │   │   └── irods-seq-sr04-ddn-gc10-30-31-32
    │   ├── green5:random
    │   │   ├── irods-seq-sr04-ddn-gc10-45-46-47
    │   │   ├── irods-seq-sr04-ddn-gc10-48-49-50
    │   │   ├── irods-seq-sr04-ddn-gc10-51-52-53
    │   │   ├── irods-seq-sr04-ddn-gc10-54-55-56
    │   │   ├── irods-seq-sr04-ddn-gc10-57-58-59
    │   │   ├── irods-seq-sr04-ddn-gc10-6-7-8
    │   │   ├── irods-seq-sr04-ddn-gc10-9-10-11
    │   │   └── irods-seq-sr04-ddn-re12f-0
    │   ├── green6:random
    │   │   ├── irods-seq-sr01-ddn-ra08-42-43-44
    │   │   ├── irods-seq-sr01-ddn-ra08-45-46-47
    │   │   ├── irods-seq-sr01-ddn-ra08-48-49-50
    │   │   ├── irods-seq-sr01-ddn-ra08-51-52-53
    │   │   ├── irods-seq-sr01-ddn-ra08-54-55-56
    │   │   ├── irods-seq-sr01-ddn-ra08-57-58-59
    │   │   ├── irods-seq-sr01-ddn-rd10-18-19-20
    │   │   ├── irods-seq-sr01-ddn-rd10-21-22-23
    │   │   └── irods-seq-sr01-ddn-rd10-24-25-26
    │   ├── green7:random
    │   │   ├── irods-seq-sr01-ddn-rd10-27-28-29
    │   │   ├── irods-seq-sr01-ddn-rd10-45-46-47
    │   │   ├── irods-seq-sr02-ddn-rd10-30-31-32
    │   │   ├── irods-seq-sr02-ddn-rd10-33-34-35
    │   │   ├── irods-seq-sr02-ddn-rd10-36-37-38
    │   │   ├── irods-seq-sr02-ddn-rd10-39-40-41
    │   │   ├── irods-seq-sr02-ddn-rd10-42-43-44
    │   │   ├── irods-seq-sr02-ddn-rd10-48-49-50
    │   │   └── irods-seq-sr02-ddn-rd10-51-52-53
    │   ├── green8:random
    │   │   ├── irods-seq-sr02-ddn-rd10-54-55-56
    │   │   ├── irods-seq-sr02-ddn-rd10-57-58-59
    │   │   ├── irods-seq-sr02-ddn-rd10-6-7-8
    │   │   ├── irods-seq-sr02-ddn-rd10-9-10-11
    │   │   ├── irods-seq-sr03-ddn-gg07-33-34-35
    │   │   ├── irods-seq-sr03-ddn-gg07-36-37-38
    │   │   ├── irods-seq-sr03-ddn-gg07-39-40-41
    │   │   ├── irods-seq-sr03-ddn-gg07-42-43-44
    │   │   ├── irods-seq-sr03-ddn-gg07-45-46-47
    │   │   └── irods-seq-sr03-ddn-gg07-48-49-50
    │   └── green9:random
    │       ├── irods-seq-sr03-ddn-gg07-51-52-53
    │       ├── irods-seq-sr03-ddn-gg07-54-55-56
    │       ├── irods-seq-sr03-ddn-gg07-57-58-59
    │       ├── irods-seq-sr03-ddn-gg07-6-7-8
    │       ├── irods-seq-sr03-ddn-gg07-9-10-11
    │       ├── irods-seq-sr04-ddn-gc10-33-34-35
    │       ├── irods-seq-sr04-ddn-gc10-36-37-38
    │       ├── irods-seq-sr04-ddn-gc10-39-40-41
    │       └── irods-seq-sr04-ddn-gc10-42-43-44
    └── red:random
        ├── red1:random
        │   ├── irods-seq-i01-bc
        │   ├── irods-seq-i01-de
        │   ├── irods-seq-i01-fg
        │   ├── irods-seq-i02-bc
        │   ├── irods-seq-i02-de
        │   ├── irods-seq-i02-fg
        │   ├── irods-seq-i03-bc
        │   ├── irods-seq-i03-de
        │   ├── irods-seq-i03-fg
        │   ├── irods-seq-i04-bc
        │   ├── irods-seq-i04-de
        │   ├── irods-seq-i04-fg
        │   ├── irods-seq-i05-bc
        │   ├── irods-seq-i05-de
        │   ├── irods-seq-i05-fg
        │   ├── irods-seq-i06-bc
        │   ├── irods-seq-i06-de
        │   ├── irods-seq-i06-fg
        │   ├── irods-seq-i07-bc
        │   └── irods-seq-i07-de
        ├── red2:random
        │   ├── irods-seq-i07-fg
        │   ├── irods-seq-i08-bc
        │   ├── irods-seq-i08-de
        │   ├── irods-seq-i08-fg
        │   ├── irods-seq-i09-bc
        │   ├── irods-seq-i09-de
        │   ├── irods-seq-i09-fg
        │   ├── irods-seq-i10-bc
        │   ├── irods-seq-i10-de
        │   ├── irods-seq-i10-fg
        │   ├── irods-seq-i11-bc
        │   ├── irods-seq-i11-de
        │   ├── irods-seq-i11-fg
        │   ├── irods-seq-i12-bc
        │   ├── irods-seq-i12-de
        │   ├── irods-seq-i12-fg
        │   ├── irods-seq-i13-bc
        │   ├── irods-seq-i13-de
        │   ├── irods-seq-i13-fg
        │   └── irods-seq-i14-bc
        └── red3:random
            ├── irods-seq-i14-de
            ├── irods-seq-i14-fg
            ├── irods-seq-i15-bc
            ├── irods-seq-i15-de
            ├── irods-seq-i15-fg
            ├── irods-seq-i16-bc
            ├── irods-seq-i16-de
            ├── irods-seq-i16-fg
            ├── irods-seq-i17-bc
            ├── irods-seq-i17-de
            ├── irods-seq-i17-fg
            ├── irods-seq-i18-bc
            ├── irods-seq-i18-de
            ├── irods-seq-i18-fg
            ├── irods-seq-i19-bc
            ├── irods-seq-i19-de
            ├── irods-seq-i19-fg
            ├── irods-seq-i20-bc
            ├── irods-seq-i20-de
            └── irods-seq-i20-fg
```

**Comment by trel** [comment] 2016-07-18 15:21
We're investigating that this issue is the same as https://github.com/irods/irods/issues/2713

It appears the resolve_resource_hierarchy isn't being called with `-R`, in 4-1-stable, without a federation involved.

**Comment by trel** [comment] 2016-07-18 16:23
Confirmed - moving #2713 to 4.1.9.

Closing this as duplicate.

**Closed by trel** 2016-07-18 16:23 UTC
Labels: consortium-member, duplicate

**Comment by keithj** [comment] 2016-07-21 15:44
An additional observation, when using a v3 client if I comment the `irodsDefResource` line then no resource appears to be found and a v3 client calling `rcDataObjOpen` returns `-130000 
SYS_INVALID_INPUT_PARAM`. Specifying a resource explicitly with `irodsDefResource` allows the client to read and write once more.
