### ISSUE TITLE
build icommands target on OSX 10.11 El Capitan

### ISSUE THREAD

**Issue by trel** [irods/irods#3011] opened 2016-01-05 20:05 UTC
Among things that are slightly different:
 - clang
 - openssl
 - implementations available in brew

**Comment by trel** [comment] 2016-02-01 14:10
linux runtime broken by the last commit.  reverting...

**Comment by trel** [comment] 2016-02-02 16:36
@keithj Can you look over this latest commit 734dd51 and confirm the iCommands work for you on 10.11?

**Comment by keithj** [comment] 2016-02-02 16:48
@trel Sorry, I can't do that - no machine running 10.11 here.

**Comment by trel** [comment] 2016-02-02 16:52
Ah, very well.

**Comment by trel** [comment] 2016-02-02 21:11
also confirmed to be working on 10.10.

**Comment by trel** [comment] 2016-02-03 20:05
@ilarik can you confirm 4-1-stable icommands are behaving for you on mac 10.10 and/or 10.11?  Thanks.

**Comment by ilarik** [comment] 2016-02-04 01:11
I confirm a fully working build for irods-icommands from the 4-1-stable branch on OS X 10.11 with the following installed:

- OSXFUSE 2.8.2
- Perl JSON module
- Homebrew, configured with
`brew tap homebrew/dupes; brew install autoconf automake curl wget libiconv help2man libtool mysql openssl pcre pkg-config shtool zlib bzip2 libxml2`

There was one issue when building the kanki-irodsclient against the newly built irods-icommands, I had to add the object `$(libClientExecObjDir)/irods_client_rule_execution_manager_factory.o` to the linkage. Is it possible and/or feasible for you to add the previous to the lib `libRodsAPIs.a` in OS X ?

With the previous change the kanki-irodsclient OS X package (which bundles irods-icommands) builds successfully. I'll test tomorrow on OS X 10.10 at the office.

**Comment by jasoncoposky** [comment] 2016-02-04 01:21
we have been working to repartition the development libraries in anticipation of moving to a dynamically linked environment.  can you look at dynamically linking the newer libraries for linking rather than using the libROdsAPIs.a?

**Comment by ilarik** [comment] 2016-02-04 01:23
I'm using the dynamic libraries in Linux but the static one in OS X, is it possible to do a dynamic build for the iRODS libraries in OS X currently out-of-the-box?

**Comment by ilarik** [comment] 2016-02-04 15:55
Update: I can confirm that irods-icommands builds from the 4-1-stable branch on OS X 10.10 with the same configuration as above. 

There is one caveat though which I didn't notice last night: openssl dylibs linkage on the client binaries goes still against the system provided `/usr/lib/libssl.dylib` while the SSL plugin links against the correct Homebrew provided `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib`

This was noticed because it used to cause the SSL handshake to fail in OS X 10.11 while worked in OS X 10.10. Apparently because of some happy accident in the OS X runtime dynamic linker would load the correct dynlib first in 10.10 while in 10.11 loading the other way at runtime and causing a symbol clash. 

Correct linkage IMO:
```
$ otool -L `which ils`                                                                                                                                   
/Applications/iRODS.app/Contents/PlugIns/irods/icommands/ils:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)

$ otool -L /Applications/iRODS.app/Contents/PlugIns/irods/network/libssl.so 
/Applications/iRODS.app/Contents/PlugIns/irods/network/libssl.so:
	.././libssl.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
``` 

The `CL_LDADD` and `MY_CFLAG` make variables in the `platform.mk.template` build configuration now doesn't have the Homebrew openssl additions on `osx_platform` as set by Niclas Jareborg, see pull request #2944

**Comment by trel** [comment] 2016-02-04 17:24
I have duplicated your dynamic linker result - thanks.

Can you tell my why you needed `libiconv` from Homebrew?  I didn't have that declared before, and it was working for me.

**Comment by ilarik** [comment] 2016-02-04 19:40
Great!

Strange, I removed brew `libiconv` install and it builds fine in El Capitan! On the other hand 10.11 appears to ship with libiconv libraries and headers, so definitely the brew package would not be needed, at least not anymore.

I distinctly remember compiling the list of brew packages to install (when writing the blog post about the client with OS X 10.10 build instructions) - starting from scratch and adding a package to the list only if the build failed without it according to compiler error messages. I might have added it by mistake.

**Comment by trel** [comment] 2016-02-04 21:19
Perfect.  I'll get these updates pushed and close this issue.

**Closed** 2016-02-04 21:20 UTC
Labels: bug

**Comment by trel** [comment] 2016-02-06 17:01
just confirmed 4-1-stable building icommands on 10.8 through 10.11.
