### ISSUE TITLE
iRods Postgres database plugin fails to recognize previous installation of Postgres 10 ODBC on Centos 7.4

### ISSUE THREAD

**Issue by cbcunc** [irods/irods#3869] opened 2018-04-04 19:04 UTC
### iRODS Version, OS and Version
4.2.2
CentOS Linux release 7.4.1708 (Core)

### What did you try to do?
`sudo yum install irods-server irods-database-plugin-postgres`

### Expected behavior
Install the packages

### Observed behavior
iRods Postgres database plugin fails to recognize previous installation of Postgres ODBC:

```
$ sudo yum install irods-server irods-database-plugin-postgres
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
11 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package irods-database-plugin-postgres.x86_64 0:4.2.2-1 will be installed
--> Processing Dependency: irods-externals-boost1.60.0-0 for package: irods-database-plugin-postgres-4.2.2-1.x86_64
--> Processing Dependency: irods-externals-clang-runtime3.8-0 for package: irods-database-plugin-postgres-4.2.2-1.x86_64
--> Processing Dependency: irods-externals-zeromq4-14.1.3-0 for package: irods-database-plugin-postgres-4.2.2-1.x86_64
--> Processing Dependency: irods-externals-jansson2.7-0 for package: irods-database-plugin-postgres-4.2.2-1.x86_64
--> Processing Dependency: authd for package: irods-database-plugin-postgres-4.2.2-1.x86_64
--> Processing Dependency: irods-externals-libarchive3.1.2-0 for package: irods-database-plugin-postgres-4.2.2-1.x86_64
--> Processing Dependency: postgresql-odbc for package: irods-database-plugin-postgres-4.2.2-1.x86_64
--> Processing Dependency: irods-externals-avro1.7.7-0 for package: irods-database-plugin-postgres-4.2.2-1.x86_64
---> Package irods-server.x86_64 0:4.2.2-1 will be installed
--> Processing Dependency: irods-icommands = 4.2.2 for package: irods-server-4.2.2-1.x86_64
--> Processing Dependency: irods-runtime = 4.2.2 for package: irods-server-4.2.2-1.x86_64
--> Processing Dependency: python-psutil for package: irods-server-4.2.2-1.x86_64
--> Processing Dependency: python-requests for package: irods-server-4.2.2-1.x86_64
--> Processing Dependency: python-jsonschema for package: irods-server-4.2.2-1.x86_64
--> Running transaction check
---> Package authd.x86_64 0:1.4.3-42.el7 will be installed
---> Package irods-database-plugin-postgres.x86_64 0:4.2.2-1 will be installed
--> Processing Dependency: postgresql-odbc for package: irods-database-plugin-postgres-4.2.2-1.x86_64
---> Package irods-externals-avro1.7.7-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-boost1.60.0-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-clang-runtime3.8-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-jansson2.7-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-libarchive3.1.2-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-zeromq4-14.1.3-0.x86_64 0:1.0-1 will be installed
---> Package irods-icommands.x86_64 0:4.2.2-1 will be installed
---> Package irods-runtime.x86_64 0:4.2.2-1 will be installed
---> Package python-requests.noarch 0:2.6.0-1.el7_1 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-1.el7_1.noarch
---> Package python2-jsonschema.noarch 0:2.5.1-3.el7 will be installed
--> Processing Dependency: python-repoze-lru for package: python2-jsonschema-2.5.1-3.el7.noarch
---> Package python2-psutil.x86_64 0:2.2.1-3.el7 will be installed
--> Running transaction check
---> Package irods-database-plugin-postgres.x86_64 0:4.2.2-1 will be installed
--> Processing Dependency: postgresql-odbc for package: irods-database-plugin-postgres-4.2.2-1.x86_64
---> Package python-repoze-lru.noarch 0:0.4-3.el7 will be installed
---> Package python-urllib3.noarch 0:1.10.2-3.el7 will be installed
--> Processing Dependency: python-six for package: python-urllib3-1.10.2-3.el7.noarch
--> Running transaction check
---> Package irods-database-plugin-postgres.x86_64 0:4.2.2-1 will be installed
--> Processing Dependency: postgresql-odbc for package: irods-database-plugin-postgres-4.2.2-1.x86_64
---> Package python-six.noarch 0:1.9.0-2.el7 will be installed
--> Finished Dependency Resolution
Error: Package: irods-database-plugin-postgres-4.2.2-1.x86_64 (renci-irods)
           Requires: postgresql-odbc
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

$ sudo yum list postgresql*
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
11 packages excluded due to repository priority protections
Installed Packages
postgresql10.x86_64                            10.3-1PGDG.rhel7                @pgdg10
postgresql10-contrib.x86_64                    10.3-1PGDG.rhel7                @pgdg10
postgresql10-libs.x86_64                       10.3-1PGDG.rhel7                @pgdg10
postgresql10-odbc.x86_64                       10.02.0000-1PGDG.rhel7          @pgdg10
postgresql10-server.x86_64                     10.3-1PGDG.rhel7                @pgdg10
Available Packages
postgresql-jdbc.noarch                         42.2.2-1.rhel7                  pgdg10
postgresql-jdbc-javadoc.noarch                 42.2.2-1.rhel7                  pgdg10
postgresql-pgpool-II.x86_64                    3.4.6-1.el7                     epel
postgresql-pgpool-II-devel.x86_64              3.4.6-1.el7                     epel
postgresql-pgpool-II-extensions.x86_64         3.4.6-1.el7                     epel
postgresql-plruby.x86_64                       0.5.3-13.el7                    epel
postgresql-plruby-doc.x86_64                   0.5.3-13.el7                    epel
postgresql-unit10.x86_64                       6.0-1.rhel7                     pgdg10
postgresql-unit10-debuginfo.x86_64             6.0-1.rhel7                     pgdg10
postgresql10-debuginfo.x86_64                  10.3-1PGDG.rhel7                pgdg10
postgresql10-devel.x86_64                      10.3-1PGDG.rhel7                pgdg10
postgresql10-docs.x86_64                       10.3-1PGDG.rhel7                pgdg10
postgresql10-plperl.x86_64                     10.3-1PGDG.rhel7                pgdg10
postgresql10-plpython.x86_64                   10.3-1PGDG.rhel7                pgdg10
postgresql10-pltcl.x86_64                      10.3-1PGDG.rhel7                pgdg10
postgresql10-tcl.x86_64                        2.4.0-1.rhel7                   pgdg10
postgresql10-tcl-debuginfo.x86_64              2.3.1-1.rhel7                   pgdg10
postgresql10-test.x86_64                       10.3-1PGDG.rhel7                pgdg10
```

### Steps to reproduce

1. Install postgresql10-odbc.x86_64 from official PGDG
2. Attempt to install irods-database-plugin-postgres

### Failed Workaround

```
$ sudo yum install --skip-broken irods-database-plugin-postgres
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
11 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package irods-database-plugin-postgres.x86_64 0:4.2.2-1 will be installed
--> Processing Dependency: authd for package: irods-database-plugin-postgres-4.2.2-1.x86_64
--> Processing Dependency: postgresql-odbc for package: irods-database-plugin-postgres-4.2.2-1.x86_64
--> Running transaction check
---> Package authd.x86_64 0:1.4.3-42.el7 will be installed
---> Package irods-database-plugin-postgres.x86_64 0:4.2.2-1 will be installed
--> Processing Dependency: postgresql-odbc for package: irods-database-plugin-postgres-4.2.2-1.x86_64
base/7/x86_64/filelists_db                                     | 6.7 MB  00:00:00
renci-irods/7/x86_64/filelists_db                              | 121 kB  00:00:00

Packages skipped because of dependency problems:
    authd-1.4.3-42.el7.x86_64 from base
    irods-database-plugin-postgres-4.2.2-1.x86_64 from renci-irods
```

### Current work-around

```
$sudo yum install -y postgresql-odbc
$sudo emacs /etc/yum.repos.d/CentOS-Base.repo # add exclude=postgresql* to [base] and [updates]
$sudo yum install https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7.4-x86_64/pgdg-centos10-10-2.noarch.rpm
$sudo yum makecache fast
$sudo yum install -y \
     postgresql10 \
     postgresql10-server \
     postgresql10-contrib \
     postgresql10-libs \
     postgresql10-odbc \
     unixODBC
```

**Comment by cbcunc** [comment] 2020-04-01 20:37
This issue has moved through six release milestones in two years now. I still do the workaround every time I install iRODS. I may soon be embedded in an Ansible playbook. Was kinda hoping not to have to.

**Comment by trel** [comment] 2020-04-01 21:13
The problem is that the `irods-database-plugin-postgres` package declares a dependency on `postgresql-odbc` that isn't satisfied by `postgresql10-odbc` being installed, correct?

Is there a way to declare a dependency on `packageA` OR `packageB`?

Or, in the reverse sense... make it so that `postgresql10-odbc` `Provides` `postgresql-odbc`?

https://rpm.org/user_doc/dependencies.html#provides
https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides

**Comment by cbcunc** [comment] 2021-12-13 14:20
Three and a half years later, I'm starting the install of an ICAT server over because this is still an issue. Now postgresql14 and Centos 7.9. I don't have control of the postgresql14 package, nor should I need to. Can irods irods-database-plugin-postgres somehow declare a dependency on postgresql*-odbc? It's weird that irods-server is not dependent on a non-versioned postgres package, but the database plugin is.

**Comment by trel** [comment] 2021-12-13 14:33
I don't think packages can declare dependencies with wildcards.

We're still on iRODS 4.2 for what you're seeing, and we have not changed the packaging very much in the stable branch.  Do you know how we can solve this?   We haven't seen this anywhere else.

That said... be aware of https://github.com/irods/irods/issues/5325 as you go beyond PG11.

Does this go away on Rocky/AlmaLinux8? (to be supported in the upcoming iRODS 4.3 release)

**Comment by korydraughn** [comment] 2024-10-15 18:50
CentOS 7 and PostgreSQL 10 have reached EOL.

For users still running CentOS 7, consider upgrading to Almalinux 8+ or Rocky Linux 8+. They have been tested against PostgreSQL 14 and later.

Closing.

**Closed by korydraughn** 2024-10-15 18:50 UTC
Labels: resolved/invalid, packaging, consortium-member
