### ISSUE TITLE
irepl in backup mode reports wrong error

### ISSUE THREAD

**Issue by ciklysta** [irods/irods#7951] opened 2024-09-06 08:33 UTC
### iRODS Version, OS and Version

4.3.0

### What did you try to do?

We have the following resource hierarchy:

```
CacheResource:passthru
└── CacheDiskResource:unixfilesystem
NFSResource:passthru
└── NFSReplica:deferred
    ├── NFSVolume0000Passthru:passthru
    │   └── NFSVolume0000:unixfilesystem
    ├── NFSVolume0001Passthru:passthru
    │   └── NFSVolume0001:unixfilesystem
    └── NFSVolume0002Passthru:passthru
        └── NFSVolume0002:unixfilesystem
```

If I run `irepl -B -M -S CacheResource -R NFSResource -N 1 /nkZone/LTPStorage/prod_2024_08_25_ndk_000000500394_md01_2_2528601.zip` under the admin user and there is already a healthy replica in the target resource, I get this error

```
remote addresses: 127.0.0.1 ERROR: replUtil: repl error for /nkZone/LTPStorage/prod_2024_08_25_ndk_000000500394_md01_2_2528601.zip, status = -168000 status = -168000 SYS_REPLICA_INACCESSIBLE
Level 0: SYS_REPLICA_INACCESSIBLE: hierarchy descending from specified source resource name [CacheResource] does not have a replica or the replica is inaccessible at this time
```

and the return code of the command is 3

### Expected behavior

Documentation says: _-B  Backup mode - if a good copy already exists in this resource, don't make another copy._ Therefore I would expect the command to return 0 and not to report a misleading error _SYS_REPLICA_INACCESSIBLE_.

### Observed behavior (including steps to reproduce, if applicable)

A relevant piece of information might be that the object is not owned by _admin_, but some normal unprivileged user.
However, if I run that command under the user that owns the object, I observe the same behavior.

**Comment by trel** [comment] 2024-09-06 13:08
Thanks for the report.  I'm not sure the intended design of the `-B` option.

Can you do what you are attempting to do without the `-B` option?

If so... we should consider deprecating and then removing the option.

**Comment by alanking** [comment] 2024-09-06 13:36
I was able to reproduce the incorrect error on both 4.3.0 and 4.3.3. However, backup mode (`irepl -B`) has been deprecated as of 4.3.2 (https://github.com/irods/irods/issues/6953).

**Comment by trel** [comment] 2024-09-06 13:45
Ah, very good.

And I see removal is scheduled in 5.0.0... https://github.com/irods/irods/issues/7594

I think we close this as resolved.

**Comment by korydraughn** [comment] 2024-09-06 14:05
Agreed.

This can be closed now that it points to the deprecation and removal issues.

**Closed** 2024-09-06 14:09 UTC
Labels: resolved/invalid, bug
