### ISSUE TITLE
Free space check done on iCAT instead of the resource server

### ISSUE THREAD

**Issue by fconagy** [irods/irods#3340] opened 2016-10-24 12:30 UTC
With version 4.1.9 the unix file system plugin seems to check if
there is enough free space before writing the file. When the
destination is a resource on a server different from the iCAT
server, in our case it was incorrectly reported that there is not
enough space to store the file in the vault. Checking the source suggests that
the check for free space is actually done on the iCAT server
instead of the resource server. This scenario had been verified on
a test setup.

**Comment by ilarik** [comment] 2016-10-24 12:41
I was able to replicate this scenario in a clean virtual environment configured similarly as our actual setup. The iCAT server log reflects that it is unable to find a valid child resource when the filesystem present on the iCAT server with similar paths hasn't got enough space.

```
Oct 23 09:25:16 pid:31452 NOTICE: Agent process 28560 started for puser=rods and cuser=rods from 192.168.56.1
Oct 23 09:25:30 pid:31452 NOTICE: Agent process 28564 started for puser=rods and cuser=rods from 192.168.56.1
Oct 23 09:25:30 pid:28564 ERROR: [-]    iRODS/server/api/src/rsDataObjPut.cpp:89:rsDataObjPut :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [rsDataObjPut :: failed in irods::irods::resolve_resource_hierarchy for [/tempZone/home/rods/testfile1G]]
    [-]    iRODS/server/core/src/irods_resource_redirect.cpp:291:resolve_hier_for_create :  status [NO_NEXT_RESC_FOUND]  errno [] -- message []
        [-]    iRODS/server/core/src/irods_resource_redirect.cpp:74:request_vote_for_file_object :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [failed in call to redirect host [rodsmaster1]  hier []]
            [-]    librepl.cpp:1528:replRedirect :  status [NO_NEXT_RESC_FOUND]  errno [] -- message []
                [-]    librepl.cpp:1476:repl_redirect_impl :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [repl_redirect_impl - Failed to redirect to all children.]
                    [-]    librepl.cpp:1307:replRedirectToChildren :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [replRedirectToChildren - Failed calling redirect on the child "notPDC"]
                        [-]    librandom.cpp:829:random_redirect :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [Failed getting next valid child.]
                            [-]    librandom.cpp:758:get_next_valid_child_resource :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [No valid child found.]
```

It looks like the redirect of the `irods::RESOURCE_OP_FREESPACE` operation doesn't never get executed in the actual resource server but on the iCAT host.

**Comment by trel** [comment] 2016-10-24 13:22
This is a duplicate of #3306 and the reason for 4.1.10.

Thank you both.

**Closed by trel** 2016-10-24 13:22 UTC
