### ISSUE TITLE
FUSE (irodsFs) does not exit with an error code on "non empty" mount point

### ISSUE THREAD

**Issue by jerry57** [irods/irods#2275] opened 2014-08-14 17:09 UTC
Running `irodsFs $HOME/fuse_mount` will fail to mount if the `fuse_mount` directory contains anything already.  It displays a message about using a "nonempty" parameter and fails to mount.

If you are trying to use `irodsFs` as part of a shellscript, it would be nice to be able to trap the response exit code to know if the script should continue or not.  ie: if mount fails, exit script with message.

Example:

``` bash
irodsFs $HOME/fuse_mount  >> $LOGFILE 2>&1
if [ "$?" = "0" ]; then
    echo "iRODS FUSE exitcode was [$?]" >> $LOGFILE
else
    echo "FUSE exited with an error" >> $LOGFILE
    echo "FUSE exitcode was [$?]" >> $LOGFILE
    exit 1
fi
```

**Comment by trel** [comment] 2015-09-10 16:02
@iychoi is this handled now?

**Comment by iychoi** [comment] 2015-09-10 16:50
It seemed this isn't shown when I did a quick test. Let me try this again for double check.

**Comment by iychoi** [comment] 2015-09-14 03:47
When I test this, it returns an error immediately with messages below:
/irods_mount/
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option

With a -ononempty parameter on command-line, it works fine and this seems correct.

**Comment by trel** [comment] 2015-09-14 13:22
@iychoi the issue is that the return-code is still `0`.

@jerry57 is requesting it return a non-zero code if the mountpoint does not mount.

  
```
$ mkdir testmountpoint
$ touch testmountpoint/foo
$ irodsFs testmountpoint/
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
$ echo $?
0
```

this should be

```
$ echo $?
1
```

**Comment by iychoi** [comment] 2015-09-15 10:32
I commit a patch to handle this on #2877 .

**Comment by trel** [comment] 2017-02-10 18:44
closing

**Closed by trel** 2017-02-10 18:44 UTC
Labels: bug
