### ISSUE TITLE
Fresh 4.2.7 install server starts but operations fail NO_MICROSERVICE_FOUND_ERR

### ISSUE THREAD

**Issue by mcv21** [irods/irods#5274] opened 2020-11-25 13:00 UTC
### iRODS Version, OS and Version
iRODS 4.2.7, Ubuntu 18.04

### What did you try to do?
Fresh install of 4.2.7 irods consumer to join an existing zone, using unattended_install.json. That JSON file (with secrets replaced by fish):
```JSON
{
    "admin_password": "FISH1",
    "host_access_control_config": {
        "access_entries": []
    },
    "host_system_information": {
        "service_account_user_name": "irods-cgp",
	"service_account_group_name": "cancer"
    },
    "hosts_config":
        {
            "host_entries": [], 
            "schema_name": "hosts_config", 
            "schema_version": "v3"
        },
    "service_account_environment":
        {
    "irods_client_server_negotiation": "request_server_negotiation",
    "irods_client_server_policy": "CS_NEG_REQUIRE",
    "irods_connection_pool_refresh_time_in_seconds": 300,
    "irods_cwd": "/cgp/home/irods",
    "irods_default_hash_scheme": "MD5",
    "irods_default_number_of_transfer_threads": 4,
    "irods_default_resource": "demoResc",
    "irods_encryption_algorithm": "AES-256-CBC",
    "irods_encryption_key_size": 32,
    "irods_encryption_num_hash_rounds": 16,
    "irods_encryption_salt_size": 8,
    "irods_home": "/cgp/home/irods",
    "irods_host": "irods-cgp-ig01.internal.sanger.ac.uk",
    "irods_match_hash_policy": "compatible",
    "irods_maximum_size_for_single_buffer_in_megabytes": 32,
    "irods_port": 1247,
    "irods_server_control_plane_encryption_algorithm": "AES-256-CBC",
    "irods_server_control_plane_encryption_num_hash_rounds": 16,
    "irods_server_control_plane_key": "FISH2",
    "irods_server_control_plane_port": 1248,
    "irods_ssl_ca_certificate_file": "/etc/ssl/certs/ca-certificates.crt",
    "irods_ssl_certificate_chain_file": "/etc/irods/chain.pem",
    "irods_ssl_certificate_key_file": "/etc/irods/server.key",
    "irods_ssl_dh_params_file": "/etc/irods/dhparams.pem",
    "irods_ssl_verify_server": "cert",
    "irods_transfer_buffer_size_for_parallel_transfer_in_megabytes": 4,
    "irods_user_name": "irods",
    "irods_zone_name": "cgp",
    "schema_name": "irods_environment",
    "schema_version": "v3"
},
    "server_config":
        {
    "advanced_settings": {
        "default_number_of_transfer_threads": 4, 
        "default_temporary_password_lifetime_in_seconds": 120, 
        "maximum_number_of_concurrent_rule_engine_server_processes": 4, 
        "maximum_size_for_single_buffer_in_megabytes": 32, 
        "maximum_temporary_password_lifetime_in_seconds": 1000, 
        "rule_engine_server_execution_time_in_seconds": 120, 
        "rule_engine_server_sleep_time_in_seconds": 30, 
        "transfer_buffer_size_for_parallel_transfer_in_megabytes": 4, 
        "transfer_chunk_size_for_parallel_transfer_in_megabytes": 40
    }, 
    "catalog_provider_hosts": [
        "irods-cgp-g1-vm.internal.sanger.ac.uk"
    ],
    "catalog_service_role": "consumer", 
    "default_dir_mode": "0750", 
    "default_file_mode": "0640", 
    "default_hash_scheme": "MD5", 
    "default_resource_directory": "/var/lib/irods/iRODS/Vault", 
   "default_resource_name": "irods-cgp-ig01Resource",
    "environment_variables": {
        "LC_ALL": "en_GB.UTF-8", 
        "NLS_LANG": "AMERICAN_AMERICA.AL32UTF8"
    }, 
    "federation": [],
    "match_hash_policy": "compatible", 
    "negotiation_key": "FISH3", 
  "plugin_configuration": {
    "authentication": {},
    "network": {},
    "resource": {},
    "rule_engines": [
      {
        "instance_name": "irods_rule_engine_plugin-irods_rule_language-instance",
        "plugin_name": "irods_rule_engine_plugin-irods_rule_language",
        "plugin_specific_configuration": {
          "re_data_variable_mapping_set": [
            "core"
          ],
          "re_function_name_mapping_set": [
            "core"
          ],
          "re_rulebase_set": [
            "cgp",
            "core"
          ],
          "regexes_for_supported_peps": [
            "ac[^ ]*",
            "msi[^ ]*",
            "[^ ]*pep_[^ ]*_(pre|post)"
          ]
        },
        "shared_memory_instance": "upgraded_irods_rule_language_rule_engine"
      }
    ]
  },
  "rule_engine_namespaces": [
    ""
  ],
  "schema_name": "server_config",
  "schema_validation_base_uri": "https://schemas.irods.org/configuration",
  "schema_version": "v3",
  "server_control_plane_encryption_algorithm": "AES-256-CBC",
  "server_control_plane_encryption_num_hash_rounds": 16,
  "server_control_plane_key": "FISH4",
  "server_control_plane_port": 1248,
  "server_control_plane_timeout_milliseconds": 10000,
  "server_port_range_end": 20199,
  "server_port_range_start": 20000,
  "xmsg_port": 1279,
  "zone_auth_scheme": "native",
  "zone_key": "FISH5",
  "zone_name": "cgp",
  "zone_port": 1247,
  "zone_user": "irods"
}}
```

### Observed behavior (including steps to reproduce, if applicable)

The setup script makes config files and starts iRODS OK, but fails to make the initial resource (SYS_AGENT_INIT_ERR), and you see similar trying to ils:
```
irods-cgp@irods-cgp-ig01:~$ ils
remote addresses: 10.144.0.68 ERROR: read_client_server_negotiation_message :: received error message -38000
remote addresses: 10.144.0.68 ERROR: _rcConnect: connectToRhost error, server on irods-cgp-ig01.internal.sanger.ac.uk:1247 is probably down status = -38000 SYS_AGENT_INIT_ERR
```
From the log side, we see:
```
Nov 25 12:07:15 pid:15994 remote addresses: 10.144.0.68, 172.30.157.10 ERROR: applyRule: -1102000, [-]  /irods/server/re/include/irods_re_plugin.hpp:325:irods::error irods::dynamic_operation_execution_manager<std::__1::tuple<>, RuleExecInfo *, irods::rule_execution_manager_pack::DONT_AUDIT_RULE>::call(std::string, std::string, OP, As &&...) [T = std::__1::tuple<>, C = RuleExecInfo *, Audit = irods::rule_execution_manager_pack::DONT_AUDIT_RULE, OP = std::__1::function<irods::error (const std::__1::basic_string<char> &, RuleExecInfo *&)>, As = <const std::__1::basic_string<char> &, RuleExecInfo *&>] :  status [NO_MICROSERVICE_FOUND_ERR]  errno [] -- message [default_microservice_manager: no microservice found acChkHostAccessControl]
        [-]     /irods/server/re/src/irods_re_plugin.cpp:111:irods::error irods::default_microservice_manager<RuleExecInfo *>::exec_microservice_adapter(std::string, default_ms_ctx, std::list<boost::any> &) :  status [NO_MICROSERVICE_FOUND_ERR]  errno [] -- message [default_microservice_manager: no microservice found acChkHostAccessControl]

Nov 25 12:07:15 pid:15994 remote addresses: 10.144.0.68, 172.30.157.10 ERROR: initAgent: acChkHostAccessControl error, status = -1102000
Nov 25 12:07:15 pid:15994 remote addresses: 10.144.0.68, 172.30.157.10 ERROR: agentMain :: initAgent failed: -1102000
Nov 25 12:07:15 pid:15640  ERROR: Agent process [15994] exited with status [1]
```

We also tried putting back the rule_engine_namespaces setting in server_config.json to match what we have elsewhere (in case that was the problem):
```
    "rule_engine_namespaces": [
        "",
        "audit_",
        "indexing_"
    ], 
```
but that didn't change the failure mode. Other than the default resource name, server_config.json is identical to working consumers in the CGP zone.

My colleague tells me he encountered a similar failure trying to install a 4.2.7 provider and gave up and installed 4.1.x and upgraded to 4.2.x instead; so it seems to be a problem with fresh installs of 4.2.7 systems.

**Comment by korydraughn** [comment] 2020-11-25 16:20
We will look into reproducing this and adding tests for it.

**Comment by mcv21** [comment] 2020-11-30 17:34
So I can confirm that @alanking 's suggestion of adding:
```
        {
            "instance_name": "irods_rule_engine_plugin-cpp_default_policy-instance",
            "plugin_name": "irods_rule_engine_plugin-cpp_default_policy",
            "plugin_specific_configuration": {
            }
      },
```
to server_config.json (and its inclusion in unattended_install.json) results in successful installation, but none of our systems upgraded from 4.1.x have this stanza in their server_config.json files and work just fine...

**Comment by korydraughn** [comment] 2020-11-30 17:42
I believe this stanza was needed for the machine that was failing because `acChkHostAccessControl` was not defined anywhere. Can you verify if that PEP is defined in the machines that weren't experiencing problems following the upgrade?

**Comment by mcv21** [comment] 2020-12-02 11:03
Ah, we're getting somewhere now! On an upgraded system:
```
root@irods-seq-sb06:/# grep acChkHostAccessControl /etc/irods/core.re 
# 15) acChkHostAccessControl - This rule checks the access control by host
# acChkHostAccessControl {msiCheckHostAccessControl; }
acChkHostAccessControl { }
```
whereas on a fresh 4.2 install:
```
root@irods-hum-ig01:/# grep acChkHostAccessControl /etc/irods/core.re 
# 15) acChkHostAccessControl - This rule checks the access control by host
# acChkHostAccessControl {msiCheckHostAccessControl; }
```
...which is a consequence of setup_irods templating out core.re at install time, but that file then not being touched in future.

**Comment by trel** [comment] 2020-12-02 14:30
Aha... https://github.com/irods/irods/issues/3549 (specifically https://github.com/irods/irods/commit/76745decafbdad0cfe258479648c31a881acdc61) removed the default empty rules and moved them to the cpp rule engine for 4.2.1.

I don't think there's anything to do for this issue... if agreed, we can close it.

**Comment by mcv21** [comment] 2020-12-02 14:43
If you could just confirm that there's no harm having that additional stanza in the config of a machine that has been upgraded (so has the definition in core.re), that'd be good to know :)

**Comment by trel** [comment] 2020-12-02 14:53
Confirmed, the irods server package now ships with the `cpp_default_policy` rule engine out of the box...

```
$ ls -l /usr/lib/irods/plugins/rule_engines/
total 17508
-rwxr-xr-x 1 root root  1169296 May 21  2020 libirods_rule_engine_plugin-cpp_default_policy.so
-rwxr-xr-x 1 root root  1470256 May 21  2020 libirods_rule_engine_plugin-irods_rule_language.so
-rwxr-xr-x 1 root root   420464 May 21  2020 libirods_rule_engine_plugin-passthrough.so
```

**Closed by trel** 2020-12-02 14:53 UTC
Labels: consortium-member
