### ISSUE TITLE
USER_FILE_TOO_LARGE error from failure to signal resource was modified

### ISSUE THREAD

**Issue by kript** [irods/irods#3468] opened 2017-02-03 14:10 UTC
The error we get/and is returned to the user on an iput seems at odds with what irods is actually saying;
```
Jan 14 05:12:36 pid:30800 ERROR: [-]    iRODS/server/api/src/rsModDataObjMeta.cpp:257:_call_file_modified_for_modification :  status [USER_FILE_TOO_LARGE]  errno [] -- message [_call_file_modified_for_modification - Failed to signal the resource that the data object "/seq/20758/InterOp/ColorMatrixMetricsOut.bin.md5" was modified.]
[-]     iRODS/server/drivers/src/fileDriver.cpp:723:fileModified :  status [USER_FILE_TOO_LARGE]  errno [] -- message [fileModified - Failed to call modified interface.]
[-]     libpassthru.cpp:667:passthru_file_modified :  status [USER_FILE_TOO_LARGE]  errno [] -- message [failed calling child modified.]
[-]     librepl.cpp:492:replFileModified :  status [USER_FILE_TOO_LARGE]  errno [] -- message [Failed to replicate create/write operation for object: "/seq/20758/InterOp/ColorMatrixMetricsOut.bin.md5".]
[-]     librepl.cpp:297:replReplicateCreateWrite :  status [USER_FILE_TOO_LARGE]  errno [] -- message [replReplicateCreateWrite - Failed to replicate the create/write operation to the siblings.]
[-]     irods_replicator.cpp:28:replicate :  status [USER_FILE_TOO_LARGE]  errno [] -- message [replicate - Failed to replicate object "/seq/20758/InterOp/ColorMatrixMetricsOut.bin.md5" with operation "WRITE"]
[-]     irods_create_write_replicator.cpp:64:replicate :  status [USER_FILE_TOO_LARGE]  errno [] -- message [Failed to replicate the data object: "/seq/20758/InterOp/ColorMatrixMetricsOut.bin.md5" from resource: "root;replicate;seq-red;red2;irods-seq-i13-bc" to sibling: "root;replicate;seq-green;green4;irods-seq-sr04-ddn-gc10-12-13-14" - USER_FILE_TOO_LARGE .]
```
Given that it was an MD5 file, there is enough space to write the file, I would imagine;
```
~$ df -h /irods-seq-sr04-ddn-gc10-12-13-14
Filesystem                            Size  Used Avail Use% Mounted on
/dev/mapper/ddn_gc10_vd12_to_14-data   43T   42T  862G  99% /irods-seq-sr04-ddn-gc10-12-13-14
```
However, as its at 99%, and iRODS should have this marked as too full to write to, as we have minimum_free_space_for_create_in_bytes set;
```
irods@irods-seq-sr04:~$ iadmin lr irods-seq-sr04-ddn-gc10-12-13-14
resc_id: 3319662
resc_name: irods-seq-sr04-ddn-gc10-12-13-14
zone_name: seq
resc_type_name: unix file system
resc_net: irods-seq-sr04
resc_def_path: /irods-seq-sr04-ddn-gc10-12-13-14
free_space: 924755439616
free_space_ts 2017-02-03.13:45:55
resc_info: 
r_comment: 
resc_status: up
create_ts 2013-04-22.13:17:35
modify_ts 2017-02-03.13:45:55
resc_children: 
resc_context: minimum_free_space_for_create_in_bytes=2348910274150
resc_parent: green4
resc_objcount: 235980
irods@irods-seq-sr04:~$ bc
bc 1.06.95
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006 Free Software Foundation, Inc.
This is free software with ABSOLUTELY NO WARRANTY.
For details type `warranty'. 
924755439616 - 2348910274150
-1424154834534
```
which it does appear to.

I would say that this is a race condition and that iRODS selected the resource for replication and in between the selection and writing the file enough files had gone in that the resource was now full, and the resources denied the write on that basis.

A couple of things give me pause with this though;

1. 1424154834534 bytes is 11Tb - that's quite a lot of files to write in the intervening time between selection and replication.
2. IIRC the logic had been moved in 4.1.9 preview to deny the write before the replication started (and select another resource), but I could be misremembering. Its possible that the fix was in a later preview of 4.1.10 than we're on in production (we're on 4.1.9 preview3 and 4.1.10 was what came out of 4.1.9~preview10

**Comment by kript** [comment] 2017-02-03 15:10
I should add that this isn't an error thats occurring a lot (but our users say they get it more than I've been able to find evidence in the logs);
```
$ grep -c USER_FILE_TOO_LARGE /var/lib/irods/iRODS/server/log/rodsLog.2017.*
/var/lib/irods/iRODS/server/log/rodsLog.2017.01.01:0
/var/lib/irods/iRODS/server/log/rodsLog.2017.01.06:8
/var/lib/irods/iRODS/server/log/rodsLog.2017.01.11:8
/var/lib/irods/iRODS/server/log/rodsLog.2017.01.16:0
/var/lib/irods/iRODS/server/log/rodsLog.2017.01.21:0
/var/lib/irods/iRODS/server/log/rodsLog.2017.01.26:0
/var/lib/irods/iRODS/server/log/rodsLog.2017.01.31:0
/var/lib/irods/iRODS/server/log/rodsLog.2017.02.01:0
```

**Comment by kript** [comment] 2017-03-16 09:29
Any thoughts on this?

**Comment by trel** [comment] 2017-03-16 13:10
On what date was the 4.1.10-final installed in production?

I think this should have been handled in the run-up to getting 4.1.10 out the door (in on of the previews, but also, I don't remember which one).

**Comment by kript** [comment] 2017-03-16 14:28
That rings a bell. We got everything upgraded 2016-02-13, and I've not heard of it occurring since. I'll confirm and update.

**Comment by trel** [comment] 2017-03-16 14:30
Just to clarify, that's Feb 2017, this year.   Thanks.

**Comment by kript** [comment] 2017-03-16 14:30
<facepalm> Yes, that's what I meant..

**Comment by kript** [comment] 2017-03-16 14:38
We have a report of `-311000 USER_FILE_TOO_LARGE` from the 17th.
However, in auditing the zone I have also found three servers out of the ~30 that are running 4.1.9, evidently missed in the update, one of one which was implicated in the report above, so I'll get them upgraded.

**Comment by trel** [comment] 2017-03-16 14:49
Okay, so I'm going to mark this as a duplicate of #3306 for now - and if something new comes up, we can create a new issue.

The specific commit that addressed the 'race condition' and removed the free_space check on the actual create (after the redirect) is commit https://github.com/irods/irods/commit/7c6544cf2310674e9437055e898f01df384fc879.

**Closed by trel** 2017-03-16 14:49 UTC
Labels: consortium-member
