### ISSUE TITLE
test_parallel_transfer_engine on branch with apparently unrelated changes.

### ISSUE THREAD

**Issue by phdavis1027** [irods/irods#6490] opened 2022-07-21 14:28 UTC
### iRODS Version, OS and Version
iRODS commit 26fe8ada26aa169fb76b0beb91656e9f65e94577
Ubuntu 18.04 Docker Container from the most up-to-date testing environment

### What did you try to do?
Build and test the branch 'metadata-lib-refactoring' using the command:
```
python run_unit_tests.py --project-directory ./projects/ubuntu-18.04/ubuntu-18.04-postgres-10.12 --irods-package-directory ../builds/irods_build --leak-container
```
Where 

### Expected behavior
Metadata-related tests would either pass or fail and other tests would pass.

### Observed behavior (including steps to reproduce, if applicable)
Metadata tests passed, but test_parallel_transfer_engine failed. After building the main branch and running the same test command, all tests succeeded. The test report from the metadata-lib-refactoring branch yielded this junit report: 
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="irods_parallel_transfer_engine" errors="1" failures="0" tests="54" hostname="tbd" time="2.363" timestamp="2022-07-21T14:01:09Z">
    <testcase classname="irods_parallel_transfer_engine.global" name="parallel transfer engine" time="0.164" status="run"/>
    <testcase classname="irods_parallel_transfer_engine.global" name="parallel transfer engine/no restart" time="0.672" status="run"/>
    <testcase classname="irods_parallel_transfer_engine.global" name="parallel transfer engine/with restart" time="0.336" status="run">
      <error message="[&amp;] { using restart_handle_type = typename io::parallel_transfer_engine&lt;SourceStream, SinkStream>::restart_handle_type; restart_handle_type restart_handle; { io::parallel_transfer_engine_builder&lt;SourceStream, SinkStream> builder{_source_stream_factory, _sink_stream_factory, io::close_stream&lt;SinkStream>, _total_bytes_to_transfer}; auto transfer = builder.number_of_channels(_number_of_channels) .offset(_offset) .build(); restart_handle = transfer.restart_handle(); using namespace std::chrono_literals; std::this_thread::sleep_for(250ms); transfer.stop_and_wait(); } io::parallel_transfer_engine&lt;SourceStream, SinkStream> transfer{restart_handle, _source_stream_factory, _sink_stream_factory, io::close_stream&lt;SinkStream>}; transfer.wait(); do { (void)__builtin_constant_p(transfer.success()); Catch::AssertionHandler catchAssertionHandler( &quot;REQUIRE&quot;_catch_sr, ::Catch::SourceLineInfo( &quot;/irods_source/unit_tests/src/test_parallel_transfer_engine.cpp&quot;, static_cast&lt;std::size_t>( 104 ) ), &quot;transfer.success()&quot;, Catch::ResultDisposition::Normal ); try { _Pragma( &quot;clang diagnostic push&quot; ) _Pragma( &quot;clang diagnostic ignored \&quot;-Wparentheses\&quot;&quot; ) catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= transfer.success() ); _Pragma( &quot;clang diagnostic pop&quot; ) } catch(...) { catchAssertionHandler.handleUnexpectedInflightException(); } catchAssertionHandler.complete(); } while( (void)0, (false) &amp;&amp; static_cast&lt;bool>( !!(transfer.success()) ) ); do { (void)__builtin_constant_p(transfer.errors().empty()); Catch::AssertionHandler catchAssertionHandler( &quot;REQUIRE&quot;_catch_sr, ::Catch::SourceLineInfo( &quot;/irods_source/unit_tests/src/test_parallel_transfer_engine.cpp&quot;, static_cast&lt;std::size_t>( 105 ) ), &quot;transfer.errors().empty()&quot;, Catch::ResultDisposition::Normal ); try { _Pragma( &quot;clang diagnostic push&quot; ) _Pragma( &quot;clang diagnostic ignored \&quot;-Wparentheses\&quot;&quot; ) catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= transfer.errors().empty() ); _Pragma( &quot;clang diagnostic pop&quot; ) } catch(...) { catchAssertionHandler.handleUnexpectedInflightException(); } catchAssertionHandler.complete(); } while( (void)0, (false) &amp;&amp; static_cast&lt;bool>( !!(transfer.errors().empty()) ) ); }()" type="REQUIRE_NOTHROW">
FAILED:
  REQUIRE_NOTHROW( [&amp;] { using restart_handle_type = typename io::parallel_transfer_engine&lt;SourceStream, SinkStream>::restart_handle_type; restart_handle_type restart_handle; { io::parallel_transfer_engine_builder&lt;SourceStream, SinkStream> builder{_source_stream_factory, _sink_stream_factory, io::close_stream&lt;SinkStream>, _total_bytes_to_transfer}; auto transfer = builder.number_of_channels(_number_of_channels) .offset(_offset) .build(); restart_handle = transfer.restart_handle(); using namespace std::chrono_literals; std::this_thread::sleep_for(250ms); transfer.stop_and_wait(); } io::parallel_transfer_engine&lt;SourceStream, SinkStream> transfer{restart_handle, _source_stream_factory, _sink_stream_factory, io::close_stream&lt;SinkStream>}; transfer.wait(); do { (void)__builtin_constant_p(transfer.success()); Catch::AssertionHandler catchAssertionHandler( "REQUIRE"_catch_sr, ::Catch::SourceLineInfo( "/irods_source/unit_tests/src/test_parallel_transfer_engine.cpp", static_cast&lt;std::size_t>( 104 ) ), "transfer.success()", Catch::ResultDisposition::Normal ); try { _Pragma( "clang diagnostic push" ) _Pragma( "clang diagnostic ignored \"-Wparentheses\"" ) catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= transfer.success() ); _Pragma( "clang diagnostic pop" ) } catch(...) { catchAssertionHandler.handleUnexpectedInflightException(); } catchAssertionHandler.complete(); } while( (void)0, (false) &amp;&amp; static_cast&lt;bool>( !!(transfer.success()) ) ); do { (void)__builtin_constant_p(transfer.errors().empty()); Catch::AssertionHandler catchAssertionHandler( "REQUIRE"_catch_sr, ::Catch::SourceLineInfo( "/irods_source/unit_tests/src/test_parallel_transfer_engine.cpp", static_cast&lt;std::size_t>( 105 ) ), "transfer.errors().empty()", Catch::ResultDisposition::Normal ); try { _Pragma( "clang diagnostic push" ) _Pragma( "clang diagnostic ignored \"-Wparentheses\"" ) catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= transfer.errors().empty() ); _Pragma( "clang diagnostic pop" ) } catch(...) { catchAssertionHandler.handleUnexpectedInflightException(); } catchAssertionHandler.complete(); } while( (void)0, (false) &amp;&amp; static_cast&lt;bool>( !!(transfer.errors().empty()) ) ); }() )
No such file or directory
at /irods_source/unit_tests/src/test_parallel_transfer_engine.cpp:106
      </error>
    </testcase>
    <testcase classname="irods_parallel_transfer_engine.global" name="stream factory utilities/#5851: stream factory utilities support targeting a specific replica" time="0.404" status="run"/>
    <testcase classname="irods_parallel_transfer_engine.global" name="stream factory utilities/#5851: stream factory utilities support targeting a specific replica/target replica using leaf resource name" time="0.051" status="run"/>
    <testcase classname="irods_parallel_transfer_engine.global" name="stream factory utilities/#5851: stream factory utilities support targeting a specific replica/target replica using replica number" time="0.084" status="run"/>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```

Creating this issue on advice of Kory to figure out what's going on there.

**Comment by korydraughn** [comment] 2022-12-15 22:28
I have not been able to reproduce this issue against 4-2-stable and given the output, it's not clear what would cause this.

Given that several changes have been merged into the server and no one has reported having issues with the test since this issue was reported, I'm going to mark this as `resolved/invalid` and close it.

**Closed** 2022-12-15 22:29 UTC
Labels: resolved/invalid, testing
