### ISSUE TITLE
itouch non existent file creates undeletable object

### ISSUE THREAD

**Issue by darthtux** [irods/irods#6479] opened 2022-07-19 15:51 UTC
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
I am running irods 4.3.0 with icommand 4.3.0
I tried running itouch on a file in irods that does not exist.  Doing so results in a file I have been unable to delete

```
[root@elite ~]# itouch test 
Level 0: SYS_NO_GOOD_REPLICA: No good replicas found.
```
```
-bash-4.2$ ils -L
/msi_test/projects/aso:
  emunsell          0 s3resc            0 2022-07-19.10:08 ? test
        generic    /msi_irods_tier2_poc/msi_test/projects/aso/test
```
As an administrator tried irm
```
-bash-4.2$ irm test
remote addresses: 10.31.6.36 ERROR: rmUtil: rm error for /msi_test/projects/aso/test, status = -1803000 status = -1803000 HIERARCHY_ERROR
```
this was logged on the server
```
Jul 19 10:45:15 elite irodsServer[24375]: {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"[rsDataObjUnlink_impl:334] - [HIERARCHY_ERROR: no valid resource found for data object\n\n]","request_api_name":"DATA_OBJ_UNLINK_AN","request_api_number":615,"request_api_version":"d","request_client_user":"rods","request_host":"10.31.6.36","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"elite.msi.umn.edu","server_pid":24375,"server_timestamp":"2022-07-19T15:45:15.985Z","server_type":"agent"}
```
still as administrator irm -f
```
-bash-4.2$ irm -f test
remote addresses: 10.31.6.36 ERROR: rmUtil: rm error for /msi_test/projects/aso/test, status = -406000 status = -406000 LOCKED_DATA_OBJECT_ACCESS
```
this was logged on the server
```
Jul 19 10:47:50 elite irodsServer[24638]: {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"[rsDataObjUnlink_impl:334] - [HIERARCHY_ERROR: no valid resource found for data object\n\n]","request_api_name":"DATA_OBJ_UNLINK_AN","request_api_number":615,"request_api_version":"d","request_client_user":"rods","request_host":"10.31.6.36","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"elite.msi.umn.edu","server_pid":24638,"server_timestamp":"2022-07-19T15:47:50.677Z","server_type":"agent"}
Jul 19 10:47:50 elite irodsServer[24638]: {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"[try_lock_for_locked_data_object:304] - data object is locked. [path=[/msi_test/projects/aso/test], hierarchy=[s3resc]]","request_api_name":"DATA_OBJ_UNLINK_AN","request_api_number":615,"request_api_version":"d","request_client_user":"rods","request_host":"10.31.6.36","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"elite.msi.umn.edu","server_pid":24638,"server_timestamp":"2022-07-19T15:47:50.682Z","server_type":"agent"}
Jul 19 10:47:50 elite irodsServer[24638]: {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"[_rsDataObjUnlink:285] - unlink not allowed because data object is locked[error code=[-406000], logical path=[/msi_test/projects/aso/test]]","request_api_name":"DATA_OBJ_UNLINK_AN","request_api_number":615,"request_api_version":"d","request_client_user":"rods","request_host":"10.31.6.36","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"elite.msi.umn.edu","server_pid":24638,"server_timestamp":"2022-07-19T15:47:50.682Z","server_type":"agent"}
```
and just for kicks i tried iunreg
```
-bash-4.2$ iunreg -M test
remote addresses: 10.31.6.36 ERROR: rmUtil: rm error for /msi_test/projects/aso/test, status = -1803000 status = -1803000 HIERARCHY_ERROR
```
this was logged on the server
```
Jul 19 10:49:20 elite irodsServer[24796]: {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"[rsDataObjUnlink_impl:334] - [HIERARCHY_ERROR: no valid resource found for data object\n\n]","request_api_name":"DATA_OBJ_UNLINK_AN","request_api_number":615,"request_api_version":"d","request_client_user":"rods","request_host":"10.31.6.36","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"elite.msi.umn.edu","server_pid":24796,"server_timestamp":"2022-07-19T15:49:20.228Z","server_type":"agent"}
```

**Comment by alanking** [comment] 2022-07-19 18:07
Also, please see the Troubleshooting docs for how to remove the offending data object(s): https://docs.irods.org/4.3.0/system_overview/troubleshooting/#data-object-stuck-in-locked-or-intermediate-status

**Comment by JustinKyleJames** [comment] 2022-07-19 18:25
This has previously been reported in irods/irods_resource_plugin_s3#1978.

**Comment by darthtux** [comment] 2022-07-19 18:48
Thanks @alanking and @JustinKyleJames !

I tried to replicate this behavior on a POSIX backed storage resource and the problem did not exist.  So this can be closed as a duplicate of the other issue.  

I do have one last question though.  I tried to remove the object using the link provided but I was unable to  

I am not sure on the replica number so I tried 0 and 1

```
  iadmin modrepl logical_path /msi_test/projects/aso/test replica_number 0 DATA_REPL_STATUS good
  iadmin modrepl logical_path /msi_test/projects/aso/test replica_number 1 DATA_REPL_STATUS good
```
both resulted in this error
```
rcModDataObjMeta failed when modifying replica: [CAT_SQL_ERR (-806000)]
```
Is there another way I can try to remove these objects?

**Comment by alanking** [comment] 2022-07-19 19:13
Ah, the documentation still hasn't been fixed. The replica statuses are actually set by the integer values used in the database when using `iadmin modrepl`. In this case, you will want to use `1` for "good".

The replica number can be seen to the right of the resource which hosts the replica and to the left of the timestamp:
```
$ ils -L
/msi_test/projects/aso:
  emunsell          0 s3resc            0 2022-07-19.10:08 ? test
        generic    /msi_irods_tier2_poc/msi_test/projects/aso/test
```
For this case, the replica number is 0.

So what you typed is very close. Here is what you would want to run:
```
$ iadmin modrepl logical_path /msi_test/projects/aso/test replica_number 0 DATA_REPL_STATUS 1
```

**Comment by darthtux** [comment] 2022-07-19 19:35
Thanks that allowed me to delete the object!

**Comment by alanking** [comment] 2022-07-19 19:45
Ah, very good. I'm going to re-open this for purposes of milestone tracking when we get to fixing this. We will close it once we resolve the duplicate.

**Comment by alanking** [comment] 2022-07-26 15:24
We should also consider closing the L3 descriptor of the open replica in `close_replica` before finalizing: https://github.com/irods/irods_resource_plugin_s3/pull/2077#discussion_r929323322 This would prevent the stat of the S3 object from failing because the zero-length object would then exist.

**Comment by darthtux** [comment] 2022-07-26 15:34
> Ah, very good. I'm going to re-open this for purposes of milestone tracking when we get to fixing this. We will close it once we resolve the duplicate.
> 
> This duplicates #6154

Sounds good.  Also I was thinking about updating the documentation around desired_replica_status.  If you can tell me how to find the different values for stale, good, intermediate, and write-locked.  I will send over a PR to make that more clear.

**Comment by alanking** [comment] 2022-07-26 15:54
@darthtux I recently expanded the documentation from the Troubleshooting section here: https://github.com/irods/irods_docs/commit/d528ae3e7cc004ef34791067ac915e4b648b70d7 Please feel free to make your own edition for consideration and/or feedback for the changes :)

I'm also currently working on a pretty expansive documentation effort to consolidate knowledge about data objects, replicas, logical locking, and various operations that can be performed on data objects and replicas. That progress can be tracked here, if you're interested, but just know that it's a work in progress that may or may not move around or disappear: https://github.com/alanking/irods_docs/tree/data-objects

**Comment by darthtux** [comment] 2022-07-26 15:56
Oh great, thanks for the info!

**Comment by alanking** [comment] 2022-07-27 18:09
Thinking about this more, I'm not convinced this is a duplicate of #6154. While that issue deals with objects getting stuck when an error occurs during the close plugin operation, this issue has to do with the order of operations in `replica_close` (i.e. stat'ing an S3 object on finalize before closing it). Plus, the issue described there is related to `iput`, which uses `rsDataObjClose`, a different operation.

You can also get less serious situation when using `istream` for what I suspect is the same reason, even if the stream writes bytes. Output courtesy of @JustinKyleJames:
```
$ ls -l f1
-rw-rw-r-- 1 irods irods 21 Jul 26 23:45 f1
$ cat f1 | istream write -R s3resc f1
$ ils -l f1
  rods              0 s3resc            0 2022-07-27.17:57 & f1
$ aws s3 ls s3://<redactedbucketname>/amazons3resc/home/rods/f1
2022-07-27 17:57:10         21 f1
```
The finalize step failed to get the correct size of the object because it stats the object before closing it. The result is a 0-length, marked-good replica. I'm not quite sure why this result is different from `itouch` (maybe the seek or write has something to do with it?), but I suspect that this too would be remedied by the order of operation reversal in `replica_close`.

**Closed** 2023-02-20 16:30 UTC
Labels: bug
