### ISSUE TITLE
delay execution server

### ISSUE THREAD

**Issue by xu-hao** [irods/irods#3222] opened 2016-07-12 20:27 UTC
From @lstillwe:

This is irods 4.1.8 

We have experienced some logging issues with the dfcmain main grid.
We are starting to set up some rules that run periodically, and since we have queued up these rules, there have been intermittent logging problems.

For no known reason, logging will suddenly starts spitting out the following:

Jul 12 04:47:12 pid:24213 NOTICE: reServerMain: checking the queue for jobs
Jul 12 04:47:12 pid:24213 NOTICE: getNextQueuedRuleExec: reId 1942177 in RUNNING state. Run again
Jul 12 04:47:12 pid:24213 NOTICE: waitAndFreeReThr: no outstanding child. but runCnt=1
Jul 12 04:47:12 pid:24213 NOTICE: getNextQueuedRuleExec: reId 1942177 in RUNNING state. Run again
Jul 12 04:47:12 pid:24213 NOTICE: waitAndFreeReThr: no outstanding child. but runCnt=1

Once this starts, this message will get printed over and over again, repeating on the order of every 1/100th of a second. If iRODS is not restarted, this will continue until /var runs out of space.

I have collected some information from this most recent occurrence:
(I also have saved the 1.7G reLog file, if you wish to look at that)

Please let me know if you guys have any idea what might cause this.

Thanks,
Lisa

Here is the currently queued rule:

```
-bash-4.1$ iqstat
id     name
1942177
           msiWriteRodsLog("Performing Rebalance for *Resource replication resource", *Status);

           if (errorcode(msiRunRebalance(*Resource)) < 0) {
              msiWriteRodsLog("ERROR: Rebalance for *Resource replication resource Failed", *Status);
           }
           else {
              msiWriteRodsLog("Rebalance for *Resource replication resource complete", *Status);
           }
   |
```

```
-bash-4.1$ ps -ef | grep rods
irods    10321 24212  0 Jul06 ?        00:00:00 irodsAgent
root     17226 17201  0 13:50 pts/1    00:00:00 sudo su - irods
root     17228 17226  0 13:50 pts/1    00:00:00 su - irods
irods    17229 17228  0 13:50 pts/1    00:00:00 -bash
irods    18406 17229  0 14:13 pts/1    00:00:00 ps -ef
irods    18407 17229  0 14:13 pts/1    00:00:00 grep rods
irods    24212     1  0 Jun10 ?        00:10:19 /var/lib/irods/iRODS/server/bin/irodsServer
irods    24213 24212  0 Jun10 ?        06:53:45 irodsReServer
```

```
   top - 14:17:25 up 445 days, 21:11,  2 users,  load average: 0.02, 0.04, 0.01
Mem:   8061572k total,  6100444k used,  1961128k free,    40864k buffers
Swap:  1047548k total,   626932k used,   420616k free,  1967932k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
24213 irods     20   0 3661m 2.9g 4020 S  0.3 37.6 413:45.54 irodsReServer
    1 root      20   0 23508 1164  944 S  0.0  0.0   4:33.08 init
    2 root      20   0     0    0    0 S  0.0  0.0   0:00.18 kthreadd
    3 root      RT   0     0    0    0 S  0.0  0.0   2:44.67 migration/0
    4 root      20   0     0    0    0 S  0.0  0.0   1:40.67 ksoftirqd/0
    5 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/0
    6 root      RT   0     0    0    0 S  0.0  0.0   1:08.43 watchdog/0

-rw------- 1 irods irods 1.7G Jul 12 14:18 reLog.2016.07.11
```

**Comment by trel** [comment] 2016-10-12 14:13
@lstillwe did this get resolved?

**Comment by lstillwe** [comment] 2016-10-12 14:31
Don’t know - have not attempted the same scenario since problem occurred. I was going to wait for 4.1.10 and retry.
I guess you can close in meantime if you feel you have addressed this issue.

On Oct 12, 2016, at 10:13 AM, Terrell Russell <notifications@github.com<mailto:notifications@github.com>> wrote:


@lstillwe<https://github.com/lstillwe> did this get resolved?

**Comment by trel** [comment] 2016-10-12 14:53
no worries - we'll wait.

**Comment by trel** [comment] 2017-08-15 16:40
@lstillwe any news on this?   we can close it if no update.

**Comment by lstillwe** [comment] 2017-08-15 17:44
You can close
On Aug 15, 2017, at 12:40 PM, Terrell Russell <notifications@github.com<mailto:notifications@github.com>> wrote:


@lstillwe<https://github.com/lstillwe> any news on this? we can close it if no update.

**Comment by trel** [comment] 2017-08-15 18:22
Haven't been able to reproduce - closing.

If this comes up again, we can reference this issue, but please don't reopen it.

**Closed** 2017-08-15 18:22 UTC
Labels: resolved/invalid
