### ISSUE TITLE
/var/lib/irods/packaging/setup_irods.sh hangs at end of setup (Ubuntu precise)

### ISSUE THREAD

**Issue by keithj** [irods/irods#2549] opened 2015-03-04 12:42 UTC
Looking at the processes, it seems everything is wating for ````iinit````, which is stuck in ````read````

**Comment by trel** [comment] 2015-03-04 13:54
i wonder what is different...

i have a local bash function to do this handsfree
-- and it passes without incident on current master (66854125068af0d985a3f32d4649931b105b6ab5):

```
$ cat /etc/issue
Ubuntu 12.04.5 LTS \n \l

$ reinstall-irods 
(Reading database ... 1015315 files and directories currently installed.)
Removing irods-database-plugin-postgres ...
Purging configuration files for irods-database-plugin-postgres ...
(Reading database ... 1015296 files and directories currently installed.)
Removing irods-icat ...
Stopping iRODS :: /var/lib/irods/iRODS/irodsctl stop
Stopping iRODS server...
Found 2 processes:
        Stopping process id 2112
        Stopping process id 2117
        Killing process id 2112
        Killing process id 2117
NOTE :: The Local System Administrator should delete these if necessary.
     :: Leaving irods Service Account in place.
     :: try:
     ::      sudo userdel irods
 Removing any system startup links for /etc/init.d/irods ...
   /etc/rc0.d/K20irods
   /etc/rc1.d/K20irods
   /etc/rc2.d/S20irods
   /etc/rc3.d/S20irods
   /etc/rc4.d/S20irods
   /etc/rc5.d/S20irods
   /etc/rc6.d/K20irods
Purging configuration files for irods-icat ...
Processing triggers for ureadahead ...
ureadahead will be reprofiled on next reboot
Processing triggers for man-db ...
Selecting previously unselected package irods-icat.
(Reading database ... 1014719 files and directories currently installed.)
Unpacking irods-icat (from .../irods-icat-4.1.0-64bit.deb) ...
Setting up irods-icat (4.1.0) ...
 Adding system startup for /etc/init.d/irods ...
   /etc/rc0.d/K20irods -> ../init.d/irods
   /etc/rc1.d/K20irods -> ../init.d/irods
   /etc/rc6.d/K20irods -> ../init.d/irods
   /etc/rc2.d/S20irods -> ../init.d/irods
   /etc/rc3.d/S20irods -> ../init.d/irods
   /etc/rc4.d/S20irods -> ../init.d/irods
   /etc/rc5.d/S20irods -> ../init.d/irods

=======================================================================

Welcome to iRODS.

This installation of an iCAT server is currently incomplete and
needs a database plugin to be installed and configured before
it can be started and used.

Please consult the manual for further instructions.

=======================================================================


Processing triggers for man-db ...
Processing triggers for ureadahead ...
Selecting previously unselected package irods-database-plugin-postgres.
(Reading database ... 1015297 files and directories currently installed.)
Unpacking irods-database-plugin-postgres (from .../irods-database-plugin-postgres-1.5.deb) ...
Setting up irods-database-plugin-postgres (1.5) ...

=======================================================================

iRODS Postgres Database Plugin installation was successful.

To configure this plugin, the following prerequisites need to be met:
 - an existing database user (to be used by the iRODS server)
 - an existing database (to be used as the iCAT catalog)
 - permissions for existing user on existing database

Then run the following setup script:
  sudo /var/lib/irods/packaging/setup_irods.sh

=======================================================================

===================================================================

The iRODS service account name needs to be defined.

iRODS service account name [irods]: 
iRODS service group name [irods]: 
===================================================================
Creating Service Group: irods 
Creating Service Account: irods at /var/lib/irods 
===================================================================

You are installing iRODS.

The iRODS server cannot be started until it has been configured.

iRODS server's zone name [tempZone]: 
iRODS server's port [1247]: 
iRODS port range (begin) [20000]: 
iRODS port range (end) [20199]: 
iRODS Vault directory [/var/lib/irods/iRODS/Vault]: 
iRODS server's zone_id [TEMPORARY_zone_id]: 
iRODS server's negotiation_key [TEMPORARY_32byte_negotiation_key]: 
iRODS server's administrator username [rods]: 
iRODS server's administrator password: 

-------------------------------------------
iRODS Zone:             tempZone
iRODS Port:             1247
Range (Begin):          20000
Range (End):            20199
Vault Directory:        /var/lib/irods/iRODS/Vault
zone_id:                TEMPORARY_zone_id
negotiation_key:        TEMPORARY_32byte_negotiation_key
Administrator Username: rods
Administrator Password: Not Shown
-------------------------------------------
Please confirm these settings [yes]: 

Updating /etc/irods/server_config.json...
Updating /var/lib/irods/iRODS/server/icat/src/icatSysInserts.sql...
>>> Copying new database_config.json to [/etc/irods]
===================================================================

You are installing an iRODS database plugin.

The iRODS server cannot be started until its database
has been properly configured.

Database server's hostname or IP address: 
Database server's port [5432]: 
Database name [ICAT]: 
Database username [irods]: 
Database password: 

-------------------------------------------
Database Type:     postgres
Hostname or IP:    localhost
Database Port:     5432
Database Name:     ICAT
Database User:     irods
Database Password: Not Shown
-------------------------------------------
Please confirm these settings [yes]: 

===================================================================
Updating /etc/irods/database_config.json...

Stopping iRODS server...
Found 0 processes:
        There are no iRODS servers running.

-----------------------------
Running irods_setup.pl...

Step 1 of 4:  Configuring database user...
    Creating user's .pgpass...

Step 2 of 4:  Creating database and tables...
    Checking whether iCAT database exists...
        [ICAT] on [localhost] found.
    Updating Postgres UNIX ODBC odbc.ini configuration...
    Updating user's .odbc.ini...
        Touching... /var/lib/irods/.odbc.ini
    Creating iCAT tables...
        Inserting iCAT tables...
    Testing database communications...

Step 3 of 4:  Configuring iRODS server...
        Updating /etc/irods/server_config.json....
        Updating /etc/irods/database_config.json....
    Starting iRODS server with boot environment...
    Opening iRODS connection with boot password...
    Creating iRODS directories...
    Creating iRODS group 'public'...
    Creating iRODS user account...
    Setting iRODS directory ownership...
    Setting iRODS user password...
    Checking for iRODS boot user...
        Removing iRODS boot user...
Found 0 processes:
        There are no iRODS servers running.
    Stopping iRODS server...
Found 0 processes:
        There are no iRODS servers running.

Step 4 of 4:  Configuring iRODS user and starting server...
    Updating iRODS user's ~/.irods/irods_environment.json...
    Starting iRODS server...
    Opening iRODS connection...
    Creating default resource...
        ... Success [demoResc] [/var/lib/irods/iRODS/Vault]
    Testing resource...

Done.  Additional detailed information is in the log file:
    /var/lib/irods/iRODS/installLogs/irods_setup.log

-----------------------------
Running update_catalog_schema.py...
Updating to Catalog Schema... 2
Updating to Catalog Schema... 3
Done.
$ 
```

**Comment by keithj** [comment] 2015-03-04 14:04
````
sudo dpkg -i irods-icat-4.1.0-64bit.deb irods-database-plugin-postgres-1.5.deb 
Selecting previously unselected package irods-icat.
(Reading database ... 307052 files and directories currently installed.)
Unpacking irods-icat (from irods-icat-4.1.0-64bit.deb) ...
Selecting previously unselected package irods-database-plugin-postgres.
Unpacking irods-database-plugin-postgres (from irods-database-plugin-postgres-1.5.deb) ...
Setting up irods-icat (4.1.0) ...
 Adding system startup for /etc/init.d/irods ...
   /etc/rc0.d/K20irods -> ../init.d/irods
   /etc/rc1.d/K20irods -> ../init.d/irods
   /etc/rc6.d/K20irods -> ../init.d/irods
   /etc/rc2.d/S20irods -> ../init.d/irods
   /etc/rc3.d/S20irods -> ../init.d/irods
   /etc/rc4.d/S20irods -> ../init.d/irods
   /etc/rc5.d/S20irods -> ../init.d/irods

=======================================================================

Welcome to iRODS.

This installation of an iCAT server is currently incomplete and
needs a database plugin to be installed and configured before
it can be started and used.

Please consult the manual for further instructions.

=======================================================================


Processing triggers for man-db ...
Processing triggers for ureadahead ...
Setting up irods-database-plugin-postgres (1.5) ...

=======================================================================

iRODS Postgres Database Plugin installation was successful.

To configure this plugin, the following prerequisites need to be met:
 - an existing database user (to be used by the iRODS server)
 - an existing database (to be used as the iCAT catalog)
 - permissions for existing user on existing database

Then run the following setup script:
  sudo /var/lib/irods/packaging/setup_irods.sh

=======================================================================

keith@vim:~/dev$  sudo /var/lib/irods/packaging/setup_irods.sh
===================================================================

The iRODS service account name needs to be defined.

iRODS service account name [irods]: 

iRODS service group name [irods]: 

===================================================================
Existing Group Detected: irods 
Existing Account Detected: irods 
===================================================================

You are installing iRODS.

The iRODS server cannot be started until it has been configured.

iRODS server's zone name [tempZone]: 

iRODS server's port [1247]: 

iRODS port range (begin) [20000]: 

iRODS port range (end) [20199]: 

iRODS Vault directory [/var/lib/irods/iRODS/Vault]: 

iRODS server's zone_id [TEMPORARY_zone_id]: 

iRODS server's negotiation_key [TEMPORARY_32byte_negotiation_key]: 

iRODS server's administrator username [rods]: irods

iRODS server's administrator password: 

-------------------------------------------
iRODS Zone:             tempZone
iRODS Port:             1247
Range (Begin):          20000
Range (End):            20199
Vault Directory:        /var/lib/irods/iRODS/Vault
zone_id:                TEMPORARY_zone_id
negotiation_key:        TEMPORARY_32byte_negotiation_key
Administrator Username: irods
Administrator Password: Not Shown
-------------------------------------------
Please confirm these settings [yes]: 


Updating /etc/irods/server_config.json...
Updating /var/lib/irods/iRODS/server/icat/src/icatSysInserts.sql...
>>> Copying new database_config.json to [/etc/irods]
===================================================================

You are installing an iRODS database plugin.

The iRODS server cannot be started until its database
has been properly configured.

Database server's hostname or IP address: localhost

Database server's port [5432]: 

Database name [ICAT]: 

Database username [irods]: 

Database password: 

-------------------------------------------
Database Type:     postgres
Hostname or IP:    localhost
Database Port:     5432
Database Name:     ICAT
Database User:     irods
Database Password: Not Shown
-------------------------------------------
Please confirm these settings [yes]: 


===================================================================
Updating /etc/irods/database_config.json...

Stopping iRODS server...
Found 0 processes:
        There are no iRODS servers running.

-----------------------------
Running irods_setup.pl...

Step 1 of 4:  Configuring database user...
    Creating user's .pgpass...

Step 2 of 4:  Creating database and tables...
    Checking whether iCAT database exists...
        [ICAT] on [localhost] found.
    Updating Postgres UNIX ODBC odbc.ini configuration...
    Updating user's .odbc.ini...
        Touching... /var/lib/irods/.odbc.ini
    Creating iCAT tables...
        Skipped.  Tables already created.
    Testing database communications...

Step 3 of 4:  Configuring iRODS server...
        Updating /etc/irods/server_config.json....
        Updating /etc/irods/database_config.json....
    Starting iRODS server with boot environment...
    Opening iRODS connection with boot password...
    Opening iRODS connection with admin password...
Found 0 processes:
        There are no iRODS servers running.
^C
````

It never gets to Step 4. The VM had a previous build installed before this, but I removed it
prior to installing using ````synaptic````'s "complete removal" option.

**Comment by trel** [comment] 2015-03-04 14:10
I see it already had the database tables ("Skipped. Tables already created.")...

I'm not sure if that is related to the hanging - I'll try to reproduce.

**Comment by trel** [comment] 2015-03-04 14:13
not sure - worked with the existing tables already in place from the earlier install...

```
$ sudo /var/lib/irods/packaging/setup_irods.sh 
===================================================================

You are installing iRODS.

The iRODS server cannot be started until it has been configured.

iRODS server's zone name [tempZone]: 

iRODS server's port [1247]: 

iRODS port range (begin) [20000]: 

iRODS port range (end) [20199]: 

iRODS Vault directory [/var/lib/irods/iRODS/Vault]: 

iRODS server's zone_id [TEMPORARY_zone_id]: 

iRODS server's negotiation_key [TEMPORARY_32byte_negotiation_key]: 

iRODS server's administrator username [rods]: 

iRODS server's administrator password: 

-------------------------------------------
iRODS Zone:             tempZone
iRODS Port:             1247
Range (Begin):          20000
Range (End):            20199
Vault Directory:        /var/lib/irods/iRODS/Vault
zone_id:                TEMPORARY_zone_id
negotiation_key:        TEMPORARY_32byte_negotiation_key
Administrator Username: rods
Administrator Password: Not Shown
-------------------------------------------
Please confirm these settings [yes]: 


Updating /etc/irods/server_config.json...
Updating /var/lib/irods/iRODS/server/icat/src/icatSysInserts.sql...
===================================================================

You are installing an iRODS database plugin.

The iRODS server cannot be started until its database
has been properly configured.

Database server's hostname or IP address [localhost]: 

Database server's port [5432]: 

Database name [ICAT]: 

Database username [irods]: 

Database password: 

-------------------------------------------
Database Type:     postgres
Hostname or IP:    localhost
Database Port:     5432
Database Name:     ICAT
Database User:     irods
Database Password: Not Shown
-------------------------------------------
Please confirm these settings [yes]: 


===================================================================
Updating /etc/irods/database_config.json...

Stopping iRODS server...
Found 2 processes:
        Stopping process id 11727
        Stopping process id 11729
        Killing process id 11727
        Killing process id 11729

-----------------------------
Running irods_setup.pl...

Step 1 of 4:  Configuring database user...
    Updating user's .pgpass...
        Skipped.  File already uptodate.

Step 2 of 4:  Creating database and tables...
    Checking whether iCAT database exists...
        [ICAT] on [localhost] found.
    Updating Postgres UNIX ODBC odbc.ini configuration...
    Updating user's .odbc.ini...
    Creating iCAT tables...
        Skipped.  Tables already created.
    Testing database communications...

Step 3 of 4:  Configuring iRODS server...
        Updating /etc/irods/server_config.json....
        Updating /etc/irods/database_config.json....
    Starting iRODS server with boot environment...
    Opening iRODS connection with boot password...
    Opening iRODS connection with admin password...
Found 0 processes:
        There are no iRODS servers running.
    Creating iRODS directories...
        Skipped.  Directories already created.
    Creating iRODS group 'public'...
        Skipped.  Group already created.
    Creating iRODS user account...
        Skipped.  Account already created.
    Setting iRODS directory ownership...
    Checking for iRODS boot user...
        No boot user found.
    Stopping iRODS server...
Found 0 processes:
        There are no iRODS servers running.

Step 4 of 4:  Configuring iRODS user and starting server...
    Updating iRODS user's ~/.irods/irods_environment.json...
    Starting iRODS server...
    Opening iRODS connection...
    Creating default resource...
        Skipped.  Resource [demoResc] already created.
    Testing resource...

Done.  Additional detailed information is in the log file:
    /var/lib/irods/iRODS/installLogs/irods_setup.log

-----------------------------
Running update_catalog_schema.py...
Catalog Schema Version is already up to date (version=3).
$
```

**Comment by keithj** [comment] 2015-03-04 14:33
````
└─sudo,4480 /var/lib/irods/packaging/setup_irods.sh
   └─setup_irods.sh,4482 -e /var/lib/irods/packaging/setup_irods.sh
     └─sudo,4558 su - irods -c ORACLE_HOME=; /var/lib/irods/packaging/setup_irods_database.sh
        └─su,4559 - irods -c ORACLE_HOME=; /var/lib/irods/packaging/setup_irods_database.sh
           └─bash,4567 -c ORACLE_HOME=; /var/lib/irods/packaging/setup_irods_database.sh
              └─setup_irods_dat,4568 -e /var/lib/irods/packaging/setup_irods_database.sh
                  └─perl,4637 ./scripts/perl/irods_setup.pl postgres localhost 5432 irods irods
                     └─iinit,4767 irods

$ sudo strace -p 4767
Process 4767 attached - interrupt to quit
read(0, 

````

There was no iRODS server running before I ran the script.

**Comment by keithj** [comment] 2015-03-05 11:51
I've narrowed this down somewhat. The hang does not occur if I drop the ICAT tables before running the script. Neither does it occur if I run the script repeatedly i.e. the 2nd run and beyond have the ICAT tables from the previous run.

The ICAT that I was using when the problem occurred was created during a 4.0.3 install and had been upgraded to 4.1.0 by installing .deb packages. I suspect that something went bad during the upgrade.

**Comment by trel** [comment] 2015-03-05 13:47
That makes a bit more sense.

All the configuration files have been moved/touched since 4.0.3 - and the upgrade path has not been ironed out as much.  It's on the list of things to focus on once our main features are settled.

Thanks.

**Comment by trel** [comment] 2015-03-16 17:59
closing - awaiting upgrade work on #2292

**Closed by trel** 2015-03-16 17:59 UTC
Labels: bug
