### ISSUE TITLE
irm exits success when it should exit with HIERARCHY_ERROR

### ISSUE THREAD

**Issue by keithj** [irods/irods#3566] opened 2017-05-30 15:07 UTC
iRODS 4.1.10, icommands 4.1.10

The following illustrates the situation. The data object is on a resource that is unavailable. `iget` fails as expected, but `irm` reports success.

````
$ irm /seq/trash/orphan/file3
$ echo $?
0
$ ils /seq/trash/orphan/file3
  /seq/trash/orphan/file3

$ iget /seq/trash/orphan/file3 -
ERROR: getUtil: get error for ./file3 status = -1803000 HIERARCHY_ERROR
````

**Comment by tempoz** [comment] 2017-07-11 15:42
I tried to reproduce this on 4.1.10 with 4.1.10 icommands. If I mark the resource down, I get a `HIERARCHY ERROR` for both `iget` and `irm`. If I actually take the resource down by shutting down the resource server hosting it, I get a `USER_SOCK_CONNECT_ERR` for both the `iget` and `irm`. I did this with the trash both on and off and got the same result. What did you do to make the resource 'unavailable'?

**Comment by tempoz** [comment] 2017-07-11 15:45
Ben has pointed out that this may only be in federation, and thus be a dupe of https://github.com/irods/irods/issues/3493 . What do you think?

**Comment by keithj** [comment] 2017-07-11 16:09
The resource is unavailable because it is marked as down (@kript can confirm). This is happening in federation. It seems quite likely that it's the same underlying issue as #3439.

**Closed** 2017-07-11 19:31 UTC
Labels: bug, duplicate
