### ISSUE TITLE
Weird orphaned directory

### ISSUE THREAD

**Issue by fconagy** [irods/irods#5206] opened 2020-10-21 11:40 UTC
### iRODS Version, OS and Version

We are running iRODS 4.2.6 .

### What did you try to do?

The user tries to put files into a collection using WebDAV.
The operation fails. The collection does not seem to have
a parent.

This inconsistency had been reported by Ilari's consistency
checking script:
he consistency check script (https://github.com/KTH-PDC/irods-extras/blob/master/irods-reporting/verify_irods_tree.py) gives out:

CONSISTENCY ERROR: collection id 10800052 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort05-001_1986-2011
CONSISTENCY ERROR: collection id 10800139 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort05-002_1986-2012
CONSISTENCY ERROR: collection id 10800207 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort05-003_1986-2013
CONSISTENCY ERROR: collection id 10800314 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort05-004_1986-2014

Querying from the DB it looks like this:

ICAT=# select coll_id, parent_coll_name, coll_name from r_coll_main where coll_id = 10800052;
 coll_id  |                                             parent_coll_name                                              |                                                         coll_name
----------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------
 10800052 | /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort | /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort05-001_1986-2011
(1 row)

ICAT=# select coll_id, parent_coll_name, coll_name from r_coll_main where coll_id = 10800139;
 coll_id  |                                             parent_coll_name                                              |                                                         coll_name
----------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------
 10800139 | /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort | /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort05-002_1986-2012
(1 row)

ICAT=# select coll_id, parent_coll_name, coll_name from r_coll_main where coll_id = 10800207;
 coll_id  |                                             parent_coll_name                                              |                                                         coll_name
----------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------
 10800207 | /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort | /snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort05-003_1986-2013
(1 row)

ICAT=# select coll_id, parent_coll_name, coll_name from r_coll_main where coll_id = 10800314;
 coll_id  |                                             parent_coll_name                                              |                                                         coll_name
----------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------
 10800314 | /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort | /snic.se/projects/xxx/Arkivet_Gamla_strukturen/SND/Serier/SOM/den<http://snic.se/projects/snd/Arkivet_Gamla_strukturen/SND/Serier/SOM/den> nationella SOM-undersökningen//ta bort05-004_1986-2014
(1 row)

[...user/project name redacted...]

### Expected behavior

User file transfer succeeds.

### Observed behavior (including steps to reproduce, if applicable)

User fails to access collection. Transfer to a different collection works fine.
I don't think we can reproduce this, we suspect it is a result of interaction
between WebDAV and iRODS.

[...reporting on behalf of Ilari...]

Janos

**Comment by trel** [comment] 2020-10-21 11:46
I notice a `//` in the path.

Any chance this is related to https://github.com/UtrechtUniversity/davrods/issues/19 ?

**Comment by fconagy** [comment] 2020-10-21 11:52
On 2020-10-21 11:46, Terrell Russell wrote:
> I notice a `//` in the path.
> 
> Any chance this is related to https://github.com/UtrechtUniversity/davrods/issues/19 ?
> 
> 
> 
Sorry, I don't know.

Janos

**Comment by trel** [comment] 2020-10-21 11:59
When you say WebDAV... are you using davrods?    If so, @cjsmeele could have an opinion...

**Comment by cjsmeele** [comment] 2020-10-21 22:15
Terrell Russell schreef op wo 21-10-2020 om 05:00 [-0700]:
> When you say WebDAV... are you using davrods?    If so, @cjsmeele
> could have an opinion...
> 

Hi! That Davrods issue should be unrelated, as it normalizes URLs
submitted by clients before they reach iRODS.

Clearly something has created an inconsistency in the parent collection
field in the iCAT, but I don't think Davrods should be able to trigger
that.

For what it's worth, those paths in your iCAT look very suspicious.
Almost as if a script or some tool had trouble with the space after
"den" in those file paths, and caused a URL to the same file to be
pasted after it...

**Comment by trel** [comment] 2020-10-21 23:53
Yes, @fconagy, can you share whatever action was taken to get this file into the system?

Was it a drag and drop?   An external script?

How do the angle brackets get into the file name?  The spaces?  The double slash?

**Comment by fconagy** [comment] 2020-10-22 07:44
I don't know. As far as I know the user is using WebDAV as a mounted
file system on a Windows machine. So this all is a bit vague.

Janos

**Comment by ilarik** [comment] 2020-11-10 09:34
Hi,
Sorry about the late response, I thought that there was no need for my input yet...

We are using davrods as the WebDAV gateway, and not to put blame on davrods, but so far, as far as I know, the only users that have been able to provoke this behaviour are our WebDAV users, probably mostly on Windows clients. Last time I checked this specific user group seemed to be using Windows native WebDAV clients (connected as a "mapped network drive").

To try to answer the question by @trel, as far as I can imagine, this would be drag&drop kind of behaviour, since these are normal end users, there are other related projects as well, which use some kind of automation to put in files, and IIRC this misbehaviour hasn't occurred yet with those. And sorry, the angle brackets was probably an intended 'anonymization' by my colleague and/or some markdown typesetting issue, there are no angle brackets or brackets in these paths. The double slash however is there! In the catalog...

If I try to clean up the names to a more readable layout, it would look something like the following.

The error output of the verification script can be reduced to the following:
```
CONSISTENCY ERROR: collection id 10800052 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//ta bort05-001_1986-2011
CONSISTENCY ERROR: collection id 10800139 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//ta bort05-002_1986-2012
CONSISTENCY ERROR: collection id 10800207 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//ta bort05-003_1986-2013
CONSISTENCY ERROR: collection id 10800314 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//ta bort05-004_1986-2014
```
and the entries from the catalog DB look like this:
```
ICAT=# select coll_id, parent_coll_name, coll_name from r_coll_main where coll_id = 10800052;
 coll_id  |             parent_coll_name            |                      coll_name                                                         
----------+-----------------------------------------+----------------------------------------------------------
 10800052 | /snic.se/projects/[proj]/[path]//ta bort | /snic.se/projects/[proj]/[path]//ta bort05-001_1986-2011
(1 row)


ICAT=# select coll_id, parent_coll_name, coll_name from r_coll_main where coll_id = 10800139;
 coll_id  |             parent_coll_name            |                      coll_name                                                         
----------+-----------------------------------------+----------------------------------------------------------
 10800139 | /snic.se/projects/[proj]/[path]//ta bort | /snic.se/projects/[proj]/[path]//ta bort05-002_1986-2012
(1 row)


ICAT=# select coll_id, parent_coll_name, coll_name from r_coll_main where coll_id = 10800207;
 coll_id  |             parent_coll_name            |                      coll_name                                                         
----------+-----------------------------------------+----------------------------------------------------------
 10800207 | /snic.se/projects/[proj]/[path]//ta bort | /snic.se/projects/[proj]/[path]//ta bort05-003_1986-2013
(1 row)


ICAT=# select coll_id, parent_coll_name, coll_name from r_coll_main where coll_id = 10800314;
 coll_id  |             parent_coll_name            |                      coll_name                                                         
----------+-----------------------------------------+----------------------------------------------------------
 10800314 | /snic.se/projects/[proj]/[path]//ta bort | /snic.se/projects/[proj]/[path]//ta bort05-004_1986-2014
(1 row)
```
where `[proj]`= project name and `[path]`= subcollection path inside the project.

To @cjsmeele I can only guess that its probably encoding related, as you say, but something that happens in the backend (the iRODS server/agent) when something goes wrong somewhere along the line. It could be client/firewall/network/WebDAV/apache related, but still one could hope that the server would recover and not mangle the DB in a client operation gone wrong. That's all I can think of yet.

**Comment by ilarik** [comment] 2020-12-10 18:29
Hi,

Any updates on this @trel ?

We have gotten further errors, similar to the ones reported before (and the ones before are still waiting for a fix).

The new ones are similar, but not entirely. Consistency check output:

```
CONSISTENCY ERROR: collection id 25383908 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]018-2015
CONSISTENCY ERROR: collection id 25383985 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]043-2016
CONSISTENCY ERROR: collection id 25382795 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]216-1986
CONSISTENCY ERROR: collection id 25382817 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]228-1987
CONSISTENCY ERROR: collection id 25382860 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]264-1988
CONSISTENCY ERROR: collection id 25382908 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]279-1989
CONSISTENCY ERROR: collection id 25382944 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]296-1990
CONSISTENCY ERROR: collection id 25382985 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]395-1991
CONSISTENCY ERROR: collection id 25383024 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]436-1992
CONSISTENCY ERROR: collection id 25383050 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]465-1993
CONSISTENCY ERROR: collection id 25383071 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]484-1994
CONSISTENCY ERROR: collection id 25383086 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]511-1995
CONSISTENCY ERROR: collection id 25383109 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]589-1996
CONSISTENCY ERROR: collection id 25383139 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]635-1997
CONSISTENCY ERROR: collection id 25383173 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]739-1998
CONSISTENCY ERROR: collection id 25383224 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]746-1999
CONSISTENCY ERROR: collection id 25383252 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]761-2000
CONSISTENCY ERROR: collection id 25383303 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]797-2001
CONSISTENCY ERROR: collection id 25383354 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]801-2002
CONSISTENCY ERROR: collection id 25383379 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]813-2003
CONSISTENCY ERROR: collection id 25383416 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]827-2004
CONSISTENCY ERROR: collection id 25383452 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]851-2005
CONSISTENCY ERROR: collection id 25383500 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]853-2006
CONSISTENCY ERROR: collection id 25383545 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]868-2007
CONSISTENCY ERROR: collection id 25383583 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]878-2008
CONSISTENCY ERROR: collection id 25383629 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]888-2009
CONSISTENCY ERROR: collection id 25383667 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]898-2010
CONSISTENCY ERROR: collection id 25383716 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]912-2011
CONSISTENCY ERROR: collection id 25383755 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]937-2012
CONSISTENCY ERROR: collection id 25383814 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]972-2013
CONSISTENCY ERROR: collection id 25383849 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]990-2014
CONSISTENCY ERROR: collection id 25384051 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]OM 2017
CONSISTENCY ERROR: collection id 25384111 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//[prefix1]OM 2018
CONSISTENCY ERROR: collection id 10800052 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//ta bort05-001_1986-2011
CONSISTENCY ERROR: collection id 10800139 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//ta bort05-002_1986-2012
CONSISTENCY ERROR: collection id 10800207 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//ta bort05-003_1986-2013
CONSISTENCY ERROR: collection id 10800314 has no parent in iCAT!
ORPHAN PATH: /snic.se/projects/[proj]/[path]//ta bort05-004_1986-2014
```
where `[proj]` and `[path]` as before but now we have also `[prefix1]` which is the new lead here. We had a discussion with the user and it looks like that the user was trying to compress (zip) remote directories in Windows Explorer (the iRODS colletction is WebDAV-mounted via a `davrods` gateway) into a subdirectory called `[prefix1]` within `[path]`, which exists as an iRODS collection, but does not have the desired content.

Now here it gets interesting. In the filesystem resources, currently the backing directories for the broken collections do not exist, however there exists one subdirectory, and that is for `[prefix1]` 
```
# for resc in /gpfs/fs1/iRODS/*; do for path in "projects/[proj]/[path]"; do echo $resc; for subdir in "$resc/Vault/$path"/[prefix1]*; do [ -d "$subdir" ] && ls -ld "$subdir" || echo "$subdir does not exist"; done; done; done
/gpfs/fs1/iRODS/eudat
/gpfs/fs1/iRODS/eudat/Vault/projects/[proj]/[path]/[prefix1]* does not exist
/gpfs/fs1/iRODS/fs0resc0
/gpfs/fs1/iRODS/fs0resc0/Vault/projects/[proj]/[path]/[prefix1]* does not exist
/gpfs/fs1/iRODS/fs0resc1
/gpfs/fs1/iRODS/fs0resc1/Vault/projects/[proj]/[path]/[prefix1]* does not exist
/gpfs/fs1/iRODS/fs0resc2
/gpfs/fs1/iRODS/fs0resc2/Vault/projects/[proj]/[path]/[prefix1]* does not exist
/gpfs/fs1/iRODS/fs0resc3
/gpfs/fs1/iRODS/fs0resc3/Vault/projects/[proj]/[path]/[prefix1]* does not exist
/gpfs/fs1/iRODS/resc0
drwxr-x--- 3 irods irods 4096 Dec  3 11:22 /gpfs/fs1/iRODS/resc0/Vault/projects/[proj]/[path]/[prefix1]
/gpfs/fs1/iRODS/resc1
drwxr-x--- 2 irods irods 4096 Dec  3 11:38 /gpfs/fs1/iRODS/resc1/Vault/projects/[proj]/[path]/[prefix1]
/gpfs/fs1/iRODS/resc2
drwxr-x--- 3 irods irods 4096 Dec  3 11:38 /gpfs/fs1/iRODS/resc2/Vault/projects/[proj]/[path]/[prefix1]
/gpfs/fs1/iRODS/resc3
/gpfs/fs1/iRODS/resc3/Vault/projects/[proj]/[path]/[prefix1]* does not exist
/gpfs/fs1/iRODS/snic1
/gpfs/fs1/iRODS/snic1/Vault/projects/[proj]/[path]/[prefix1]* does not exist
# 
```
Further revelations can be found from the filesystem snapshots from the night of the day in question (Dec 3), but I would like to enlist someone from the iRODS consortium to check those with me rather than copy pasting the contents here.

Comments? Anyone available for debugging?

**Comment by trel** [comment] 2020-12-10 20:38
We had a call.

Current best guess is that a manual rename on a Windows 10 machine via WebDAV via davrods, possibly entered a malformed directory (collection) name (perhaps including an errant backslash?) and the following three things are seen as a result:
- a double slash at the beginning of the renamed collection in the catalog
- a loss of trailing slash between the renamed collection and its children in the catalog
- a loss of the first character of its children in the catalog

All the data on disk is still reachable at their `data_path`, but logically, cannot be reached as the collection names no longer have good parent paths and cannot be joined via SQL.

Approach at this time will be to:
- confirm no data loss and manually fix the ~32 entries with bad/mangled collection names
- try to reproduce the name mangling

Possible culprits are one or more of the following:
 - Windows10 (probably not)
 - WebDAV protocol (probably not)
 - davrods implementation (unlikely, but also... most likely?)
 - iRODS 4.2.6 (possible, we've updated our path handling quite a bit in the last year)

**Comment by trel** [comment] 2023-01-31 02:48
Noticing this is still open - and I don't expect we'll be able to reproduce it.

Closing.  Please link to this issue if something similar/identical is seen again.

**Closed by trel** 2023-01-31 02:48 UTC
Labels: resolved/invalid, consortium-member
