### ISSUE TITLE
Calling `iput -f file --metadata "same avus"` throws `CAT_SQL_ERR` and changes the object status to `X`

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6894] opened 2023-02-06 13:23 UTC
### iRODS Version, OS and Version
4.2.11, centos7, mysql

### What did you try to do?

I did try to run the `iput` command with the overwrite option (`-f`) for a data object already registered and with the `--metadata` option for the same avus. 

### Expected behavior
I expect it to overwrite the file and and ignore metadata wanted to be added if already registered for the said data object.

### Observed behavior (including steps to reproduce, if applicable)
I see the `CAT_SQL_ERR` error  and a no good replica status.

```
-bash-4.2$ iput test.txt --metadata "atr3; val; unit; atr4; val1; unit1;"
-bash-4.2$ imeta ls -d test.txt
AVUs defined for dataObj /u0137480/home/rods/test.txt:
attribute: atr3
value:  val
units:  unit
----
attribute:  atr4
value:  val1
units:  unit1
```

Overwrites on the same object:
```
-bash-4.2$ iput -f test.txt --metadata "atr3; val; unit; atr4; val1; unit1;"
remote addresses: 10.0.2.100 ERROR: putUtil: put error for /u0137480/home/rods/test.txt, status = -806000 status = -806000 CAT_SQL_ERR
```

status of the object:
```
-bash-4.2$ ils -L
/u0137480/home/rods:
  rods              0 default;netapp            6 2023-02-06.14:13 X test.txt
        generic    /vault/home/rods/test.txt

```

logs:
```
rsyslogd stdout | 2023-02-06T14:15:05.838458+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: bindVar[1]=10035
rsyslogd stdout | 2023-02-06T14:15:05.838555+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: bindVar[2]=10027
rsyslogd stdout | 2023-02-06T14:15:05.838594+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: bindVar[3]=01675689305
rsyslogd stdout | 2023-02-06T14:15:05.838637+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: bindVar[4]=01675689305
rsyslogd stdout | 2023-02-06T14:15:05.838680+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: _cllExecSqlNoResult: SQLExecDirect error: -1 sql:insert into R_OBJT_METAMAP (object_id, meta_id, create_ts, modify_ts) values (?, ?, ?, ?)
rsyslogd stdout | 2023-02-06T14:15:05.838772+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: SQLSTATE: S1010
rsyslogd stdout | 2023-02-06T14:15:05.838813+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: SQLCODE: 0
rsyslogd stdout | 2023-02-06T14:15:05.838852+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: SQL Error message: [unixODBC][Driver Manager]Function sequence error
rsyslogd stdout | 2023-02-06T14:15:05.838961+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: chlAddAVUMetadata cmlExecuteNoAnswerSql insert failure -806000
rsyslogd stdout | 2023-02-06T14:15:05.839172+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: chlAddAVUMetadata cmlExecuteNoAnswerSql(rollback) succeeded
rsyslogd stdout | 2023-02-06T14:15:05.839313+01:00 dev-u0137480 rodsServer[16623]: u0137480 - NOTICE: rsModAVUMetadata: rcModAVUMetadata failed
rsyslogd stdout | 2023-02-06T14:15:05.860513+01:00 dev-u0137480 rodsServer[16623]: u0137480 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:2:4d87 ERROR: [single_buffer_put:368] - error finalizing replica; [CAT_SQL_ERR: rsModAVUMetadata failed#012#012]

```

### Notes:
This has not occurred in a test with the client and server versions are 4.3.0.

**Comment by trel** [comment] 2023-02-06 13:49
Re: your final note - it works as expected with 4.3.0?   File is uploaded, overwritten, and the AVUs are not changed (b/c they were 'ignored' or 'skipped')?

To make this complete... we'll need to define / explain the behavior if the new metadata is:
 - identical to the original
 - a subset of the original
 - a superset of the original
 - some identical, some new, some missing

**Comment by alanking** [comment] 2023-02-06 13:53
This is a duplicate of #6409 and was fixed for 4.3.0. There had not been plans to include it in the 4.2.x series, but obviously that can be arranged if needed.

**Comment by mstfdkmn** [comment] 2023-02-06 15:35
Ahh sorry I didn't see that issue. Since we are moving to 4.3.0 I guess we personally don't see any need for this. But of course not sure for other users.

@trel, yes that is correct - it works as expected with 4.3.0. Thanks.

**Comment by trel** [comment] 2023-02-07 00:23
Very good.

To answer my own question/comment above...

`iput -f --metadata` should NOT delete any metadata already associated on the target data object.

Any new/different metadata that is passed in should be added to the data object.

We do not / should not consider removing existing metadata during an `iput` command.

**Comment by trel** [comment] 2023-02-07 00:24
Closing this as duplicate.

**Closed by trel** 2023-02-07 00:24 UTC
Labels: bug, consortium-member
