### ISSUE TITLE
Is RedHat Supported?

### ISSUE THREAD

**Issue by kript** [irods/irods#2969] opened 2015-11-26 12:18 UTC
I mostly care about 7.1, but at the moment packages are only built for Centos, so is RedHat a supported installation infrastructure? 

The reason we care is that we may migrate our iRODS systems to RedHat to gain vendor support for the hardware (e.g. HP, or DDN et al), and this is only useful if we are also running on a supported OS for iRODS.

Thanks!

**Comment by trel** [comment] 2015-11-30 14:43
The iRODS Consortium is holding a strict definition of 'supported'.

If it is in Continuous Integration (at https://jenkins.irods.org), then it is supported.  Otherwise, not at this time.

That said, we have bench tested many operating systems that are not included in CI, and have fixed things as we have found them.

RHEL is confirmed to work, and there are many sites using RHEL in production, but it is not currently in our CI, due to its non-zero licensing cost.  If this is something that is key to your organizational policy, we can certainly work out how to get RHEL into CI.

**Comment by jasoncoposky** [comment] 2015-12-10 17:01
closing, as there was no further discussion.

**Closed by jasoncoposky** 2015-12-10 17:01 UTC
Labels: question
