### ISSUE TITLE
irsynch endlessly synching with Odum vs. 4.0.3

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2551] opened 2015-03-04 12:54 UTC
Odum runs irsynch on dataverse, and every time it runs (nightly) it endlessly synchs every file, not seeming to detect checksum matches.  This is preventing DataVerse at Odum to federate with DFC.

Hao and Mike are available to help test with Jon.  We may try installing and running an engineering build of iRODS to see if the problem persists.  Mike verifies that the command is properly formatted and indeed does exhibit the described behavior.

**Comment by trel** [comment] 2015-03-04 13:46
duplicate of #2467

**Closed by trel** 2015-03-04 13:46 UTC
Labels: bug, duplicate
