### ISSUE TITLE
Setting up iRODS fails on Ubuntu 24.04 with Postgres 16

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7742] opened 2024-05-13 23:37 UTC
I was going to treat this as part of #7592, but I decided to open a separate issue so I can have a place to document any potential findings specific to this issue.

When attempting to set up iRODS in an Ubuntu 24.04 container, using the postgres db plugin pointed at a Postgres 16 server in the same container from the distro-provided packages, I get the following error:
```
Listing database tables...
List of tables:
[]
Creating database tables...
Executing SQL in /var/lib/irods/packaging/sql/icatSysTables.sql
Executing SQL statement:
create table R_ZONE_MAIN ( zone_id bigint not null, zone_name varchar(250) not null, zone_type_name varchar(250) not null, zone_conn_string varchar(1000), r_comment varchar(1000), create_ts varchar(32), modify_ts varchar(32)) ;

Rolling back database changes...
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 540, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/lib/irods/scripts/setup_irods.py", line 526, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 134, in setup_server
    database_interface.setup_catalog(irods_config, default_resource_directory=default_resource_directory, default_resource_name=default_resource_name)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 26, in setup_catalog
    if database_connect.create_database_tables(irods_config, cursor) != 'skipped':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/irods/scripts/irods/database_connect.py", line 369, in create_database_tables
    execute_sql_file(sql_file, cursor, by_line=True)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 267, in execute_sql_file
    cursor.execute(line)
pyodbc.ProgrammingError: ('42501', '[42501] ERROR: permission denied for schema public;\nError while executing the query (1) (SQLExecDirectW)')
```

**Comment by SwooshyCueb** [comment] 2024-05-13 23:40
Looks like the solution might be relatively simple: https://stackoverflow.com/q/67276391/6278710

**Comment by korydraughn** [comment] 2024-05-13 23:51
Duplicate of #7382.

**Closed** 2024-06-20 18:49 UTC
Labels: duplicate, bug
