### ISSUE TITLE
data object name does not match filename when name starts with tilde (using iput)

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#4467] opened 2019-08-01 15:22 UTC
- [x] master
- [x] 4-2-stable

### iRODS Version, OS and Version
Centos7 iRODS  4.2.6   (also found in 4.1.11)

### What did you try to do?
Use iput to add a data object with a name starting with tilde character

### Expected behavior
dataobject registered under this name

### Observed behavior (including steps to reproduce, if applicable)
first 2 characters of filename chopped off
NB: registered as issue in the iRODS repo because rods object pathname parsing takes place in lib/core/src/rodsPath.cpp

```
-bash-4.2$ iput VERSION.json '~VERSION.json'
-bash-4.2$ ils
/nluu5a/home/rods:
  ERSION.json
-bash-4.2$ 
```

**Comment by trel** [comment] 2019-08-01 15:37
I believe this is a duplicate of https://github.com/irods/irods/issues/3060 ?

**Comment by trel** [comment] 2019-08-01 15:37
Nope, not a duplicate, that is for a trailing tilde ... but probably the same root cause.

**Comment by stsnel** [comment] 2019-09-06 09:03
This issue also occurs when the first character of the data object name in the iput command is a caret (^, ascii code 94).

**Closed** 2019-09-30 16:23 UTC
Labels: bug, consortium-member
