### ISSUE TITLE
pam_password_max_time not working

### ISSUE THREAD

**Issue by kuntzagk** [irods/irods#3742] opened 2017-11-29 13:53 UTC
- [x] main
- [x] 4-3-stable
---

I have two conflicting interpretations, what this pam_password_max_time should achieve. 

###  1st interpretation

After pam_password_max_time (hours/seconds ?) the user is asked again for his password

### 2nd interpretation

After pam_password_max_time the irods server transparently checkes the cached password again using PAM

### test

I put pam_password_min_time and pam_password_max_time into server_config.json (values 1&2), restarted the server.

As a user with "irods_authentication_scheme": "PAM", I did an iinit. 
This is logged in /var/log/secure
`Nov 28 09:35:39 irods_server PamAuthCheck: pam_warn(irods:auth): function=[pam_sm_authenticate] service=[irods] terminal=[<unknown>] user=[XXXX] ruser=[<unknown>] rhost=[<unknown>]`

After 24 hours I can still do an "ils" and do not see any additional PAM actions logged in /var/log/secure.

**Comment by kuntzagk** [comment] 2017-12-15 11:08
After digging around in the code (my C++ is a little bit rusty) I at least found this:

- in table R_USER_PASSWORD the pass_expiry_ts is set to 1209600 (the default value), so the setting in server_config.json seems to be ignored.

- according to  irods/lib/core/include/irods_configuration_keywords.hpp the configuration keyword is "password_max_time" , but setting this does not work either

**Comment by trel** [comment] 2017-12-15 13:33
Ah, good digging.

**Comment by othmar-weber** [comment] 2018-07-11 06:11
Any progress on this one?

**Comment by jasoncoposky** [comment] 2018-07-11 18:12
@othmar-weber, @kuntzagk 

Per the database plugin, it appears the original intent was to only honor those settings when the TTL was set during the ```iinit``` process.  If you set a ttl, do you get the expected behavior?  

[The code for reference](
https://github.com/irods/irods/blob/master/plugins/database/src/db_plugin.cpp#L7369)

We can discuss whether this makes sense and what the future behavior should be, once we confirm there is no bug with the intended behavior.

**Comment by jasoncoposky** [comment] 2018-08-01 14:03
@othmar-weber, @kuntzagk 

Any updates regarding the use of the TTL?

**Comment by othmar-weber** [comment] 2018-08-02 06:08
@jasoncoposky , @kuntzagk 
Not yet, sorry. Andreas will test that when he is back from vacation.

**Comment by alanking** [comment] 2023-10-23 20:26
I think that this is fixed now if we are going by the 1st interpretation in OP.

**Comment by korydraughn** [comment] 2023-10-23 20:45
Hmm, aren't both interpretations related?

I'd expect you get (1) as a result of (2). The checks for (2) always have to be performed until the time limit is reached.

Thoughts?

**Comment by alanking** [comment] 2023-10-23 21:30
On expiration, prompting the user for the PAM password again is required in order to check with the PAM service because the PAM password is not stored by iRODS.

**Comment by korydraughn** [comment] 2023-10-23 21:39
Sounds good. Close when ready.

**Closed** 2023-11-21 20:29 UTC
Labels: bug, needs-test, consortium-member
