### ISSUE TITLE
Cannot get custom rule to work

### ISSUE THREAD

**Issue by K41eb** [irods/irods#5472] opened 2021-03-08 11:10 UTC
I am trying to make custom processing rules for iRODS and cannot make the simplest rule to work.

### iRODS Version, OS and Version

iRODS 4.2.8
CentOS 7

### What did you try to do? 1/2

In the `core.re` rule file; uncomment the `pep_api_data_obj_put_post` rule and put two `writeline` commands like so:
```
pep_api_data_obj_put_post(*INSTANCE_NAME, *COMM, *DATAOBJINP, *BUFFER, *PORTAL_OPR_OUT) {
  writeline("serverLog", "core.re");
  writeline("stdout", "core.re");
}
```

### Expected behavior 1/2

`core.re` as output of any `iput` command, and maybe a line with `core.re` in a log file (`writeline` is not documented so I don't know where, I assume `/var/lib/irods/log/reLog*`, `/var/lib/irods/log/rodsLog*`, or `/var/lib/irods/log/rodsServerLog*`).

### Observed behavior 1/2

`iput test.txt`:
```
remote addresses: 10.10.10.10 ERROR: putUtil: put error for /TEST_ZONE/home/rods/test.txt, status = -1102000 status = -1102000 NO_MICROSERVICE_FOUND_ERR
```

This error can also be observed if, instead of editing the `core.re`file, I put my rule in an other file `test.re`, mention it in the `server_config.json` and do not uncomment the empty `pep_api_data_obj_put_post` rule in `core.re`.

### What did you try to do? 2/2

In the `core.re` rule file; uncomment the `pep_api_data_obj_put_post` rule and put two `writeline` commands like so:
```
pep_api_data_obj_put_post(*INSTANCE_NAME, *COMM, *DATAOBJINP, *BUFFER, *PORTAL_OPR_OUT) {
  writeline("serverLog", "core.re");
  writeline("stdout", "core.re");
}
```

Make a separate rule file called `test.re` besides the `core.re` file:
```
pep_api_data_obj_put_post(*INSTANCE_NAME, *COMM, *DATAOBJINP, *BUFFER, *PORTAL_OPR_OUT) { 
  writeline("stdout", "test.re"); 
  writeline("serverLog", "test.re"); 
}
```

And add it in the `server_config.json` file:
```
...
"re_rulebase_set": [
      "core",
      "test"
], 
...
```

### Expected behavior 2/2

`core.re` then `test.re` as output of any `iput` command, and maybe two lines with `core.re` and `test.re` in a log file.

### Observed behavior 2/2

`iput test.txt`:
```
<no output>
```

The command successfully `put`s the file but doesn't do anything else, no command output, no logs whatsoever.

# General remarks and feedback

For some reason all log files are dated 2 days in the past compared to what `date` gives me on the system where iRODS and the database are installed. And I did a server restart with `systemctl` beforehand so that should not be the date at which the server was started.

iRODS commands rarely fail elegantly and will output raw errors most of the time, forcing users to investigate whether it's their fault (incorrect configuration / arguments) or a legitimate issue.

**Comment by trel** [comment] 2021-03-08 12:32
It looks like the `NO_MICROSERVICE_FOUND_ERR` in complaining about your call to `writeline`.

Please try `writeLine` with a capital `L`.

**Comment by K41eb** [comment] 2021-03-08 13:41
`NO_MICROSERVICE_FOUND_ERR` == "Undefined function / microservice" =~ misspelled stuff, gotcha

I can now write stuff to the rodsLog* file but the `stdout` variant does not work:
```
Mar  8 14:37:17 pid:16124 remote addresses: 10.10.10.10 ERROR: addMsParam: NULL msParamArray or label input
```

Rule line:
```
writeLine("stdout", "Hello, world!");
```
(copy pasted from the documentation this time)

**Comment by trel** [comment] 2021-03-08 14:36
> log files are dated 2 days in the past compared to what date gives me on the system

The log files for iRODS are rotated, by default, the first of each month and then every five days - so you get rodsLog files with dates ending in 1 and 6.

The logging framework has been overhauled (https://github.com/irods/irods/pull/4075/commits/37778565932fcb141017afc5614da98373ef4ed0) to use syslog in the master branch (for 4.3.0).

----

> Related to #3998?

Very possibly.

`writeLine("stdout", ...)` within a user-run rule via `irule` sends the output back out to the caller's console.
`writeLine("serverLog", ...)` within a user-run rule via `irule` sends the output to the server's rodsLog.

If used in a rule/PEP in the server, `stdout` should behave equivalently to `writeLine("serverLog", ...)`.
If it does not, that is a bug and we will fix it.

**Comment by alanking** [comment] 2021-03-08 14:41
#4018 may be related as well

**Comment by trel** [comment] 2021-03-08 14:46
Just confirmed locally.

Yes, @alanking #4018 is identical.

Marking this as duplicate.

**Closed by trel** 2021-03-08 14:46 UTC
