### ISSUE TITLE
replication resource does not replicate for new empty data object

### ISSUE THREAD

**Issue by anderbubble** [irods/irods#4779] opened 2020-03-08 20:11 UTC
## Bug Report

Since the behavior of the iRODS coordinating resources shouldn't be dependent on client behavior, I expect this is a bug in iRODS, not in DAVRODS

### iRODS Version, OS and Version

- CentOS Linux release 7.7.1908 (Core)
- irods-server-4.2.7-1.x86_64
- civilfritz/docker-davrods:4.2.7

### What did you try to do?

I have this resource hierarchy:

```
rootResc:passthru
└── replResc:replication
    ├── fox1Resc:unixfilesystem
    ├── mybook:unixfilesystem
    └── rsync_net:unixfilesystem
www:passthru
└── ln1:unixfilesystem
```

rootResc is my default resource, defined in server_config.json[default_resource_name] and core.re.

```
acSetRescSchemeForCreate {msiSetDefaultResc("rootResc","null"); }
acSetRescSchemeForRepl {msiSetDefaultResc("rootResc","null"); }
```

```
  "default_resource_name": "rootResc",
```

### Expected behavior

When I copy data to iRODS using DAVRODS I expect files written to rootResc to have replicas on fox1Resc, mybook, and rsync_net.

### Observed behavior (including steps to reproduce, if applicable)

Only a single replica is created, seemingly chosen from the last of the available child resources.

```
[janderson@fox1 ~]$ ils -L "old ogg files/Winter.ogg"
  janderson         0 rootResc;replResc;rsync_net      4324659 2020-03-08.13:49 & Winter.ogg
        generic    /media/rsync.net/Vault/home/janderson/old ogg files/Winter.ogg
```

**Comment by anderbubble** [comment] 2020-03-08 21:48
Looks like I'm not the first to notice this, and it's been going on since 2017.

https://github.com/UtrechtUniversity/davrods/issues/12

**Comment by anderbubble** [comment] 2020-03-08 22:00
Confirmed that this does _not_ happen when using Cyberduck to connect to the webdav share; only when using the macOS Finder WebDAV client.

It'd be good to know what the two clients are doing differently. But, again, I'd say it shouldn't be possible for any client to disrupt this kind of replication.

I also noticed many of these errors during transfers using Finder for WebDAV; but not Cyberduck.

```
[Sun Mar 08 21:46:10.172411 2020] [dav:error] [pid 31] (104)Connection reset by peer: [client 192.168.2.3:59143] Could not write contents to filter.  [500, #0]
[Sun Mar 08 21:46:23.635162 2020] [dav:error] [pid 21] [client 192.168.2.3:59171] Unable to deliver content.  [500, #0]
```

**Comment by trel** [comment] 2020-03-09 13:05
Agreed - for now, this feels like a davrods or webdav issue, rather than a server-side iRODS issue.

**Comment by trel** [comment] 2020-03-09 13:12
That said, the move to all dstream-based data movement in iRODS *should* alleviate this as the number of codepaths on the server will be dramatically reduced and all data movement will hit the same policy enforcement points, regardless of client and access/write method.

**Comment by cjsmeele** [comment] 2020-03-11 12:50
This might be related: it appears that creating empty data objects with rcDataObjCreate/rcDataObjClose (as used by Davrods and PRC) currently does not trigger replication in replication resources (in contrast with an iput of an empty file).

As a result, creating an empty file (with PRC `open()`/`close()`, or with `touch` in davfs and waiting for it to sync), and subsequently writing data to it (whether via `iput -f`, PRC or Davrods) seems to trigger this same issue.

I have an (unconfirmed) suspicion that Finder uses this strategy - PUTting an empty file before writing content to it.

Either way, I do not currently know of a way for Davrods to influence this behavior, and I expect that the reduced codepaths indeed resolve this.

**Comment by trel** [comment] 2020-03-11 13:01
Interesting - that could very well be the case with OSX Finder.   Can confirm that suspicion by instrumenting the create/open/write peps to log their activity.

**Comment by jpmcfarland** [comment] 2021-02-09 12:40
I have found that in addition to macOS (11.1) native client causing this behavior, the Windows (Server 2012 R2) native client causes it as well.  This is quite alarming since most of our users use one of these two for file upload/updates and we replicate across datacenters for data security.

I think the empty file idea of @cjsmeele is the key.  In trying to trigger metadata extraction in acPostProcForPut around 2 years ago, I noticed that the (apparent) standard webdav behavior was to allocate the entire empty file prior to "filling" its contents in.  Once the file existed, an attempt was made to extract the metadata, which failed because the required part of the file content was still missing.  I thought this was typical for webdav, but perhaps it is client specific.

I can see one of two things happening here: either there is a missing notification of when the first replica is fully uploaded preventing the replication trigger, or that the replication of a file allocated in this way is simply not supported.

**Comment by trel** [comment] 2021-02-09 15:24
We are getting closer, but not quite fixed...   We expect fixing the scenario below will fix the same behavior seen via different webdav clients.

With the `zero.py` script from [this issue](https://github.com/irods/irods/issues/5193#issue-721798412)... 

We see the following results...

```
$ ilsresc
replresc:replication
├── ufs1:unixfilesystem
└── ufs2:unixfilesystem
demoResc:unixfilesystem
```

iRODS 4.2.8 - no replication at all (confirming same as davrods):
```
$ python zero.py
$ ils -l
/tempZone/home/rods:
  rods              0 replresc;ufs1            0 2021-02-09.11:09 & irodsctl
```

iRODS 4-2-stable (today) - replication, but still an intermediate replica-0:
```
$ python zero.py
$ ils -l
/tempZone/home/rods:
  rods              0 replresc;ufs1            0 2021-02-09.14:53 ? irodsctl
  rods              1 replresc;ufs2            0 2021-02-09.14:53 & irodsctl
```

**Comment by trel** [comment] 2021-02-10 00:43
Alan has demonstrated a fix at the bench - PR coming soon.

**Comment by alanking** [comment] 2021-04-09 13:50
Demonstrated fix from closing of #5193:
```
$ python zero.py
$ ils -l
/tempZone/home/rods:
  rods              0 repla;leafa            0 2021-04-09.13:48 & VERSION.json
  rods              1 repla;leafc            0 2021-04-09.13:48 & VERSION.json
  rods              2 repla;leafb            0 2021-04-09.13:48 & VERSION.json
```

**Comment by trel** [comment] 2021-04-09 13:53
So we can close this I think...  yes?

**Comment by alanking** [comment] 2021-04-09 14:27
I believe so.

**Closed by alanking** 2021-04-09 14:27 UTC
Labels: bug, consortium-member
