### ISSUE TITLE
iphymv fails -154000 SYS_INTERNAL_ERR if replication puts second replica on same resource

### ISSUE THREAD

**Issue by mcv21** [irods/irods#5070] opened 2020-08-21 10:45 UTC
- [ ] master
- [ ] 4-2-stable
-------

### iRODS Version, OS and Version

irods 4.2.7 / Ubuntu 18.04

### What did you try to do?

We had this object:
```
irods@irods-seq-ies5:~$ ils -L '/seq/10050/10050_6#11.composition.json'
  srpipe            0 irods-sidecar-vdb           61 2019-05-27.21:10 & 10050_6#11.composition.json
    40c5135a3547e4ae39e4542964c9b35c    generic    /data/10050/10050_6#11.composition.json
  srpipe            1 root;replicate;seq-green;green2;irods-seq-sr02-ddn-ra08-0-1-2           61 2019-05-27.21:10 & 10050_6#11.composition.json
    40c5135a3547e4ae39e4542964c9b35c    generic    /irods-seq-sr02-ddn-ra08-0-1-2/10050/10050_6#11.composition.json
  srpipe            2 root;replicate;seq-red;red5;irods-seq-i25-sdd           61 2020-02-17.11:38 & 10050_6#11.composition.json
    40c5135a3547e4ae39e4542964c9b35c    generic    /irods-seq-i25-sdd/10050/10050_6#11.composition.json
```

And we wanted it off the irods-sidecar-vdb resource, so we iphymv'd it to root (expecting to end up with a number of copies in root):
```
irods@irods-seq-ies5:~$ iphymv -M -S irods-sidecar-vdb -R root '/seq/10050/10050_6#11.composition.json'
remote addresses: 10.160.2.33 ERROR: phymvUtil: phymv error for /seq/10050/10050_6#11.composition.json, status = -154000 status = -154000 SYS_INTERNAL_ERR
```

### Expected behavior

We expected to end up with 4 replicas in root, and `iphymv` to return successfully; this means our existing replica-handling code can remove the excess without having to understand what the sidecar resource is.

### Observed behavior (including steps to reproduce, if applicable)

iphymv failed as above, but did leave us with 4 objects. Note the locations and paths of replicas 0 and 2:
```
irods@irods-seq-ies5:~$ ils -L '/seq/10050/10050_6#11.composition.json'
  srpipe            0 root;replicate;seq-red;red5;irods-seq-i25-sdd           61 2019-05-27.21:10 & 10050_6#11.composition.json
    40c5135a3547e4ae39e4542964c9b35c    generic    /irods-seq-i25-sdd/10050/10050_6#11.composition.json.0
  srpipe            1 root;replicate;seq-green;green2;irods-seq-sr02-ddn-ra08-0-1-2           61 2019-05-27.21:10 & 10050_6#11.composition.json
    40c5135a3547e4ae39e4542964c9b35c    generic    /irods-seq-sr02-ddn-ra08-0-1-2/10050/10050_6#11.composition.json
  srpipe            2 root;replicate;seq-red;red5;irods-seq-i25-sdd           61 2020-02-17.11:38 & 10050_6#11.composition.json
    40c5135a3547e4ae39e4542964c9b35c    generic    /irods-seq-i25-sdd/10050/10050_6#11.composition.json
  srpipe            3 root;replicate;seq-green;green6;irods-seq-sb09-sda           61 2020-08-21.11:20 & 10050_6#11.composition.json
    40c5135a3547e4ae39e4542964c9b35c    generic    /irods-seq-sb09-sda/10050/10050_6#11.composition.json
```

So we've ended up with 2 objects in the same resource with different paths (in this case fine, if a bit suboptimal); it seems to be this state that results in `iphymv` failing.

Log-wise, @bh9 reports:
```
Aug 21 10:27:26 pid:25282 remote addresses: 10.160.2.33, 172.17.72.39 ERROR: [-]        /irods/server/api/src/rsDataObjPhymv.cpp:314:int rsDataObjPhymv(rsComm_t *, dataObjInp_t *, transferStat_t **) :  status [SYS_INTERNAL_NULL_INPUT_ERR]  errno [] -- message [null _data_obj_info or _comm]
        [-]     /irods/server/api/src/rsDataObjPhymv.cpp:38:irods::error test_source_replica_for_write_permissions(rsComm_t *, std::string, dataObjInfo_t *) :  status [SYS_INTERNAL_NULL_INPUT_ERR]  errno [] -- message [null _data_obj_info or _comm]
```

**Comment by trel** [comment] 2020-09-03 00:30
We believe this is fixed in 4-2-stable.  Confirming...

**Comment by trel** [comment] 2020-09-03 01:37
4-2-stable `iphymv` appears to be working as intended in this scenario - however, `iphymv` must target a leaf resource... so your existing approach of targeting the root will need to be more precise.

---

preparing the mcv21 use-case 2 from https://github.com/irods/irods/issues/5070#issuecomment-678283124:
```
$ ilsresc
demoResc:unixfilesystem
replResc:replication
├── ufs1:unixfilesystem
└── ufs2:unixfilesystem
sidecar:unixfilesystem

$ ils -L testfile
  rods              3 replResc;ufs1          224 2020-09-02.21:22 & testfile
        generic    /tmp/ufs1Vault/home/rods/testfile
  rods              4 replResc;ufs2          224 2020-09-02.21:22 & testfile
        generic    /tmp/ufs2Vault/home/rods/testfile

$ iphymv -S ufs2 -R sidecar testfile

$ ils -L testfile
  rods              3 replResc;ufs1          224 2020-09-02.21:22 & testfile
        generic    /tmp/ufs1Vault/home/rods/testfile
  rods              4 sidecar          224 2020-09-02.21:22 & testfile
        generic    /tmp/sidecarVault/home/rods/testfile
```

replicating to the root detects it already has one, so is a no-op (same as 4.2.7):
```
$ irepl -R replResc testfile

$ ils -L testfile
  rods              3 replResc;ufs1          224 2020-09-02.21:22 & testfile
        generic    /tmp/ufs1Vault/home/rods/testfile
  rods              4 sidecar          224 2020-09-02.21:22 & testfile
        generic    /tmp/sidecarVault/home/rods/testfile
```

targeting a physical move to the root now demands a leaf resource be named (new in 4-2-stable, to be in 4.2.9):
```
$ iphymv -S sidecar -R replResc testfile
remote addresses: 127.0.1.1 ERROR: phymvUtil: phymv error for /tempZone/home/rods/testfile, status = -361000 status = -361000 USER_INVALID_RESC_INPUT
Level 0: Destination resource must be a leaf - coordinating resource provided.
```

targeting a leaf works cleanly:
```
$ iphymv -S sidecar -R ufs2 testfile

$ ils -L testfile
  rods              3 replResc;ufs1          224 2020-09-02.21:22 & testfile
        generic    /tmp/ufs1Vault/home/rods/testfile
  rods              4 replResc;ufs2          224 2020-09-02.21:23 & testfile
        generic    /tmp/ufs2Vault/home/rods/testfile
```

(perhaps surprisingly, but I believe correctly) targeting the existing leaf will overwrite it:
```
$ iphymv -S ufs2 -R sidecar testfile

$ ils -L testfile
  rods              3 replResc;ufs1          224 2020-09-02.21:22 & testfile
        generic    /tmp/ufs1Vault/home/rods/testfile
  rods              4 sidecar          224 2020-09-02.21:24 & testfile
        generic    /tmp/sidecarVault/home/rods/testfile

$ iphymv -S sidecar -R ufs1 testfile

$ ils -L testfile
  rods              4 replResc;ufs1          224 2020-09-02.21:25 & testfile
        generic    /tmp/ufs1Vault/home/rods/testfile
```

**Comment by trel** [comment] 2020-09-03 02:44
Confirming this is broken in 4.2.8 (but slightly differently than as seen in https://github.com/irods/irods/issues/5070#issuecomment-678283124):
```
$ ils -L testfile
  rods              0 sidecar          224 2020-09-02.22:37 & testfile
        generic    /tmp/sidecarVault/home/rods/testfile
  rods              1 replResc;ufs1          224 2020-09-02.22:37 & testfile
        generic    /tmp/ufs1Vault/home/rods/testfile

$ iphymv -S sidecar -R replResc testfile
remote addresses: 127.0.1.1 ERROR: phymvUtil: phymv error for /tempZone/home/rods/testfile, status = -154000 status = -154000 SYS_INTERNAL_ERR

$ ils -L testfile
  rods              0 replResc;ufs1          224 2020-09-02.22:37 & testfile
        generic    /tmp/ufs1Vault/home/rods/testfile
  rods              1 replResc;ufs1          224 2020-09-02.22:37 & testfile
        generic    /tmp/ufs1Vault/replica/home/rods/testfile.3224487862
  rods              2 replResc;ufs2          224 2020-09-02.22:39 & testfile
        generic    /tmp/ufs2Vault/home/rods/testfile
```

So, this has been fixed in 4-2-stable.  Putting into the 4.2.9 milestone and closing.

**Closed by trel** 2020-09-03 02:44 UTC
Labels: bug, consortium-member

**Comment by trel** [comment] 2020-09-03 02:46
related to https://github.com/irods/irods/issues/4212
