### ISSUE TITLE
msiDataObjChksum replNum does not work

### ISSUE THREAD

**Issue by luijs** [irods/irods#7133] opened 2023-06-26 10:12 UTC
- [x] main (add test)
- [x] 4-3-stable (add test)
---
### iRODS Version, OS and Version
irods version 4.3.0, ubuntu 20.04

### What did you try to do?
I tried to calculate the checksum of one specific replica, using msiDataObjChksum.

### Expected behavior

I have in my code python rule engine code the following line:

```
def checksum_file_in_archive(tarfile,callback):
    generic_msi_status = 1
    callback.msiDataObjChksum(tarfile,"replNum=4++++forceChksum=",generic_msi_status)
```

if I do ```ils -L ``` I see the following:

```
user@machine:~/scripts/archiving$ ils -L /zone/home/user/testbundledir2.tar
  user          4 tape_1;tape_leaf1        10240 2023-06-26.09:58 & testbundledir2.tar
        generic    /tape_leaf1/home/user/testbundledir2.tar
  user          5 tape_2;tape_leaf2        10240 2023-06-26.09:58 & testbundledir2.tar
        generic    /tape_leaf2/home/user/testbundledir2.tar
  user          6 hot_1        10240 2023-06-26.10:00 & testbundledir2.tar
        generic    /local/dir/testbundledir2.tar
```

What I expect is that the checksum of tarfile is calculated and stored in the catalog.

### Observed behavior (including steps to reproduce, if applicable)

The python rule executes without error(expected). However, the checksum of the wrong replica is calculated, it will ignore replNum, and somehow choose a different replica. If I again do an ```ils -L``` I see that not replica 4 has calculated a checksum, but replica 6 somehow did.

```
user@machine:~/scripts/archiving$ ils -L /zone/home/user/testbundledir2.tar
  user          4 tape_1;tape_leaf1        10240 2023-06-26.09:58 & testbundledir2.tar
        generic    /tape_leaf1/home/user/testbundledir2.tar
  user          5 tape_2;tape_leaf2        10240 2023-06-26.09:58 & testbundledir2.tar
        generic    /tape_leaf2/home/user/testbundledir2.tar
  user          6 hot_1        10240 2023-06-26.10:00 & testbundledir2.tar
        generic    /local/dir/testbundledir2.tar
    sha2:6bsejctiNA78PHDlRLPxAnwpvVB4w7E5hhLoc591E/A=    generic    /local/dir/testbundledir2.tar
```

**Comment by korydraughn** [comment] 2023-06-26 13:24
First thing that sticks out is the inputs you're passing to `msiDataObjChksum`. 

The MSI accepts `(DataObjInp or string, string, string)`, but you're passing an integer as the last argument.

Please make the necessary adjustments and see if anything changes. See https://docs.irods.org/4.3.0/doxygen/reDataObjOpr_8cpp.html#aae61683c7a9ab9cc59cb2125426387ef.

**Comment by alanking** [comment] 2023-06-26 13:39
What type of resources are `tape_1` and `tape_2`? I'm guessing that they are weighted passthrus with low read weights. If so, I have reproduced the issue here:
```bash
$ ilsresc -l pt0 | grep context
context: read=0.1
parent context: 
$ ils -L foo
  rods              0 pt0;ufs0          284 2023-06-26.13:27 & foo
        generic    /var/lib/irods/ufs0vault/home/rods/foo
  rods              1 pt1;ufs1          284 2023-06-26.13:27 & foo
        generic    /var/lib/irods/ufs1vault/home/rods/foo
  rods              2 ufs2          284 2023-06-26.13:27 & foo
        generic    /var/lib/irods/ufs2vault/home/rods/foo
$ ichksum -n0 foo
    foo    sha2:0b/caJh7OhG6gOm71ro9pUqHfGnD206PLVtNNJNPojw=
$ ils -L foo
  rods              0 pt0;ufs0          284 2023-06-26.13:27 & foo
        generic    /var/lib/irods/ufs0vault/home/rods/foo
  rods              1 pt1;ufs1          284 2023-06-26.13:27 & foo
    sha2:0b/caJh7OhG6gOm71ro9pUqHfGnD206PLVtNNJNPojw=    generic    /var/lib/irods/ufs1vault/home/rods/foo
  rods              2 ufs2          284 2023-06-26.13:27 & foo
        generic    /var/lib/irods/ufs2vault/home/rods/foo
```

This may be related to https://github.com/irods/irods/issues/6896, the fix for which will be included in 4.3.1.

I have demonstrated that this works as expected on tip of 4-3-stable:
```bash
$ ils -L foo
  rods              0 pt0;ufs0          284 2023-06-26.13:34 & foo
        generic    /var/lib/irods/ufs0vault/home/rods/foo
  rods              1 pt1;ufs1          284 2023-06-26.13:34 & foo
        generic    /var/lib/irods/ufs1vault/home/rods/foo
  rods              2 ufs2          284 2023-06-26.13:34 & foo
        generic    /var/lib/irods/ufs2vault/home/rods/foo
$ ichksum -n0 foo
    foo    sha2:0b/caJh7OhG6gOm71ro9pUqHfGnD206PLVtNNJNPojw=
$ ils -L foo
  rods              0 pt0;ufs0          284 2023-06-26.13:34 & foo
    sha2:0b/caJh7OhG6gOm71ro9pUqHfGnD206PLVtNNJNPojw=    generic    /var/lib/irods/ufs0vault/home/rods/foo
  rods              1 pt1;ufs1          284 2023-06-26.13:34 & foo
        generic    /var/lib/irods/ufs1vault/home/rods/foo
  rods              2 ufs2          284 2023-06-26.13:34 & foo
        generic    /var/lib/irods/ufs2vault/home/rods/foo
```

**Comment by alanking** [comment] 2023-06-26 16:34
I've added tests which exercise this behavior using `ichksum`. Leaving this open in case we want to add tests for the `replNum` keyword and the microservice, and also just in case I've completely missed the mark in terms of what the problem is here.

**Comment by korydraughn** [comment] 2023-06-26 16:46
I tried reproducing this issue and immediately triggered an error due to the incorrect call in the PREP code presented.

Let's wait for @luijs' response before claiming this is resolved/invalid.

**Comment by korydraughn** [comment] 2023-06-27 11:45
Great. Happy to see things are back in order.

**Comment by korydraughn** [comment] 2023-06-27 11:47
> I've added tests which exercise this behavior using `ichksum`. Leaving this open in case we want to add tests for the `replNum` keyword and the microservice, and also just in case I've completely missed the mark in terms of what the problem is here.

Yes, let's add tests for these cases. Can never have too many tests.

**Closed** 2023-06-27 16:58 UTC
Labels: duplicate, bug, needs-test
