### ISSUE TITLE
Ubuntu 22.04 Version Support

### ISSUE THREAD

**Issue by kript** [irods/irods#6597] opened 2022-09-21 15:12 UTC
- [x] main (irods/irods and irods/irods_client_icommands)
- [x] 4-3-stable (irods/irods and irods/irods_client_icommands)
- [x] GitHub Actions (main)
- [x] GitHub Actions (4-3-stable)
- [x] development environment
- [x] testing environment

----

## Feature

My apologies if this is in one of the development updates, but I couldn't find it and I didn't see an issue so I thought I'd ask; since Ubuntu 22.04 is now released, what is the roadmap for it being supported on iRODS (taking into account #4637 ) on both 4.3.x and 4.2.x?

Thanks!

John

**Comment by trel** [comment] 2022-09-21 15:52
We will support Ubuntu22.04 in an upcoming 4.3.x release.  No known blockers at this time.

We will not support Ubuntu22.04 for 4.2.x. - see earlier discussion at https://github.com/irods/irods/issues/4883.

**Comment by alanking** [comment] 2022-09-21 16:04
I have demonstrated that iRODS 4.3.x can build and run on Ubuntu 22.04, but it will require several changes across a few repositories (including, probably, all of the plugins). These mainly have to do with the version bump to OpenSSL 3.0 and a lot of deprecation warnings.

**Comment by korydraughn** [comment] 2023-01-25 16:08
We have not confirmed anything yet. That effort has taken a backseat to other issues. Once those are taken care of, we'll be able to focus on Ubuntu 22.

Is support for Ubuntu 22 urgent?

**Comment by ccacciari** [comment] 2023-02-02 14:40
We offer iRODS to our users in a cloud environment deployed on our infrastructure. iRODS is one of the default components, therefore the missing Ubuntu 22 iRODS packages prevent us to support Ubuntu 22 in that environment, unless we remove iRODS from the default software stack. We would like to offer Ubuntu 22 before the summer.
However, it would be enough to have the icommands client package as a start, not everything. Would providing just the icommands for Ubuntu 22 makes the things easier for you? Or it does not change much?

**Comment by alanking** [comment] 2023-02-02 15:22
I was able to build and install iRODS (future 4.3.1) and iCommands on Ubuntu 22.04 with the following changes:
irods/externals: https://github.com/irods/externals/pull/178
irods/irods: https://github.com/irods/irods/pull/6620
irods/irods_client_icommands: https://github.com/irods/irods_client_icommands/pull/323

I have not tried building the plugins yet, so those will likely require changes to how they are being built.

For completeness, the development and testing environments have changes in the wings as well:
irods_development_environment: https://github.com/irods/irods_development_environment/pull/72
irods_testing_environment: https://github.com/irods/irods_testing_environment/pull/118

Haven't tried this since these PRs were open, but it didn't take me too long to get there back then.

**Comment by trel** [comment] 2023-03-31 14:22
To build the iCommands, we need the `irods-dev` package, which happens when building the server itself.  Pretty sure 4.2.11, as tagged, will not build on Ub22.

The main hurdles with 4.2.x on Ub20+ are/were the Python2/3 differences and the OpenSSL1.0/1.1 differences.

We can look again, but we can't re-release 4.2.11 (the SHA is fixed)... but you may be able to get it working until 4.3.1 is out with 'real' support.  We have shown 4-3-stable to build on Ub22, but have not yet put it through the full test suite.

4.2.12 is coming 'soon' and we will keep this use case in mind.  We might be able to put a version switch or two in the server to get it to build on Ub20/Ub22 - at least enough to produce a usable `irods-dev` package.

**Comment by kript** [comment] 2023-04-12 10:26
Might be a moot point with 4.2.12 but is it possible to release 4.2.11.1 of icommands?

**Comment by trel** [comment] 2023-04-12 11:26
We don't have four 'digits' for the iCommands - they walk along with the server.

What would you want included in such a release?

**Comment by mherkazandjian** [comment] 2023-06-28 16:48
I managed to build irods and the icommands for version 4.2.11 on ubuntu 22.04 (all from source) using openssl 1.1.
I did not make a .deb package yet but preliminary tests of the icommands, ils, iput, iget seems to work.

i can probably do the same for 4.2.11, i'll share a dockerfile or a bunch of patches once i polish 
the procedure and produce the .deb packages.

![image](https://github.com/irods/irods/assets/3264637/7cf7850e-1dc1-4518-b800-1ad2e18339bd)

**Comment by trel** [comment] 2023-06-28 18:28
Nice!  Thanks.

**Comment by prhbrt** [comment] 2023-07-18 14:40
When will the focal version be on the [packages website](https://packages.irods.org/apt/dists/)?

**Comment by alanking** [comment] 2023-07-18 20:07
iRODS 4.3.0 and its attendant iCommands and plugins packages are available for focal today. We are planning to support focal for 4.3.1 as well.

**Comment by alanking** [comment] 2023-07-19 16:43
The changes for externals, iRODS, and iCommands are now merged.

GitHub Actions changes cannot be made until we release the externals at least on unstable.

Development and Testing environment changes are basically ready, but may require facelifts.

**Closed** 2023-10-02 18:04 UTC
Labels: enhancement, packaging, consortium-member
