### ISSUE TITLE
OSX externals fail to build on master (OSX 10.7.5)

### ISSUE THREAD

**Issue by keithj** [irods/irods#2709] opened 2015-05-26 20:30 UTC
The build script starts 11 concurrent `wget` processes and builds the results as they arrive. In this case, the last error message is from building posgresql. I suspect the real error is elsewhere. The wget curses progress bars and output of all makes are sent to the terminal, so it's impossible to give you a clean error report. I'll try again and redirect to a log to see if I can spot the upstream error.

Can I presume that the build works for you?

Example:

````
$ ./packaging/build.sh --run-in-place clean

...

$ ./packaging/build.sh --run-in-place icat postgres

...

make -C isolation distclean
rm -f regress.so   libregress.a  libregress.pc
rm -f regress.o refint.so autoinc.so dummy_seclabel.so
rm -f pg_regress_main.o pg_regress.o pg_regress
rm -f expected/constraints.out expected/copy.out expected/create_function_1.out expected/create_function_2.out expected/largeobject.out expected/largeobject_1.out expected/misc.out expected/security_label.out expected/tablespace.out sql/constraints.sql sql/copy.sql sql/create_function_1.sql sql/create_function_2.sql sql/largeobject.sql sql/misc.sql sql/security_label.sql sql/tablespace.sql
rm -rf testtablespace
rm -rf results/ regression.diffs regression.out tmp_check/ log/
rm -f isolationtester pg_isolation_regress specparse.o isolationtester.o isolation_main.o
rm -f pg_regress.o
rm -rf results/ regression.diffs regression.out tmp_check/ log/
make -C tutorial NO_PGXS=1 distclean
rm -f complex.so funcs.so complex.o funcs.o
rm -f advanced.sql basics.sql complex.sql funcs.sql syscat.sql
make -C test/isolation distclean
rm -f isolationtester pg_isolation_regress specparse.o isolationtester.o isolation_main.o
rm -f pg_regress.o
rm -rf results/ regression.diffs regression.out tmp_check/ log/
make -C test/thread distclean
rm -f thread_test thread_test.o
rm -f Makefile.port Makefile.global
rm -f config.cache config.log config.status GNUmakefile
make: *** [external] Error 2
````

**Comment by trel** [comment] 2015-05-26 20:34
You can use the --jobs or -j option:

```
./packaging/build.sh --run-in-place -j 1 icat postgres
```

and you'll see the specific `make` errors without any interleaving.

**Comment by keithj** [comment] 2015-05-26 21:16
The culprit is zeromq with the error I reported in #2475

````
Making all in doc
asciidoc -d manpage -b docbook -f ./asciidoc.conf \
		-azmq_version=4.1.0 -ozmq_bind.xml zmq_bind.txt
xmlto man zmq_bind.xml
xmlto: /Users/keith/dev/work/irods.git/external/zeromq-4.1.0/doc/zmq_bind.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/Users/keith/dev/work/irods.git/external/zeromq-4.1.0/doc/zmq_bind.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
Document /Users/keith/dev/work/irods.git/external/zeromq-4.1.0/doc/zmq_bind.xml does not validate
make[3]: *** [zmq_bind.3] Error 13
rm zmq_bind.xml
make[2]: *** [all-recursive] Error 1
make[1]: *** [zeromq] Error 2
make: *** [external] Error 2
````

**Comment by trel** [comment] 2015-05-26 23:00
My first thought was a firewall issue..., but then, in Debian-land, it looks like a docbook-xml issue...

From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=709158:

> The package was missing a build-dependency on docbook-xml, it has been
added in the newest version.

Perhaps... ```brew install docbook``` or some variant?

**Comment by trel** [comment] 2015-05-27 13:06
Tried again this morning, and it works for me on 10.7.5 with a new checkout in a new user account.

**Comment by trel** [comment] 2015-05-28 18:00
@keithj we will release 4.1.0 tomorrow - i've not been able to reproduce this error.  we can close this if you can solve it - or we'll bump it to 4.2.0.  thanks.

**Comment by keithj** [comment] 2015-06-12 11:04
As iRODS builds the zeromq documentation, then yes, there is a dependency on docbook. I did have docbook installed, but I also have to tell the build where to find the XML catalog files via an environment variable. If I do this, then the build completes successfully. (This is on a checkout of the 4.1.0 release tag).

**Comment by trel** [comment] 2015-11-24 18:32
closing this as we are moving to a new externals repository for 4.2+.

**Closed by trel** 2015-11-24 18:32 UTC
Labels: packaging

**Comment by keithj** [comment] 2015-12-02 18:40
I'm not going to re-open this, but FYI the new externals repository doesn't build on OSX either.

**Comment by trel** [comment] 2015-12-02 19:33
Which project isn't building?   What error(s) are you seeing?  

I was able to get everything working on 10.10 with these packages from homebrew...
  https://github.com/irods/externals/blob/master/osx.sh

Let's open a ticket over there...
