### ISSUE TITLE
setup_irods.py should support high availability (HA) (multiple providers)

### ISSUE THREAD

**Issue by bitkid** [irods/irods#4381] opened 2019-05-08 13:00 UTC
## Question

i try to dockerize our irods deployment (the icat server) and i am hitting the problem when i run the setup_irods.py twice it always fails with a unique key violation. 

 ```
IrodsError: pypyodbc encountered an error executing the statement:
        insert into R_ZONE_MAIN values (?,?,'local','','',?,?);
('23505', '[23505] ERROR: duplicate key value violates unique constraint "idx_zone_main2"\nKey (zone_name)=(zoneName) already exists.;\nError while executing the query')
```

it's a bit strange because i get a warning 

```
WARNING:                                              |
| The database specified is an already-configured     |
| iRODS database, so first-time database setup will   |
| not be performed.
```

so i assume that it would still work, meaning that this kind of key violation should be a warning as well.

**Comment by kript** [comment] 2021-09-10 10:34
We have just hit this on 4.2.7 using PostgreSQL as a back end. I don't _think_ we hit it using Oracle.

For us we were installing a provider into an already setup Zone - actually connecting a provider to a copy of the database that we had exported to postgreSQL from Oracle.

**Comment by kript** [comment] 2021-09-10 10:39
pertinent bit from `/var/lib/irods/log/setup_log.txt`

```2021-09-09 15:29:44,045 -    INFO -            database_connect.py: 315 - The following tables already exist in the database, table creation will be skipped:
['r_coll_main',
 'r_data_main',
 'r_grid_configuration',
 'r_meta_main',
 'r_microsrvc_main',
 'r_microsrvc_ver',
 'r_objt_access',
 'r_objt_audit',
 'r_objt_deny_access',
 'r_objt_metamap',
 'r_quota_main',
 'r_quota_usage',
 'r_resc_group',
 'r_resc_main',
 'r_rule_base_map',
 'r_rule_dvm',
 'r_rule_dvm_map',
 'r_rule_exec',
 'r_rule_fnm',
 'r_rule_fnm_map',
 'r_rule_main',
 'r_server_load',
 'r_server_load_digest',
 'r_specific_query',
 'r_ticket_allowed_groups',
 'r_ticket_allowed_hosts',
 'r_ticket_allowed_users',
 'r_ticket_main',
 'r_tokn_main',
 'r_user_auth',
 'r_user_group',
 'r_user_main',
 'r_user_password',
 'r_user_session_key',
 'r_zone_main']
2021-09-09 15:29:44,045 -   DEBUG -            database_connect.py: 225 - Executing SQL statement:
select nextval('R_OBJECTID');
with the following parameters:
()
2021-09-09 15:29:44,046 -   DEBUG -            database_connect.py: 225 - Executing SQL statement:
insert into R_ZONE_MAIN values (?,?,'local','','',?,?);
with the following parameters:
(52695394L, 'cgp', '01631201384', '01631201384')
2021-09-09 15:29:44,051 -   DEBUG -          database_interface.py:  31 - Rolling back database changes...
2021-09-09 15:29:44,051 -   ERROR -                 setup_irods.py: 440 - Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 438, in main
    setup_server(irods_config, json_configuration_file=options.json_configuration_file)
  File "/var/lib/irods/scripts/setup_irods.py", line 124, in setup_server
    database_interface.setup_catalog(irods_config, default_resource_directory=default_resource_directory)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 27, in setup_catalog
    database_connect.setup_database_values(irods_config, cursor, default_resource_directory=default_resource_directory)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 368, in setup_database_values
    timestamp)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 231, in execute_sql_statement
    sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/database_connect.py", line 227, in execute_sql_statement
    return cursor.execute(statement, params)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 1596, in execute
    check_success(self, ret)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 986, in check_success
    ctrl_err(SQL_HANDLE_STMT, ODBC_obj.stmt_h, ret, ODBC_obj.ansi)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 958, in ctrl_err
    raise IntegrityError(state,err_text)
IrodsError: pypyodbc encountered an error executing the statement:
        insert into R_ZONE_MAIN values (?,?,'local','','',?,?);
('23505', '[23505] ERROR: duplicate key value violates unique constraint "idx_zone_main2";\nError while executing the query')
2021-09-09 15:29:44,052 -    INFO -                 setup_irods.py: 441 - Exiting...
```

```
$ dpkg -l | grep irod
ii  irods-database-plugin-postgres     4.2.7                                       amd64        The integrated Rule-Oriented Data System
ii  irods-externals-avro1.7.7-0        1.0~xenial                                  amd64        iRODS Build Dependency
ii  irods-externals-boost1.60.0-0      1.0~xenial                                  amd64        iRODS Build Dependency
ii  irods-externals-clang-runtime3.8-0 1.0~xenial                                  amd64        iRODS Build Dependency
ii  irods-externals-jansson2.7-0       1.0~xenial                                  amd64        iRODS Build Dependency
ii  irods-externals-libarchive3.3.2-0  1.0~xenial                                  amd64        iRODS Build Dependency
ii  irods-externals-zeromq4-14.1.3-0   1.0~xenial                                  amd64        iRODS Build Dependency
rc  irods-icat                         4.1.12                                      amd64        The integrated Rule-Oriented Data System (iRODS)
ii  irods-icommands                    4.2.7                                       amd64        The integrated Rule-Oriented Data System
ii  irods-runtime                      4.2.7                                       amd64        The integrated Rule-Oriented Data System
ii  irods-server                       4.2.7                                       amd64        The integrated Rule-Oriented Data System
```
Ubuntu 18.04

**Comment by trel** [comment] 2021-09-10 11:27
This is the currently expected behavior - out of an abundance of safety/caution.  If `setup_irods.py` sees an existing Zone, it stops.

That said, if the `server_config.json` is populated correctly, you should be able to start the server manually (`./irodsctl start`).

We are planning to add HA-aware support to `setup_irods.py` in 4.3.0.   This will mean we need to ask at least one additional question (which will affect any automated `.input` or JSON inputs you may be building/using).

**Comment by kript** [comment] 2021-09-10 12:28
> This is the currently expected behavior - out of an abundance of safety/caution. If `setup_irods.py` sees an existing Zone, it stops.

OK, fair enough, but it should probably say that - and have a way to say that yes, I do intend to connect a new server to an existing zone. Otherwise one can never, ever, build new servers!

> That said, if the server_config.json is populated correctly, you should be able to start the server manually (./irodsctl start).

That appears to work (well, it has errors but I will take that offline as its not germane to this issue)

**Comment by trel** [comment] 2021-09-10 13:17
"a way to say that yes..." - Yeps, coming in 4.3.0

Glad the manual startup (almost) works.

**Comment by trel** [comment] 2022-03-26 01:48
I think this is now a subset of the work being done for https://github.com/irods/irods/issues/4381.

Need to carefully consider whether that statement is true before closing this issue.

**Comment by kript** [comment] 2022-04-14 12:23
Is this still being planned for 4.3? Asking for a friend who is me...

**Comment by trel** [comment] 2022-04-14 12:35
Yes.

Happy to have your friend provide thought experiments as well as real experiments with the implementation - initial work to ask the new question about 'local storage' is in https://github.com/irods/irods/commit/f6d1595d01dc0cb61b382c34fd51be79503ac25a.

**Comment by kript** [comment] 2022-04-14 13:21
Use cases ~my friend~ I can think of;

1. Reinstall existing server
2. Install additional server in a zone (cloud-y scaling up / HA uses)
3. Install new server when old server has failed/been decomissioned (this is _very_ similar to 1 and 2 but subtly different because it assumes (1) cannot be done and (2) doesn't apply as its the _only_ Provider for a zone

**Comment by trel** [comment] 2022-05-11 17:14
1. can safely re-run `setup_irods.py` ... since 4.2.9 ... https://github.com/irods/irods/issues/4602
2. same, won't complain since it will skip ahead if the database is already 'ready/done'
3. 1 can be done, so, we're good!

**Comment by trel** [comment] 2022-05-19 02:37
@kript closing this as 'done' for 4.3.0.    if we find an issue, we'll open something new with more detail then.

**Closed by trel** 2022-05-19 02:37 UTC
Labels: enhancement, consortium-member

**Comment by yr-wang-hit** [comment] 2024-04-17 09:52
We just hit this issue, we have set up a irods zone and consider to replace the icat-server to a newer/stronger server.  The db server seperated with icat, just rerun setup.py on new icat server will not violate the metadata in existed db since 4.3.0?

**Comment by alanking** [comment] 2024-04-17 22:39
@yr-wang-hit - The duplicate key constraint violation described in this issue has to do with trying to create a zone in the catalog which already exists (namely, the zone the server is supposed to go into). So I don't think that there will be any problems with metadata. What version of iRODS are you running? Can you share the output that you see so that we might be able to pinpoint the issue?
