### ISSUE TITLE
iquest matches the select keyword when it shouldn't

### ISSUE THREAD

**Issue by bh9** [irods/irods#5178] opened 2020-10-08 13:25 UTC
### iRODS Version, OS and Version
4.2.7 icommands + imeta -z fix
Ubuntu 18.04

### What did you try to do?
Select the resource ids of the good replicas of a file from it's path with 
```
iquest "%d" "SELECT RESC_ID WHERE COLL_NAME = '/seq/illumina/runs/32/32734/cellranger/cellranger400_count_32734_MRC_Endo8712024_GRCh38-2020-A/analysis/pca/10_components' AND DATA_NAME = 'features_selected.csv' AND DATA_REPL_STATUS = '1'"
```

### Expected behavior
iquest returns a list of RESC_IDs which have good replicas of this file

### Observed behavior (including steps to reproduce, if applicable)
iquest returns 4 and outputs
```
 ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND
```

This seems to be because iquest is matching the `select` in the DATA_NAME, from testing with `like` and wildcards:
```
irods@irods-seq-ies6:~$ iquest "SELECT DATA_NAME WHERE DATA_ID = '300857337' AND DATA_NAME like '%selec%'"
DATA_NAME = features_selected.csv
------------------------------------------------------------
irods@irods-seq-ies6:~$ iquest "SELECT DATA_NAME WHERE DATA_ID = '300857337' AND DATA_NAME like '%select%'"
 ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND
irods@irods-seq-ies6:~$ iquest "SELECT DATA_NAME WHERE DATA_ID = '300857337' AND DATA_NAME like '%elect%'"
DATA_NAME = features_selected.csv
------------------------------------------------------------
```
notice that as soon as the query includes the `select` keyword in the quotes, the error occurs

**Comment by trel** [comment] 2020-10-08 16:08
alas, a duplicate of https://github.com/irods/irods/issues/4697

**Comment by trel** [comment] 2020-10-08 20:22
The workaround, https://github.com/irods/irods/issues/3613#issuecomment-317453126, is to use lowercase `select` at the beginning of the general query.

**Comment by trel** [comment] 2020-10-09 01:37
moving this to 4.2.9 - we can fix this on the client side.

**Comment by trel** [comment] 2021-04-21 19:47
#4697 closes this same issue from a microservice-based genQuery by lowercasing the constructed query string.

The workaround for this issue - a manually generated general query via iquest .... is to use the lowercase 'select' at the beginning.

Closing and marking as workaround.

**Closed by trel** 2021-04-21 19:47 UTC
Labels: bug, consortium-member, duplicate, workaround
