### ISSUE TITLE
no tools to update/overwrite a checksum in iRODS?

### ISSUE THREAD

**Issue by kript** [irods/irods#3495] opened 2017-03-17 12:02 UTC
Apologies if I'm mis-reading a man page, or Doing This The Wrong way, but I can't see a way to update the checksum of an object in iRODS.

As we are cleaning up some our our files in iRODS, we have found a few edge cases where;

1. a file is marked as zero length in iRODS with a checksum, but actually exists on disk with the path specified in the output of `ils -L` for the replica number
2. a file has a replica with a checksum that is right for all the other replicas, but wrong for this one. We want to preserve the file, so mark it as a dirty copy. To do this we need to update the checksum for that replica within iRODS, without making it the only good copy, so that `iget` will not retrieve it unless directed to the replica number manually.

Any suggestions? What have I missed?

Thanks,

John

**Comment by trel** [comment] 2017-03-17 13:21
A few questions to make sure I can reproduce in a test:

Edge Case 1)
- What is the status of the database checksum on this zero-length-in-db replica?  Is it a known good checksum, or is it bad and should be disregarded/paved?
- Is there another replica in a known-good state for this dataObject?  Or is this the only replica for this dataObject?

Edge Case 2)
- This sounds like you're trying to keep different versions of a file under a single logical representation of a dataObject.  This will break all other assumptions in iRODS.  If I'm understanding correctly... this is a bad idea and is not recommended.
- If you want to keep the copy of the file on the disk, I'd suggest making a physical copy, and registering that copy as a new dataObject.  You can track the history/provenance in metadata if you'd like to keep the two logical entities related to one another.

**Comment by kript** [comment] 2017-03-17 14:35
> Edge Case 1)
> 
> What is the status of the database checksum on this zero-length-in-db replica? Is it a known good  checksum, or is it bad and should be disregarded/paved?

As far as I have found so far its good;

```
ils -L /seq/20755/log/20160929_160912_HS31_20755_A_C9WAFANXX.log.tar.xz
  srpipe            0 root;replicate;seq-red;red1;irods-seq-i06-de            0 2016-09-29.22:19 & 20160929_160912_HS31_20755_A_C9WAFANXX.log.tar.xz
    a91d7d0cc3b68c54c3f53d1e8c7f0935    generic    /irods-seq-i06-de/20755/log/20160929_160912_HS31_20755_A_C9WAFANXX.log.tar.xz
```
```
md5sum /irods-seq-i06-de/20755/log/20160929_160912_HS31_20755_A_C9WAFANXX.log.tar.xz
a91d7d0cc3b68c54c3f53d1e8c7f0935  /irods-seq-i06-de/20755/log/20160929_160912_HS31_20755_A_C9WAFANXX.log.tar.xz
```

> Is there another replica in a known-good state for this dataObject? Or is this the only replica for this dataObject?

**Comment by kript** [comment] 2017-03-17 15:01
If we don't want edge case 2 any more, then this issue is mis-named, as all the objects I've found so far have valid checksums so perhaps should be renamed *update file size in iRODS database*?

**Comment by trel** [comment] 2017-03-17 16:50
> If we don't want edge case 2 any more, then this issue is mis-named, as all the objects I've found so far have valid checksums so perhaps should be renamed update file size in iRODS database?

Agreed - this sounds like, if you only have a few of these files (with a single good replica, but bad filesize in the database), the best way to mitigate it is to very carefully update the record in the database to have the correct filesize.  But that would be outside of the iCommands.  iRODS must always assume the database is correct, and in this case, that assumption is incorrect (like you said, probably due to 3.3.1).

If you had a good other replica in Edge Case 1), you could unregister that replica, and then reregister the file in place as a new replica:
```
irm -U -n<TARGETREPLICANUMBER> /logical/path/to/dataObject
ireg -Kk --repl -R<TARGETRESOURCE> /physical/path/to/replica /logical/path/to/dataObject
```

**Comment by trel** [comment] 2017-03-17 16:51
Now that I think about it - you could unregister and re-register, even if there are no other replicas.

That's the approach to fix Edge Case 1).

**Comment by kript** [comment] 2017-03-21 14:25
The only problem with that approach, I realise is that it would lose the metadata 'attached' to the replica/object. We can copy and reload using baton, but thats getting rather unwieldy..

**Comment by trel** [comment] 2017-03-21 15:03
Well, that is true for the case of a single replica...   Strike that option.

I think you should be able to copy the physical file to a separate resource disk, register it as a second replica and trim the first. 


How many of these 'only the size in the db is incorrect' entries do you have?

**Comment by kript** [comment] 2017-03-21 15:17
Hard to tell. We have 234 zero length files, 39 of which are either single copy (no replicas) or zero length, the rest are zero length replicas.
I'm working through them all one by one ATM, since each need checking to be sure there isn't a file on disk. Fortunately, so far, where there *is* a file, its a tar file and we've been able to show that it doesn't extract, so a failed upload and can be removed..

**Comment by trel** [comment] 2017-03-21 15:34
That number is heartening, and not so large.

When the bookkeeping in the database is correct, there appears to be no new tools needed other than repl/trim.

Let's leave this issue open until you work through the ~200.
But then, if all your file_sizes and checksums are healed, we can close it.

**Comment by kript** [comment] 2017-03-29 15:07
Trying the add additional-replica-from-a-copy-of-the-file approach and it doesn't seem to update the file size;

```
#before updating the file
@irods-g1:~$ ils -L /seq/21052/qc/21052_3#188.insert_size.json
  srpipe            0 root;replicate;seq-red;red1;irods-seq-i01-bc            0 2016-10-26.06:14 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
```

```
#updating the file
@irods-seq-i01:~$ ls -lah /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
-rw------- 1 irods irods 1.9K Oct 26 06:14 /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
irods-seq-i01:~$ mkdir -p /irods-seq-i01-de/21052/qc
irods-seq-i01:~$ cp -rax /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json
irods-seq-i01:~$ ireg -Kk --repl -R root /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json /seq/21052/qc/21052_3#188.insert_size.json
```

```
#after updating the file;
@irods-g1:~$ ils -L /seq/21052/qc/21052_3#188.insert_size.json
  srpipe            0 root;replicate;seq-red;red1;irods-seq-i01-bc            0 2016-10-26.06:14 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
  srpipe            1 root;replicate;seq-red;red1;irods-seq-i01-bc            0 2017-03-29.15:56 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json
```

I thought that `ireg` would add the file size in, but it appears it hasn't. Have I missed something?

**Comment by trel** [comment] 2017-03-29 21:03
I see the bug (see 1 below).

So two things:

1) `ireg --repl` should now allow users to specify a coordinating resource as the target resource for the newly to-be-registered replica (in this case, `root` should not be allowed).  Only leaf resources should be allowed (in this case, `irods-seq-i01-de`).

2) iRODS assumes that a newly registered replica is exactly like the clean replicas already in the catalog.  This includes the data object's system metadata (including the size information).  This explains the reuse of the 'incorrect' file size. 

You should be able to repave a particular replica with `iput -f -n`.

Steps to fix original scenario:
- register replica to leaf resource
- make a copy of physical file to temp space
- force put over the target replica number (which will mark other replicas as out-of-date)
- rebalance, which will clean up the replicas as per policy

**Comment by kript** [comment] 2017-04-10 10:40
An update on when I did this, it updated the size on both copies, while marking the old one out of date;

```
@irods-g1:~$ ils -L /seq/21052/qc/21052_3#188.insert_size.json
  srpipe            0 root;replicate;seq-red;red1;irods-seq-i01-bc            0 2016-10-26.06:14 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
  srpipe            1 root;replicate;seq-red;red1;irods-seq-i01-bc            0 2017-03-29.15:56 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json
...
@irods-g1:~$ ils -L /seq/21052/qc/21052_3#188.insert_size.json
  srpipe            0 root;replicate;seq-red;red1;irods-seq-i01-bc         1899 2017-04-10.11:18   21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
  srpipe            1 root;replicate;seq-red;red1;irods-seq-i01-bc         1899 2017-04-10.11:18 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json
```
I wouldn't have expected the out of date replica information to have been updated?
I did update the ACL membership before the `iput`, since we use a different irods user on the iCAT as on the iRES's, but when I tested than on another file it wasn't reproducible..

**Comment by kript** [comment] 2017-04-12 11:59
This worked, but appears to have updated the file size on both the replica *and* the original, which wasn't what I was expecting;

```
@irods-g1:~$ ils -L /seq/21052/qc/21052_3#188.insert_size.json
  srpipe            0 root;replicate;seq-red;red1;irods-seq-i01-bc            0 2016-10-26.06:14 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
  srpipe            1 root;replicate;seq-red;red1;irods-seq-i01-bc            0 2017-03-29.15:56 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json
```

copy the file;
```
irods@irods-seq-i01:~$ ls -lah /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
-rw------- 1 irods irods 1.9K Oct 26 06:14 /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
irods@irods-seq-i01:~$ mkdir -p /irods-seq-i01-de/21052/qc
irods@irods-seq-i01:~$ cp -rax /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json
irods@irods-seq-i01:~$ ireg -Kk --repl -R root /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json /seq/21052/qc/21052_3#188.insert_size.json
irods@irods-seq-i01:~$ iput -f -n 1 /tmp/21052_3#188.insert_size.json /seq/21052/qc/21052_3#188.insert_size.json

```
check the `ils` again;
```
irods-g1@irods-g1:~$ ils -L /seq/21052/qc/21052_3#188.insert_size.json
  srpipe            0 root;replicate;seq-red;red1;irods-seq-i01-bc         1899 2017-04-10.11:18   21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
  srpipe            1 root;replicate;seq-red;red1;irods-seq-i01-bc         1899 2017-04-10.11:18 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json
```

You might notice the the permissions had an addition in-between the two `ils` (we run a different user for the iCat as the iRES's, but I tested on another zero length replica and this didn't produce the update, where as the `iput` did.

**Comment by kript** [comment] 2017-04-12 15:20
Frustratingly, now I can't reproduce this; the last three have only updated the file size for the forced iput replica.

**Comment by trel** [comment] 2017-04-12 15:24
The good news is that once there is a known good copy, marked good, with a good checksum... The rebalance should heal the other replicas without any trouble.

**Comment by trel** [comment] 2017-04-18 13:55
So we've found one bug (now #3517), and the rest of this thread has been to document a workaround for when the catalog has a bad filesize due to an older version of iRODS.

I will close this issue since it appears the workaround gets you back on the rails.  Please reopen if there is something else actionable regarding the file sizes or the checksums.

**Closed by trel** 2017-04-18 13:55 UTC
Labels: consortium-member

**Comment by kript** [comment] 2017-07-03 10:53
Apologies for reopening this, but I think I have an example use case for needing up today the checksum. IN this case, we have some objects that were uploaded in our old 3.3.1 days, and later over-written using iput with zero length files. In these cases the checksum hasn't been updated;

```
irods@irods-arch-g1-vm:/tmp$ ils -L /archive/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
  ib5               0 root;repl;green;irods-arch-sr1-bc            0 2014-07-28.14:45 & 6182386071_R05C01_Red.idat
    079202ecf898a54b5fb04dec052f4689    generic    /irods-arch-sr1-bc/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
irods@irods-arch-g1-vm:/tmp$ ichksum -f -K -a !$
ichksum -f -K -a /archive/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
ERROR: initCondForChksum: the 'K' and 'f' option cannot be used together
irods@irods-arch-g1-vm:/tmp$ ichksum -f  -a /archive/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
    6182386071_R05C01_Red.idat        d41d8cd98f00b204e9800998ecf8427e
Total checksum performed = 1, Failed checksum = 0
irods@irods-arch-g1-vm:/tmp$ ichksum -K  -a /archive/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
    6182386071_R05C01_Red.idat        d41d8cd98f00b204e9800998ecf8427e
Total checksum performed = 1, Failed checksum = 0
```

**Comment by trel** [comment] 2017-07-03 11:10
I'd like to reproduce this...

What is the actual size and checksum of the file on disk?

```
ls -l /irods-arch-sr1-bc/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
```
and
```
md5sum /irods-arch-sr1-bc/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
```

**Comment by kript** [comment] 2017-07-03 12:07
```
irods@irods-arch-sr1:~$ ls -l /irods-arch-sr1-bc/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
-rwx------ 1 irods irods 0 Jul 28  2014 /irods-arch-sr1-bc/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
irods@irods-arch-sr1:~$ md5sum !$
md5sum /irods-arch-sr1-bc/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
d41d8cd98f00b204e9800998ecf8427e  /irods-arch-sr1-bc/GAPI/gen/infinium/07/92/02/6182386071_R05C01_Red.idat
```

**Comment by trel** [comment] 2017-07-03 13:28
So it is a zero-length file on disk, the md5sum of that zero-length file is confirmed, and the catalog shows a zero-length, but holds an incorrect checksum.

```
$ ls -l emptyfile 
-rw-rw-r-- 1 tgr tgr 0 Jul  3 09:14 emptyfile

$ md5sum emptyfile 
d41d8cd98f00b204e9800998ecf8427e  emptyfile

$ ils -L
/tempZone/home/rods:
  rods              0 demoResc            0 2017-07-03.09:18 & emptyfile
    079202ecf898a54b5fb04dec052f4689    generic    /var/lib/irods/iRODS/Vault/home/rods/emptyfile
```

`ichksum -f` should overwrite that bad value in the catalog, and I've confirmed that behavior locally with 4.1.10:
```
$ ichksum -f  -a /tempZone/home/rods/emptyfile
    emptyfile                         d41d8cd98f00b204e9800998ecf8427e
Total checksum performed = 1, Failed checksum = 0

$ ils -L
/tempZone/home/rods:
  rods              0 demoResc            0 2017-07-03.09:18 & emptyfile
    d41d8cd98f00b204e9800998ecf8427e    generic    /var/lib/irods/iRODS/Vault/home/rods/emptyfile

**Comment by kript** [comment] 2017-07-04 14:44
Yup, that works for me too. I swear I tested that before re-opening...
