### ISSUE TITLE
Data object name containing the word select

### ISSUE THREAD

**Issue by ll4strw** [irods/irods#7174] opened 2023-07-06 11:49 UTC
- iRODS v4.3.0
- Rocky v8
- icommands v4.3.0

Please have a look at the following session

```
# iput test1 select
# ils
/zone/home/user:
  select

# iquest "SELECT DATA_NAME, DATA_CREATE_TIME WHERE DATA_NAME = 'select'" 
 ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND

# iquest "SELECT DATA_NAME, DATA_CREATE_TIME WHERE DATA_NAME like '%select%'" 
 ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND
```

Apparently this happens with any object name containing the word <em>select</em>

```
# iput test1 selected_file
# iquest "SELECT DATA_NAME, DATA_CREATE_TIME WHERE DATA_NAME = 'selected_file'"
 ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND

# iquest "SELECT DATA_NAME, DATA_CREATE_TIME WHERE DATA_NAME like 'select%'"
 ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND
```

Is this a known feature?

**Comment by korydraughn** [comment] 2023-07-06 12:29
Duplicate of #4697.
Will be resolved by #3902.

You can use lowercase `select` to get around this limitation.

GenQuery2 is also a good alternative. It can be compiled and used today with 4.2.11 and later. For 4.2.11 and 4.2.12, use the 4-2-stable branch. See https://github.com/irods/irods_api_plugin_genquery2. **Keep in mind that GenQuery2 is still in development and could change over time as we learn more through community feedback.**

**Comment by korydraughn** [comment] 2023-07-06 13:28
I believe that is true.

**Comment by trel** [comment] 2024-03-24 13:58
Need to make sure we add tests for these two cases:

```
$ ienv | grep version
irods_version - 4.3.1

$ itouch select.txt
Level 0: NO_COLUMN_NAME_FOUND: query fill failed for [SELECT DATA_ID, DATA_COLL_ID, DATA_NAME, DATA_REPL_NUM, DATA_VERSION,DATA_TYPE_NAME, DATA_SIZE, DATA_RESC_NAME, DATA_PATH, DATA_OWNER_NAME, DATA_OWNER_ZONE, DATA_REPL_STATUS, DATA_STATUS, DATA_CHECKSUM, DATA_EXPIRY, DATA_MAP_ID, DATA_COMMENTS, DATA_CREATE_TIME, DATA_MODIFY_TIME, DATA_MODE, DATA_RESC_HIER, DATA_RESC_ID, COLL_NAME WHERE DATA_NAME = 'select.txt' AND COLL_NAME = '/tempZone/home/rods' AND DATA_REPL_NUM = '0']

$ itouch where.txt
Level 0: NO_COLUMN_NAME_FOUND: query fill failed for [SELECT DATA_ID, DATA_COLL_ID, DATA_NAME, DATA_REPL_NUM, DATA_VERSION,DATA_TYPE_NAME, DATA_SIZE, DATA_RESC_NAME, DATA_PATH, DATA_OWNER_NAME, DATA_OWNER_ZONE, DATA_REPL_STATUS, DATA_STATUS, DATA_CHECKSUM, DATA_EXPIRY, DATA_MAP_ID, DATA_COMMENTS, DATA_CREATE_TIME, DATA_MODIFY_TIME, DATA_MODE, DATA_RESC_HIER, DATA_RESC_ID, COLL_NAME WHERE DATA_NAME = 'where.txt' AND COLL_NAME = '/tempZone/home/rods' AND DATA_REPL_NUM = '0']
```

**Closed** 2024-12-17 17:01 UTC
Labels: bug
