### ISSUE TITLE
missing acPostProcForDataCopyReceived leads to resources depletion

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#3773] opened 2017-12-22 19:04 UTC
Context: iRODS 4.1.11: Missing core.re static policy acPostProcForDataCopyReceived does not only leave debug messages in log, but also the related process does not stop.  Ultimately this may deplete available ICAT connections or other resources which leads to all sort of undesirable behavior.

Suggestion: update note in release notes 4.1.10 to indicate that the two static policies *must* be added.

rodsLog trail:
```
Dec 22 13:51:07 pid:51397 ERROR: generateErrMsg: ruleBaseName of unknown type: [error: cannot find rule for action "acPostProcForDataCopyReceived" available: 502.] [0] []
Dec 22 13:51:07 pid:51397 DEBUG: <unknown source type>
```

**Comment by jaking92** [comment] 2018-02-15 20:29
I have not been able to reproduce this issue yet. Running 4.1.11 server and 4.1.11 client, I deleted the two mentioned rules from core.re and am able to trigger the error messages when attempting to perform a put to a replication node. Here is my output:
```
Feb 15 14:39:14 pid:19335 NOTICE: Agent process 23824 started for puser=rods and cuser=rods from xxx.xx.xx.xxx
Feb 15 14:39:15 pid:23824 ERROR: generateErrMsg: ruleBaseName of unknown type: [error: cannot find rule for action "acPostProcForDataCopyReceived" available: 99.] [0] []
Feb 15 14:39:15 pid:23824 DEBUG: <unknown source type>
Feb 15 14:39:15 pid:23824 NOTICE: readAndProcClientMsg: received disconnect msg from client
Feb 15 14:39:15 pid:23824 NOTICE: Agent exiting with status = 0
Feb 15 14:39:15 pid:19335 NOTICE: Agent process 23824 exited with status 0
```
As you can see, the agent process exits cleanly. However, I feel that my steps to reproduce may not be the same as yours. Could you provide more details about your specific setup and/or any rules that might be causing this to trigger?

**Comment by trel** [comment] 2018-03-20 13:10
@tsmeele Is there anything else you can tell us about this setup that might affect what you were seeing?  I realize you probably have not seen this issue since you added the two static policies.

If not, I think we're going to mark this one as resolved/invalid.

**Comment by tsmeele** [comment] 2018-03-20 13:58
Nothing conclusive, yet it appears one of the servers might have suffered from an invalid certificate.

Met vriendelijke groet,

Ton

On 20 Mar 2018, at 15:10, Terrell Russell <notifications@github.com<mailto:notifications@github.com>> wrote:


@tsmeele<https://github.com/tsmeele> Is there anything else you can tell us about this setup that might affect what you were seeing? I realize you probably have not seen this issue since you added the two static policies.

If not, I think we're going to mark this one as resolved/invalid.

**Comment by trel** [comment] 2018-05-07 12:38
Planning to bump this to the 4.2.x series unless we can reproduce the issue.

**Comment by trel** [comment] 2018-08-29 15:12
Marking this as resolved/invalid.   Please open a new issue if this arises again.

**Closed by trel** 2018-08-29 15:12 UTC
Labels: bug, consortium-member
