### ISSUE TITLE
json configuration enhancement

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#2980] opened 2015-12-09 12:12 UTC
It would be great if there was a setup JSON file that could be configured before running the setup_irods.sh script which would negate the need to pass arguments to setup_irods.sh. This would make automation of the setup process easier (from our point of view) and would be more in line with your JSON approach in general. You guys are probably planning this already, however I thought I would suggest it as an enhancement just in case.

**Comment by trel** [comment] 2015-12-09 19:26
Agreed.

You can already redirect a simple text file, with one line per input (we use this in our test environments).  But this is relatively brittle over time.

We can discuss how an optional argument to the setup script (which will shortly all be in python) will look.  We think a new schema that defines the input format (using existing server_config.json and database_config.json schemas makes the most sense).

**Comment by trel** [comment] 2015-12-09 19:41
ah, already brought up and ticketed.   closing as duplicate of https://github.com/irods/irods/issues/2790.

**Closed by trel** 2015-12-09 19:41 UTC
Labels: enhancement
