### ISSUE TITLE
pam_password_max_time does not allow pass_expiry_ts above 1209600

### ISSUE THREAD

**Issue by bh9** [irods/irods#5096] opened 2020-09-03 14:49 UTC
- [x] main
- [x] 4-3-stable
---
## Bug Report
Probably related to #3742 #4198 and #4904 
### iRODS Version, OS and Version
4.2.7 Ubuntu 18.04

### What did you try to do?
Set `pam_password_max_time` in `/etc/irods/server_config.json` to allow for longer pam authentication (in this case to 5184000 for 60 days)

### Expected behavior
`iinit --ttl 1400` should give me an `pass_expiry_ts` of `5040000` since that is less than the maximum

### Observed behavior (including steps to reproduce, if applicable)
`iinit --ttl 1400` gives me a `pass_expiry_ts` of `1209600`

Of note: without the `pam_password_max_time` setting, `iinit --ttl 1400` gives 2 prompts: the first PAM prompt as expected, and then an iRODS password prompt afterwards. With the setting, this second prompt does not occur, so it does change something.

**Comment by bh9** [comment] 2020-09-03 15:21
I also tried the below config from #4904, but that didn't remove the 2nd prompt
```
'authentication' : { 
    'pam' : { 
        'password_max_time': 5184000
    } 
}
```
Combining the two options also gave the unexpected iRODS password prompt
```
...
  "pam_password_max_time": 5184000,
  "plugin_configuration": {
    "authentication": {
      "pam" : {
        "password_max_time": 5184000
      }
    },
...
```

**Comment by darthtux** [comment] 2020-11-19 19:12
This issue is of particular interest to us as well.  As bh9 said, no matter what we do we are unable to get an iRODS pass_expiry_ts to last longer then 2 weeks.  

@jasoncoposky This is the PAM issue I was talking about during our meeting yesterday.

**Comment by jasoncoposky** [comment] 2020-11-19 19:52
I believe the issue is [here](https://github.com/irods/irods/blob/master/plugins/database/src/db_plugin.cpp#L1917) where we first need to get the `plugins {}` object of the server configuration, then the `authentication{...}` section, then the `pam {...}` section.

**Comment by bzizou** [comment] 2021-01-04 14:59
Same problem here. We're using PAM and we are unable to do `iinit` with the `--ttl` option. It asks for the PAM password, and then the unexpected iRods password, and returns without any error, but the auth is not ok:

```
bzizou@f-dahu:~$ iinit --ttl 9000
Enter your current PAM password:
Enter your current iRODS password:
bzizou@f-dahu:~$ ils
[-]     /build/source/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_co
ntext &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]

 failed with error -826000 CAT_INVALID_AUTHENTICATION
```
Without the `--ttl` option, everything goes fine:
```
bzizou@f-dahu:~$ iinit           
Enter your current PAM password:
bzizou@f-dahu:~$ ils
/mantis/home/bzizou:
```
Also tried to setup the `password_max_time` configuration option without any success.

It's annoying for us as we just upgraded our set-up and started using PAM auth recently. Our users are running long-term computing job campaigns, and it now fail because of expired auth token. Any fix or workaround should be really appreciated.

**Comment by bzizou** [comment] 2023-03-16 09:58
Hello. Any news about that?

**Comment by korydraughn** [comment] 2023-03-20 16:47
There's been no activity on this issue at the moment. When new info becomes available, we'll be sure to update this thread.

**Comment by alanking** [comment] 2023-10-23 20:28
I think that this is fixed in 4.3.1. See #7274

**Comment by korydraughn** [comment] 2023-10-23 20:38
Please confirm, update, and close if resolved.

**Comment by alanking** [comment] 2023-11-09 16:20
We do not have a test which shows success when `--ttl` is higher than 1209600, so I will add that.

**Closed** 2023-11-21 20:29 UTC
Labels: bug, needs-test, consortium-member
