### ISSUE TITLE
foreach msiGetMoreRows error when processing multiple of 256 rows

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#3489] opened 2017-03-06 13:21 UTC
- [x] 4-1-stable
- [x] 4-2-stable
- [x] master

---

foreach loop processing fails when processing through large number of rows.  
This can be reproduced on an iRODS instance with 2.7M objects, see rule example below.
Context: iRODS 4.1.8 server

```
-bash-4.2$ date;irule -F testforeach.r ;date
Mon Mar  6 13:23:27 CET 2017
ERROR: rcExecMyRule error.  status = -808000 CAT_NO_ROWS_FOUND
Level 0: DEBUG: msiGetMoreRows error
line 4, col 3
   foreach (*rows in SELECT COLL_NAME,DATA_NAME,DATA_ID
   ^


Mon Mar  6 13:33:44 CET 2017
-bash-4.2$ cat testforeach.r
# rule to test execution of foreach on system with 2.7M objects 

replMyData {

   foreach (*rows in SELECT COLL_NAME,DATA_NAME,DATA_ID
      ) {
      *id   = *rows.DATA_ID;
      *coll = *rows.COLL_NAME;
      *obj  = *rows.DATA_NAME;
      *path = "*coll/*obj";
   }
}


input null
output ruleExecOut
-bash-4.2$ iquest "select count(DATA_NAME)"
DATA_NAME = 2648671
------------------------------------------------------------
-bash-4.2$ 
```

irodsLog info:
```
Mar  6 13:33:44 pid:31961 ERROR: executeRuleAction Failed for foreach2 status = -808000 CAT_NO_ROWS_FOUND
Mar  6 13:33:44 pid:31961 NOTICE: executeRuleBody: Microservice or Action foreach2 Failed with status -808000
Mar  6 13:33:44 pid:31961 NOTICE: execRuleNodeRes: applyRule Failed: replMyData with status -808000
Mar  6 13:33:44 pid:31961 DEBUG: msiGetMoreRows error
line 4, col 3
   foreach (*rows in SELECT COLL_NAME,DATA_NAME,DATA_ID
   ^

Mar  6 13:33:44 pid:31961 NOTICE: execMyRule @external
# rule to test execution of foreach on system with 2.7M objects

replMyData {

   foreach (*rows in SELECT COLL_NAME,DATA_NAME,DATA_ID
      ) {
      *id   = *rows.DATA_ID;
      *coll = *rows.COLL_NAME;
      *obj  = *rows.DATA_NAME;
      *path = "*coll/*obj";
   }
}
```

**Comment by xu-hao** [comment] 2017-03-15 17:53
Hello,

It seems object count is not the cause of this error.

I was able to ingest exact the same number of objects

-bash-4.2$ iquest "select count("DATA_NAME")"
DATA_NAME = 2648671
------------------------------------------------------------

then the rule runs successfully.

This is tested on Centos 7, postgres 9.2, irods 4.1.8.


Could you give us more information on how your data are set up.

**Comment by tsmeele** [comment] 2017-03-16 11:08
Hello Xu-Hao,

Our env is also Centos7, Postgres 9.2 and iRODS 4.1.8.

Some specifics on the data:
- collect names are quite long, example:

COLL_NAME = /nluu6p/home/grp-celbiologie/archive/Akhmanova Lab/Akhmanova HDs/Andrea Serra Marques/Andrea HD1/KIF13B project/Analysis/ATrackJ analysis - 2nd analysis (withOUT Golgi)/09102013 HeLaRSL2 - Kif13B£1 siRNA control 100 ms 08 corrected/09102013 HeLaRSL2 - Kif13B£1 siRNA control 100 ms 08.stk

- total no of collections is 155768

What other info can help?

Met vriendelijke groet, kind regards,

Ton

**Comment by xu-hao** [comment] 2017-03-16 17:05
If you run this gen query through iquest,

iquest "SELECT COLL_NAME,DATA_NAME,DATA_ID"

do you get any error?

Thanks,
  Hao

**Comment by tsmeele** [comment] 2017-03-16 18:13
Yes, similar error, see below output:
```
-bash-4.2$ iquest --no-page "select COLL_NAME,DATA_NAME,DATA_ID" >catlist.txt
-bash-4.2$ cat catlist.txt|wc
6210561 21376488 340710867
-bash-4.2$ tail catlist.txt
------------------------------------------------------------
COLL_NAME = /nluu6p/home/y.katrukha@uu.nl/papers/published/MT_neurons/20140905_M_M_Eugene
DATA_NAME = MixedMT_steer.pdf
DATA_ID = 616548
------------------------------------------------------------
COLL_NAME = /nluu6p/home/y.katrukha@uu.nl/papers/published/MT_neurons/20140905_M_M_Eugene
DATA_NAME = mmc1.pdf
DATA_ID = 616549
------------------------------------------------------------
CAT_NO_ROWS_FOUND: Nothing was found matching your query
-bash-4.2$
```

**Comment by trel** [comment] 2017-03-16 18:18
How many results are in the catlist.txt file?

How many results are **not** in the catlist.txt file?

And more speculatively...

Are there any dataObjects in the database that have an empty COLL_NAME, DATA_NAME, or DATA_ID?

**Comment by trel** [comment] 2017-03-16 18:22
Do any of the following queries fail?

`iquest --no-page "select COLL_NAME" > coll_name.txt`

`iquest --no-page "select DATA_NAME" > data_name.txt`

`iquest --no-page "select DATA_ID" > data_id.txt`

Do each of the result files have the same number of results?

**Comment by tsmeele** [comment] 2017-03-16 19:21
The queries produce different number of results and query with DATA_ID fails:
```
-bash-4.2$ iquest --no-page "select COLL_NAME" >t1.txt
-bash-4.2$ wc <t1.txt
  311536   961562 22601884
-bash-4.2$ tail t1.txt
COLL_NAME = /nluu6p/trash/home/r.j.a.vanschip@uu.nl
------------------------------------------------------------
COLL_NAME = /nluu6p/trash/home/rods
------------------------------------------------------------
COLL_NAME = /nluu6p/trash/home/r.vandenbroek@uu.nl
------------------------------------------------------------
COLL_NAME = /nluu6p/trash/home/s.holleman@uu.nl
------------------------------------------------------------
COLL_NAME = /nluu6p/trash/home/y.katrukha@uu.nl
------------------------------------------------------------
-bash-4.2$ iquest --no-page "select DATA_NAME" >t2.txt
-bash-4.2$ wc <t2.txt
  571348  1830996 33336717
-bash-4.2$ tail t2.txt
DATA_NAME = α-distrobrevin-1 and 2 (prot sequences).docx
------------------------------------------------------------
DATA_NAME = α-distrobrevin-1 (nucleotide sequence from Marv Adams & Margaret Maimone).docx
------------------------------------------------------------
DATA_NAME = α-distrobrevin-1 sequencing.docx
------------------------------------------------------------
DATA_NAME = Β-dystrobrevin.docx
------------------------------------------------------------
DATA_NAME = β-Dystrobrevin into pEGFP-C1.docx
------------------------------------------------------------
-bash-4.2$ iquest --no-page "select DATA_ID" >t3.txt
-bash-4.2$ wc <t3.txt
  3105281   6210567 121816313
-bash-4.2$ tail t3.txt
------------------------------------------------------------
DATA_ID = 2050767
------------------------------------------------------------
DATA_ID = 2050769
------------------------------------------------------------
DATA_ID = 2050771
------------------------------------------------------------
DATA_ID = 2050773
------------------------------------------------------------
CAT_NO_ROWS_FOUND: Nothing was found matching your query
-bash-4.2$ 
```

**Comment by kellerb** [comment] 2017-03-16 19:30
Is there anything in the server log when you run one of the `iquest`s that returns `CAT_NO_ROWS_FOUND`?

**Comment by kellerb** [comment] 2017-03-16 19:30
Is giving as a snapshot of your DB an option?

**Comment by tsmeele** [comment] 2017-03-16 19:43
server rodslog has no error info.
A psql query directly on the Postgres ICAT database returns same count as iquest (except on data_id because the iquest then fails):
ICAT=> select count(*) from r_data_main;
  count  
---------
 2648671
(1 row)

ICAT=> select count(*) from r_data_main where data_id is null;
 count 
-------
     0
(1 row)

ICAT=> select count(*) from r_data_main where data_name is null;
 count 
-------
     0
(1 row)

ICAT=> select count(*) from r_coll_main where coll_name is null;
 count 
-------
     0
(1 row)

ICAT=> select count(*) from r_coll_main where coll_id is null;
 count 
-------
     0
(1 row)

ICAT=> select count(*) from r_coll_main;
 count  
--------
 155768
(1 row)

ICAT=> 
ICAT=> select count(data_id) from r_data_main;
  count  
---------
 2648671
(1 row)

ICAT=>
``

**Comment by tsmeele** [comment] 2017-03-16 19:47
cannot provide snapshot, it is production research data sorry

**Comment by trel** [comment] 2017-03-16 19:49
What is DATA_ID = 2050775 ?

**Comment by tsmeele** [comment] 2017-03-16 19:51
select * from r_data_main where data_id=2050775;
returns 0 rows

**Comment by trel** [comment] 2017-03-16 19:59
and you have data_id's much larger than that in the system?

`select max(data_id) from r_data_main;`

**Comment by tsmeele** [comment] 2017-03-16 20:06
Nop:
```
 ICAT=> select max(data_id) from r_data_main;
   max   
---------
 2050773
(1 row)
```

**Comment by trel** [comment] 2017-03-16 20:07
Interesting - otherwise, the Zone is behaving as expected?

**Comment by trel** [comment] 2017-03-16 20:10
How about...

`iquest --no-page "select DATA_ID, DATA_NAME" >t4.txt`

`iquest --no-page "select DATA_ID, COLL_NAME" >t5.txt`

`iquest --no-page "select COLL_NAME, DATA_NAME" >t6.txt`

**Comment by kellerb** [comment] 2017-03-16 20:10
Lets also throw in a:
``` sql
select count(distinct data_id) from r_data_main;
```

**Comment by tsmeele** [comment] 2017-03-16 20:16
```
ICAT=> select count(distinct data_id) from r_data_main;
  count  
---------
 1552640
(1 row)
-bash-4.2$ iquest --no-page "select DATA_ID,DATA_NAME">t4.txt
-bash-4.2$ wc <t4.txt
  4657921  11895477 169869034
-bash-4.2$ tail t4.txt
DATA_ID = 42949
DATA_NAME = α-distrobrevin-1 sequencing.docx
------------------------------------------------------------
DATA_ID = 42950
DATA_NAME = Β-dystrobrevin.docx
------------------------------------------------------------
DATA_ID = 43365
DATA_NAME = β-Dystrobrevin into pEGFP-C1.docx
------------------------------------------------------------
CAT_NO_ROWS_FOUND: Nothing was found matching your query

```

**Comment by tsmeele** [comment] 2017-03-16 20:24
```
-bash-4.2$ iquest --no-page "select DATA_ID,COLL_NAME">t5.txt

-bash-4.2$ 
-bash-4.2$ wc <t5.txt
  4657921  15691578 292658146
-bash-4.2$ tail t5.txt
DATA_ID = 616548
COLL_NAME = /nluu6p/home/y.katrukha@uu.nl/papers/published/MT_neurons/20140905_M_M_Eugene
------------------------------------------------------------
DATA_ID = 616549
COLL_NAME = /nluu6p/home/y.katrukha@uu.nl/papers/published/MT_neurons/20140905_M_M_Eugene
------------------------------------------------------------
DATA_ID = 616550
COLL_NAME = /nluu6p/home/y.katrukha@uu.nl/papers/published/MT_neurons/20140905_M_M_Eugene
------------------------------------------------------------
CAT_NO_ROWS_FOUND: Nothing was found matching your query
-bash-4.2$ 
```

**Comment by kellerb** [comment] 2017-03-16 20:26
There is a common type of issue ([another example](https://github.com/irods/irods/issues/3405)) in which the number of results is a multiple of 256 and the code that iterates over the genquery receives a `CAT_NO_ROWS_FOUND` and interprets this as an error instead of an end-of-results. I'm noticing that your number of distinct `data_id`s, 1,552,640, is a multiple of 256.

Is it possible for you to add or delete a data object (not just one replica) and retry one of the failing `iquest`s?

**Comment by tsmeele** [comment] 2017-03-16 20:40
Good catch Ben!  Indeed after an iput the query runs normal again:
```
-bash-4.2$ iput t1.txt
-bash-4.2$ iquest "select count(DATA_ID)"
DATA_ID = 2648672
------------------------------------------------------------
-bash-4.2$ iquest --no-page "select DATA_ID">t7.txt
-bash-4.2$ wc <t7.txt
  3105282   6210564 121816335
-bash-4.2$ tail t7.txt
DATA_ID = 2050767
------------------------------------------------------------
DATA_ID = 2050769
------------------------------------------------------------
DATA_ID = 2050771
------------------------------------------------------------
DATA_ID = 2050773
------------------------------------------------------------
DATA_ID = 3603375
------------------------------------------------------------
-bash-4.2$ 
```

**Comment by trel** [comment] 2017-03-16 20:45
Very good.

This is related to or possibly a duplicate of https://github.com/irods/irods/issues/3262

**Comment by tsmeele** [comment] 2017-03-16 20:58
if I manually page through rows (msiGetMoreRows) the queries seemed to run smooth while a foreach select would fail.  maybe this helps to pinpoint.

**Comment by xu-hao** [comment] 2017-03-16 21:18
Could you send us your rule using msiGetMoreRows which ran without
returning errors? Thanks.

**Comment by kellerb** [comment] 2017-03-16 21:19
The problem is probably that `CAT_NO_ROWS_FOUND` is not being handled appropriately [here](https://github.com/irods/irods/blob/4.1.10/iRODS/server/re/src/functions.cpp#L395-L397).

**Comment by xu-hao** [comment] 2017-03-16 21:42
Note that iquest generates a similar behaviour. This points to the question
whether CAT_NO_ROWS_FOUND should be considered an error code or a normal
return status. Are there cases in the gen query subsystem where it is being
used as an error code. Are there cases where it is used as a normal return
status?

**Closed** 2017-05-09 15:58 UTC
Labels: bug, consortium-member
