### ISSUE TITLE
msiDataObjPhymv() fails to move into a resource hierarchy

### ISSUE THREAD

**Issue by trel** [irods/irods#3234] opened 2016-07-28 16:51 UTC
- [x] master
- [x] 4-2-stable

**Comment by alanking** [comment] 2019-10-10 14:09
Cannot reproduce on 4.2.6 as described.
```
$ cat phymv.r
phymv_thing {
        msiDataObjPhymv("/tempZone/home/rods/foo", "repl0", "demoResc", "0", "", *status);
        writeLine("stdout", "*status");
}
INPUT null
OUTPUT ruleExecOut
irods@1969df377261:~$ iput VERSION.json foo
irods@1969df377261:~$ ils -l foo
  rods              0 demoResc          814 2019-10-10.14:07 & foo
$ irule -F phymv.r
0
$ ils -l foo
  rods              0 repl0;ufs5          814 2019-10-10.14:07 & foo
  rods              1 repl0;ufs4          814 2019-10-10.14:07 & foo
```
Am I missing anything? Can we close this?

**Closed** 2020-03-04 02:22 UTC
Labels: bug
