### ISSUE TITLE
ils -L fails when given multiple arguments

### ISSUE THREAD

**Issue by keithj** [irods/irods#3562] opened 2017-05-23 09:30 UTC
iRODS 4.1.10, icommands 4.1.10

````
$ iput README
$ iput README2

$ ils -L
/Sanger1-dev/home/kdj:
  kdj               0 data         3403 2017-05-19.11:22 & README
    5e3982f9d1b8e97fb073459453db4dba    generic    /data/home/kdj/README
  kdj               0 data          136 2017-05-23.10:22 & README2
    7a599ac50c29c7856b79119df058a2cf    generic    /data/home/kdj/README2

$ ils -L README
  kdj               0 data         3403 2017-05-19.11:22 & README
    5e3982f9d1b8e97fb073459453db4dba    generic    /data/home/kdj/README
$ ils -L README2
  kdj               0 data          136 2017-05-23.10:22 & README2
    7a599ac50c29c7856b79119df058a2cf    generic    /data/home/kdj/README2

$ ils README README2
  /Sanger1-dev/home/kdj/README
  /Sanger1-dev/home/kdj/README2

$  ils -L README README2
  kdj               0 data         3403 2017-05-19.11:22 & README
    5e3982f9d1b8e97fb073459453db4dba    generic    /data/home/kdj/README
ERROR: /Sanger1-dev/home/kdj/README2 does not exist or user lacks access permission
````

Adding further items to the command line gives other errors:

````
$ iput README README3
$ iput README README4

$  ils -L README README2 README3 README4
  kdj               0 data         3403 2017-05-19.11:22 & README
    5e3982f9d1b8e97fb073459453db4dba    generic    /data/home/kdj/README
ERROR: /Sanger1-dev/home/kdj/README2 does not exist or user lacks access permission
ERROR: [-]	iRODS/lib/core/src/procApiRequest.cpp:266:readAndProcApiReply :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
	[-]	iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
		[-]	libtcp.cpp:197:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [only read [0] of [4]]

ERROR: lsDataObjUtilLong: rcGenQuery error for /Sanger1-dev/home/kdj/README3 status = -4000 SYS_HEADER_READ_LEN_ERR
ERROR: [-]	iRODS/lib/core/src/procApiRequest.cpp:266:readAndProcApiReply :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
	[-]	iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
		[-]	libtcp.cpp:197:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [only read [0] of [4]]

ERROR: rcObjStat of /Sanger1-dev/home/kdj/README4 failed status = -4000 SYS_HEADER_READ_LEN_ERR
ERROR: [-]	iRODS/lib/core/src/rcConnect.cpp:269:rcDisconnect :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
	[-]	iRODS/lib/core/src/sockComm.cpp:1386:sendRodsMsg :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [failed to call 'write body']
		[-]	libtcp.cpp:358:tcp_send_rods_msg :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [writeMsgHeader failed]
			[-]	iRODS/lib/core/src/sockComm.cpp:473:writeMsgHeader :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
				[-]	libtcp.cpp:279:tcp_write_msg_header :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected -1946157056]
````

**Comment by trel** [comment] 2017-05-23 10:28
Duplicate of https://github.com/irods/irods/issues/3520?

**Closed** 2017-07-04 01:42 UTC
Labels: bug, consortium-member, duplicate
