### ISSUE TITLE
4.1.0 --run-in-place install fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by keithj** [irods/irods#2747] opened 2015-06-12 16:28 UTC
After failing to install on OSX 10.7.5 in #2744 I wanted to check that I can get it to work on Linux. Having created an empty Postgres ICAT database owned by the correct user, on the default port, I ran the setup and used all the default responses:

````
Stopping iRODS server...

-----------------------------
Running irods_setup.pl...

Step 1 of 4:  Configuring database user...
    Updating user's .pgpass...
        Skipped.  File already uptodate.

Step 2 of 4:  Creating database and tables...
    Checking whether iCAT database exists...

Install problem:
    Database [ICAT] on [localhost] cannot be found.
    
Found 0 processes:
        There are no iRODS servers running.

Abort.
````

I can connect to the database using either pgAdmin or psql.

**Comment by trel** [comment] 2015-06-15 18:40
Does `isql` work?  (via ODBC)

**Comment by keithj** [comment] 2015-06-16 09:02
Yes, it does. As the user that is building iRODS I can use `isql` to insert a test table into the prepared ICAT database.

**Comment by trel** [comment] 2015-06-16 19:22
The only two ways iRODS communicates with the database are via `psql` and ODBC (like `isql`).

We have not been able to reproduce this behavior.  Are you using the default 'ident' authentication for Postgres?

Is there anything else you can share/show to help us reproduce this error?

**Comment by keithj** [comment] 2015-06-16 21:38
I've tried both `ident` and `trust`. I can see that the setup script is using `psql`, yet the postgresql server log shows that there isn't even a connection attempt made, not even a failed one.

The setup log is more informative...

````
Creating database and tables...
------------------------------------------------------------------------

Checking whether iCAT database exists...
    Connecting with: /psql -U irods -p 5432 -l ICAT

Install problem:
    Database [ICAT] on [localhost] cannot be found.
````

That `psql` command is wrong: `/psql` is not the path to the `psql` client on this host, it's `/usr/bin/psql`

**Comment by keithj** [comment] 2015-06-16 22:13
After putting some debug print statements in the `irods_setup.pl` script, I've discovered that these values are being used in `Postgres_CreateDatabase`:

````
finding_psql is '/home/keith/dev/irods.git/packaging/find_bin_postgres.sh'
PSQL is ''
````

There are two problems here. Firstly, the path to `find_bin_postgres.sh` is set up for a binary install, yet earlier the install script output I see:

````
 ./plugins/database/packaging/setup_irods_database.sh
===================================================================

You are installing iRODS with the --run-in-place option.
````

Secondly, the incorrect path is executed without checking the exit code, so the calling script doesn't know that the prefix path is actually empty because of the failure.

(Also, it's always good to `use strict` and `use warnings` in Perl scripts).

**Comment by trel** [comment] 2015-06-17 15:56
Agreed, it is now checking the return code.  https://github.com/irods/irods/commit/ee93bfe5856f726cd88b0c815ab4c1da9698779c#diff-4cc2fe309e3f4bedc7af46d39da95c61R1798

I'm most concerned about the reason you're hitting the 'binary' script path rather than the run-in-place script path.  That RUNINPLACE variable is set correctly for me and triggers the correct code.

Can you try to reproduce this with a checkout of the 4-1-stable branch?

We've heard a similar report with a run-in-place with mysql, but have not been able to understand how it's getting into this state.

**Comment by keithj** [comment] 2015-06-18 08:52
I've just tried this on the stable branch 5bf7a808a34c61cd10ff31114cba4650559d0284 and saw no problems.

**Comment by trel** [comment] 2015-06-18 14:05
Thanks, closing.

**Closed by trel** 2015-06-18 14:05 UTC
Labels: bug
