### ISSUE TITLE
imeta mod Error: -816000 CAT_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by SeanDeitrich** [irods/irods#3866] opened 2018-03-30 15:12 UTC
### iRODS Version, OS and Version
Most Recent Version (Fresh Install), CentOS 7.4.1708

### What did you try to do?
Followed beginner training up until 7.7, where `imeta mod -d grapes.jpg author AJones v:BSmith` throws me the error `-816000 CAT_INVALID_ARGUMENT`

### Expected behavior
imeta mod should change the author value from AJones to BSmith

### Notes
Hi everyone, let me know if I need to reformat this post or anything, it's my first time posting an issue. 
Thanks for the help in advance. I'm entirely new to iRODS and am trying learn as quickly as possible.

**Comment by trel** [comment] 2018-03-30 17:15
This appears to be a duplicate of https://github.com/irods/irods/issues/3787

**Closed** 2018-04-11 00:41 UTC
Labels: duplicate
