### ISSUE TITLE
error updating to 4.1.1

### ISSUE THREAD

**Issue by childers** [irods/irods#2733] opened 2015-06-05 14:18 UTC
Hi all, I posted this to the google group, and wanted to also submit it as an issue here.

We ran into a problem upgrading to 4.1.1. the short version is that the database plugin updated without issue, but the iCAT package failed.  Has anyone else reported this issue? 

Looking at /etc/passwd, I have the following entry for the irods user I am testing with:
irods:x:370:487:iRODS Administrator:/var/lib/irods:/bin/bash

It looks like the error was generated because the updater was trying to use the UID, but the number it references is the group ID (487). 

The longer version:
The irods-postgres plugin installed okay.  When I try to update the irods-icat, I get the following:

[root@dev rpms]# rpm -U irods-icat-4.1.1-centos6-x86_64.rpm
error: Failed dependencies:
        perl(JSON) is needed by irods-icat-4.1.1-0.x86_64
        perl-JSON is needed by irods-icat-4.1.1-0.x86_64
        python-jsonschema is needed by irods-icat-4.1.1-0.x86_64
        python-psutil is needed by irods-icat-4.1.1-0.x86_64
        python-requests is needed by irods-icat-4.1.1-0.x86_64
[root@dev rpms]#

I installed python-requests, python-psutil, python-jsonschema, and perl-JSON packages. 

Then when I retry, I get the following:

[root@dev rpms]# rpm -U irods-icat-4.1.1-centos6-x86_64.rpm
Upgrading Existing iRODS Installation
Traceback (most recent call last):
  File "/var/lib/irods/packaging/convert_configuration_to_json.py", line 510, in <module>
    main()
  File "/var/lib/irods/packaging/convert_configuration_to_json.py", line 506, in main
    convert_legacy_configuration_to_json()
  File "/var/lib/irods/packaging/convert_configuration_to_json.py", line 501, in convert_legacy_configuration_to_json
    convert_serverconfig_and_irodsconfig()
  File "/var/lib/irods/packaging/convert_configuration_to_json.py", line 469, in convert_serverconfig_and_irodsconfig
    new_group = get_group('/etc/irods/core.re')
  File "/var/lib/irods/packaging/convert_configuration_to_json.py", line 47, in get_group
    return pwd.getpwuid(os.stat(filename).st_gid).pw_name
KeyError: 'getpwuid(): uid not found: 487'
warning: %post(irods-icat-4.1.1-0.x86_64) scriptlet failed, exit status 1
warning: /etc/irods/server.config saved as /etc/irods/server.config.rpmsave
warning: /etc/irods/irods.config saved as /etc/irods/irods.config.rpmsave

**Comment by trel** [comment] 2015-06-05 15:42
You beat me to it, but I didn't see it until I'd already pushed.  Closing this as duplicate of #2734

**Closed by trel** 2015-06-05 15:42 UTC
Labels: bug
