### ISSUE TITLE
out of date replica stops the rebalance with 'data object probably doesn't have any good replicas'

### ISSUE THREAD

**Issue by kript** [irods/irods#4105] opened 2018-09-10 10:09 UTC
## Bug Report

Out of date replica stops the rebalance with 'data object probably doesn't have any good replicas'.
This is likely caused by or related to #3862 as we didn't get this before this error, and the rebalance has fixed similar situations in the past. It may be that this error is actually the above issue being incorrectly reported as bad replicas (see observed behaviors)

### iRODS Version, OS and Version

iRODS 4.1.10
OS: Ubuntu 12.04

### What did you try to do?

run a rebalance with `iadmin modresc root rebalance`

### Expected behavior

Rebalance operation updates dirty and single replicas.

### Observed behavior (including steps to reproduce, if applicable)

```
Aug 31 14:21:12 pid:13138 ERROR: [-]    libpassthru.cpp:793:passthru_file_rebalance :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message []
                [-]     irods_repl_rebalance.cpp:464:proc_results_for_rebalance :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message []
                        [-]     irods_repl_rebalance.cpp:267:get_source_data_object_attributes :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message [genQuery failed: _data_id [162458980] _parent [replicate]. data object probably doesn't have any good replicas]
Aug 31 14:21:12 pid:13138 ERROR: [-]    iRODS/server/api/src/rsGeneralAdmin.cpp:623:_rsGeneralAdmin :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message [failed to rebalance resource]
        [-]     libpassthru.cpp:799:passthru_file_rebalance :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message []
                        [-]     irods_repl_rebalance.cpp:464:proc_results_for_rebalance :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message []
                                [-]     irods_repl_rebalance.cpp:267:get_source_data_object_attributes :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message [genQuery failed: _data_id [162458980] _parent [replicate]. data object probably doesn't have any good replicas
```

```
:~$ ils -L /seq/26381/qc/26381_1#438_phix.bam_flagstats.json
  srpipe            0 root;replicate;seq-red;red4;irods-seq-i21-de         1405 2018-08-30.03:09 & 26381_1#438_phix.bam_flagstats.json
    e667a0787b5e250eafaab3999bfa4c43    generic    /irods-seq-i21-de/26381/qc/26381_1#438_phix.bam_flagstats.json
  srpipe            1 root;replicate;seq-green;green5;irods-seq-sr06-bc         1405 2018-07-26.04:31   26381_1#438_phix.bam_flagstats.json
    e5f54fe5a101bd72401cfcd54fd4d765    generic    /irods-seq-sr06-bc/26381/qc/26381_1#438_phix.bam_flagstats.json
  srpipe            2 root;replicate;seq-green;green5;irods-seq-sr06-fg         1405 2018-08-30.03:09 & 26381_1#438_phix.bam_flagstats.json
    e667a0787b5e250eafaab3999bfa4c43    generic    /irods-seq-sr06-fg/26381/qc/26381_1#438_phix.bam_flagstats.json

Note replica 1 doesn’t have the ‘good flag’ of ‘&’

This matches the md5sum of the files themselves;
e667a0787b5e250eafaab3999bfa4c43  /irods-seq-i21-de/26381/qc/26381_1#438_phix.bam_flagstats.json
e5f54fe5a101bd72401cfcd54fd4d765  /irods-seq-sr06-bc/26381/qc/26381_1#438_phix.bam_flagstats.json
e667a0787b5e250eafaab3999bfa4c43  /irods-seq-sr06-fg/26381/qc/26381_1#438_phix.bam_flagstats.json
```

**Comment by trel** [comment] 2018-09-10 12:06
Yes, I think this is just an over-confident attribution of cause in the error message.

This appears to be #3862.

**Comment by JustinKyleJames** [comment] 2018-09-12 16:44
We looked into this some more.  Terrell is correct.  The message is misleading here.  If the data object doesn't have any good replicas the error message would be CAT_NO_ROWS_FOUND.

Ideally the code should separate the CAT_NO_ROWS_FOUND from all other errors and only put the "data object probably doesn't have any good replicas" message under the former condition.

**Comment by trel** [comment] 2018-09-12 17:13
Closing as duplicate of #3862.

**Closed by trel** 2018-09-12 17:13 UTC
Labels: consortium-member, duplicate

**Comment by kript** [comment] 2018-09-13 09:36
This is actually two issues, I realise; the duplicate as mentioned but also the incorrect marking the object as not having any good replicas (it has two)... Can we keep open for that please?

**Comment by trel** [comment] 2018-09-13 12:51
It’s not marking the replicas as out-of-date.

It’s just making a poor guess at *why* an error was returned in that codepath.  Once we clean up the statement table management, the guess will no longer be as poor.

Is there some other action you’re suggesting here?

**Comment by kript** [comment] 2018-09-17 15:47
The underlying error is that the rebalance is failing because an object doesn't have any good replicas. However, as can be seen by the `ils` and `md5sum` two of the replica's *are* good, and so the error shouldn't have been raised in the first place.

The issue has reoccurred on a  subsequent rebalance, on a different file as well;

```
Sep 17 16:37:52 pid:14310 ERROR: [-]    libpassthru.cpp:793:passthru_file_rebalance :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message []
                [-]     irods_repl_rebalance.cpp:464:proc_results_for_rebalance :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message []
                        [-]     irods_repl_rebalance.cpp:267:get_source_data_object_attributes :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message [genQuery failed: _data_id [168610027] _parent [replicate]. data object probably doesn't have any good replicas]
Sep 17 16:37:52 pid:14310 ERROR: [-]    iRODS/server/api/src/rsGeneralAdmin.cpp:623:_rsGeneralAdmin :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message [failed to rebalance resource]
        [-]     libpassthru.cpp:799:passthru_file_rebalance :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message []
                        [-]     irods_repl_rebalance.cpp:464:proc_results_for_rebalance :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message []
                                [-]     irods_repl_rebalance.cpp:267:get_source_data_object_attributes :  status [CAT_STATEMENT_TABLE_FULL]  errno [] -- message [genQuery failed: _data_id [168610027] _parent [replicate]. data object probably doesn't have any good replicas]
```
file info;
```
(virtualenv_prc_0.6.0_beta_plus_tools)irods-g1@irods-g1:~$ iquest "%s/%s" "SELECT COLL_NAME, DATA_NAME where DATA_ID = '168610027'"
/seq/26660/26660_3#6_phix.bam_stats
(virtualenv_prc_0.6.0_beta_plus_tools)irods-g1@irods-g1:~$ python sanger-scripts/manually_verify_replica.py /seq/26660/26660_3#6_phix.bam_stats
checking: /seq/26660/26660_3#6_phix.bam_stats
(virtualenv_prc_0.6.0_beta_plus_tools)irods-g1@irods-g1:~$ ils -L /seq/26660/26660_3#6_phix.bam_stats
  srpipe            0 root;replicate;seq-red;red3;irods-seq-i19-de          619 2018-08-30.21:03 & 26660_3#6_phix.bam_stats
    4f0abb250e9475b06967d7cb4225ed93    generic    /irods-seq-i19-de/26660/26660_3#6_phix.bam_stats
  srpipe            1 root;replicate;seq-green;green5;irods-seq-sr07-fg          619 2018-08-30.21:03 & 26660_3#6_phix.bam_stats
    4f0abb250e9475b06967d7cb4225ed93    generic    /irods-seq-sr07-fg/26660/26660_3#6_phix.bam_stats
  srpipe            2 root;replicate;seq-green;green5;irods-seq-sr05-bc          592 2018-08-24.22:58   26660_3#6_phix.bam_stats
    57f4974b8d498917060c61c63492c30a    generic    /irods-seq-sr05-bc/26660/26660_3#6_phix.bam_stats
```

**Comment by trel** [comment] 2018-09-17 16:41
I think that's backwards.  I think there is a bug (#3862) where the STATEMENT_TABLE is not being cleaned up, and then it maxes out.

The object's replicas' status are not at issue, I think.

**Comment by kript** [comment] 2018-09-18 08:58
Ok, thanks.
