### ISSUE TITLE
`-f` option in `irm` doesn't check if objects exists

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7117] opened 2023-06-09 14:06 UTC
### iRODS Version, OS and Version
4.3.0 almalinux8
iCommands 4.3.0

### What did you try to do?
I tried to delete nonexistent objects by `irm` with/without the option `-f`.

### Expected behavior
I expected to see an output/error with "object does not exist" when I tried to remove by `irm -f`. 

### Observed behavior (including steps to reproduce, if applicable)
It returns success. That may make someone felt that a nonexistent object is removed.

```
root@010f175da147:/tmp# ils
/gbiomed/home/u0137480/test_irm:
root@010f175da147:/tmp# echo $?
0
root@010f175da147:/tmp# irm test.txt
remote addresses: 134.58.67.74 ERROR: rmUtil: srcPath /gbiomed/home/u0137480/test_irm/test.txt does not exist
root@010f175da147:/tmp# echo $?
3
root@010f175da147:/tmp# irm -f test.txt
root@010f175da147:/tmp# echo $?
0
```

**Comment by korydraughn** [comment] 2023-06-09 18:47
This is by design.

See #5438.

**Comment by trel** [comment] 2023-06-11 00:53
yes, closing.

behaving the same as `rm -f` is the design...

```
$ ls doesnotexist
ls: doesnotexist: No such file or directory
$ rm doesnotexist
rm: doesnotexist: No such file or directory
$ echo $?
1
$ rm -f doesnotexist
$ echo $?
0
```

**Closed by trel** 2023-06-11 00:53 UTC
Labels: resolved/invalid, consortium-member
