### ISSUE TITLE
`iqstat -a` crashes - cannot handle wrong input

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6740] opened 2022-11-24 18:58 UTC
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
-----

### iRODS Version, OS and Version
IRODS 4.2.11 on Centos 7 containers
iCommands 4.2.11

### What did you try to do?
An input after iqstat -a`, like;

`iqstat -a a`

or

`iqstat -a 1`

### Expected behavior
Smoothly handle it and/or warn the client with: `status = -318000 USER_INPUT_OPTION_ERR`

### Observed behavior (including steps to reproduce, if applicable)

On the client side:
```
-bash-4.2$ iqstat -a a
Pending rule-executions
rcGenQuery failed with error -154000 SYS_INTERNAL_ERR
 ERROR: [-]     /irods_source/lib/core/src/rcConnect.cpp:279:int rcDisconnect(rcComm_t *) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'client stop']
        [-]     /irods_source/lib/core/src/sockComm.cpp:98:irods::error sockClientStop(irods::network_object_ptr, rodsEnv *) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'client stop']
                [-]     /irods_source/plugins/network/src/ssl.cpp:593:irods::error ssl_client_stop(irods::plugin_context &, rodsEnv *) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error shutting down the SSL connection]



```

In the logs:

`irods stdout | {"log_category":"server","log_facility":"local0","log_level":"critical","log_message":" 0# stacktrace_signal_handler in /lib/libirods_server.so.4.3.0\n 1# 0x00007F8AA7D11630 in /lib64/libpthread.so.0\n 2# getZoneHintForGenQuery in /lib/libirods_server.so.4.3.0\n 3# rsGenQuery(RsComm*, GenQueryInp*, GenQueryOut**) in /lib/libirods_server.so.4.3.0\n 4# irods::api_call_adaptor<GenQueryInp*, GenQueryOut**>::operator()(irods::plugin_context&, RsComm*, GenQueryInp*, GenQueryOut**) in /lib/libirods_server.so.4.3.0\n 5# std::__1::__function::__func<irods::api_call_adaptor<GenQueryInp*, GenQueryOut**>, std::__1::allocator<irods::api_call_adaptor<GenQueryInp*, GenQueryOut**> >, irods::error (irods::plugin_context&, RsComm*, GenQueryInp*, GenQueryOut**)>::operator()(irods::plugin_context&, RsComm*&&, GenQueryInp*&&, GenQueryOut**&&) in /lib/libirods_server.so.4.3.0\n 6# int irods::api_entry::call_handler<GenQueryInp*, GenQueryOut**>(RsComm*, GenQueryInp*, GenQueryOut**) in /lib/libirods_server.so.4.3.0\n 7# rsApiHandler(RsComm*, int, BytesBuf*, BytesBuf*) in /lib/libirods_server.so.4.3.0\n 8# readAndProcClientMsg(RsComm*, int) in /lib/libirods_server.so.4.3.0\n 9# agentMain(RsComm*) in /lib/libirods_server.so.4.3.0\n10# runIrodsAgentFactory(sockaddr_un) in /lib/libirods_server.so.4.3.0\n11# main::$_5::operator()() const in /usr/sbin/irodsServer\n12# main in /usr/sbin/irodsServer\n13# __libc_start_main in /lib64/libc.so.6\n14# _start in /usr/sbin/irodsServer\n","server_host":"dev-u0137480-instance2.irods.t.icts.kuleuven.be","server_pid":108,"server_timestamp":"2022-11-24T18:57:07.031Z","server_type":"server","stacktrace_agent_pid":"5923","stacktrace_timestamp_epoch_milliseconds":"101","stacktrace_timestamp_epoch_seconds":"1669316226","stacktrace_timestamp_utc":"2022-11-24T18:57:06.101Z"}`

**Comment by alanking** [comment] 2022-12-20 18:28
I poked my head in here to see what might be happening and it seems that many mechanisms used in `rsGenQuery` are not checking for `nullptr` in the substructs of `GenQueryInp`. The `inx` and `val` member of `selectInp` and `sqlCondInp` can be `nullptr` and are dereferenced with `operator[]` in many places with no checks.

`iqstat` is generating a query which is either dereferencing a `nullptr` in the agent, or the `len` member of one of these structs causes the agent to access memory out of bounds. `packStruct` is protecting the server against clients feeding incorrect `len`s because it wouldn't be able to pack the inputs if `len` was longer than the allocated memory (which would cause the client to blow up, not the agent). Therefore, the out of bounds memory access would be caused by some mechanism in the server, OR (more likely, in my opinion), the substructs are `nullptr`.

Separately, the `iqstat` output is wrong because it's not responding correctly to the returned error codes from the `rcGenQuery` call(s).

**Comment by alanking** [comment] 2023-02-24 14:51
I created https://github.com/irods/irods/issues/6936 to address the API side of this equation so as to not block this issue.

**Comment by d-w-moore** [comment] 2023-02-24 14:57
Oh, good... thanks.

**Comment by alanking** [comment] 2023-02-24 20:09
D'oh. Missed #6267 when linking issues in the commit message. For the sake of consistency, let's just continue linking this issue for the main/4-3-stable cherry-picks and mark the other as duplicate.

Please chime in if others have opinions on this matter

**Comment by d-w-moore** [comment] 2023-02-25 19:35
What do we think about perhaps closing that one? https://github.com/irods/irods/issues/6267#issuecomment-1445188810

**Comment by korydraughn** [comment] 2023-02-27 23:50
> What do we think about perhaps closing that one? [#6267 (comment)](https://github.com/irods/irods/issues/6267#issuecomment-1445188810)

It's now closed.

**Comment by korydraughn** [comment] 2023-02-27 23:51
Let's get the cherry-picks squared up and merged so we can close this.

**Comment by d-w-moore** [comment] 2023-02-28 06:19
OK, cherry picks done and PR's have been made to main and 4-3-stable.

main:
https://github.com/irods/irods_client_icommands/pull/366
https://github.com/irods/irods/pull/6941
4-3-stable:
https://github.com/irods/irods_client_icommands/pull/367
https://github.com/irods/irods/pull/6942

**Comment by d-w-moore** [comment] 2023-03-07 15:09
yes

**Closed** 2023-03-07 15:10 UTC
Labels: bug, consortium-member
