### ISSUE TITLE
rebalance of replication resource stopping on checksum mismatch

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3524] opened 2017-04-26 19:35 UTC
Reported by Sanger on 4.1.10:

> In other news, we’ve seen the rebalance stop with a checksum error, but while it was running we found and fixed a file that had no good replicas (both failed checksum validation), and have removed that. We’ve restarted the rebalance again, but should the rebalance have stopped there, given your earlier investigations into the log_and_continue behavior?

> The message was:
```
                [-]     irods_repl_rebalance.cpp:570:proc_results_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message []
                        [-]     irods_repl_rebalance.cpp:570:proc_results_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message []
```

**Comment by trel** [comment] 2017-07-28 20:22
@kript have you seen this occur again?   we have not reproduced this error.

**Comment by kript** [comment] 2017-07-31 12:48
From memory,  yes, but I wonder if this is actually #3537 under the hood.

**Comment by trel** [comment] 2017-07-31 13:11
seems reasonable.   let's wait a few more days for a #3537 fix, and maybe this one we mark as duplicate.

**Comment by trel** [comment] 2017-09-12 02:22
Closing - no known bugs at this time.  Famous last words.

**Comment by trel** [comment] 2017-09-12 02:23
Duplicate of #3537

**Closed by trel** 2017-09-12 02:22 UTC
Labels: bug, consortium-member
