### ISSUE TITLE
iget error for registered file that service account cannot read (because permissions are wrong OR file does not exist) is not helpful

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2425] opened 2014-11-24 18:23 UTC
Current `iget` error:
`ERROR: getUtil: get error for foo status = -1 Unknown iRODS error, Operation not permitted`

Current log output for wrong permissions:
```
Nov 24 13:20:01 pid:14151 NOTICE: Agent process 30113 exited with status 0
Nov 24 13:20:01 pid:14151 NOTICE: Agent process 30135 started for puser=rods and cuser=rods from 152.54.8.81
Nov 24 13:20:01 pid:30135 ERROR: [-]    iRODS/server/api/src/rsFileOpen.cpp:163:_rsFileOpen :  status [UNIX_FILE_OPEN_ERR]  errno [Permission denied] -- message [_rsFileOpen: fileOpen for [/var/lib/irods/tmp/temp_file]]
        [-]     iRODS/server/drivers/src/fileDriver.cpp:69:fileOpen :  status [UNIX_FILE_OPEN_ERR]  errno [Permission denied] -- message [failed to call 'open']
                [-]     libunixfilesystem.cpp:531:unix_file_open_plugin :  status [UNIX_FILE_OPEN_ERR]  errno [Permission denied] -- message [Open error for "/var/lib/irods/tmp/temp_file", errno = "Permission denied", status = -510013, flags = 0.]

Nov 24 13:20:01 pid:30135 NOTICE: _rsFileGet: fileGet for /var/lib/irods/tmp/temp_file, status = -1
Nov 24 13:20:01 pid:30135 NOTICE: readAndProcClientMsg: received disconnect msg from client
Nov 24 13:20:01 pid:30135 NOTICE: Agent exiting with status = 0
```

Current log output for missing file:
```
Nov 24 13:25:49 pid:14151 NOTICE: Agent process 30220 exited with status 0
Nov 24 13:25:49 pid:14151 NOTICE: Agent process 30225 started for puser=rods and cuser=rods from 152.54.8.81
Nov 24 13:25:49 pid:30225 ERROR: [-]    iRODS/server/api/src/rsFileOpen.cpp:163:_rsFileOpen :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message [_rsFileOpen: fileOpen for [/var/lib/irods/tmp/temp_file]]
        [-]     iRODS/server/drivers/src/fileDriver.cpp:69:fileOpen :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message [failed to call 'open']
                [-]     libunixfilesystem.cpp:531:unix_file_open_plugin :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message [Open error for "/var/lib/irods/tmp/temp_file", errno = "No such file or directory", status = -510002, flags = 0.]

Nov 24 13:25:49 pid:30225 NOTICE: _rsFileGet: fileGet for /var/lib/irods/tmp/temp_file, status = -1
Nov 24 13:25:49 pid:30225 NOTICE: readAndProcClientMsg: received disconnect msg from client
Nov 24 13:25:49 pid:30225 NOTICE: Agent exiting with status = 0
```

**Comment by tempoz** [comment] 2015-03-18 20:06
Can you confirm this still occurs? I cannot reproduce.

**Comment by tempoz** [comment] 2015-03-18 20:17
Error is more informative, closing.

**Closed by tempoz** 2015-03-18 20:17 UTC
Labels: enhancement
