### ISSUE TITLE
Investigate test_control_plane.py with PREP on Debian 11

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6441] opened 2022-06-11 16:17 UTC
- [x] main
- [x] 4-3-stable

---

- Tests cannot find `irods-grid` command
- Agent factory and Delay server become orphans

Observed while using the testing environment.

**Comment by trel** [comment] 2022-06-11 17:21
only on Debian11?

**Comment by korydraughn** [comment] 2022-06-11 17:23
That is the only place I've seen it happen. Almalinux did not have this problem and Ubuntu 20 did not either.

I'm running CentOS 7 tests now to see if it has any issues.

**Comment by alanking** [comment] 2024-01-09 20:31
Looks like #7389 is a duplicate of this issue.

**Comment by alanking** [comment] 2024-03-15 19:45
While investigating this, I've made a couple of observations...

1. `irods-grid` cannot be found in the `$PATH` for the service account whether PREP is involved or not. The executable is installed in `/usr/sbin`, but `/usr/sbin` is not in the `$PATH` of the service account. This problem does not exist on, e.g. Ubuntu 22.04 because the `$PATH` of the service account includes `/usr/sbin` on that platform. We probably need to rectify this so that the service account can reliably execute all of our stuff in `/usr/sbin` *or* we need to update the tests to not assume `irods-grid` will be found in the path.

2. `ps`, `pkill`, etc. are not available on the Debian 11 image in the testing environment. `procps` is being installed manually on the Debian 12 image, but not Debian 11 (see irods/irods_testing_environment#176). I think we should probably do that as well. Probably don't need to worry about the `pip` stuff.

**Comment by alanking** [comment] 2024-03-15 20:02
On point 1 in my previous comment, it should be noted that, while `irods-grid` cannot be found in the `$PATH` of the service account regardless of whether PREP is installed/configured, `test_control_plane.TestControlPlane.test_status` fails for PREP but passes for the "core" tests. The test uses `irods-grid` without using a full path or modifying the environment in any special way.

**Closed** 2024-03-27 21:13 UTC
Labels: testing, prep
