### ISSUE TITLE
do not set socket options related to buffer size

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3156] opened 2016-05-03 00:42 UTC
iRODS should allow Linux to optimize accordingly.  Significant performance issues have been identified over high performance networks.

**Comment by trel** [comment] 2016-05-03 20:28
On a low-latency intra-building link, from machine A to B, both with SSDs, the existing 4.1.8 settings were fastest.

stock 4.1.8 to 4.1.8

```
~/irods$ time iput -r iRODS rec
real    0m38.953s

~/irods$ time iput -br iRODS recbulk
real    0m24.836s

~/irods$ time iput 10gfile 10gfile
real    1m32.417s
```

Letting the linux autotune happen slowed things down by 20-30% for small files (the files were completely transferred before the TCP window could scale up) since the TCP window started smaller than in our original settings.  The large file transfer was saturating the link and showed no effect of the changed window size.

4.1.8 w/ no tcp window settings to 4.1.8 w/ no tcp window settings

```
~/irods$ time iput -r iRODS rec-notcp
real    0m54.549s

~/irods$ time iput -br iRODS recbulk-notcp
real    0m38.042s

~/irods$ time iput 10gfile 10gfile-notcp
real    1m32.104s
```

Fixing the send and receive window sizes to exactly 16M had a similar slow-down effect on the small files.  Large files were still unaffected, the link was still saturated.

4.1.8 w/ 16M buffer to 4.1.8 w/ 16M buffer

```
~/irods$ time iput -r iRODS rec-16Mbuf
real    0m53.946s

~/irods$ time iput -br iRODS recbulk-16Mbuf
real    0m34.522s

~/irods$ time iput 10gfile 10gfile-16Mbuf
real    1m32.126s
```

This suggests we need to run a similar set of tests on a high-speed WAN (w/ latency) that will affect the buffers along the way.

**Comment by tedgin** [comment] 2016-05-06 22:17
I'm trying to reproduce the bulk tests on our LAN.  These are Two machines with 10 Gbit/s ethernet and an RTT of 0.123ms.  I created a single directory with 1000 1 MB files.  I see a possible 5-10% performance hit for bulk uploads, but no difference for the other.

4.1.8 stock to 4.1.8 stock
```
[root@new-apollo ~]# time iput -r tony-test bulk

real	0m32.093s
user	0m1.450s
sys	0m1.009s
[root@new-apollo ~]# time iput -b -r tony-test bulk2

real	0m21.580s
user	0m0.045s
sys	0m1.106s
```

4.1.8 w/ not tcp window settings to 4.1.8 w/ no tcp window settings
```
[root@new-apollo ~]# time iput -r tony-test bulk

real	0m30.067s
user	0m2.381s
sys	0m1.014s
[root@new-apollo ~]# time iput -b -r tony-test bulk2

real	0m23.024s
user	0m0.051s
sys	0m1.129s
```

What are the specifics of the files you are uploading? I'd like to understand the difference.

**Comment by trel** [comment] 2016-05-06 23:51
The iRODS in my example is just the iRODS directory in the 4.1.8 source.

The 10gfile was created with

truncate -s 10G 10gfile

**Comment by tedgin** [comment] 2016-05-10 00:10
I was able to reproduce your results, though less dramatically.  I think the slow storage we are using on our test systems is masking the results somewhat.

4.1.8 stock to 4.1.8 stock
{code}
[root@new-apollo ~]# time iput -r iRODS 
real	0m45.741s

[root@new-apollo ~]# time iput -b -r iRODS 
real	0m30.665s
{code}

4.1.8 w/ no tcp window settings to 4.1.8 w/ no tcp window settings
{code}
[root@new-apollo ~]# time ./iput-4ab -r iRODS 
real	0m51.984s

[root@new-apollo ~]# time ./iput-4ab -b -r iRODS 
real	0m34.931s
{code}

**Comment by jasoncoposky** [comment] 2016-05-10 20:39
Do we expose a new advanced specifically for the TCP window and also provide a 'none' option to not set it at all?

**Comment by trel** [comment] 2016-06-15 20:41
need to cherry-pick to XBB-2, then close.

**Comment by trel** [comment] 2016-06-24 15:59
needs
- revert 58eb275
- new commit removing TCP settings, letting TCP autotune take over
- cherry-pick to XBB-2

**Closed** 2016-06-28 15:35 UTC
Labels: bug
