### ISSUE TITLE
bad hierarchy after iput in 4.1.9

### ISSUE THREAD

**Issue by trel** [irods/irods#3586] opened 2017-06-26 15:26 UTC
From https://groups.google.com/forum/#!topic/irod-chat/qw5cVBeEzXY

Using iRODS 4.1.9:

```
$ ilsresc --tree rootResc
rootResc:passthru
└── randResc:random
    ├── pt0:passthru
    │   └── ufs0
    ├── pt1:passthru
    │   └── ufs1
    └── pt2:passthru
        └── ufs2
```

With `pt0` modified for read-only:
```
$ iadmin modresc pt0 context 'write=0.0;read=1.0'
```

A new file is put, and then `ils -L` shows an incorrect hierarchy (too much "pt0;ufs0"):
```
  irodsadmin        0 rootResc;randResc;pt0;ufs0;pt2;ufs2          475 2017-06-26.16:17 & testfile3
        generic    /var/test/ufs2/home/irodsadmin/test/testfile3
```

**Comment by kellerb** [comment] 2017-06-26 15:45
This may be a duplicate of [#3315](https://github.com/irods/irods/issues/3315).

**Comment by trel** [comment] 2017-06-26 15:54
Good catch, sir.

**Closed** 2017-06-26 18:48 UTC
Labels: bug, duplicate
