### ISSUE TITLE
icp erratic behaviour with the 'passthru' resource

### ISSUE THREAD

**Issue by triitaojcsc** [irods/irods#2789] opened 2015-07-10 10:24 UTC
Hi,

in iRODS 4.X the newish 'passthru' resource has a weird bug(/feature?) related to 'icp' and the 'replication' resource.

In a situation where an iRODS administrator would like to allow writes but to prevent reads to/from a certain (slow) resource, the resource tree might look like the following:

```
    test_resource:replication
    ├── test_resource_1
    └── weightResc:passthru
            └── test_resource_2
```

Where 'weightResc' has the context "read=0.00;write=0.25".

This works fine for 'iput' (the data object gets replicated to both test_resource_1 and test_resource_2) and for 'iget' (the data object is retrieved from test_resource_1, and not from test_resource_2).

However, an 'icp' operation for a data object causes the new copy to only have one replica. The 'read=0.00' when used with 'icp' for some reason prevents the creation of a second replica, though 'iput' works OK.

Different scenarios:

- icp, iput, iget work, and icp produces 2 replicas:

```
    test_resource:replication
    ├── test_resource_1
    └── test_resource_2
```

- icp, iput, and iget work, but icp produces only 1 replica:

```
    test_resource:replication
    ├── test_resource_1
    └── weightResc:passthru    <---- read=0.00
            └── test_resource_2
```
        
- icp, iput, iget work, and icp produces 2 replicas:

```
    test_resource:replication
    ├── test_resource_1
    └── weightResc:passthru    <---- read=0.25
            └── test_resource_2
```

The desired outcome is that 'icp' would behave like 'iput' and produce two replicas when 'read=0.00'.

-- Taneli Riitaoja / CSC - IT Center for Science Ltd.

**Comment by trel** [comment] 2015-07-10 13:10
confirmed - working on a fix.   thanks!

**Comment by trel** [comment] 2015-07-10 14:19
1) If the child resource is the weighted passthru with a read=0.0 and it receives the first replica (from the cp) the weighted passthru will prevent replication (as intended).  Set the write to a value < 1.0 in order for it to not receive the first replica (meaning another child resource would 'win').

2) A put succeeds because it is a 'write' operation and the weighted passthru is set to accept writes (write > 0.0).

3) If the source file of the icp resides on the same replication resource, the operation is a 'read' first, which excludes the weighted passthru child since it voted 0 for the read operation.  It is then not a candidate for replication.  **This is the bug** and will need to be fixed by constructing a secondary candidate list for the replicating (write) operation.

The above scenarios work as intended if the original data object is on a separate resource (with a non-zero read vote).

**Closed** 2015-07-15 01:44 UTC
Labels: bug
