### ISSUE TITLE
Delayed rule run by a rodsuser fails to update last_exe_time.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#5257] opened 2020-11-19 16:19 UTC
- [x] master
- [x] 4-2-stable
-----

## Bug Report

A permission error is generated after a delayed rule that is scheduled to run periodically by a rodsuser is executed.  This is due to trying to modify the rule (probably last_exe_time).

### iRODS Version, OS and Version

iRODS 4.2.8 and CentOS Linux release 7.8.2003

### What did you try to do?

Create a rule that runs every 30 seconds to print out a message.

### Expected behavior

The message is printed out every 30 seconds.  No errors are generated.

### Observed behavior (including steps to reproduce, if applicable)

The following error is generated.

```
Nov 19 16:14:49 pid:82656 NOTICE: rsApiHandler: User has no permission for apiNumber 708
```

This is the RULE_EXEC_MOD_AN API.

**Comment by korydraughn** [comment] 2020-11-20 00:29
I created a user with the type `rodsuser` and executed the following command:
```bash
irule -r irods_rule_engine_plugin-irods_rule_language-instance 'delay("<EF>5s</EF><INST_NAME>irods_rule_engine_plugin-irods_rule_language-instance</INST_NAME>") { writeLine("serverLog", "hello, iRODS!"); }' null ruleExecOut
```
It is executing and updating the `last_exe_time` without any errors.

@JustinKyleJames Can you reproduce this against the tip of 4-2-stable or master?

**Comment by trel** [comment] 2020-11-20 00:41
needs to run more than once?  try `<EF>REPEAT FOR EVER</EF>`?

**Comment by korydraughn** [comment] 2020-11-20 00:52
i was able to reproduce this. i'll have a fix for this soon.

**Comment by korydraughn** [comment] 2020-11-20 13:50
These are lines that trigger that error message:
https://github.com/irods/irods/blob/9ceade8c76471f8f2dbdc0ec92fe182f072ff01f/server/core/src/rsApiHandler.cpp#L420-L423

When the delay server attempts to update the delay rule's catalog entry, the request is rejected because the API definition requires `LOCAL_PRIV_USER_AUTH`. The user's privilege level comes in at `LOCAL_USER_AUTH` which is less the required privilege level. See their values below:
https://github.com/irods/irods/blob/9ceade8c76471f8f2dbdc0ec92fe182f072ff01f/lib/core/include/rodsUser.h#L21-L26

Below is the API definition:
https://github.com/irods/irods/blob/8c1d5038c65bd2a340dacea55285cbcadb4c7477/lib/api/include/apiTable.hpp#L736-L742

So, the result is correct based on how the implementation is and the API definition is configured.

### Questions
1. How do we want to resolve this?
2. Should the API definition be changed?
3. The API number for this endpoint is in the client API allow list. Does that mean the API definition's privilege level should be lowered to `LOCAL_USER_AUTH`?

**Comment by trel** [comment] 2020-11-20 14:11
This started happening when we made the delay server a client in 4.2.0.

We need to relax the API definition because it's not *in* the server anymore.

**Closed** 2020-11-20 21:43 UTC
Labels: bug, consortium-member
