### ISSUE TITLE
pythonRuleEnginePluginTest fires twice per irule invocation

### ISSUE THREAD

**Issue by cbcunc** [irods/irods#7407] opened 2023-10-20 22:05 UTC
iRODS 4.2.11 on updated Centos 7.9

1) As root user `yum install -y irods-rule-engine-plugin-python-4.2.11.1-1`

2) As irods user `cp -a /etc/irods/core.py.template /etc/irods/core.py`

3) As irods user include standard python rule engine plug-in stanza in `/etc/irods/server_config.json`:
```
       "rule_engines": [
            {
                "instance_name": "irods_rule_engine_plugin-irods_rule_language-instance",
                "plugin_name": "irods_rule_engine_plugin-irods_rule_language",
                "plugin_specific_configuration": {
                    "re_data_variable_mapping_set": [
                        "core"
                    ],
                    "re_function_name_mapping_set": [
                        "core"
                    ],
                    "re_rulebase_set": [
                        "hydroshare",
                        "core"
                    ],
                    "regexes_for_supported_peps": [
                        "ac[^ ]*",
                        "msi[^ ]*",
                        "[^ ]*pep_[^ ]*_(pre|post|except|finally)"
                    ]
                },
                "shared_memory_instance": "upgraded_irods_rule_language_rule_engine"
            },
            {
                "instance_name": "irods_rule_engine_plugin-cpp_default_policy-instance",
                "plugin_name": "irods_rule_engine_plugin-cpp_default_policy",
                "plugin_specific_configuration": {}
            },
            {
                "instance_name": "irods_rule_engine_plugin-python-instance",
                "plugin_name": "irods_rule_engine_plugin-python",
                "plugin_specific_configuration": {}
            }
        ]
```

4) As irods user `irule pythonRuleEnginePluginTest "null" "null"`

5) Output in `/tmp/from_core_py.txt`:
```
2023-10-20 16:27:12.127592
2023-10-20 16:27:12.128070
```

6) Output in `rodsLog`
```
Oct 20 16:27:12 pid:16353 NOTICE: writeLine: inString = Printed to server log from python rule engine
Oct 20 16:27:12 pid:16353 NOTICE: writeLine: inString = Printed to server log from python rule engine
```

**Comment by alanking** [comment] 2023-10-31 16:03
Transferring to irods/irods so it gets a milestone...

**Comment by alanking** [comment] 2024-01-09 19:48
Took another look at this, and I think this is actually the expected behavior. Here's what's happening:

When PREP is configured, any rules defined in `core.py` or even imported by `core.py` become available for use in any other rule engine plugin, including the native rule engine plugin. `irule` when run with no target REP will give every configured REP a chance to execute the rule, in order. What we're seeing is the rule `pythonRuleEnginePluginTest` being executed by all configured REPs. We only see two because `irods_rule_engine_plugin-cpp_default_policy-instance` produces no output when it executes the rule.

If you define `pythonRuleEnginePluginTest` inside `core.re` with a different implementation, the output changes:
```bash
$ head /etc/irods/core.re
pythonRuleEnginePluginTest {
        writeLine("serverLog", "Printed to server log from native rule engine");
}

# iRODS core.re Rule Base
#
# Defines the SSL (client-server negotiation) policy for this server
# - CS_NEG_REFUSE - No SSL
# - CS_NEG_DONT_CARE - Depends on the Client request
# - CS_NEG_REQUIRE - Require SSL
$ irule pythonRuleEnginePluginTest "null" "null"
```

Here's the `/tmp/from_core_py.txt` file:
```
$ cat /tmp/from_core_py.txt
2024-01-09 19:47:03.001249
```

Here's the output in the log:
```json
{
  "log_category": "legacy",
  "log_level": "info",
  "log_message": "writeLine: inString = Printed to server log from python rule engine\n",
  "request_api_name": "EXEC_MY_RULE_AN",
  "request_api_number": 625,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "192.168.240.5",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.1",
  "server_host": "e03ada129702",
  "server_pid": 1512222,
  "server_timestamp": "2024-01-09T19:47:03.001Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
{
  "log_category": "legacy",
  "log_level": "info",
  "log_message": "writeLine: inString = Printed to server log from native rule engine\n",
  "request_api_name": "EXEC_MY_RULE_AN",
  "request_api_number": 625,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "192.168.240.5",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.1",
  "server_host": "e03ada129702",
  "server_pid": 1512222,
  "server_timestamp": "2024-01-09T19:47:03.001Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
```

So, if we're all in agreement about this assessment, I think we can close this.

**Comment by alanking** [comment] 2024-01-09 19:50
Oh, the output from above is ordered as such because my configured REP order is slightly different now. I can redo the output with the right ordering if desired.

**Comment by trel** [comment] 2024-01-09 20:01
yes, agreed with your assessment - please align output in an expected boring normal way for future spelunkers.

**Comment by alanking** [comment] 2024-01-09 20:28
Okey dokey, here's the output when the REPs are configured in the order shown above in OP:
From the log:
```json
{
  "log_category": "legacy",
  "log_level": "info",
  "log_message": "writeLine: inString = Printed to server log from native rule engine\n",
  "request_api_name": "EXEC_MY_RULE_AN",
  "request_api_number": 625,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "192.168.240.5",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.1",
  "server_host": "e03ada129702",
  "server_pid": 1512846,
  "server_timestamp": "2024-01-09T20:26:48.735Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
{
  "log_category": "legacy",
  "log_level": "info",
  "log_message": "writeLine: inString = Printed to server log from python rule engine\n",
  "request_api_name": "EXEC_MY_RULE_AN",
  "request_api_number": 625,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "192.168.240.5",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.1",
  "server_host": "e03ada129702",
  "server_pid": 1512846,
  "server_timestamp": "2024-01-09T20:26:48.736Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
```
From `/tmp/from_core_py.txt`:
```bash
$ cat /tmp/from_core_py.txt
2024-01-09 20:26:48.736336
```

**Comment by trel** [comment] 2024-01-09 20:31
looks good.  i think we can close this.

**Closed** 2024-01-09 20:32 UTC
Labels: resolved/invalid, bug, consortium-member, prep
