### ISSUE TITLE
Failure during setup_irods.py: iRODS port returned non-heartbeat message

### ISSUE THREAD

**Issue by dwcaraway** [irods/irods#4098] opened 2018-09-04 14:46 UTC
### iRODS Version, OS and Version

IRODS: used the [xenial package for debian](https://packages.irods.org/apt/dists/xenial/)
OS: Ubuntu 16.04
Postgres: 10.4

### What did you try to do?

I was attempting to launch an iRODS system in Docker using `docker-compose` to orchestrate.

Here's my iRODS Dockerfile:

```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y wget apt-transport-https && wget -qO - https://packages.irods.org/irods-signing-key.asc | apt-key add -
RUN echo "deb [arch=amd64] https://packages.irods.org/apt/ xenial main" | tee /etc/apt/sources.list.d/renci-irods.list
RUN apt-get update && apt-get install -y irods-server irods-database-plugin-postgres
```

Here's my docker compose file:

```
version: '3.5'
services:
  irods:
    build:
      context: .
      dockerfile: ./compose/irods/Dockerfile
    depends_on:
      - db
  db:
    image: postgres:10.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
```

There's a `.env` file containing the environment variables:

```
POSTGRES_USER=irods
POSTGRES_PASSWORD=<yourpasswordhere>
POSTGRES_DB=icat
```

After building the dockers, I launched the setup script:

```bash
$ docker-compose run irods python /var/lib/irods/scripts/setup_irods.py
```
I go through all the prompts, entering a bunch of different keys / passwords for iRODS.

### Expected behavior

iRODS server would launch at the end of setup

### Observed behavior (including steps to reproduce, if applicable)

Received error during the `setup_irods.py` script:

```
+-------------------+
| Starting iRODS... |
+-------------------+

Validating [/var/lib/irods/.irods/irods_environment.json]... Success
Validating [/var/lib/irods/VERSION.json]... Success
Validating [/etc/irods/server_config.json]... Success
Validating [/etc/irods/host_access_control_config.json]... Success
Validating [/etc/irods/hosts_config.json]... Success
Ensuring catalog schema is up-to-date...
Updating to schema version 2...
Updating to schema version 3...
Updating to schema version 4...
Updating to schema version 5...
Catalog schema is up-to-date.
Starting iRODS server...
Failure
Error encountered running setup_irods:
Traceback (most recent call last):
  File "./setup_irods.py", line 436, in main
    setup_server(irods_config, json_configuration_file=options.json_configur
ation_file)
  File "./setup_irods.py", line 126, in setup_server
    IrodsController(irods_config).start()
  File "/var/lib/irods/scripts/irods/controller.py", line 121, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/controller.py", line 112, in start
    raise IrodsError('iRODS port returned non-heartbeat message:\n{0}'.forma
t(message))
IrodsError: iRODS port returned non-heartbeat message:

Exiting...
```

It looks like the `message` is empty. I tried rerunning the setup script and received same result.

**Comment by tempoz** [comment] 2018-09-07 14:32
Can I see the contents of your rodsLog and setup_log, both located in var/lib/irods/log/ ?

**Comment by dwcaraway** [comment] 2018-09-10 13:39
The tl;dr is `libxml2` needs to be installed.

---
`/var/lib/irods/log/rodsLog.2018.09.06` is empty.

Here's the contents of `/var/lib/irods/log/rodsServerLog.2018.09.06`:

```
Sep 10 12:36:47 pid:29 NOTICE: Agent factory process pid = [30]
    LocalHostName:  localhost, 1e86e35e1bc0, Port Num: 1247.

Zone Info:
    ZoneName: tempZone   Type: LOCAL_ICAT    HostAddr: localhost   PortNum: 1247

reHost:   localhost

Sep 10 12:36:47 pid:29 NOTICE: rodsServer Release version rods4.2.3 - API Version d is up
Sep 10 12:36:47 pid:31 NOTICE: Starting irodsReServer
Sep 10 12:36:47 pid:29 NOTICE: >>> control plane :: listening on port 1248
Sep 10 12:36:47 pid:29 remote addresses: 172.22.0.3 ERROR: readWorkerTask - readStartupPack failed. -1808000
.
.
.
```

`172.22.0.3` is the ip address of the docker container.

The log didn't offer much information, so I checked the `reLog`, which offered the the needed insight:

```
remote addresses: 172.22.0.3 ERROR: [-] /tmp/tmpLnowvJ/lib/core/src/sockComm.cpp:1159:int sendStartupPack(rcComm_t *, int, int) :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/network/libtcp_client.so] :: dlerror: is [libxml2.so.2: cannot open shared object file: No such file or directory]]
```

I installed libxml2:

```
apt-get install -y libxml2
```

after rebuilding the docker image, I was able to run the setup successfully. I curled localhost:

```
curl localhost:1247
```
and received:

```
<MsgHeader_PI>
<type>RODS_VERSION</type>
<msgLen>186</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>
<Version_PI>
<status>-4000</status>
<relVersion>rods4.2.4</relVersion>
<apiVersion>d</apiVersion>
<reconnPort>0</reconnPort>
<reconnAddr></reconnAddr>
<cookie>400</cookie>
</Version_PI>
```
I'm not sure what a `-4000` status code means but the server is responding.

**Comment by trel** [comment] 2018-09-10 13:45
We may need to update our packages to declare the `libxml2` dependency.

**Comment by trel** [comment] 2018-09-27 04:06
marking as duplicate of #4061

**Closed by trel** 2018-09-27 04:06 UTC
Labels: packaging
