### ISSUE TITLE
rodslog rotation didn't

### ISSUE THREAD

**Issue by kript** [irods/irods#3483] opened 2017-02-20 13:15 UTC
for some reason, log rotation didn't occur on this system last week;

```
irods@XXXXXXXsr08:~$ ls -last /var/lib/irods/iRODS/server/log/
total 58684
   0 drwx------ 2 irods irods       6 Feb 20 13:11 proc
 372 -rw------- 1 irods irods  378101 Feb 20 13:11 rodsLog.2017.02.11
   4 drwxr-xr-x 3 irods irods    4096 Feb 13 11:32 .
  60 -rw------- 1 irods irods   57862 Feb  9 21:44 rodsLog.2017.02.06
 248 -rw------- 1 irods irods  251542 Feb  8 20:10 rodsLog.2017.02.01
```
I've seen this occur sporadically but never bothered reporting it before. There's 120G free on the filesystem, so its not run out of space. Anywhere else I should be looking for rotation errors?

**Comment by kellerb** [comment] 2017-02-20 19:43
Are new agents still writing to the old log?

If you connect directly to this server and run 50 `ils`s successfully, in theory that should be enough to trigger the rotation.

**Comment by trel** [comment] 2017-05-26 19:17
similar, but not identical to the 4.2 bug of not writing to the latest logfile #3563

**Comment by keithj** [comment] 2017-06-09 09:14
Are #2112  / #2730 under consideration for future releases?

**Comment by trel** [comment] 2017-06-09 10:51
Yes, those are both already marked for the 4.3.0 milestone.

**Comment by trel** [comment] 2020-01-27 22:20
was this ever resolved / reproduced?

**Comment by korydraughn** [comment] 2020-01-27 23:55
I haven't taken a look at this due to other issues and enhancements.

**Comment by trel** [comment] 2020-01-28 06:36
@keithj is there anything else you can tell us?    I see the 'iRODS' in the path, so this is 4.1.x.

**Comment by kjsanger** [comment] 2020-01-28 09:07
It will be 4.1.12, that I know. You'll need to get @kript 's input on this for the details, though.

**Comment by kript** [comment] 2020-01-28 13:34
We do still get it from time to time, unfortunately, we implemented our own compression log wrapper, which compresses and moves all but the latest files to a subdir, once there are no further open file handles, so its hard to say if its _still_ an issue.

**Comment by trel** [comment] 2020-01-28 13:39
Okay - this was originally opened when 4.1.10 was the latest 4.1.x.

We won't be releasing another 4.1, and we've already overhauled logging for 4.3/master.

I'll plan to close this soon unless there's pushback.

**Closed** 2022-01-10 20:28 UTC
Labels: bug, consortium-member
