### ISSUE TITLE
Need to document the maximum host name length of 64 characters

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#2777] opened 2015-06-29 20:36 UTC
Need to:
- [x] document the max of 64 characters
- [x] fix the error message going to the log

---

Whenever a remote rule executes with a hostname that is larger than 32 characters, the iRODS errors out with an `rstrcpy not enough space is dest` error.

For example the following:
`remote( "this.is.a.very.long.remote.hostname.irods.renci.org", "null" )`
Produces the following error:
`Jun 29 16:30:29 pid:26946 ERROR: rstrcpy not enough space in dest, slen:51, maxLen:32`

This should be noted as a limitation in the documentation.

**Comment by kellerb** [comment] 2015-10-09 16:25
https://github.com/irods/irods/blob/4.1.6/iRODS/lib/core/src/rcMisc.cpp#L3678

If a `:` (and therefore a port) is not found in the host string, the entire hostname string is copied into the buffer used to hold the port. It may be the case that this error just results in spurious log output and that hostnames of length greater than 32 should still work.

**Comment by jrandall** [comment] 2016-01-13 12:10
I am also having this issue (although now the limit seems to have been raised to 64?), in the form of occasionally failing travis CI tasks for a thrid party project in which we are testing against an iRODS system installed inside travis. When travis gives us a hostname longer than 64 characters, we get something like the following error:

```
        ERROR: rstrcpy not enough space in dest, slen:66, maxLen:64
        ERROR: unknown hostname: [testing-gce-dde92079-4db6-4e3c-9257-737c5343523f.c.eco-emissary-�]
        ERROR: _rcConnect: setRhostInfo error, irodsHost is probably not set correctly status = -303000 USER_RODS_HOSTNAME_ERR
        ERROR: Saved password, but failed to connect to server testing-gce-dde92079-4db6-4e3c-9257-737c5343523f.c.eco-emissary-�
```

It seems that the constant NAME_LEN is used for copying the irodsHost from the environment variable, and the copy is therefore limited to NAME_LEN, failing with the rstrcpy error if the actual value of irodsHost is longer than that. The problem is in rcConnect.cpp: https://github.com/irods/irods/blob/c4dd07936f5324d52416e383df1eacf472ccb292/iRODS/lib/core/src/rcConnect.cpp#L219

RFC1035 specifies that fully qualified domain names (FQDN) can be up to 255 characters, while individual components of a DNS name are limited to 63 characters. Since irodsHost can (and usually does) contain FQDN, it should probably use LONG_NAME_LEN instead of NAME_LEN (both are defined in https://github.com/irods/irods/blob/d3d9ef0a5eea9e3cbc0f78f58ea659f842368762/iRODS/lib/core/include/rodsDef.h#L56-L58).

**Comment by Pete-C** [comment] 2016-01-13 12:50
Sounds interesting, any chance of an update on this project ?
 

    On Wednesday, 13 January 2016, 12:10, Joshua C. Randall <notifications@github.com> wrote:
 

 I am also having this issue (although now the limit seems to have been raised to 64?), in the form of occasionally failing travis CI tasks for a thrid party project in which we are testing against an iRODS system installed inside travis. When travis gives us a hostname longer than 64 characters, we get something like the following error:        ERROR: rstrcpy not enough space in dest, slen:66, maxLen:64
        ERROR: unknown hostname: [testing-gce-dde92079-4db6-4e3c-9257-737c5343523f.c.eco-emissary-��]
        ERROR: _rcConnect: setRhostInfo error, irodsHost is probably not set correctly status = -303000 USER_RODS_HOSTNAME_ERR
        ERROR: Saved password, but failed to connect to server testing-gce-dde92079-4db6-4e3c-9257-737c5343523f.c.eco-emissary-��
It seems that the constant NAME_LEN is used for copying the irodsHost from the environment variable, and the copy is therefore limited to NAME_LEN, failing with the rstrcpy error if the actual value of irodsHost is longer than that. The problem is in rcConnect.cpp: https://github.com/irods/irods/blob/c4dd07936f5324d52416e383df1eacf472ccb292/iRODS/lib/core/src/rcConnect.cpp#L219RFC1035 specifies that fully qualified domain names (FQDN) can be up to 255 characters, while individual components of a DNS name are limited to 63 characters. Since irodsHost can (and usually does) contain FQDN, it should probably use LONG_NAME_LEN instead of NAME_LEN (both are defined in https://github.com/irods/irods/blob/d3d9ef0a5eea9e3cbc0f78f58ea659f842368762/iRODS/lib/core/include/rodsDef.h#L56-L58). —

**Comment by jrandall** [comment] 2016-01-13 13:18
This is for `baton` development (https://github.com/wtsi-npg/baton), for which we are also working on new specific-query functionality (https://github.com/wtsi-hgi/baton/tree/feature/specificquery).

**Comment by kellerb** [comment] 2016-01-13 20:00
@jrandall do you know how you got a computer with longer than 64 character hostname (e.g. which OS)? I'm trying to test a fix for this issue, but don't have any computers that accept >64 character hostnames.

**Comment by Pete-C** [comment] 2016-01-14 09:46
Hmm, is there a reason why we now have 2 Sanger baton repositories rather than one with a branch arrangement ? 

    On Wednesday, 13 January 2016, 20:00, kellerb <notifications@github.com> wrote:
 

 @jrandall do you know how you got a computer with longer than 64 character hostname (e.g. which OS)? I'm trying to test a fix for this issue, but don't have any computers that accept >64 character hostnames.—

**Comment by keithj** [comment] 2016-01-14 10:10
@Pete-C It's a standard git workflow; @jrandall forked https://github.com/wtsi-npg/baton in order to add a new feature and the fork is public at https://github.com/wtsi-hgi/baton. This has two benefits 1) it means that we can use GitHub's (and Travic CI's) infrastructure to manage the merging of their new feature and 2) we don't need to provide write access for other groups into our repository.

**Comment by Pete-C** [comment] 2016-01-14 11:15
I see, I think that this is one for the internal irods-discussion board 

    On Thursday, 14 January 2016, 10:10, Keith James <notifications@github.com> wrote:
 

 @Pete-C It's a standard git workflow; @jrandall forked https://github.com/wtsi-npg/baton in order to add a new feature and the fork is public at https://github.com/wtsi-hgi/baton. This has two benefits 1) it means that we can use GitHub's (and Travic CI's) infrastructure to manage the merging of their new feature and 2) we don't need to provide write access for other groups into our repository.—

**Comment by keithj** [comment] 2016-01-14 14:13
@kellerb We are seeing this on Ubuntu precise. `rcConnect` is getting its hostname from `getRodsEnv`, not `gethostname` so is not limited to `HOST_NAME_MAX`. In our case I'm populating `irods_host` with the result of `hostname --fqdn` which is on Travis e.g. `testing-gce-84fc2369-bdb0-4cab-ab7c-dd0de07befbc.c.eco-emissary-99515.internal` (78 characters, if I've counted correctly). The docs for `irods_environment.json` say that `irods_host` should be the FQDN.

**Comment by kellerb** [comment] 2016-01-14 16:14
Do you know which OS is on your Travis machine? I'm looking for a way to have a computer with a >64 character hostname, so that I can install an iRODS server on it and test the fix.

**Comment by keithj** [comment] 2016-01-14 16:44
@kellerb It's Ubuntu precise. In the cases where it fails the hostname (as returned by `hostname`) is 48 characters, while the FQDN (as returned by `hostname --fqdn`) is 78 characters. See https://travis-ci.org/keithj/baton/jobs/102359207

**Comment by kellerb** [comment] 2016-01-14 16:51
Ah, I see. Thank you.

**Comment by trel** [comment] 2016-02-16 18:58
Need to:

- document the max of 64 characters
- fix the error message going to the log

**Comment by burnce** [comment] 2016-07-15 13:14
I seeing these errors as well. There appears to be no impact on functionality, but the error messages are quite distracting when going through the logs. Will this be fixed in 4.2?

**Comment by kellerb** [comment] 2016-07-15 15:26
Yes

**Comment by kellerb** [comment] 2016-08-04 19:34
There should now no longer be error messages for hostnames of length [33,64].

**Comment by kellerb** [comment] 2016-08-10 19:58
With regard to increasing the maximum allowed hostname length to the RFC1035 specification of 255:

The imposed limit of `NAME_LEN` (64, 63 with null character) characters is in a [packing instruction](https://github.com/irods/irods/blob/5c60095959ec44f6b06817f33cee67e65995eee6/lib/core/include/rodsPackInstruct.h#L80) (iRODS' custom serialization code). Packing instructions have hardcoded lengths, causing communication between two iRODS programs using different versions of packing instructions to fail. I'm not sure if this particular packing instruction is used during federation (which would prevent us from changing it, as we have claimed that all iRODS 4 releases will be able to federate with iRODS 3), but even if it isn't, changing this would break the use of e.g. iRODS 4.1 icommands with an iRODS 4.2 server.

The hardcoded lengths in the packing instructions are the reason for many of the length restrictions in iRODS that we would like to change but cannot without introducing version incompatibility.

**Comment by trel** [comment] 2020-09-11 13:15
part of #5073

**Closed** 2020-10-21 19:23 UTC
Labels: bug, consortium-member, documentation, needs-test
