### ISSUE TITLE
`itree` gives confusing errors for missing data objects and collections

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6627] opened 2022-10-07 09:13 UTC
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
We are testing 4.2.11 with iCommands 4.2.11. We observed `itree` command cannot correctly handle wrong inputs/arguments for options.

```
[user1@dev-u0137480 ~]$ itree -L 1 0
terminating with uncaught exception of type irods::experimental::filesystem::filesystem_error: could not open collection for reading: Unknown error -310000
Aborted (core dumped)
```

Logs:
```
[2022-10-07T09:06:04.434Z][icts-t-cloud-hev-3] rsyslogd stdout | 2022-10-07T11:06:04.433858+02:00 demo rodsServer[29524]: icts_demo - remote addresses: 2a02:2c40:0:221::3306:10, 2a02:2c40:0:451:67:242:ac11:16 ERROR: [-]#011/work/server/core/src/rodsAgent.cpp:566:int runIrodsAgentFactory(sockaddr_un) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']#012#011[-]#011/work/lib/core/src/sockComm.cpp:160:irods::error sockAgentStop(irods::network_object_ptr) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']#012#011#011[-]#011/work/plugins/network/ssl/libssl.cpp:952:irods::error ssl_agent_stop(irods::plugin_context &) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error completing shutdown of SSL connection]#012
[2022-10-07T09:06:04.434Z][icts-t-cloud-hev-3] rsyslogd stdout | 2022-10-07T11:06:04.433267+02:00 demo rodsServer[29524]: icts_demo - remote addresses: 127.0.0.1, 2a02:2c40:0:221::3306:10, 2a02:2c40:0:451:67:242:ac11:16 ERROR: [-]#011/work/server/core/src/rsApiHandler.cpp:542:int readAndProcClientMsg(rsComm_t *, int) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']#012#011[-]#011/work/lib/core/src/sockComm.cpp:198:irods::error readMsgHeader(irods::network_object_ptr, msgHeader_t *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']#012#011#011[-]#011/work/plugins/network/ssl/libssl.cpp:572:irods::error ssl_read_msg_header(irods::plugin_context &, void *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]#012
[2022-10-07T09:06:04.461Z][icts-t-cloud-hev-3] rsyslogd stdout | 2022-10-07T11:06:04.461080+02:00 demo rodsServer[102]: (null) -  ERROR: Agent process [29524] exited with status [64]
```

We see the same for usages below:

```
[user1@dev-u0137480 ~]$ itree --indent 3 0
terminating with uncaught exception of type irods::experimental::filesystem::filesystem_error: could not open collection for reading: Unknown error -310000
Aborted (core dumped)
```

```
[user1@dev-u0137480 ~]$ itree -I alice.txt test.txt
terminating with uncaught exception of type irods::experimental::filesystem::filesystem_error: could not open collection for reading: Unknown error -814000
Aborted (core dumped)

```
Also, we can say that having a feature to provide more than one argument or patter (regex) to `itree -I` `itree --ignore` could be much useful. (Or a possibility to use in combination with --pattern)

Thanks.

**Comment by d-w-moore** [comment] 2022-12-19 20:35
I'm going to assume also, since the stated purpose of itree is to list a collection's contents, that
**itree** _logical_path_to_known_data_object_
should remain off the table as a valid usage?

**Comment by d-w-moore** [comment] 2022-12-19 20:55
If we're going to make pattern accept (P) and ignore (I) filters multi-argument
   - should it be a separate issue? I think maybe.
   - should the filters be additive in inclusitivity (OR) or exclusivity (AND)

**Comment by korydraughn** [comment] 2022-12-19 21:36
> I'm going to assume also, since the stated purpose of itree is to list a collection's contents, that
itree logical_path_to_known_data_object
should remain off the table as a valid usage?

Right. What would `itree <data_object>` mean/do?

> should it be a separate issue? I think maybe.

Yes.

> should the filters be additive in inclusitivity (OR) or exclusivity (AND)

How do other Unix commands work in regard to accepting multiple regular expressions?

**Comment by trel** [comment] 2022-12-19 21:38
As we're largely modeling `tree` itself... 

```
$ tree test1/
test1/
└── thefile

0 directories, 1 file
```

And so...
```
$ tree test1/thefile 
test1/thefile [error opening dir]

0 directories, 0 files
```

Shows an 'error' opening the directory, but still has a returncode of `0`.

**Comment by d-w-moore** [comment] 2022-12-19 23:22
oh - yes, thanks.  that does help. I did not know of the existence of `tree`

**Comment by d-w-moore** [comment] 2022-12-19 23:27
@korydraughn Still trying to figure out why `tree` doesn't respect the same form of -I as itree
on a subdir / subcoll named c, and containing {x1,x2,y1,y2}:

```
daniel@prec3431:~/github/irods/x$ tree -I 'x.' c
c
├── x1
├── x2
├── y1
└── y2

0 directories, 4 files
daniel@prec3431:~/github/irods/x$ itree -I 'x.' c
c
  y1
  y2
Found 0 collections and 2 data objects

```

**Comment by korydraughn** [comment] 2022-12-19 23:34
It could be using a different regular expression engine than `itree`.

What happens if you use `tree -I 'x*' c`?

**Comment by trel** [comment] 2022-12-20 00:15
Indeed - does seem something is not consistent...

```
$ tree -I 'x*' c
c
├── y1
└── y2

0 directories, 2 files
```

```
$ tree -I 'x.' c
c
├── x1
├── x2
├── y1
└── y2

0 directories, 4 files
```

and `itree`...

```
$ itree -I 'x*' c
c
  x1
  x2
  y1
  y2
Found 0 collections and 4 data objects
```

```
$ itree -I 'x.' c
c
  y1
  y2
Found 0 collections and 2 data objects
```

Definitely can tighten up this test a bit more for some edge cases.
https://github.com/irods/irods/blob/527f3a174f31f225f7b01281bc2b1e6079446b6e/scripts/irods/test/test_itree.py#L49-L58

**Comment by trel** [comment] 2022-12-20 00:29
So we're using ECMAScript by default...

https://github.com/irods/irods_client_icommands/blob/41acd583290c4e3e405a58831b6a57e6d2e2c240/src/itree.cpp#L39-L40
```
static std::regex matcher;
static std::optional<std::regex> exclude_matcher;
```

**Comment by korydraughn** [comment] 2022-12-20 00:33
Those are updated here: https://github.com/irods/irods_client_icommands/blob/41acd583290c4e3e405a58831b6a57e6d2e2c240/src/itree.cpp#L84-L89
```cpp
        matcher = std::regex(vm["pattern"].as<std::string>(),
                             std::regex::basic | std::regex::optimize );
        if (vm.count("ignore")) {
            exclude_matcher = std::regex(vm["ignore"].as<std::string>(),
                                         std::regex::basic | std::regex::optimize);
        }
```

**Comment by korydraughn** [comment] 2022-12-20 00:47
From https://man7.org/linux/man-pages/man7/glob.7.html:
```
NOTES         top
   Regular expressions
       Note that wildcard patterns are not regular expressions, although
       they are a bit similar.  First of all, they match filenames,
       rather than text, and secondly, the conventions are not the same:
       for example, in a regular expression '*' means zero or more
       copies of the preceding thing.

       Now that regular expressions have bracket expressions where the
       negation is indicated by a '^', POSIX has declared the effect of
       a wildcard pattern "[^...]" to be undefined.
```
Basically, file globbing patterns are not regular expressions, hence the results we've seen so far.

**Comment by d-w-moore** [comment] 2022-12-20 05:20
That checks out. Looking at what multiple --ignore/-I or --pattern/-P invocations do, I see a fairly simplistic approach being taken.  Not "AND," nor "OR" behavior, just the last-used pattern overrides:
```
$ mkdir -p c; touch c/{x,y,z}{1,2}; ls c
$ tree -P '*1' -P 'x*' c
c
├── x1
└── x2
$ tree -I '*1' -I 'x*' c
c
├── y1
├── y2
├── z1
└── z2
```
However -I and -P are like cascaded (AND'ed) filters, and commutative.
```
$ tree -P '*1' -I 'x*' c
c
├── y1
└── z1

0 directories, 2 files
daniel@prec3431:~/tmp$ tree -I 'x*' -P '*1' c
c
├── y1
└── z1

```

```

**Comment by trel** [comment] 2022-12-20 05:24
nice.    so, we should be able to make `itree` pattern/ignore behave.

please tackle that in a new issue and link back here - and leave this one to fixing the core dump.

**Comment by d-w-moore** [comment] 2022-12-20 18:04
@mstfdkmn Could you elaborate exactly how the argument of 0 is wrong?  Is it a collection that does not exist,  or is too deep or has wrong permissions? I am not able to reproduce the uncaught-exception + abort behavior that you are seeing.

**Comment by d-w-moore** [comment] 2022-12-21 13:45
Ok, after reinstalling 4.2.11 on Ub18 from release, I do get the uncaught exception, and abort message.

**Comment by d-w-moore** [comment] 2022-12-21 17:32
itree in 4-2-stable catches `std::exception` , but in 4.2.11, it is never caught, leading to the abort.  So although the core-dump side of  things is already fixed for 4.2.12, we still have some oddness. The question is what we consider correct handling.
For instance, on current 4-2-stable, `itree 0` when 0 is a non-existing collection, does this:
```
$ itree 0
Error:could not open collection for reading: Unknown error -310000
  -h [ --help ]              Display help
  --dir arg (=.)             The initial collection to render (defaults to the 
                             current working collection)
  -c [ --collections-only ]  Only list collections
  -f [ --fullpath ]          print the full path of each item listed
  -L [ --depth ] arg (=1000) Limit the depth of the listing.
  -P [ --pattern ] arg (=.*) Filter files by a regexp
  -s [ --size ]              Display the size of each data object
  -I [ --ignore ] arg        Ignore matching data objects.
  -F [ --classify ]          Display a / at the end of listings of collections
  --indent arg (=2)          The number of spaces each level of nested 
                             collection adds.
  -J [ --json ]              Produce json instead of a human readable output
  -C [ --color ]             Print in color (requires ansi terminal)

```
So then:
   - do we want an error followed by usage, or just the error.  I think: _just the error_. but boost::program_options evidently different ideas.  (my guess is anytime main returns status !=0 , a usage is automatically printed.)
   - should we be printing out USER_FILE_DOES_NOT_EXIST?  And how would that work? I've already tried catching irods::exception and printing out client_display_what, thinking that might improve things, but no cigar.  Maybe clients cannot catch irods::exception , or ... maybe an `irods::exception-`derived error is not what filesystem library is throwing?

**Comment by korydraughn** [comment] 2022-12-21 18:03
> do we want an error followed by usage, or just the error. I think: just the error.

Just the error message.

We shouldn't be using the help text provided by Boost.ProgramOptions because it doesn't match the format of other icommands. The help text should be similar to the help text of `itouch`. Please capture that in an issue.

> should we be printing out USER_FILE_DOES_NOT_EXIST? And how would that work?

To help the user and for consistency purposes, yes. There are functions you can invoke to get the name of an error code. Look in other icommands for example. I think it is something like `rodsErrorName()`?

> Maybe clients cannot catch irods::exception , or ... maybe an irods::exception-derived error is not what filesystem library is throwing?

Clients can catch `irods::exception`. Once caught, we can print whatever we want. We don't have to use the `.what()` / `.client_display_what()` member functions of the exception.

The filesystem library does not throw `irods::exception`-derived types. It throws `irods::experimental::filesystem::filesystem_error` and they must be caught directly. There may be an argument for changing that, but the goal of the filesystem lib was to mirror the C++ filesystem lib as much as possible.

**Comment by d-w-moore** [comment] 2022-12-21 19:19
Oh, good. 

Ok, will make the new issue then, regarding the style of help text.

I also finally spotted the `cout << desc` , which is responsible for printing the help text.

**Comment by d-w-moore** [comment] 2022-12-22 13:46
> The filesystem library does not throw `irods::exception`-derived types. It throws `irods::experimental::filesystem::filesystem_error` and they must be caught directly.  

So far, attempts to print out an error string a la rodsErrorName haven't been satisfactory when catching `fs::filesystem` directly:
  - e.code( ) returns std::system_error instead  of int -  not usable with rodsErrorName
  - e.what( ) is a string containing the integer errorcode, which could be parsed out and used as an input for rodsErrorName, but that feels too hackish

**Comment by d-w-moore** [comment] 2022-12-22 14:44
That does it,  although _internally_ the text from e.what( ) seems to like declaring a known iRODS error value as "Unknown".
```\root@182a5489b4c0:/b-icommands# ./itree nonexisting
iRODS filesystem error: could not open collection for reading: Unknown error -310000 - USER_FILE_DOES_NOT_EXIST 
```
That is with this code in place, ahead of the std::exception catch clause:
```
+    catch(const fs::filesystem_error & e) {
+        int status = e.code().value();
+        char* mySubName {};
+        const char *myName = rodsErrorName(status, &mySubName);
+        std::cerr << fmt::format("iRODS filesystem error: [{}] - {} {}\n", e.what(), myName, mySubName);
+        std::free(mySubName);
+        return 1;
+    }

```

**Comment by korydraughn** [comment] 2022-12-22 14:48
Let's create an issue for that.

The name for those error codes is known so we should never see `Unknown error`. It should be simple enough to fix.

**Comment by d-w-moore** [comment] 2022-12-22 14:57
Yes ... may be in how `fs::detail::make_error_code` translates the integer. 
https://github.com/irods/irods/blob/02b03c67ff428959a758a17fdbcbd25001b4e39d/lib/filesystem/src/collection_iterator.cpp#L47

**Comment by korydraughn** [comment] 2023-03-14 00:37
@d-w-moore Has the work for this issue been completed for 4-2-stable?

**Comment by d-w-moore** [comment] 2023-03-14 17:12
I couldn't find any dev branches of mine that are relevant to the issue number, but with your closing of https://github.com/irods/irods/issues/6794 I have just now tried reintroducing this [catch clause from the discussion above](https://github.com/irods/irods/issues/6627#issuecomment-1362923136).
Here's the result -
```
$ ./itree nonexisting
iRODS filesystem error: [could not open collection for reading: USER_FILE_DOES_NOT_EXIST] - USER_FILE_DOES_NOT_EXIST 
```
Whittled down, it's probably exactly the right thing for addressing this issue.

**Comment by d-w-moore** [comment] 2023-03-14 17:15
@korydraughn Probably don't need the rodsErrorName call( ) in the client anymore, since all of that info seems to be provided now in the `e.what( )`

**Comment by korydraughn** [comment] 2023-03-14 17:24
Excellent.

Do you think that error code is appropriate for what you tried to do?

**Comment by d-w-moore** [comment] 2023-03-14 17:59
Things still seem off.  Given the path to a data object which does exist, we get the `what` message (in []):
```
iRODS filesystem error: [could not open collection for reading: CAT_UNKNOWN_COLLECTION]
```
whereas if the path argument is a collection that doesn't exist, we have (as before)
```
[could not open collection for reading: USER_FILE_DOES_NOT_EXIST]
```
I'll do a little bit more investigating as to where & why the errors are being thrown, but this does seem odd and not as helpful as it could be.

**Comment by trel** [comment] 2023-03-28 16:19
Any exceptions now caught due to https://github.com/irods/irods_client_icommands/commit/c41f6989d0ee414f28e344876fa6cb367de13eee  as part of https://github.com/irods/irods/issues/6075 for 4.2.12.

**Comment by alanking** [comment] 2023-04-06 16:56
@d-w-moore - Please close if complete. Thanks

**Closed** 2023-04-06 17:03 UTC
Labels: bug, consortium-member
