### ISSUE TITLE
irepl doesn't correctly set RESC_NAME

### ISSUE THREAD

**Issue by bh9** [irods/irods#4158] opened 2018-10-23 11:03 UTC
### iRODS Version, OS and Version
4.1.10

### What did you try to do?
irepl -R root $myfile

### Expected behavior
A new replica is produced in root, with correct DATA_RESC_HIER and RESC_NAME

### Observed behavior (including steps to reproduce, if applicable)
```
RESC_NAME = demoResc
DATA_RESC_HIER = root;replicate;seq-red;red4;irods-seq-i24-bc
```
RESC_NAME is demoResc, but DATA_RESC_HIER is root;etc.
The file is stored on the resource identified by DATA_RESC_HIER, not on demoResc.

**Comment by bh9** [comment] 2018-10-23 12:58
Fixed by #3915 and #3914 in 4.2 and master

**Comment by bh9** [comment] 2018-10-23 14:10
Since this is already fixed in 4.2+, and I don't want it to delay 4.1.12 or encourage a 4.1.13, I'll just close this

**Comment by alanking** [comment] 2018-10-25 12:08
Okay. In that case, we can close this as a duplicate of #4010 and mark it for the 4.2 milestone. Thanks!

**Closed by alanking** 2018-10-25 12:08 UTC
Labels: consortium-member, duplicate

**Comment by bh9** [comment] 2018-10-25 12:15
There is still the issue that the combination of rule and irepl didn't put in the correct resc_name

**Comment by bh9** [comment] 2018-10-25 12:28
It's worth noting that we don't set acSetRescSchemeForRepl, only acSetRescSchemeForCreate. As a result, I wouldn't expect irepl to follow the force to root rule.
