### ISSUE TITLE
new api plugin - finalize data transfer

### ISSUE THREAD

**Issue by trel** [irods/irods#4331] opened 2019-04-05 16:08 UTC
- [x] master
- [x] 4-2-stable
---------

## Feature

A new server api plugin to check integrity of completed transfer, possibly checksum, update catalog, report success.

takes json manifest of
 - data object name
 - data transfer map of parts on disk
 - flags (checksum, force, etc.)
 - atomic metadata
 - atomic acls
 - storage resource
 - physical path

**Comment by kript** [comment] 2019-04-08 09:15
Naively, this looks like it would be helpful for #4314 and #4170?

**Comment by trel** [comment] 2019-04-08 12:01
As currently being designed, yes - a new multipart transfer mechanism (https://github.com/irods/irods/issues/4336) would fix a lot of the issues with parallel transfer.

**Comment by michael-conway** [comment] 2019-04-08 12:31
Is this intended to be a follow up call after oper complete on a parallel
transfer? Should it be baked in to client apis? As an  option? I was not
sure the context for this plugin.

**Comment by trel** [comment] 2019-04-08 16:26
This is a replacement, not a thing to call at the end of existing parallel transfer.

**Comment by trel** [comment] 2020-11-25 14:53
@alanking is this complete?   seems it should at least be pulled into the current milestone?

**Comment by alanking** [comment] 2020-11-30 14:33
I would say this is not quite complete, but it is definitely part of my current efforts. I'll pull it in.

**Comment by alanking** [comment] 2021-04-09 20:22
I think this will be complete after this upcoming write-lock implementation PR.

I do have some concerns around the API's usage from the client side and as it relates to the iRODS permissions model. These are probably pretty easily resolved, but let's only close it after it has been confirmed that these check out.

**Comment by alanking** [comment] 2021-05-06 13:41
#5594 (and imminent 4-2-stable equivalent) will close this issue. It addresses the permissions concern.

**Comment by trel** [comment] 2021-05-17 03:09
@alanking i think this is done?    anything else?

**Comment by alanking** [comment] 2021-05-17 13:24
Yes, the remaining concerns that I had for this have been addressed.

**Closed** 2021-05-17 13:30 UTC
Labels: consortium-member, enhancement
