### ISSUE TITLE
A groupadmin cannot remove users from groups

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#6885] opened 2023-01-30 19:27 UTC
### iRODS Version, OS and Version
4.2.11, 4.3.0 - Ubuntu 18

### What did you try to do?
Remove a user from a group as an `groupadmin`

### Expected behavior
Since as a `groupadmin` we can create users and groups, and add users to groups, we should also be able to remove them from groups. This is advertised in the `igroupadmin` help text as the `rfg` subcommand.

### Observed behavior (including steps to reproduce, if applicable)
As a groupadmin-type user:
```
$ igroupadmin mkgroup lab3
$ igroupadmin mkuser user1
$ igroupadmin atg lab3 user1
$ igroupadmin rfg lab3 user1
remote addresses: 127.0.0.1 ERROR: rcUserAdmin failed with error -830000 CAT_INSUFFICIENT_PRIVILEGE_LEVEL 
```
So `user1` currently must be removed from the `lab3` group by a `rodsadmin`, which can be done with either `iadmin rfg ...` or `igroupadmin rfg ...`

**Comment by trel** [comment] 2023-01-30 19:32
definitely get a test written first please.    this is quite surprising.

**Comment by kript** [comment] 2023-02-01 09:53
This will affect us when we upgrade to 4.2.11, unless 4.2.12 comes out Real Soon Now ™️ with a fix, so we have a use case where a team have groupadmin for a zone but we prefer not to provide them a rodsadmin account to reduce the security threat landscape and accidents. The alternative methods I can see to do group membership via groupadmin accounts would be;

1. an addition to baton to use the C API via an account with groupadmin rights
2. a script in the python iRODS client via an account with groupadmin rights

So it would be helpful to know if this bug is within the `igroupadmin` program, or the wider API, and if there are other ways we can achieve group membership management as a non-rodsadmin please?

**Comment by kript** [comment] 2023-02-01 11:36
Perhaps anecdotal, and please tell me where I have made mistakes in my code, but it seems this also affects python iRODSclient on 4.2.11 as well;

```
$ iadmin lu jc18 | grep user_type_name
user_type_name: groupadmin
```
running as a groupadmin user;

```
$ ienv | grep -e zone -e user
irods_user_name - jc18
irods_environment_file - /nfs/users/nfs_j/jc18/.irods/irods_environment.json_Sanger1-dev
irods_zone_name - Sanger1-dev
```

with the latest released version of the python library;

```
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ pip freeze
defusedxml==0.7.1
importlib-metadata==4.8.3
pkg-resources==0.0.0
prettytable==2.5.0
python-irodsclient==1.1.6
six==1.16.0
typing-extensions==4.1.1
wcwidth==0.2.6
zipp==3.6.0
```

Using the the following code;

```
import os
import ssl
from irods.session import iRODSSession
from irods.models import User, UserGroup
from irods.user import iRODSUser, iRODSUserGroup

try:
    env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
     #env_file = os.path.expanduser('~/.irods/irods_environment.json')
     env_file = os.path.expanduser('/nfs/users/nfs_j/jc18/.irods/irods_environment.json_Sanger1-dev')

ssl_settings = {} # Or, optionally: {'ssl_context': <user_customized_SSLContext>}
with iRODSSession(irods_env_file=env_file, **ssl_settings) as session:
    #show group admin accounts
    groups = session.query(User).filter( User.type == 'groupadmin' )
    print("group admin accounts in this zone")
    print([x[User.name] for x in groups])

    # show all groups (takes a few mins very verbose eve on sanger1-dev zone!)
    #print("listing all groups")
    #grp_usr_mapping = [ (iRODSUserGroup ( session.user_groups, result), iRODSUser (session.users, result)) \
    #    for result in session.query(UserGroup,User) ]
    #print(grp_usr_mapping)

    #create a test group
    group_name = "test_6885"
    user_name = "jc18"
    print(f"creating group {group_name}")
    group = session.user_groups.create(group_name)
    #add user to test group
    print(f"adding {user_name} user to {group_name} group")
    group.addmember(user.name)
    #remove user from group
    print(f"removing {user_name} from group {group_name}")
    group.removemember(user.name)
```
I get the following error;

```
$ python groupadmin.py
group admin accounts in this zone
['kdj', 'dj3', 'jc18']
creating group test_6885
Traceback (most recent call last):
  File "groupadmin.py", line 36, in <module>
    group = session.user_groups.create(group_name)
  File "/nfs/users/nfs_j/jc18/code/venvs/python-irodsclient_1.1.6/lib/python3.6/site-packages/irods/manager/user_manager.py", line 213, in create
    response = conn.recv()
  File "/nfs/users/nfs_j/jc18/code/venvs/python-irodsclient_1.1.6/lib/python3.6/site-packages/irods/connection.py", line 133, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.SYS_NO_API_PRIV: None
```

Which (unless in the highly likely situation where I have done something wrong)  implies to me its a wider scope than just deletion, but wider group management.

That being said, I can't reproduce the actual error reported on our 4.2.11 zone using 4.2.7 icommands;

```
$ igroupadmin -h
Usage: igroupadmin [-hvV] [command]

This is for users of type 'groupadmin' which are allowed to perform
certain administrative functions.  It can also be used by regular
users to list groups ('lg') and by the admin for all operations.

A blank execute line invokes the interactive mode, where it
prompts and executes commands until 'quit' or 'q' is entered.
Single or double quotes can be used to enter items with blanks.
Commands are:
 lg [name] (list group info (user member list))
 mkuser Name Password (make a user and set the initial password)
 atg groupName userName[#Zone] (add to group - add a user to a group)
 rfg groupName userName[#Zone] (remove from group - remove a user from a group)
 mkgroup groupName[#Zone] (make a new group)
 help (or h) [command] (this help, or more details on a command)

iRODS Version 4.2.7                igroupadmin
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin mkgroup test_6885
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin lg test_6885
Members of group test_6885:
No rows found
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin atg test_6885 jc18
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin lg test_6885
Members of group test_6885:
jc18#Sanger1-dev
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin rfg test_6885 jc18
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin lg test_6885
Members of group test_6885:
No rows found
```
on 4.2.11 I get;

```
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ module add ISG/experimental/irods
/4.2.11
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin -h
Usage: igroupadmin [-hvV] [command]

This is for users of type 'groupadmin' which are allowed to perform
certain administrative functions.  It can also be used by regular
users to list groups ('lg') and by the admin for all operations.

A blank execute line invokes the interactive mode, where it
prompts and executes commands until 'quit' or 'q' is entered.
Single or double quotes can be used to enter items with blanks.
Commands are:
 lg [name] (list group info (user member list))
 mkuser Name Password (make a user and set the initial password)
 atg groupName userName[#Zone] (add to group - add a user to a group)
 rfg groupName userName[#Zone] (remove from group - remove a user from a group)
 mkgroup groupName[#Zone] (make a new group)
 help (or h) [command] (this help, or more details on a command)

iRODS Version 4.2.11                igroupadmin
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin mkgroup test_6885
Level 0 message: Error -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME
Level 1 message: DEBUG:

remote addresses: 172.30.157.13 ERROR: rcUserAdmin failed with error -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME
Level 0: Error -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME
Level 1: DEBUG:
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin lg test_6885
Members of group test_6885:
No rows found
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin atg test_6885 jc18
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin lg test_6885
Members of group test_6885:
jc18#Sanger1-dev
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin rfg test_6885 jc18
(python-irodsclient_1.1.6) jc18@farm5-head1:~/code/ISG/quickies/jc18/irods_groupadmin$ igroupadmin lg test_6885
Members of group test_6885:
No rows found
```

**Comment by trel** [comment] 2023-02-01 12:18
A counter example...  surprising.   Thanks.

**Comment by d-w-moore** [comment] 2023-02-01 12:33
Thanks @kript ! - Yes, I'd  also tried in PRC and seen the same behavior in PRC as well. I'll poke around with 4.2.7 to see what is different there....

**Comment by alanking** [comment] 2023-02-01 14:21
I tried this as a `groupadmin` named `labadmin`:
```bash
$ igroupadmin mkgroup lab3
$ igroupadmin mkuser user1
$ igroupadmin atg lab3 user1
$ igroupadmin lg lab3
Members of group lab3:
user1#tempZone
$ igroupadmin rfg lab3 user1
remote addresses: 127.0.0.1 ERROR: rcUserAdmin failed with error -830000 CAT_INSUFFICIENT_PRIVILEGE_LEVEL 
```
This reproduced the issue. I then found that I wasn't able to add any other users to the group, even the managing `groupadmin` named `labadmin`:
```bash
$ igroupadmin atg lab3 labadmin
remote addresses: 127.0.0.1 ERROR: rcUserAdmin failed with error -830000 CAT_INSUFFICIENT_PRIVILEGE_LEVEL 
```
So, I tried again with a new group, first adding `labadmin` to it:
```bash
$ igroupadmin mkgroup lab4
$ igroupadmin atg lab4 labadmin
$ igroupadmin lg lab4
Members of group lab4:
labadmin#tempZone
```
I was then able to add `user1` *and* remove `user1`:
```bash
$ igroupadmin atg lab4 user1
$ igroupadmin lg lab4
Members of group lab4:
labadmin#tempZone
user1#tempZone
$ igroupadmin rfg lab4 user1
$ igroupadmin lg lab4
Members of group lab4:
labadmin#tempZone
```

So, there is a workaround for this: `groupadmin`s must be the first user added to groups that they manage.

**Comment by alanking** [comment] 2023-02-01 14:26
This is stated in the help text for `igroupadmin`, so this is actually behaving as described:
```
Make a new group.  You will need to add yourself to the new group to then
be able to add and remove others (when the group is empty groupadmins are
allowed to add themselves.)
```
https://docs.irods.org/master/icommands/groupadmin/#mkgroup

See also: https://github.com/irods/irods/issues/4823

If we wish to change this behavior, then that's a different story. :)

**Comment by trel** [comment] 2023-02-01 15:07
Ah, I thought I remembered something like that.

So, the original issue is 'resolved/understood/notbroken' and Dan's not being able to reproduce is also explained/correct.

We did it?

Does the help text need more clarification?  More bumpers?

**Comment by trel** [comment] 2023-02-01 15:09
Why does @kript not have that in his help text?   Ohh, he didn't see the help text that is for `mkgroup` specifically...

**Comment by d-w-moore** [comment] 2023-02-01 15:28
It's not in my help text either, whether in igroupadmin -h or man igroupadmin (4.2.11)

**Comment by trel** [comment] 2023-02-01 15:33
4.2.11:
```
$ igroupadmin h mkgroup
 mkgroup groupName[#Zone] (make a new group)
Make a new group.  You will need to add yourself to the new group to then
be able to add and remove others (when the group is empty groupadmins are
allowed to add themselves.)
```

**Comment by d-w-moore** [comment] 2023-02-01 16:44
OK, confirmed and this is how it behaves: a groupadmin creates a group (eg. lab) and adds themself first to the group, allowing the adding and removing of other users as desired.

But (and this is a "small but"):
If your user is a groupadmin, you can administrate any group to which you belong (I just confirmed this by manual experiment. This is admittedly coarse-granular approach and doesn't allow for the use case where you want to be the only admin for a group that needs to contain other groupadmins.  (E.g. you're administering a lab that contains not just  rodsuser/students but also groupadmin/graduate-students who are administering other labs)

**Comment by trel** [comment] 2023-02-01 18:08
Ah, great.   So this is a documentation issue now, only.   Making this story easier to understand in the help text and/or main irods_docs.

**Comment by d-w-moore** [comment] 2023-02-10 02:35
Since the central issue in this bug report is based on a lack of understanding of how groups behave under groupadmin management, we should probably either
   - close this issue now, or
   - keep it open but just until we've updated the documentation to include a description of how this works, ie "a groupadmin must add himself first to a group they manage, so that they are able to remove as well as add other users."

**Comment by trel** [comment] 2023-02-10 02:38
yes, b) please.   update the docs, link here, and then close.

**Comment by mstfdkmn** [comment] 2023-02-10 11:27
> This is stated in the help text for `igroupadmin mkgroup`, so this is actually behaving as described:
> 
> ```
> Make a new group.  You will need to add yourself to the new group to then
> be able to add and remove others (when the group is empty groupadmins are
> allowed to add themselves.)
> ```
> 
> https://docs.irods.org/4.3.0/icommands/groupadmin/#mkgroup
> 
> See also: #4823
> 
> If we wish to change this behavior, then that's a different story. :)

What we experience is that groupadmins can add the "first member" to the new group without any need to add themselves to the new group. No matter what is the user profile or who is, the first user always can be added by groupadmins.

**Comment by trel** [comment] 2023-02-10 12:41
That is correct.

Are you suggesting the first member of an empty group should be *required* to be the `groupadmin` themself?

**Comment by mstfdkmn** [comment] 2023-02-10 13:12
Yes, because after a groupadmin first adds a regular user, then he cannot manage that group anymore - a rodsadmin is needed to add that groupadmin. Also as part of some of our workflows, a group should always have a groupadmin and that group admin should add other users.

**Comment by d-w-moore** [comment] 2023-02-10 14:06
Yes, and the documentation to that effect will be more prominent, as opposed to lurking beneath an obscure command-line invocation such as `igroupadmin h mkgroup`...

**Comment by korydraughn** [comment] 2023-02-10 18:36
Do we have tests that capture the requirement that a groupadmin must be the first member of a group?

That is, a test that demonstrates a groupadmin CANNOT add themselves to a non-empty group they aren't a member of.

**Comment by d-w-moore** [comment] 2023-02-10 20:12
Right ... I think if we're enforcing that as the philosophy, there should be a test to back it up. It makes sense because as a groupadmin, you don't want another groupadmin hijacking your group.

**Comment by trel** [comment] 2023-02-10 20:46
Pretty sure we need a test for that.

**Comment by korydraughn** [comment] 2023-02-18 19:24
@d-w-moore's recent PR, https://github.com/irods/irods/pull/6915, covers the test case mentioned at https://github.com/irods/irods/issues/6885#issuecomment-1426192279.

We need to update the help text for `igroupadmin mkgroup` to include a statement saying the groupadmin user must be the first member of the new group in order for them to manage it. It needs to be clear to the reader that once a group is non-empty, groupadmins aren't allowed to add themselves to the group without the help of a rodsadmin.

Do we have a test that shows that a groupadmin is not allowed to remove members from a group they aren't a member of?

**Comment by d-w-moore** [comment] 2023-02-19 07:10
> Do we have a test that shows that a groupadmin is not allowed to remove users from a group they aren't a member of?

I don't think so. This could easily be added, however.

**Comment by korydraughn** [comment] 2023-02-20 13:44
Please add a test that captures that.

**Comment by alanking** [comment] 2023-02-24 23:11
Hmm... this is very closely related to the things happening in changes related to #6888 (see https://github.com/irods/irods/pull/6924 and related). @d-w-moore - Should we link against this issue in addition to/instead of #6888?

**Comment by d-w-moore** [comment] 2023-02-25 01:33
Both are tenuous links, so maybe link to both?   This issue and #6888 were both created due to lack of readily available docs on the groupadmin M.O.  and philosophy, so it's a toss-up, I think.

**Comment by alanking** [comment] 2023-02-27 13:51
Eh, I say just let it ride. We can mark this as duplicate since the other issue got all the love vis a vis issue linkage. @korydraughn / @trel may disagree, so I defer :)

**Comment by trel** [comment] 2023-02-27 13:56
as long as we cover the work, and help the future forensics teams figure out what happened, doesn't matter to me.

**Comment by alanking** [comment] 2023-02-28 16:35
Closing with #6888

**Closed by alanking** 2023-02-28 16:35 UTC
Labels: duplicate, documentation, needs-test
