### ISSUE TITLE
Replication Resource and Checksums doing write() action on disks

### ISSUE THREAD

**Issue by Msaum87** [irods/irods#4110] opened 2018-09-18 10:11 UTC
## Bug Report
ichksum on objects in a Replication Resource are generating write() file system calls in the size of the file(s) checksummed.

### iRODS Version, OS and Version
CentOS 7.5
iRODS 4.1.10 and iRODS 4.1.11 confirmed
iRODS 4.2.4 does NOT reproduce error

### What did you try to do?
We saw snapshots of the file system were larger than expected. Troubleshooting some rules, we found that the checksums were writing to the file system. This only affected the locations under a Replication Resource object. Not manually replicated items.

### Expected behavior
Would not expect a checksum to do a write action on a file system.

### Observed behavior (including steps to reproduce, if applicable)
Disk write() is occurring with the checksum, increasing snapshot size by size of cheksum'd data.

Test Suite:
Centos7.5
iRODS 4.1.11
All actions done on a consumer server, nothing on a provider.

**NOTE:** I use dstat to monitor the actions.

> bash-4.2$ ilsresc
> 1192_168_1_18Resource
> demoResc
> REPL:replication
> ├── rep1
> └── rep2

I made a decent 1GB text file. On one terminal, I am watching a dstat output for system writes:
`dstat -td`

I see the expected write() of the file being ingested into iRODS.

> bash-4.2$ iput -R REPL testFile
> 
> bash-4.2$ ils -L
> /tempZone/home/rods:
>   rods              0 REPL;rep2   1024000000 2018-09-18.11:41 & testFile
>         generic    /nfs/rep2/home/rods/testFile
>   rods              1 REPL;rep1   1024000000 2018-09-18.11:41 & testFile
>         generic    /nfs/rep1/home/rods/testFile

At this point, watching the dstat output will show several MB of write() actions when the checksum is run.
> bash-4.2$ ichksum testFile
>     testFile                          sha2:v8IQFLAR5MxhgsQoOeB2S16jsvkySU3rjBZyMKr6u0w=

>       time     | read  writ
> 18-09 11:41:58|   0     0 
> 18-09 11:41:59|   0   495M
> 18-09 11:42:00|   0   226M
> 18-09 11:42:01|   0     0 

However, now that the iCAT has a checksum value, the writes do not happen. None of the following options generate a write() to filesystem.

`
ichksum -K testFile
ichksum -a testFile
ichksum -Ka testFile
ichksum -K -n 0 testFile
`

This led to a small discovery: using the -n flag does not generate the write() action ever.

On a fresh iput of the file, with no checksum in the iCAT:

> bash-4.2$ ils -L
> /tempZone/home/rods:
>   rods              0 REPL;rep2   1024000000 2018-09-18.11:46 & testFile
>         generic    /nfs/rep2/home/rods/testFile
>   rods              1 REPL;rep1   1024000000 2018-09-18.11:46 & testFile
>         generic    /nfs/rep1/home/rods/testFile
> 
> bash-4.2$ ichksum -n 0 testFile
>     testFile                          sha2:v8IQFLAR5MxhgsQoOeB2S16jsvkySU3rjBZyMKr6u0w=
> Total checksum performed = 1, Failed checksum = 0

and yet my dstat output never shows the large write() action happening. So using a -n flag bypasses the bug.

**Comment by trel** [comment] 2018-09-18 11:56
This sounds like the same issue as https://github.com/irods/irods/issues/4099.

**Comment by trel** [comment] 2018-09-18 12:57
It has to do with setting the 'file_modified' flag within the codepath too enthusiastically.

There should be no write() called if it is unnecessary, you are correct.

The fix will probably be a more surgical decision of when to set that flag (i.e. only on a data change).

We're still working to trap the bug and understand the other ramifications of changing the file_modified behavior.

**Comment by trel** [comment] 2018-10-18 17:05
Closing as duplicate of #4099.

**Closed by trel** 2018-10-18 17:05 UTC
Labels: bug, consortium-member, duplicate
