### ISSUE TITLE
Add orphan file creation behavior to documentation

### ISSUE THREAD

**Issue by kript** [irods/irods#3556] opened 2017-05-19 15:42 UTC
We find we have a number of files like;

```
ils -L /seq/trash/orphan/srpipe#Sanger1/20221_7#10_F0xB00.stats.2538565540
  srpipe            0 root;replicate;seq-green;green2;irods-seq-sr02-ddn-rd10-9-10-11       179150 2017-02-13.09:45 & 20221_7#10_F0xB00.stats.2538565540
    d27601a130dc01eebfdfa67d5f1c60ea    generic    /irods-seq-sr02-ddn-rd10-9-10-11/20221/20221_7#10_F0xB00.stats
  srpipe            1 root;replicate;seq-red;red3;irods-seq-i17-bc       179150 2017-05-19.16:16 & 20221_7#10_F0xB00.stats.2538565540
    d27601a130dc01eebfdfa67d5f1c60ea    generic    /irods-seq-i17-bc/trash/orphan/srpipe#Sanger1/20221_7#10_F0xB00.stats.2538565540
```

Which we didn't (intentionally) create and have also disabled trash. Could we have the orphan file creation behavior documented in the manual for >=4.1.10 and 4.2.x please?

**Comment by trel** [comment] 2017-05-20 14:56
duplicate of #3550

**Closed by trel** 2017-05-20 14:56 UTC
Labels: consortium-member, documentation
