### ISSUE TITLE
Runtime errors put some clients in an unusable state in 4.1.3, 3.3.1

### ISSUE THREAD

**Issue by keithj** [irods/irods#2833] opened 2015-08-11 21:57 UTC
We noticed this behaviour on a  3.3.1 system this week. I can reproduce it on 4.1.3 Ubuntu packaged. 

This occurs when strict ACLs are off.

The client has a list of data objects whose contents it will read successively, across a single connection. Each file is read in turn with `rcDataObjOpen`, `rcDataObjRead`, `rcDataObjClose`. This works perfectly if the client has permissions to read the files. When it encounters a file where it does not have permissions, a suitable error is returned by the server on `rcDataObjOpen` and the client handles this by skipping to the next file.

This all works fine until a certain number of attempts have been made to read restricted files. From this point, all attempts to open any file (including those that are readable) will get CAT_NO_ACCESS_PERMISSION from `rcDataObjOpen`, even files that the client was able to read earlier in the session.

The number of errors required to get the server to always return CAT_NO_ACCESS_PERMISSION is 48 for iRODS 3.3.1 and 25 for 4.1.3

I've tested this by inserting two files, then revoking my own access from one of them. I get the client (`baton-get` in our `baton` tool suite) to read the inaccessible one `n` times, then try to read the accessible one, all on the same connection. I can read the accessible one any number of times up until `n` reaches 48 for iRODS 3.3.1 or 25 for 4.1.3.

Is there a way to account for this behaviour?

Thanks.

**Comment by trel** [comment] 2015-08-12 20:32
We'll try to get this replicated and into a test.  Thanks Keith.

**Comment by jasoncoposky** [comment] 2015-08-13 21:44
I am testing this in the master branch, with the following method:

iput -r test_coll/ -> contains 30 files
ichmod null rods test_coll/file1 ... test_coll/file26
iget -r test_coll tgt_coll

I tried this both with STRICT ACLs and not-STRICT ACLs and i did get 
tgt_coll/file27..tgt_coll/file30 in the fetched directory.

Am i missing a step?

```
irods@avogadro:~$ iget -r test_coll tgt_coll
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file1. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file10. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file11. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file12. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file13. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file14. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file15. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file16. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file17. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file18. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file19. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file2. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file20. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file21. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file22. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file23. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file24. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file25. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file26. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file3. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file4. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file5. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file6. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file7. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file8. status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/rods/test_coll/file9. status = -806000 status = -806000 CAT_SQL_ERR
ERROR: getUtil: get error for tgt_coll status = -806000 CAT_SQL_ERR

irods@avogadro:~$ ls -l tgt_coll
total 16
-rw-r--r-- 1 irods irods 454 Aug 13 17:40 file27
-rw-r--r-- 1 irods irods 454 Aug 13 17:40 file28
-rw-r--r-- 1 irods irods 454 Aug 13 17:40 file29
-rw-r--r-- 1 irods irods 454 Aug 13 17:40 file30
```

**Comment by keithj** [comment] 2015-08-13 21:49
Aren't you using one connection per get operation there? I'm doing `n` open/read/close operations on the same connection.

**Comment by keithj** [comment] 2015-08-13 22:43
I've started writing a reduced test case that doesn't require any of our code. Alternatively, our recent client releases e.g. https://github.com/wtsi-npg/baton/releases/tag/0.15.0 build cleanly against a packaged 4.1.x with just `./configure`

**Comment by jasoncoposky** [comment] 2015-08-13 23:00
iget uses a single connection but does not do everything from the client side as you are in baton.  for single buffer gets the read is done server side.  i have some test code i can respin tomorrow to try to reproduce it as well.

**Comment by jasoncoposky** [comment] 2015-08-18 19:41
on a failed query the statement table entry in the database plugin was not released which caused the table to be exhausted after a sufficient number of queries.  it ran out earlier on the 4.x series due to the extra work we do to maintain better consistency in the database.  however there is no way to know if the query need be release within the `getDataObjOInfo` call ( which is called by `rsDataObjOpen` ), and no interface with which to surgically release the query from the API call.

the uncollected queries after a failure are used in the instance of iteration over large result sets to indicate that the query is complete at which point they are released by the mid-tier database code ( `cmlGetRow*` ).  there is no way to know if this is or is not the case within the scope where the statement could be properly released in the `rsGenQuery` code.

this is an artifact of the general design principle of short running agent processes which do not require garbage collection.  this cannot be resolved due to backwards compatibility issues until such time as we begin work on the integration of the new query language which will be made available by the next generation API, perhaps within 4.3.

**Comment by keithj** [comment] 2015-08-19 00:33
Thanks for taking the time to look at this. I've run our client against a 3.3.1 server where I've inserted extra logging and I can see the open statement count being exceeded in the session. When the unreadable files are encountered early, the session runs out of statements within a second of the client connecting, so the agent can't really be described as long running.

This is quite bad for us, so I'm going to see what modifications we need to make in order to work around this on 3.3.1. My first thought is to free all open statements in the session when the requested operation fails, if I can't know which index the offending statement is at. I suspect that this might have unwanted effects elsewhere...

Alternatively, I could count the errors on the client side and drop the connection before the number of statements is exhausted. However, a major reason for writing this client was to avoid re-connection overhead, so that's not ideal.

**Comment by jasoncoposky** [comment] 2015-08-19 01:19
Understood.  There is no mechanism from the ICAT API perspective to free statements, or it could be done in the `getDataObjInfo` call in the case of an error.  To compound the issue, the `genQueryOut`structure is released in the case of an error in rsGenQuery which could have held the offending statement number in order to free it downstream.  Changing that would alter the ownership semantics across all of iRODS and the client APIs which is also undesirable.  I will continue digging, but dropping the connection is probably the safest bet at this point.

**Comment by mcast** [comment] 2015-08-19 08:34
On Tue, Aug 18, 2015 at 05:33:40PM -0700, Keith James wrote:

> Alternatively, I could count the errors on the client side

(I'm assuming we all agree this sort of white-box detail is bad?)

> and drop the connection before the number of statements is
> exhausted. However, a major reason for writing this client was to
> avoid re-connection overhead, so that's not ideal.

Would it be possible to get a different error message, to indicate
that the table is full?  Then at least there is a clear signal for
when to reconnect, and a suitable bit of text to websearch for.

-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jasoncoposky** [comment] 2015-08-19 11:28
I will take a look at a new error for 4.1.5, and continue investigating the error caused by the release of the  statement table entry.

**Comment by jasoncoposky** [comment] 2015-08-25 13:37
@keithj please run your tests against our 4-1-stable branch to determine if the fix is complete from your point of view.

**Comment by keithj** [comment] 2015-08-26 21:15
I've build 4-1-stable  at b21c2262666f2ae66a5386a70a4fa25d54fcdbb2 using --run-in-place.

I'm no longer able to get any baton client programs to connect. The server is up and I can connect with the icommands. However,  I get this sort of error:

````
ERROR: packNonpointerItem:strlen 69 of option > dim size 64,content:baton:lt-baton-list:0.15.0-3-gdc3ceab-dirtyrequest_server_negotiation
ERROR: connectToRhost: sendStartupPack to zen failed, status = -308000 status = -308000 USER_PACKSTRUCT_INPUT_ERR
ERROR: _rcConnect: connectToRhost error, server on zen:1247 is probably down status = -308000 USER_PACKSTRUCT_INPUT_ERR
````

**Comment by kellerb** [comment] 2015-08-26 21:25
It looks like baton is using the string `baton:lt-baton-list:0.15.0-3-gdc3ceab-dirtyrequest_server_negotiation` when it just should be `request_server_negotiation`.

Perhaps your `irods_environment.json` file has invalid contents. Also, it could be that something in the client code is corrupting the string used to contain `request_server_negotiation`.

It looks like the connection is going wrong before the server is involved, i.e. packStruct (the portion of the code that serializes iRODS clients requests, which is calling `packNonpointerItem()` in the error message) is failing to pack the request before sending it to the server.

**Comment by keithj** [comment] 2015-08-26 21:33
My `irods_environment.json` contains the line

````
 "irods_client_server_negotiation": "request_server_negotiation",
````

To connect, I'm calling `rcConnect` and then for an iRODS 4.x server

````
  init_client_api_table();

  status = clientLogin(conn, "", "");
````

The clients work fine on 4.1.3 and 4.1.4 (I've sent up a build matrix on Travis). Has something in the connection code changed since 4.1.4?

**Comment by keithj** [comment] 2015-08-26 21:35
Maybe it's going wrong at `getRodsEnv` ...

**Comment by keithj** [comment] 2015-08-26 22:36
I think `getRodsEnv` has a bug. I've written this client program:

````
#include <stdio.h>
#include <stdlib.h>

#include <rodsClient.h>

int main(int argc, char *argv[]) {
  argc = argc;
  argv = argv;

  rodsEnv env;
  rErrMsg_t errmsg;

  getRodsEnv(&env);

  rcComm_t *conn =
    rcConnect(env.rodsHost, env.rodsPort, env.rodsUserName, env.rodsZone,
	      NO_RECONN, &errmsg);
  rcDisconnect(conn);

  return 0;
}
````

````
export spOption=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
./envbug

ERROR: rstrcpy not enough space in dest, slen:92, maxLen:64
ERROR: packNonpointerItem:strlen 89 of option > dim size 64,content:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarequest_server_negotiation
ERROR: connectToRhost: sendStartupPack to zen failed, status = -308000 status = -308000 USER_PACKSTRUCT_INPUT_ERR
ERROR: _rcConnect: connectToRhost error, server on zen:1247 is probably down status = -308000 USER_PACKSTRUCT_INPUT_ERR
````

**Comment by kellerb** [comment] 2015-08-26 23:39
How are you building, linking `envbug` against the iRODS libraries (e.g., which library are you linking against, etc.).

**Comment by keithj** [comment] 2015-08-26 23:49
I'm linking against libRodsAPIs.a in this case.

A simpler way to do this is to rename an icommand executable to a very long name, then you can trigger the bug with it:

````
cp /home/keith/dev/renci/irods.git/iRODS/clients/icommands/bin/ils ilsaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

$ ./ilsaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
ERROR: rstrcpy not enough space in dest, slen:123, maxLen:64
ERROR: packNonpointerItem:strlen 89 of option > dim size 64,content:ilsaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarequest_server_negotiation
ERROR: connectToRhost: sendStartupPack to zen failed, status = -308000 status = -308000 USER_PACKSTRUCT_INPUT_ERR
ERROR: _rcConnect: connectToRhost error, server on zen:1247 is probably down status = -308000 USER_PACKSTRUCT_INPUT_ERR
````

**Comment by kellerb** [comment] 2015-08-27 02:18
The linchpin of all these errors appears to be that if `spOption` is too long, the client code will not work once `rcConnect` gets into `sendStartupPack`.

`startupPack.option` is `char[64]`.
The contents of `$spOption` are put into this [here](https://github.com/irods/irods/blob/4.1.4/iRODS/lib/core/src/sockComm.cpp#L1206), truncated to 63 bytes plus a NULL. Then the advanced negotiation string is appended [here](https://github.com/irods/irods/blob/4.1.4/iRODS/lib/core/src/sockComm.cpp#L1219) without performing a bounds check. This leads to a string longer than 64 bytes in `startupPack.option`, which packStruct refuses to pack.

Note that, e.g. the binary name (`illll...llls`) is added to `spOption`, so that is why changing the name of the icommand replicates the bug.

All of these issues appear to have been a part of the code since at least 4.1.4, and most likely much earlier. Is it possible that something in your test framework would be generating much longer `spOption` values now (e.g. setting the environment variable, or creating binaries with really long names)? What is the source of the string `baton:lt-baton-list:0.15.0-3-gdc3ceab-dirty`?

iRODS action items are to:
- [ ] Improve error handling/bounds checking in `sendStartupPack()` to better report the error and not copy data past the end of the array.
- [ ] @jasoncoposky has suggested that we may not need to include the binary name in `spOption` at all, which, if that is the cause of your manifestation, would fix the problem you are seeing without you needing to change anything else.

**Comment by keithj** [comment] 2015-08-27 08:10
The string `baton:lt-baton-list:0.15.0-3-gdc3ceab-dirty` is a baton client identifier created automatically by the build process. It is built from PACKAGE_NAME and PACKAGE_VERSION obtained from `config.h`, which in turn is populated by `autoconf` and `git describe`.

Rather than using the executable name directly, our clients use this string in `spOption` because it means that the output of `ips` will contain the name and release version of all the connected clients. This avoids the server admins seeing dozens of anonymous 'UNKNOWN' clients in `ips`. Is there a better way for clients to report themselves to the server for `ips?

**Comment by keithj** [comment] 2015-08-27 14:08
Amusingly, if I set `"irods_client_server_negotiation": "off"` in my config and then run `ips`, it reports itself
as

````
   25211 irods#tempZone  0:00:00  ipsoff  127.0.0.1
````

Is it trying to tell me something?

**Comment by trel** [comment] 2015-08-27 20:05
closing - the original issue is now captured in a test and passing.

**Closed by trel** 2015-08-27 20:05 UTC
Labels: bug

**Comment by keithj** [comment] 2015-08-28 13:06
Since I'm using the same `irods_environment.json` file for both client and server and have validation on, the only other permitted value for `irods_client_server_negotiation` is `off`. This string is short enough to let my client connect because the total length is <64.

Having done that, I can confirm that the original test that I submitted now passes, thanks.
