### ISSUE TITLE
Define use of /etc/irods/service_account.config, especially with regards to an upgrade

### ISSUE THREAD

**Issue by kript** [irods/irods#2975] opened 2015-12-02 15:53 UTC
Hi,

In the /etc/init.d/irods startup script, it sources the above file, which is presumably where $IRODS_SERVICE_ACCOUNT_NAME is supposed to be defined?

```
# import service account information
. /etc/irods/service_account.config
```

However, this file is not present in the /etc/irods dir in the packaging (for Ubuntu 12).
It is also not defined in the manual at https://docs.irods.org/4.1.7/manual/configuration/

The packaging does contain something related;
```
vagrant@icat:/etc/irods$ dpkg -L irods-icat | grep service_account
/var/lib/irods/packaging/setup_irods_service_account.sh
```
But the upgrade instructions https://docs.irods.org/4.1.7/manual/upgrading/ do not mention running it at stage 13.  Should this be run at some point? The packaging hasn't run it at install;

```
vagrant@icat:/etc/irods$ grep irod /etc/passwd
vagrant@icat:/etc/irods$ 
```

but it does appear to be in the setup script;

```
vagrant@icat:/etc/irods$ grep setup_irods_service_account.sh /var/lib/irods/packaging/*
/var/lib/irods/packaging/setup_irods.sh:  $DETECTEDDIR/setup_irods_service_account.sh
```

However step 13 recommends not to run this if your database is on a different server than the iCAT, and step 14 says the default service account name is irods, but this is not set anywhere in the upgrade instructions (that I can see).

Have I missed something?

Thanks!

**Comment by trel** [comment] 2015-12-17 02:09
`/etc/irods/service_account.config` does not exist just after package installation.

Creating `/etc/irods/service_account.config` is one of the first things that is handled by the `setup_irods.sh` script (which is step 13), by calling out to `setup_irods_service_account.sh`.

```bash
# service account config file
SERVICE_ACCOUNT_CONFIG_FILE="/etc/irods/service_account.config"

# define service account for this installation
if [ ! -f $SERVICE_ACCOUNT_CONFIG_FILE ] ; then
  $DETECTEDDIR/setup_irods_service_account.sh
fi

# import service account name and group
source $SERVICE_ACCOUNT_CONFIG_FILE
```

I think the confusion arises due to the wording at the end of step 13...
> The automatic ./packaging/setup_irods.sh script will work only with the system-installed database server.

This was intended to draw a distinction between the local copy of postgresql that is the default on most legacy 3.x installations and the recommended package-installed postgresql that most installations of iRODS 4.x+ will be migrating to.

Coming from your perspective with an external Oracle database was not properly taken into consideration when writing that sentence in step 13.  I think that you can run `setup_irods.sh` and point to the external database server without any surprises.  Of course, please correct me if I'm wrong.

Step 13 should be made more clear, regardless.

**Comment by kript** [comment] 2015-12-24 11:19
Just to confirm that you can run setup_irods.sh and point it to an existing oracle db (as long as you have run the upgrade script first, not tried without), and it works.

**Comment by trel** [comment] 2016-01-19 21:26
Closing - I've updated step 13 in https://github.com/irods/irods/commit/202dd902f8e267e7b96e05dd0c0009dce730dec0

**Closed by trel** 2016-01-19 21:26 UTC
Labels: consortium-member, documentation
