### ISSUE TITLE
Issue Calling Microservice From Custom Rule Engine Plugin

### ISSUE THREAD

**Issue by jacquayj** [irods/irods#3431] opened 2017-01-03 20:28 UTC
I'm attempting to call the [`msiString2KeyValPair` microservice](https://docs.irods.org/master/doxygen/keyValPairMS_8cpp.html#a91bf18da4b5141987c72b485595d4d87) from a custom rule engine plugin I'm writing, but am running into some issues. 

Basically I'm wanting to write functionality that adds AVU metadata to a data object, similar to [this Python rule engine example](http://slides.com/irods/curategear2016-pluggable-rule-engine#/12), but without having to have an intermediate `add_metadata_to_objpath` rule written in the iRODS rule language (so my custom rule engine isn't dependant on another engine running).

Here's the snippet of code that is run:
```c++
irods::callback* _cb; // assuming this is pointing to the initialized callback variable

std::list<boost::any> params;
std::string ruleName = "msiString2KeyValPair";

// Setup params (inKeyValStr is string of key=value pairs separated by %-sign)
msParam_t* inKeyValStr = (msParam_t*)malloc(sizeof(*inKeyValStr));
msParam_t* outKeyValPairP  = (msParam_t*)malloc(sizeof(*outKeyValPairP));

memset(inKeyValStr, 0, sizeof(*inKeyValStr));
memset(outKeyValPairP, 0, sizeof(*outKeyValPairP));

fillMsParam(inKeyValStr, NULL, STR_MS_T, "metakey=val%test=true", NULL);
fillMsParam(outKeyValPairP, NULL, KeyValPair_MS_T, NULL, NULL); // Fill output param with NULL

// Fill param list with msParam_t* params
params.push_back(inKeyValStr);
params.push_back(outKeyValPairP);

// Execute microservice callback
_cb->operator()(ruleName, irods::unpack(params));

```

This code fails when a `msParam_t` subtype of `KeyValPair_MS_T` is passed in the parameter std::list, but `STR_MS_T` subtypes work fine. Here is the error that's thrown:
```
ERROR: applyRule: -1, [-]	/home/irodsbuild/irods/server/re/include/irods_re_plugin.hpp:326:irods::error irods::dynamic_operation_execution_manager<std::__1::tuple<>, RuleExecInfo *, irods::rule_execution_manager_pack::DONT_AUDIT_RULE>::call(std::string, std::string, OP, As &&...) [T = std::__1::tuple<>, C = RuleExecInfo *, Audit = irods::rule_execution_manager_pack::DONT_AUDIT_RULE, OP = std::__1::function<irods::error (std::__1::basic_string<char>, irods::re_pack_inp<std::__1::tuple<> > &)>, As = <std::__1::basic_string<char> &, irods::re_pack_inp<std::__1::tuple<> > &>] :  status [Unknown iRODS error]  errno [Operation not permitted] -- message []
	[-]	/home/irodsbuild/irods/server/re/include/irods_re_plugin.hpp:326:irods::error irods::dynamic_operation_execution_manager<std::__1::tuple<>, RuleExecInfo *, irods::rule_execution_manager_pack::DONT_AUDIT_RULE>::call(std::string, std::string, OP, As &&...) [T = std::__1::tuple<>, C = RuleExecInfo *, Audit = irods::rule_execution_manager_pack::DONT_AUDIT_RULE, OP = std::__1::function<irods::error (std::__1::basic_string<char>, RuleExecInfo *&, irods::unpack &&)>, As = <std::__1::basic_string<char> &, RuleExecInfo *&, irods::unpack>] :  status [Unknown iRODS error]  errno [Operation not permitted] -- message []
		[-]	/home/irodsbuild/irods/server/re/src/irods_re_plugin.cpp:78:irods::error irods::convertFromMsParam(boost::any &, msParam_t *) :  status [Unknown iRODS error]  errno [Operation not permitted] -- message [cannot convert parameter]
```

From my understanding of this error, the `convertFromMsParam()` function [doesn't have the logic to handle/duplicate `KeyValPair_MS_T` subtypes](https://github.com/irods/irods/blob/caa31b2cd1cc99dbff40f35ffd86569bbf95c69a/server/re/src/irods_re_plugin.cpp#L62).

So my questions are:

- Is there a better way to invoke microservices from a rule engine plugin, other than `_cb->operator()(ruleName, irods::unpack(params))`?  
- Is what I'm trying to do even possible? I haven't seen any examples of the Python rule engine invoking `msiString2KeyValPair` directly, just "proxy" rules/microservices that implement the `STR_MS_T` subtype.

I know the iRODS rule language plugin is somehow able to invoke microservices, avoiding the `convertFromMsParam()` function call or else it would only support small subset of `msParam_t` subtypes.... right? Any help is greatly appreciated.

Thanks,
John

**Comment by kellerb** [comment] 2017-01-03 21:43
I can confirm your finding that the problem is that the REPF (rule engine plugin framework) does not yet support all the iRODS types. The iRODS rule language plugin currently only redirects through the framework for microservices that have [only string arguments](https://github.com/irods/irods/blob/4.2.0/plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/arithmetics.cpp#L822-L827), it [invokes all other microservices directly](https://github.com/irods/irods/blob/4.2.0/plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/arithmetics.cpp#L851-L867) (as it did before the REPF existed). [This issue](https://github.com/irods/irods/issues/3254) is about having the iRODS rule language plugin redirect all microservices through the REPF, which would fix the problem you are having, since to redirect the calls the REPF would need to handle all the types.

To work around this limitation, you could directly call the [function backing the microservice](https://github.com/irods/irods/blob/4.2.0/server/re/src/keyValPairMS.cpp#L165-L203). This function should be available to your rule engine plugin once the rule engine plugin is loaded by the server.

Specifically for the case of `msiString2KeyValPair`, you may prefer to create the `keyValPair_t` directly instead of going through the microservice. You could do so using functions like [`addKeyVal`](https://github.com/irods/irods/blob/4.2.0/lib/core/src/rcMisc.cpp#L778-L817).

Please let us know how this goes.

**Comment by jacquayj** [comment] 2017-01-04 14:49
Thank you @kellerb for this information! I recall briefly reading over issue #3254 after finding it via Google search, but I didn't understand the implications at the time. Thanks for clearing it up for me.

As you suggested, I'll try to call the `msiAssociateKeyValuePairsToObj` microservice directly using manually constructed `keyValPair_t` params.

In order to maintain a consistent API in my rule engine (for string only microservices as well as the others), I'd like to invoke the microservices using a string as the identifier. This is some code I've come up with, based on `execMicroService3()`.

```c++
ruleExecInfo_t* rei; // Assuming this is a valid pointer

char* msName = "msiAssociateKeyValuePairsToObj";

irods::ms_table_entry ms_entry;
int actionInx = actionTableLookUp(ms_entry, msName);

if ( actionInx >= 0 ) {
	std::vector<msParam_t*> myArgv;

	// Fill the vector with msParam_t*

	int ii = 0;

	// Call microservice
	ii = ms_entry.call(rei, myArgv);

	if ( ii < 0 ) {
		// Handle error
	}
} else {
	// Error, no microservice found
}
```

Would this code be decent/acceptable for my use case? 

Thanks again for everything, your help has been invaluable!

**Comment by kellerb** [comment] 2017-01-04 20:58
After talking with @xu-hao, we cannot think of any reason why that workaround won't work.

@xu-hao has pointed out that, generally speaking, not going through the callback (not that there is another option currently since the REPF doesn't support the types you need):

1. by-passes the auditing functionality provided by the REPF (i.e. calls to microservices won't be detected by the auditing rule engine plugin)
2. could break in future releases of iRODS, as e.g. `actionTableLookUp()` and `ms_entry.call()` are not guaranteed to be stable across iRODS versions (though I am not aware of any impending changes to them)

That said, it should be straightforward to convert your rule engine plugin to use the callback instead of your workaround once the REPF is updated to work with more types.

**Comment by jacquayj** [comment] 2017-01-05 18:09
Thanks @kellerb and @xu-hao. I was able to implement logic similar to the iRODS rule language plugin by calling sting-only microservices with the REPF, and using direct calls for all others. I'll keep in mind that this bypasses the auditing functionality for now.

**Comment by trel** [comment] 2017-09-04 19:40
@jacquayj @xu-hao @kellerb I think all the types are in there now.  Please confirm and we can close this issue.  Thanks.

**Comment by trel** [comment] 2017-10-19 02:04
closing - if there is something that we're missing, we'll open a new issue.

**Closed by trel** 2017-10-19 02:04 UTC
Labels: question
