### ISSUE TITLE
authentification PAM not used for GUI (java?) apps (iDrop, CyberDuck, DFC-CloudBrowser)

### ISSUE THREAD

**Issue by mgtddn** [irods/irods#3488] opened 2017-03-01 15:32 UTC
I'm using irods servers 4.2
GUI clients like iDrop don't use PAM even if I specify it. They are using the native/standard irods auth scheme (with the password stored into the irods DB) or they fail on Authentication Exception if there is no password in the irods DB.
It works well with i-commands (iinit 4.1.10-0) when I modify .irods/irods_environment.json to use standard auth:
    "irods_authentication_scheme": "native",
or PAM auth:
     "irods_authentication_scheme": "PAM",
I can choose the password DB I want with iinit (CLI access) but not with GUI:
- iDrop (2_0_1-RC1)
- CyberDuck
- DFC-CloudBrowser

**Comment by jasoncoposky** [comment] 2017-03-06 21:14
1. My understanding is that iDrop is no longer under development by the DICE group
2. We will look into Cyberduck, but I believe if SSL is correctly configured on the client side it will work
3. The latest release of the cloudbrowser, 1.0.2, will support SSL and PAM authentication

**Comment by jasoncoposky** [comment] 2017-03-09 11:37
Yes we are looking into cyberduck, it is not working for us either and I beleive the issue is that the ssl cert needs to be configured for jargon to complete the SSL handshake for sending the PAM password.  We are looking into it with @michael-conway.

Also, set acPreConnect to CS_NEG_REFUSE unless you want everything encrypted.

**Comment by michael-conway** [comment] 2017-03-09 13:26
Yes, if it's a self-signed certificate, the ssl public key might need to be
imported.

**Comment by trel** [comment] 2017-03-13 13:04
Cyberduck has been confirmed to work with a nightly build (fix will be in 5.4+, and 6.0+) with PAM.

Working (renciZone) config is here:
 https://github.com/DICE-UNC/jargon/issues/224#issuecomment-286099400

Note the new "Authorization" stanza in the config file.

**Comment by dkocher** [comment] 2017-03-13 18:32
Documentation for the new `Authorization` property in the connection profile for Cyberduck is in https://trac.cyberduck.io/wiki/help/en/howto/irods#AuthenticationwithPAMscheme

**Comment by trel** [comment] 2017-03-13 19:30
Thanks @dkocher.

@mgtddn, can we close this?

I think all action items and loose ends are complete.

**Comment by bpitollat** [comment] 2017-03-14 15:09
With cyberduck version 5.4.0 (23761) and template profile you provided, I get the error "Unable to start SSL socket".
We use a self-signed certificate but I do not know how to configure the client to use the chain.pem. Can you tell me how to do it ?

**Comment by trel** [comment] 2017-03-15 17:09
pinging @michael-conway - is that what @bpitollat needs to do?  Configure a chain cert for Jargon to use?  Or to add something to the keystore?

**Comment by michael-conway** [comment] 2017-03-15 18:52
The self-signed cert needs to be in the java keystore, a good guide to this
is here:

https://github.com/DICE-UNC/jargon/wiki/Setting-up-PAM

I don't know whether cyberduck has an embedded JVM, but the trick is to
import that into the keystore of the JVM CyberDuck uses.  If I recall
directly CyberDuck is really written with Mono, so it may no be readily
apparent where the cert needs to go.

**Comment by dkocher** [comment] 2017-03-15 18:57
The certificate chain returned from the server is validated against the system and user trust settings natively set in the operating system (Keychain on macOS and Windows Certificate Store). We do not use the trust store from Java runtime. Jargon will/should forward the chain to the certificate trust manager we register. There is an open issue that not the full chain is forwarded, see https://github.com/DICE-UNC/jargon/issues/159 and if the connection fails because of non valid certificates there must be another bug in the Jargon library that this check is done by the library itself rather than forwarding it to the registered trust manager on the SSL socket factory.

– David

**Comment by bpitollat** [comment] 2017-03-16 10:01
Would it solve our problem to install a certificate signed by a recognized organization.
If so, we can ask one.

**Comment by trel** [comment] 2017-03-16 13:05
Yes, that will definitely help.

Please try that and confirm that a good cert works with the code as is.

**Comment by bpitollat** [comment] 2017-03-21 15:21
I confirm that it works fine with a good cert (signed by a recognized organization).

**Comment by trel** [comment] 2017-03-21 15:38
Ah, very good.  In that case, I'll close this issue.

Like @dkocher said, full chain support in Jargon is DICE-UNC/jargon#159.

Thanks.

**Closed by trel** 2017-03-21 15:38 UTC
Labels: consortium-member, resolved/invalid
