### ISSUE TITLE
PUT operation should not be able to create additional replicas

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5575] opened 2021-04-29 15:24 UTC
- [x] master
- [x] 4-2-stable
---
### iRODS Version, OS and Version
4-2-stable (sha: bdea0cc178ddbadc2d4a21d4fc84f4964c48c66d)

### Script for reproducing issue
```bash
#! /bin/bash

set -x

# Tear down
irm -f foo
iadmin rmchildfromresc comp_resc cache_resc
iadmin rmchildfromresc comp_resc archive_resc
iadmin rmresc comp_resc
iadmin rmresc cache_resc
iadmin rmresc archive_resc

# Setup
iadmin mkresc comp_resc compound
iadmin mkresc cache_resc unixfilesystem `hostname`:/tmp/cache_resc_vault
iadmin mkresc archive_resc unixfilesystem `hostname`:/tmp/archive_resc_vault
iadmin addchildtoresc comp_resc cache_resc cache
iadmin addchildtoresc comp_resc archive_resc archive
truncate -s1m foo

# Demo
iput -R comp_resc foo
ils -l foo

iput -f foo # (1)
ils -l foo

iput -f foo # (2)
ils -l foo
```

**(1)** should result in `HIERARCHY_ERROR`, but it succeeds in creating a new replica on `demoResc`. `iput -fR demoResc` results in `HIERARCHY_ERROR` as expected. This command can also result in the prompt being hung. I hit this a few times, but have not been able to reproduce the hang.

**(2)** results in `-406000 LOCKED_DATA_OBJECT_ACCESS`. This should result in the same error as **(1)**.

**Comment by alanking** [comment] 2021-04-29 17:40
I was able to reproduce the hang. I have a fix but I will be investigating the cause of the hang. Given the quietness of the logs I suspect a deadlock in the RST.

**Comment by korydraughn** [comment] 2021-04-29 17:41
Excellent!

**Comment by trel** [comment] 2021-04-30 22:44
checkboxed

**Closed** 2021-04-30 22:50 UTC
Labels: bug
