### ISSUE TITLE
Replicas left in bad states after streaming into data object with `istream`

### ISSUE THREAD

**Issue by ilarik** [irods/irods#5422] opened 2021-02-18 13:33 UTC
- [x] master
- [x] 4-2-stable
----------

### iRODS Version, OS and Version

iRODS 4-2-stable (commit ID 40ad875c0f09f8e719326e3ad17f418c0545fc2a) and CentOS Linux release 7.8.2003 (Core).

### What did you try to do?

After a successful PUT of a data object `VERSION.json` into `demoResc` followed by a replication into a `replResc` (which itself is a `replication` type resource), then using `istream` to write into the data object leaves the replicas in incorrect states, all having the & flag, even though only replica ID 0 is current.

Also after this, when trying to get the replicas up-to-date using `irepl` it silently fails, returning `0` back to the shell. Also nothing in the `rodsLog`.

### Expected behavior

The data object replica states to be updated accordingly (as happens in 4.2.8) and it should be possible to get the data object out of the bad state w/o much hassle.

### Observed behavior (including steps to reproduce, if applicable)

```
-bash-4.2$ ils -l
/tempZone/home/rods:
-bash-4.2$ iput VERSION.json
-bash-4.2$ ils -l
/tempZone/home/rods:
  rods              0 demoResc          499 2021-02-18.13:19 & VERSION.json
-bash-4.2$ ils -l
/tempZone/home/rods:
  rods              0 demoResc          499 2021-02-18.13:19 & VERSION.json
  rods              1 replResc;rodsresc1_resc          499 2021-02-18.13:19 & VERSION.json
  rods              2 replResc;rodsresc2_resc          499 2021-02-18.13:19 & VERSION.json
-bash-4.2$ echo "blaa" | istream write -a -o 499 VERSION.json
-bash-4.2$ ils -l
/tempZone/home/rods:
  rods              0 demoResc          504 2021-02-18.13:20 & VERSION.json
  rods              1 replResc;rodsresc1_resc          499 2021-02-18.13:19 & VERSION.json
  rods              2 replResc;rodsresc2_resc          499 2021-02-18.13:19 & VERSION.json
-bash-4.2$ irepl -n 0 -R replResc VERSION.json
-bash-4.2$ echo $?
0
-bash-4.2$ ils -l
/tempZone/home/rods:
  rods              0 demoResc          504 2021-02-18.13:20 & VERSION.json
  rods              1 replResc;rodsresc1_resc          499 2021-02-18.13:19 & VERSION.json
  rods              2 replResc;rodsresc2_resc          499 2021-02-18.13:19 & VERSION.json
-bash-4.2$ 
```

Comparing to the behavior in an iRODS 4.2.8 development host:

```
rodsdev$ iput VERSION.json
rodsdev$ ils -l VERSION.json
  rods              0 demoResc          224 2021-02-18.14:30 & VERSION.json
rodsdev$ irepl -n 0 -R replResc VERSION.json
rodsdev$ ils -l VERSION.json
  rods              0 demoResc          224 2021-02-18.14:30 & VERSION.json
  rods              1 replResc;demoResc2          224 2021-02-18.14:30 & VERSION.json
  rods              2 replResc;demoResc3          224 2021-02-18.14:30 & VERSION.json
rodsdev$ echo "blaa" | istream write -a -o 224 VERSION.json
rodsdev$ ils -l VERSION.json
  rods              0 demoResc          229 2021-02-18.14:31 & VERSION.json
  rods              1 replResc;demoResc2          224 2021-02-18.14:30   VERSION.json
  rods              2 replResc;demoResc3          224 2021-02-18.14:30   VERSION.json
rodsdev$ irepl -n 0 -R replResc VERSION.json
rodsdev$ ils -l VERSION.json
  rods              0 demoResc          229 2021-02-18.14:31 & VERSION.json
  rods              1 replResc;demoResc2          229 2021-02-18.14:31 & VERSION.json
  rods              2 replResc;demoResc3          229 2021-02-18.14:31 & VERSION.json
rodsdev$ 
```

**Comment by trel** [comment] 2021-02-18 14:08
This is directly related to the unfinished replica work for 4.2.9 - handing to @alanking ...

**Comment by alanking** [comment] 2021-02-18 14:12
Possible duplicate of #5187

**Comment by trel** [comment] 2021-02-18 14:18
Ah, it does appear very the same.

**Comment by trel** [comment] 2021-05-04 13:37
checkboxed

**Closed** 2021-05-04 13:39 UTC
Labels: bug, consortium-member
