### ISSUE TITLE
irule PLUSET specification incorrectly ignores m(minutes) unit suffix

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#4245] opened 2019-01-20 20:28 UTC
### iRODS Version, OS and Version
iRODS 4.2.4 on Ub16
iRODS 4.3.0 (master c. 2019/Jan/18) on Ub14

### What did you try to do?
Schedule a rule (using irule) for delay execution 30m in the future 

### Expected behavior
The rule execution server should not execute the delayed rule until at least 30 minutes have expired.

### Observed behavior (including steps to reproduce, if applicable)
In contradiction of the [rule engine docs](https://docs.irods.org/4.2.4/plugins/pluggable_rule_engine/#delay-execution ) irule appears not to differentiate between 'm' and 's' as time units suffix in the PLUSET specification. In the session that follows, it's plain that  30 secs have been added instead of the expected (30*60=)1800 secs or 30 mins, and indeed the rule fires within approx. 1 minute.
```
Level 0: Available rule engine plugin instances:
	irods_rule_engine_plugin-irods_rule_language-instance
	irods_rule_engine_plugin-python-instance

15:11PM dmoore@canute:~ $ irule 'delay("<PLUSET>30m</PLUSET>"){ writeLine("serverLog","irods::cache 10m")}' null null ; date +%s ; echo ====== ; echo ; iquest "select RULE_EXEC_ID,RULE_EXEC_NAME,RULE_EXEC_TIME"
1548015123
======

RULE_EXEC_ID = 10074
RULE_EXEC_NAME =  writeLine("serverLog","irods::cache 10m")
RULE_EXEC_TIME = 1548015153
------------------------------------------------------------
15:12PM dmoore@canute:~ $ date +%s
1548015144
15:12PM dmoore@canute:~ $ iqstat
id     name
10074  writeLine("serverLog","irods::cache 10m") 
 ...
15:13PM dmoore@canute:~ $ date +%s
1548015182
15:13PM dmoore@canute:~ $ iqstat
No delayed rules pending for user rods

```

**Comment by d-w-moore** [comment] 2019-01-20 20:31
Obvious workaround for now is to use only seconds as units; for this example it would have to be expressed as `delay("<PLUSET>1800s</PLUSET>")...`

**Comment by trel** [comment] 2019-01-21 01:42
duplicate of #4055?

**Closed** 2019-01-22 07:53 UTC
