### ISSUE TITLE
imv silently fails when no intermediate collection

### ISSUE THREAD

**Issue by fconagy** [irods/irods#4117] opened 2018-09-21 08:17 UTC
## Bug Report

Command imv silently fails when no intermediate collection.
Suppose we got:
/a/b/c/x.x
We would like to move /a/b to /a/z.
The command imv /a/b /a/z finishes with no error and return
code 0. There is nothing at /a/z. Input directory is left intact.
In the iCAT server logs there are errors about /a/z/c collection
missing.

### iRODS Version, OS and Version

iRODS version: 4.1.11
OS version: CentOS 6.10

### What did you try to do?

Suppose we got:
/a/b/c/x.x
and we would like to move it /a/b to /a/z.
The command 'imv /a/b /a/z' finishes with no error and return code 0.
Collection is not moved.

### Expected behavior

Either create intermediate collection or report error.

### Observed behaviour (including steps to reproduce, if applicable)

Collection not moved, no error message from the command.

**Comment by fconagy** [comment] 2018-09-21 11:00
bash-4.1$ ils /snic.se/home/fconagy/projects/tmp/Cyberduck-6.3.1.27228.zip
 /snic.se/home/fconagy/projects/tmp/Cyberduck-6.3.1.27228.zip
-bash-4.1$ imv /snic.se/home/fconagy/projects/tmp/Cyberduck-6.3.1.27228.zip /snic.se/projects/tmp/Cyberduck-6.3.1.27228.zip
-bash-4.1$ echo $?
0
-bash-4.1$ ils /snic.se/projects/tmp/Cyberduck-6.3.1.27228.zip
ERROR: lsUtil: srcPath /snic.se/projects/tmp/Cyberduck-6.3.1.27228.zip does not exist or user lacks access permission
-bash-4.1$ ils /snic.se/projects/tmp
ERROR: lsUtil: srcPath /snic.se/projects/tmp does not exist or user lacks access permission 
 -bash-4.1$ ils /snic.se/home/fconagy/projects/tmp/Cyberduck-6.3.1.27228.zip  /snic.se/home/fconagy/projects/tmp/Cyberduck-6.3.1.27228.zip 

Sep 17 14:26:57 pid:124298 NOTICE: Agent process 22870 started for puser=rods and cuser=rods from 130.236.100.88
Sep 17 14:26:57 pid:22870 ERROR: _rsDataObjRename: dest coll /snic.se/projects/tmp does not exist, status = -808000
Sep 17 14:26:57 pid:22870 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep 17 14:26:57 pid:22870 NOTICE: Agent exiting with status = 0
Sep 17 14:26:58 pid:124298 NOTICE: Agent process 22870 exited with status 0

**Comment by trel** [comment] 2018-09-21 11:28
This is quite surprising - will reproduce.

Thanks.

**Comment by trel** [comment] 2019-05-31 01:27
Also works in 4.1.12.

```
$ imiscsvrinfo | grep relVersion
relVersion=rods4.1.12
$ imkdir -p a/b/c/d
$ iput testfile a/b/c/d/file
$ ils -r
/tempZone/home/rods:
  C- /tempZone/home/rods/a
/tempZone/home/rods/a:
  C- /tempZone/home/rods/a/b
/tempZone/home/rods/a/b:
  C- /tempZone/home/rods/a/b/c
/tempZone/home/rods/a/b/c:
  C- /tempZone/home/rods/a/b/c/d
/tempZone/home/rods/a/b/c/d:
  file

$ # move to a/g
$ imv a/b a/g

$ # file is successfully moved to be under a/g
$ ils -r
/tempZone/home/rods:
  C- /tempZone/home/rods/a
/tempZone/home/rods/a:
  C- /tempZone/home/rods/a/g
/tempZone/home/rods/a/g:
  C- /tempZone/home/rods/a/g/c
/tempZone/home/rods/a/g/c:
  C- /tempZone/home/rods/a/g/c/d
/tempZone/home/rods/a/g/c/d:
  file
```

Closing as previously fixed.

**Closed** 2019-05-31 01:48 UTC
Labels: consortium-member, resolved/invalid

**Comment by mcast** [comment] 2019-07-23 15:34
I still see this bug, transcript below.  I believe @trel's attempt to reproduce it was a different operation, because the `imv a/b a/g` is there operating on a collection not a file.

```
mca@cgpbar:~$ iput wibble /cgp/sandbox/mca/junk-file
mca@cgpbar:~$ ils -L /cgp/sandbox/mca/junk-file
  mca               0 green;greenrandom;green3;irods-cgp-sr12-sde            7 2019-07-23.16:26 & junk-file
    3e6cb75a29d570bef41cf7ce9a11bcb6    generic    /irods-cgp-sr12-sde/sandbox/mca/junk-file
mca@cgpbar:~$ imv /cgp/sandbox/mca/junk-file /cgp/sandbox/mca/subdir/junk-file 
mca@cgpbar:~$ echo $?
0
mca@cgpbar:~$ ils -L /cgp/sandbox/mca/junk-file 
  mca               0 green;greenrandom;green3;irods-cgp-sr12-sde            7 2019-07-23.16:26 & junk-file
    3e6cb75a29d570bef41cf7ce9a11bcb6    generic    /irods-cgp-sr12-sde/sandbox/mca/junk-file
mca@cgpbar:~$ ils -L /cgp/sandbox/mca/subdir/junk-file 
ERROR: lsUtil: srcPath /cgp/sandbox/mca/subdir/junk-file does not exist or user lacks access permission
4@cgpbar:~$ echo $?
4
```

This is on 4.1.12 with a mixture of Ubuntu client and Ubuntu or Red Hat servers.

I think the test above would have failed silently with `imv a/b/c/d/file a/b/c/d/e/file`, leaving `a/b/c/d/file` existing but command returning exit code zero and no output.

**Comment by trel** [comment] 2019-10-02 12:46
Agreed - conversation and resolution now happening on #4414.
