### ISSUE TITLE
 iput -b -f creates extra replicas on random resource instead of overwriting existing replicas

### ISSUE THREAD

**Issue by tedgin** [irods/irods#7110] opened 2023-06-02 16:36 UTC
- [x] main
- [x] 4-3-stable
- [x] `iput` help text (main)
- [x] `iput` help text (4-3-stable)
---
### iRODS Version, OS and Version
iRODS Version 4.2.12, CentOS 7
iCommands Version 4.2.8

### What did you try to do?

Using iput version 4.2.8, I try to bulk upload a folder on top of an existing collection. Before the upload, for each file in the folder, there existed a data object in the collection with the same name. The default resource is a `random` resource with two `passthru` child resources. Each child has a `unixfilesystem` child resource,

```console
4.2.8? ilsresc
primaryRes:random
├── primary_1:passthru
│   └── primaryStorage_1:unixfilesystem
└── primary_2:passthru
    └── primaryStorage_2:unixfilesystem
4.2.8? ls bulk
test1B  test2B
4.2.8? ils -L bulk  
/tempZone/home/user/bulk:
  user              0 primaryRes;primary_2;primaryStorage_2            1 2023-06-02.09:01 & test1B
        generic    /var/lib/irods/vaults/primary_2/home/user/bulk/test1B
  user              0 primaryRes;primary_2;primaryStorage_2            2 2023-06-02.09:01 & test2B
        generic    /var/lib/irods/vaults/primary_2/home/user/bulk/test2B
4.2.8? iput -bfr bulk
Running recursive pre-scan... pre-scan complete... transferring data...
```

### Expected behavior

I expected each replica of each data object being overwritten by its corresponding file.

### Observed behavior (including steps to reproduce, if applicable)

Each data object got a second replica on the opposite storage resource from the first replica with the first replica being write-locked.

```console
4.2.12? ils -L bulk
/tempZone/home/user/bulk:
  user              0 primaryRes;primary_2;primaryStorage_2            1 2023-06-02.09:01 ? test1B
        generic    /var/lib/irods/vaults/primary_2/home/user/bulk/test1B
  user              1 primaryRes;primary_1;primaryStorage_1            1 2023-06-02.09:02 & test1B
        generic    /var/lib/irods/vaults/primary_1/home/user/bulk/test1B
  user              0 primaryRes;primary_2;primaryStorage_2            2 2023-06-02.09:01 ? test2B
        generic    /var/lib/irods/vaults/primary_2/home/user/bulk/test2B
  user              1 primaryRes;primary_1;primaryStorage_1            2 2023-06-02.09:02 & test2B
        generic    /var/lib/irods/vaults/primary_1/home/user/bulk/test2B
4.2.12? iquest "select DATA_NAME, DATA_REPL_STATUS where COLL_NAME = '/tempZone/home/user/bulk' and DATA_REPL_NUM = '0'"
DATA_NAME = test1B
DATA_REPL_STATUS = 4
------------------------------------------------------------
DATA_NAME = test2B
DATA_REPL_STATUS = 4
------------------------------------------------------------
```

I'm using an unedited core.re, and I am using the Python rule engine with the following rule for setting `primaryRes` as the default resource.

```python
def acSetRescSchemeForCreate(*args):
    ret = args[1].msiSetDefaultResc('primaryRes', 'preferred')
    return ret['code']
```

If I redo this process, but execute `iput -bfr` using iput version 4.2.12, the overwrites happen as expected. I.e., the first replica is overwritten, and no second replica is created.

**Comment by alanking** [comment] 2023-06-02 17:10
Gah. Things getting stuck is very problematic...

However, we do not make any guarantees about cross-compatibility with respect to iCommands and iRODS server versions (i.e. this is not part of our testing). Also, we are not planning on any more releases in the 4.2 series. Since 4.2.12 `iput` is behaving as expected, I think there may not be much else to be done here.

That being said, I'm going to leave this open in case @korydraughn or @trel have any input, or if it seems useful to continue discussion here.

**Comment by tedgin** [comment] 2023-06-02 17:58
Since, I created the bug report, I've been able to reproduce this using version 4.2.12 of iput. It only happens intermittently though. It fails on occasion when the data objects in `bulk/` have two replicas each, one on `primaryRes` and one on a new resource `replicaRes`.  Here's the updated situation before `iput -bfr` is called.

```console
4.2.12? ilsresc
primaryRes:random
├── primary_1:passthru
│   └── primaryStorage_1:unixfilesystem
└── primary_2:passthru
    └── primaryStorage_2:unixfilesystem
replicaRes:passthru
└── replicaStorage_1:unixfilesystem
4.2.12? ils -L bulk
/tempZone/home/user/bulk:
  user              0 primaryRes;primary_1;primaryStorage_1            1 2023-06-02.10:45 & test1B
        generic    /var/lib/irods/vaults/primary_1/home/user/bulk/test1B
  user              1 replicaRes;replicaStorage_1            1 2023-06-02.10:45 & test1B
        generic    /var/lib/irods/vaults/replica_1/home/user/bulk/test1B
  user              0 primaryRes;primary_1;primaryStorage_1            2 2023-06-02.10:45 & test2B
        generic    /var/lib/irods/vaults/primary_1/home/user/bulk/test2B
  user              1 replicaRes;replicaStorage_1            2 2023-06-02.10:45 & test2B
        generic    /var/lib/irods/vaults/replica_1/home/user/bulk/test2B
```
Here's what it looks like after a corrupting iput call.

```console
4.2.12? iput -bfr bulk
Running recursive pre-scan... pre-scan complete... transferring data...
4.2.12?  ils -L bulk
/tempZone/home/user/bulk:
  user              0 primaryRes;primary_1;primaryStorage_1            1 2023-06-02.10:45 ? test1B
        generic    /var/lib/irods/vaults/primary_1/home/user/bulk/test1B
  user              1 replicaRes;replicaStorage_1            1 2023-06-02.10:45 ? test1B
        generic    /var/lib/irods/vaults/replica_1/home/user/bulk/test1B
  user              2 primaryRes;primary_2;primaryStorage_2            1 2023-06-02.10:45 & test1B
        generic    /var/lib/irods/vaults/primary_2/home/user/bulk/test1B
  user              0 primaryRes;primary_1;primaryStorage_1            2 2023-06-02.10:45 ? test2B
        generic    /var/lib/irods/vaults/primary_1/home/user/bulk/test2B
  user              1 replicaRes;replicaStorage_1            2 2023-06-02.10:45 ? test2B
        generic    /var/lib/irods/vaults/replica_1/home/user/bulk/test2B
  user              2 primaryRes;primary_2;primaryStorage_2            2 2023-06-02.10:45 & test2B
        generic    /var/lib/irods/vaults/primary_2/home/user/bulk/test2B
4.2.12?  iquest "select DATA_NAME, DATA_REPL_NUM, DATA_REPL_STATUS where COLL_NAME = '/tempZone/home/u
ser/bulk'"
DATA_NAME = test1B
DATA_REPL_NUM = 0
DATA_REPL_STATUS = 4
------------------------------------------------------------
DATA_NAME = test1B
DATA_REPL_NUM = 1
DATA_REPL_STATUS = 4
------------------------------------------------------------
DATA_NAME = test1B
DATA_REPL_NUM = 2
DATA_REPL_STATUS = 1
------------------------------------------------------------
DATA_NAME = test2B
DATA_REPL_NUM = 0
DATA_REPL_STATUS = 4
------------------------------------------------------------
DATA_NAME = test2B
DATA_REPL_NUM = 1
DATA_REPL_STATUS = 4
------------------------------------------------------------
DATA_NAME = test2B
DATA_REPL_NUM = 2
DATA_REPL_STATUS = 1
------------------------------------------------------------
```

**Comment by korydraughn** [comment] 2023-06-02 18:47
@alanking Please see if you can reproduce this in 4.3.0.

If the problem exists, then we'll fix it in the 4.3 series.

**Comment by alanking** [comment] 2023-06-02 19:54
On the very first attempt, even. In 4.3.0 as released on Ubuntu 20.04:
```bash
$ ls bulk
test1B  test2B
$ ils -L bulk
/tempZone/home/alan/bulk:
  alan              0 primaryRes;primary_2;primaryStorage_2            1 2023-06-02.19:50 & test1B
        generic    /var/lib/irods/primary_2/home/alan/bulk/test1B
  alan              0 primaryRes;primary_2;primaryStorage_2            2 2023-06-02.19:50 & test2B
        generic    /var/lib/irods/primary_2/home/alan/bulk/test2B
$ iput -bfr bulk
Running recursive pre-scan... pre-scan complete... transferring data...
$ ils -L bulk
/tempZone/home/alan/bulk:
  alan              0 primaryRes;primary_2;primaryStorage_2            1 2023-06-02.19:50 ? test1B
        generic    /var/lib/irods/primary_2/home/alan/bulk/test1B
  alan              1 primaryRes;primary_1;primaryStorage_1            1 2023-06-02.19:50 & test1B
        generic    /var/lib/irods/primary_1/home/alan/bulk/test1B
  alan              0 primaryRes;primary_2;primaryStorage_2            2 2023-06-02.19:50 ? test2B
        generic    /var/lib/irods/primary_2/home/alan/bulk/test2B
  alan              1 primaryRes;primary_1;primaryStorage_1            2 2023-06-02.19:50 & test2B
        generic    /var/lib/irods/primary_1/home/alan/bulk/test2B
```
We'll definitely look into this for 4.3.1.

**Comment by alanking** [comment] 2023-07-31 18:46
Here's what I've found...

When performing a bulk put, the file is bundled up and put as an object. This includes performing hierarchy resolution in order to choose a resource on which the bundle will go. Once the bundle has landed, it is unbundled, which effectively means iterating over the items from the bulk put and calling `rsDataObjPut` on each item.

The input for each put includes the hierarchy keyword for the resource on which the bundled data landed. This means that the put will not perform hierarchy resolution for the items being put into the system. Instead, the hierarchy keyword will be used and that resource is where all of the items in the bundle will go. In other words, hierarchy resolution is performed once at the bulk put stage and then everything is unpacked on the same resource, even if it's supposed to be overwriting existing data objects which may only have replicas on other resources.

The solution is to force each `rsDataObjPut` to perform hierarchy resolution so that they go to the correct resource to write over the target data object. This additionally means that bulk puts are/were not invoking policy correctly for the contained data objects. You'll notice that every bulk put will put all of the data objects on the same resource, even if it's random.

**Comment by korydraughn** [comment] 2023-07-31 18:54
If that's not part of the help text, then it needs to be added. Of course, that implies we aren't going to change the behavior.

Anyway, if the behavior is changed to do hierarchy resolution, then how should that play into situations where the some data objects exist, but the user specifies a different resource?

**Comment by trel** [comment] 2023-07-31 19:03
yes, it appears 'broken' by some definition whether we either
1) choose to resolve once and re-use
or
2) resolve every time

**Comment by alanking** [comment] 2023-07-31 19:13
I think that the current behavior is a bug and should be changed.

That said, the help text does have the following to say today:
> The -b option specifies the bulk upload operation which can do up to 50 uploads
at a time to reduce overhead. If the -b option is specified with the -f option
to overwrite existing files, the operation will work only if there is no
existing copy at all or if there is an existing copy in the target resource.
The operation will fail if there are existing copies but not in the
target resource because this type of operation requires a replication
operation and bulk replication has not been implemented yet.
The bulk option does work for mounted collections which may represent the
quickest way to upload a large number of small files.

Obviously, this description is not true. Causing the operation to fail in this case would be more in line with the description and is our only recourse for option 1. This would prevent the issue reported here, but would also remove a possibly valid use case of bulk puts. After all, the only reason this was reported is because @tedgin is using it this way. Option 1 means we must fail for this use case. If we do not fail for this case, that leaves a way for a put to create new replicas. This has been explicitly forbidden, per the help text again: 
> If the -f option is used to overwrite an existing data-object, the copy
in the resource specified by the -R option will be picked if it exists.
Otherwise, one of the copies in the other resources will be picked for the
overwrite. ***Note that a copy will not be made in the specified resource
if a copy in the specified resource does not already exist. The irepl         
command should be used to make a replica of an existing copy.***

This has also been declared in this issue from 4.2.9: https://github.com/irods/irods/issues/5575

I am leaning toward option 2 because bulk recursive put should work the same way a non-bulk recursive put works, in my opinion. Resolving the hierarchy could slow things down, but would result in correct behavior.

Thoughts?

**Comment by trel** [comment] 2023-07-31 19:17
Agreed.   2 is more correct.   And bulk is designed to save client-server back and forths.   It still will honor that goal.

**Comment by korydraughn** [comment] 2023-07-31 19:20
That makes sense. So what happens when a resource hierarchy is passed by the user?

**Comment by tedgin** [comment] 2023-07-31 19:43
I'm OK with either option. When I came upon this issue, I was exhaustively testing python rule logic. If what I were trying to do wasn't allowed, a failure would have resulted in a passed test.

**Comment by alanking** [comment] 2023-07-31 22:08
After some discussion, we think the most defensible position is to disallow overwriting data objects with bulk puts (i.e. -b and -f are incompatible parameters). 

Here are the defenses, in summary...

1. choose to resolve once and re-use

This would be most similar to the documented behavior, but is still undesirable overall because this can lead to partial success with respect to **overwriting data**.

2. resolve every time

This would be the most defensible from a policy perspective, but could lead to a performance detriment that destroys the performance gain that bulk puts are supposed to afford.

3. disallow forced overwrites
 
With this option, we don't need to worry about performance penalties being incurred for the correct behavior. Should a user wish to overwrite a collection using bulk put, the collection/objects should be moved or unlinked beforehand.

We will be thinking of ways to implement this better in the future, probably via a new/different data transfer endpoint.

**Comment by alanking** [comment] 2023-08-22 18:32
We will be moving forward with option 3: Disallow forced overwrites with bulk puts.

**Closed** 2023-08-23 19:28 UTC
Labels: bug
