### ISSUE TITLE
_ifuseFileCacheRead does not actually read to buf when fileCache->state == NO_FILE_CACHE

### ISSUE THREAD

**Issue by bpow** [irods/irods#2503] opened 2015-02-05 21:09 UTC
For both current master and stable, if `fileCache->state == NO_FILE_CACHE`, _fuseFileCacheRead (in `iFuseLib.FileCache.cpp`) sets `dataObjReadOutBBuf.buf` to be the pointer `buf` specified in its constructor, but when `rcDataObjRead` is called, it eventually calls `read_bytes_buf` in libtcp.cpp, which re-mallocs the buf field of this struct, (line 503).

Upon return from `rcDataObjRead`, `dataObjReadOutBBuf.buf` is never copied back to `buf`.

**Comment by keithj** [comment] 2015-02-05 22:15
This is a change to the behaviour of ````rcDataObjRead```` from iRODS 3.3.x, which would not
unconditionally re-malloc the field. Our client program using the client API was getting its read buffers re-malloc'd when built on 4.0.3, but was fine on 3.3.1. I changed our code to copy from whatever buffer  ````rcDataObjRead```` has allocated. However, I think this is a regression.

**Comment by bpow** [comment] 2015-02-06 14:15
The pull request I put above just makes sure to read back from dataObjReadOutBBuf, but there is at least a documentation bug in rcDataObjRead-- there should be some specification that the provided buffer will not be used if that is the intent. And documentation should specify that the caller needs to free dataObjReadOutBBuf.buf when done, or there will be a memory leak.

Otherwise, it may be worth it for performance issues to consider a specification where if the pointer passed in as dataObjReadOutBBuf is null, then rcDataObjRead will be responsible for malloc, and the caller will be responsible for free, but when the caller sets up a buffer ahead of time, then rcDataObjRead will use it and the caller is responsible for both allocation and freeing. It sounds like this may have been the case for 3.3 based on the comment by @keithj above.

**Comment by kellerb** [comment] 2015-02-24 04:14
Notifying here also that this issue may/should be fixed in master now by https://github.com/irods/irods/issues/2538

@keithj if you could test your client against master without the patch you had to hammer in since 3.3.x

**Comment by keithj** [comment] 2015-02-24 21:55
Thanks. I've reverted the memory management changes in the client(I pass in my own read buffer and free it afterwards). Valgrind is happy with the results. I'm using .deb packages built from master, but with an older 1.5 Postgres plugin package (because of #2494).

**Comment by kellerb** [comment] 2015-02-24 22:09
Thank you for testing it, glad that it works.

Are you using an older Postgres plugin because of when I said this:

> The iRODS Consortium plugins have not been updated with the new DSO locations yet. Trying to build them against master will probably fail.

If so, I see that I said that incorrectly. I meant that iRODS Consortium packages outside of the irods/irods repository (e.g. the cURL microservice plugins) have not been updated with the new lib locations, so building and/or running them will probably fail with a linker/loader issue. The DB plugins should build and run correctly.

If you are using an older DB plugin for a different lib-related reason, can you explain it? I want to make sure our lib situation is as pleasant as possible.

**Comment by keithj** [comment] 2015-02-24 22:13
I found that the Postgres plugin did not build for me. The error messages have scrolled off my terminal; stand by and I'll run it again...

**Comment by trel** [comment] 2015-03-30 15:41
thank you for testing - glad it works.

**Closed by trel** 2015-03-30 15:41 UTC
Labels: bug
