### ISSUE TITLE
irepl -U fails to update stale zero byte replicas

### ISSUE THREAD

**Issue by tedgin** [irods/irods#6285] opened 2022-03-29 23:38 UTC
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version

iRODS 4.2.8, CentOS 7

### What did you try to do?

I tried to use irepl to update a stale replica where the stale replica existed by was an empty file. 

```bash
ipc_admin@prod ~? ils -L '/iplant/home/htphytomorph/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat'
  htphytomorph      1 taccRes;corral4     24111062 2022-02-03.15:23 & {algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
    229e884a97eaade20e8d700065704dd2    generic    /corral/irods/iplant/Vault/home/htphytomorph/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
  htphytomorph      2 CyVerseRes;ds20Broker;ds20            0 2021-09-21.17:12   {algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
    d41d8cd98f00b204e9800998ecf8427e    generic    /irods_vault/ds20/home/htphytomorph/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
```

### Expected behavior

I expect the stale replica to updated so that it is identical to the fresh one.

### Observed behavior (including steps to reproduce, if applicable)

irepl fails with an `CAT_SUCCESS_BUT_WITH_NO_INFO` error.

```bash
ipc_admin@prod ~? irepl -a -M -U '/iplant/home/htphytomorph/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat'
remote addresses: 206.207.252.46 ERROR: replUtil: repl error for /iplant/home/htphytomorph/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat, status = -819000 status = -819000 CAT_SUCCESS_BUT_WITH_NO_INFO
```

The catalog provider logs the following.

```
Mar 29 16:29:30 pid:309636 NOTICE: chlModDataObjMeta cmlExecuteNoAnswerSql(rollback) succeeded
Mar 29 16:29:30 pid:309636 NOTICE: chlModDataObjMeta cmlModifySingleTable failure -819000
Mar 29 16:29:30 pid:309636 remote addresses: 206.207.252.46, 206.207.252.77, 206.207.252.81 ERROR: [-]  /irods_git_repo/server/api/src/rsModDataObjMeta.cpp:164:int _rsModDataObjMeta(rsComm_t *, modDataObjMeta_t *) :  status [CAT_SUCCESS_BUT_WITH_NO_INFO]  errno [] -- message [_rsModDataObjMeta - Failed to modify the database for object "/iplant/home/htphytomorph/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat" - CAT_SUCCESS_BUT_WITH_NO_INFO ]

Mar 29 16:29:30 pid:309636 NOTICE: _rsModDataObjMeta - Failed updating the database with object info.
Mar 29 16:29:30 pid:309636 remote addresses: 206.207.252.46, 206.207.252.77, 206.207.252.81 ERROR: dataOpen: Could not update size of data object [status = -819000, path = /iplant/home/htphytomorph/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat]
Mar 29 16:29:30 pid:309636 NOTICE: _rsDataObjRepl - Failed to update replica.
Mar 29 16:29:30 pid:309636 NOTICE: rsDataObjRepl - Failed to replicate data object.
```

I'm leaving the crazy file name in the examples, because it might be part of the cause.

**Comment by trel** [comment] 2022-03-30 04:09
Need to see if this is still true with 4.2.11.   Pretty sure all these codepaths were touched for 4.2.9 and refined since then.

**Comment by trel** [comment] 2022-03-30 04:10
Might even already have a test for this case?

**Comment by alanking** [comment] 2022-03-30 14:17
I was not able to reproduce this on 4.2.11, even with the crazy file name:
```bash
# as a rodsadmin that is not rodsuser "tony", of course :)
$ ils -L '/tempZone/home/tony/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat'
  tony              0 pt_0;rand_0;ufs_0     52428800 2022-03-30.14:07 & {algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
    sha2:hWWnFNyoQPhlLFuukkmrBfX7Wk+fE/viMwSxD2glLaI=    generic    /var/lib/irods/ufs_0_vault/home/tony/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
  tony              1 pt_2;rand_2;ufs_8            0 2022-03-30.14:06 X {algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
    sha2:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=    generic    /var/lib/irods/ufs_8_vault/home/tony/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
$ irepl -a -M '/tempZone/home/tony/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat'
$ ils -L '/tempZone/home/tony/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat'
  tony              0 pt_0;rand_0;ufs_0     52428800 2022-03-30.14:07 & {algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
    sha2:hWWnFNyoQPhlLFuukkmrBfX7Wk+fE/viMwSxD2glLaI=    generic    /var/lib/irods/ufs_0_vault/home/tony/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
  tony              1 pt_2;rand_2;ufs_8     52428800 2022-03-30.14:08 & {algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
    sha2:hWWnFNyoQPhlLFuukkmrBfX7Wk+fE/viMwSxD2glLaI=    generic    /var/lib/irods/ufs_8_vault/home/tony/sharePoint/mgb/{collectionName=Maize Gene Bank Regeneration}{plantType=Maize-Ear}{imageType=earImage}/algorithmResults/resultObjects/{algorithm=earImage}{computeStatus=complete}{input=[{accessionNumber=CIMMYTMA~217}{accessionName=MORE~17}{fieldData=PV17A}{experimentId=1903}{plotId=64}{dataType=earData}]}{inputHash=d7b8d47f13839131e805a59091f7c4f12dc553d8}.mat
```

Some other notes...

Despite its presence in the documentation, the `-U` flag is no longer meaningful in 4.2.9+. See: https://github.com/irods/irods/issues/4462#issuecomment-594547011 The new approach now ensures that `irepl` follows a distinct set of rules which are captured rather thoroughly in the `test_irepl.test_irepl_repl_status` suite. Now, if a replication operation is set to overwrite an existing replica, it is updated by default, so there is no need for the `-U` flag.

There exists a test case which is similar, but not equivalent to this situation: https://github.com/irods/irods/blob/79fde68ce5f33680ac59e7a1e52b84601db4975a/scripts/irods/test/test_irepl.py#L1072
The "start" entry describes a scenario in which:
 - A unixfilesystem resource which is not the configured default resource (`b`) has a marked-good replica of data object `foo`
 - A different unixfilesystem resource which is not the configured default resource (`c`) has a marked-stale replica of data object `foo`

The test then runs the following command: `irepl -a foo`

The expected results can be seen in the "end" entry of the dict above.

The major differences between that and the scenario described in this issue are:
 - The resources in that test are standalone, not in a hierarchy. `test_irepl.test_irepl_replication_hierachy` exists, but it is specific to the replication resource plugin and does not contain as comprehensive a set of tests as `test_irepl.test_irepl_repl_status`.
 - The admin flag is not being used in this test
 - The filename is extremely simple: `foo`

**Comment by trel** [comment] 2022-03-30 15:08
Okay, so we're pretty sure this is handled now.

To close this issue, we should add a test to capture the @tedgin scenario/variables above.

**Closed** 2023-01-20 17:29 UTC
Labels: testing
