### ISSUE TITLE
irepl -R resc_with_a_stale_replica should update the stale replica

### ISSUE THREAD

**Issue by bh9** [irods/irods#5747] opened 2021-07-14 13:36 UTC
### iRODS Version, OS and Version
4.2.7 Ubuntu 18.04 running 16.04 packages

### What did you try to do?
Use the same command to 
1. Update stale replicas
2. Create an extra replica
This command was expected to be `irepl -M -R target_resc`

### Expected behavior
`irepl -M -R target_resc` puts a good copy on the target resource, regardless of what was on the target resource beforehand

### Observed behavior (including steps to reproduce, if applicable)
`irepl -M -R resc_with_a_stale_replica` is a noop

We have since adjusted the tool to collect the DATA_REPL_NUM of the good replica, and provide that to irepl with the -n flag to ensure the target gets a good replica

**Comment by trel** [comment] 2021-07-14 15:58
If there is a good replica to use as the source of the replication... then yes, the defined target resource should end with a good replica as well.   We have tests for this.  Perhaps this is another wrinkle.

If you can share an example `ils -L`, `irepl`, and `ils -L` to show before and after... that will help to identify whether this is a missed use case.

**Comment by bh9** [comment] 2021-07-14 16:01
An example which I fixed this morning:
```
irods@irods-seq-ies6:~$ ils -L /seq/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
  srpipe            0 root;replicate;remote;seq-red;red6;irods-seq-ig07-sde         5093 2021-07-13.10:40 & 39044_1#2.adapter.json
    17b79bed0f9aaec7a0103d8c48fef389    generic    /irods-seq-ig07-sde/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
  srpipe            1 irods-seq-sb10-sdf         5093 2021-07-02.19:05   39044_1#2.adapter.json
    5b286443ce4b08012e137d85f561a51e    generic    /irods-seq-sb10-sdf/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
irods@irods-seq-ies6:~$ irepl -M -R irods-seq-sb10-sdf /seq/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
irods@irods-seq-ies6:~$ ils -L /seq/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
  srpipe            0 root;replicate;remote;seq-red;red6;irods-seq-ig07-sde         5093 2021-07-13.10:40 & 39044_1#2.adapter.json
    17b79bed0f9aaec7a0103d8c48fef389    generic    /irods-seq-ig07-sde/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
  srpipe            1 irods-seq-sb10-sdf         5093 2021-07-02.19:05   39044_1#2.adapter.json
    5b286443ce4b08012e137d85f561a51e    generic    /irods-seq-sb10-sdf/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
irods@irods-seq-ies6:~$ irepl -M -n0 -R irods-seq-sb10-sdf /seq/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
irods@irods-seq-ies6:~$ ils -L /seq/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
  srpipe            0 root;replicate;remote;seq-red;red6;irods-seq-ig07-sde         5093 2021-07-13.10:40 & 39044_1#2.adapter.json
    17b79bed0f9aaec7a0103d8c48fef389    generic    /irods-seq-ig07-sde/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
  srpipe            1 irods-seq-sb10-sdf         5093 2021-07-14.12:03 & 39044_1#2.adapter.json
    17b79bed0f9aaec7a0103d8c48fef389    generic    /irods-seq-sb10-sdf/illumina/runs/39/39044/lane1/plex2/qc/39044_1#2.adapter.json
```

**Comment by trel** [comment] 2021-07-14 16:11
Ohhh, this is 4.2.7.... yes, pretty sure this is already fixed in 4.2.9.

Will confirm.

**Comment by trel** [comment] 2021-07-14 16:14
@alanking Please confirm and tag/close as resolved - preferably with a link to the test that shows it.

**Comment by alanking** [comment] 2021-07-15 19:55
So, we have a test for standalone resources which has a good replica and a stale replica, and replicates to the resource holding the stale replica without specifying a source (which is what is happening above): https://github.com/irods/irods/blob/e9b92d2add9d1412cd4872322acee662327896c8/scripts/irods/test/test_irepl.py#L757

The main difference, of course, is that the resource being sourced is a hierarchy. I had started to write that particular scenario in this test case (resource 'c' is under replicating resource 'e' which is under passthru resource 'd'): https://github.com/irods/irods/blob/e9b92d2add9d1412cd4872322acee662327896c8/scripts/irods/test/test_irepl.py#L1522

It does not run because I didn't have time to flesh out all of these cases, but I ran just that case on an out-of-the-box 4.2.9 and it passes.

The hierarchy case also works when I run it manually:
```bash
$ head VERSION.json
{
    "catalog_schema_version": 8, 
    "commit_id": "e9b92d2add9d1412cd4872322acee662327896c8", 
    "configuration_schema_version": 3, 
    "installation_time": "2021-07-15T19:43:47.767085", 
    "irods_version": "4.2.9"
}$ ilsresc
demoResc:unixfilesystem
notdefaultresc:unixfilesystem
repl:replication
├── resource1Resource:unixfilesystem
├── resource2Resource:unixfilesystem
└── resource3Resource:unixfilesystem
$ ils -l foo
  rods              2 repl;resource2Resource          283 2021-07-15.19:45 & foo
  rods              3 notdefaultresc          283 2021-07-15.19:46 X foo
$ irepl -R notdefaultresc foo
$ ils -l foo
  rods              2 repl;resource2Resource          283 2021-07-15.19:45 & foo
  rods              3 notdefaultresc          283 2021-07-15.19:48 & foo
```

I think we can close this as resolved.

**Comment by alanking** [comment] 2021-07-15 20:03
Also, just in case it was of concern, I confirmed that the admin flag is functioning as well...
```bash
$ cat ~/.irods/irods_environment.json  | grep user
    "irods_user_name": "rods", 
$ ils -l /tempZone/home/mob/foo
  mob               2 repl;resource2Resource          187 2021-07-15.19:58 & foo
  mob               3 notdefaultresc          187 2021-07-15.19:58 X foo
$ irepl -R notdefaultresc /tempZone/home/mob/foo
remote addresses: 172.27.0.3 ERROR: replUtil: repl error for /tempZone/home/mob/foo, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
Level 0: CAT_NO_ACCESS_PERMISSION: [resolve_resource_hierarchy:381] - failed in file_object_factory:[[-]        /repos/irods/server/core/src/irods_file_object.cpp:355:irods::error irods::file_object_factory(rsComm_t *, dataObjInp_t *, irods::file_object_ptr, dataObjInfo_t **) :  status [CAT_NO_ACCESS_PERMISSION]  errno [] -- message [failed in call to getDataObjInfoIncSpecColl for [/tempZone/home/mob/foo] CAT_NO_ACCESS_PERMISSION ]

]


$ ils -l /tempZone/home/mob/foo
  mob               2 repl;resource2Resource          187 2021-07-15.19:58 & foo
  mob               3 notdefaultresc          187 2021-07-15.19:58 X foo
$ irepl -M -R notdefaultresc /tempZone/home/mob/foo
$ ils -l /tempZone/home/mob/foo
  mob               2 repl;resource2Resource          187 2021-07-15.19:58 & foo
  mob               3 notdefaultresc          187 2021-07-15.20:01 & foo
```

**Closed** 2021-07-15 20:11 UTC
Labels: consortium-member
