### ISSUE TITLE
iadmin rmuser deletes user when collections are not empty, when zone is included on username

### ISSUE THREAD

**Issue by theferrit32** [irods/irods#3931] opened 2018-05-11 16:55 UTC
### iRODS Version, OS and Version
4.2.3/4.2.2

### What did you try to do?
`iadmin rmuser` on user who has non-empty collections

### Expected behavior
command fails with:
```
remote addresses: ... ERROR: rcGeneralAdmin failed with error -821000 CAT_COLLECTION_NOT_EMPTY 
Level 0: collection '/testZone/home/fakeuser123' is not empty
```

### Observed behavior (including steps to reproduce, if applicable)
When zone is omitted from user name argument to `iadmin rmuser`, command fails as expected and leaves the user and all files in place within iRODS catalog.

When zone is included on user name argument to `iadmin rmuser`, command exits silently.  Command removed the user but failed to remove the non-empty collections, leaving the catalog in an inconsistent state, and preventing the creation of a new iRODS account with the same user name as the removed user. 

```
[irods]$ iadmin mkuser fakeuser123#testZone rodsuser
[irods]$ iadmin moduser fakeuser123#testZone password 1234

[fakeuser123]$ echo "Hello world" > hello.txt
[fakeuser123]$ iput hello.txt
[fakeuser123]$ ils
/testZone/home/fakeuser123:
  hello.txt

[irods]$ iadmin rmuser fakeuser123
remote addresses: ... ERROR: rcGeneralAdmin failed with error -821000 CAT_COLLECTION_NOT_EMPTY 
Level 0: collection '/testZone/home/fakeuser123' is not empty
Level 1: DEBUG: 
line 52, col 4, rule base core
    failmsg(*status,*msg) }}
    ^

[irods]$ iadmin rmuser fakeuser123#testZone
[irods]$ echo $?
0
[irods]$ 
[irods]$ iadmin lu | grep fakeuser123
[irods]$ psql -d ICAT -c "select coll_id,coll_name,coll_owner_name from r_coll_main;" | grep fakeuser123
   12340 | /testZone/home/fakeuser123                  | fakeuser123
   12341 | /testZone/trash/home/fakeuser123            | fakeuser123
[irods]$ iadmin mkuser fakeuser123#testZone rodsuser
remote addresses: ... ERROR: rcGeneralAdmin failed with error -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME 
Level 0: Error -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME
Level 1: DEBUG:
```
Cannot create fakeuser123#testZone because entries are still in catalog owned by the previous (now non-existent) user of the same name.

Resolving this inconsistent state currently requires admin deletion (or moving) of the previous user's state:
```
[irods]$ ichmod -rM own rods /testZone/home/fakeuser123
[irods]$ ichmod -rM own rods /testZone/trash/home/fakeuser123
[irods]$ irm -r /testZone/home/fakeuser123
[irods]$ irm -r /testZone/trash/home/fakeuser123
[irods]$ iadmin mkuser fakeuser123#testZone rodsuser
```

**Comment by trel** [comment] 2018-09-27 04:14
duplicate of #3798

**Closed by trel** 2018-09-27 04:14 UTC
Labels: bug, consortium-member, duplicate
